objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Executed_Clause_For_Flagging__c</fullName>
        <label>Executed Clause For Flagging</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Most_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Most Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PopulateMostEligibleContactBatch_Test.cls
@isTest
public class PopulateMostEligibleContactBatch_Test{
    static Id YBNAccountMasterRecordTypeId{
        get{
            return Schema.SObjectType.Account.getRecordTypeInfosByName().get('YBN Master Account').getRecordTypeId();
        }
    }
    
    static Id YBNCaseInboundRecordTypeId{
        get{
            return Schema.SObjectType.Case.getRecordTypeInfosByName().get('YBN Inbound Inquiry').getRecordTypeId();
        }
    }

    static Id YBNAccountStandardRecordTypeId{
        get{
            return Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        }
    }
    
    testMethod
    static void MECPopulatedOnContact(){
        Account relatedAccount = new Account(
            Name = 'MECPopulatedOnContact_Account',
            RecordTypeId = YBNAccountMasterRecordTypeId,
            Client_Type__c = 'YBN'
        );

        INSERT relatedAccount;
        
        Test.startTest();

        List<Contact> lstSimilarContacts = new List<Contact>();
        for(Integer i = 1; i <= 3; i++){
            lstSimilarContacts.add(
                new Contact(
                    LastName = 'MECPopulatedOnContact_Contact',
                    AccountId = relatedAccount.Id,
                    Phone = '1234567890'                    
                )
            );
        }

        INSERT lstSimilarContacts;

        Database.executeBatch(new PopulateMostEligibleContactBatch());
        
        Test.stopTest(); 
        
        lstSimilarContacts = [
            SELECT Id 
            FROM   Contact
            WHERE  Target_Account__c != NULL  AND
                   Most_Eligible__c  != FALSE AND
                   Executed_Clause_For_Flagging__c != NULL
        ];
        
        System.assertEquals(1, lstSimilarContacts.size());
    }
}