objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSC_Completed_Date__c</fullName>
        <label>CSC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Days_Live_Equivalent__c</fullName>
        <formula>IF(NOT(ISPICKVAL(Status__c,'LIVE')), null,
IF(CONTAINS(Product_Type_Transactional__c ,'TORCHx'), (TODAY() - CSC_Completed_Date__c) - Days_in_Save_Mode__c, Days_Since_Live__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Days Live Equivalent equals Days Since Live except with TORCHx. For TORCHx, Days Live Equivalent is (Today - CSC Completed Date) - Days in Save Mode</inlineHelpText>
        <label>Days Live Equivalent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Since_Live__c</fullName>
        <formula>today()- Live_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Live</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pause_Touchplan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pause Touchplan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Model_Local__c</fullName>
        <formula>if( 
IMS_Rep__r.Id = "00560000001HpEm", /* Customer Care */
"Pooled", 
if( 
or( 
contains( IMS_Rep_Role__c , "Local Consultant"),
 AND(
contains( IMS_Rep_Role__c , "Local CSM"),
contains( IMS_Rep__r.Department, "LeadStream")), 
IMS_Rep__r.Id = "005600000017MCh", /* JEnnifer Flanagan */
IMS_Rep__r.Id = "00532000005P6l3"), /*LeadStream Support*/
"Dedicated", ""))</formula>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Close_Date__c</fullName>
        <description>Date of cancellation auto close for LBW/POD accounts.</description>
        <label>Auto Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Day_Of_Next_SLA_Touch__c</fullName>
        <label>Day Of Next SLA Touch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Day_SLA_Equivalent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Day SLA Equivalent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Scheduled_Contact_Date__c</fullName>
        <label>Next Scheduled Contact Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Within_SLA__c</fullName>
        <label>Within SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Custom_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Account_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Automation_Status__c</fullName>
        <label>Automation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Outcome</fullName>
                    <default>true</default>
                    <label>Waiting on Outcome</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cancellation Request</label>
        <referenceTo>Cancellation_Request__c</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Cancellation_Request_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Since_Live_Equivalent_on_Request__c</fullName>
        <inlineHelpText>Days Since Live when a Cancellation Request was created for LBW and the number of days since the CSC was created and the Cancellation Request was created for TORCHx.</inlineHelpText>
        <label>Days Since Live Equivalent on Request</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Custom Automation</label>
    <nameField>
        <displayFormat>AAN-{0000000}</displayFormat>
        <label>Custom Automation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CancellationRequestTriggerHandler.cls
public without sharing class CancellationRequestTriggerHandler {

    private static final Map<Id, User> activeStandardUserIdMap = new Map<Id, User>([select Id from User where IsActive = true and UserType = 'Standard']);
    private static final List<Schema.PicklistEntry> ple = Cancellation_Request__c.Day_Of_Next_SLA_Touch__c.getDescribe().getPicklistValues();

    public static Map<String, Integer> orderMap(){
        Map<String, Integer> oMap = new Map<String, Integer>();

        Integer orderValue = 0;
        for(Schema.PicklistEntry f : ple){
            oMap.put(f.getLabel(), orderValue);
            orderValue++;
        }

        return oMap;
    }

    public static List<String> orderList(){
        List<String> oList = new List<String>();

        for(Schema.PicklistEntry f : ple){
            oList.add(f.getLabel());
        }
        return oList;
    }

    public static void beforeUpdateSLACheck(Map<Id, Cancellation_Request__c> newMapValues,  Map<Id, Cancellation_Request__c> oldMapValues){
        for(Cancellation_Request__c cancelRequest : newMapValues.values()){
            Cancellation_Request__c oldCancelRequest = oldMapValues.get(cancelRequest.Id);

            //system.debug(orderList().get(orderMap().get(cancelRequest.Day_Of_Next_SLA_Touch__c)+1));

            if(cancelRequest.OwnerId != oldCancelRequest.OwnerId){
                cancelRequest.Day_Of_Next_SLA_Touch__c = '1';
                if(DateTime.now().hourGMT() < DateTime.newInstanceGmt(1, 1, 1, 22, 0, 0).hourGMT()){
                    cancelRequest.Day_SLA_Equivalent__c = 1;
                }else{
                    cancelRequest.Day_SLA_Equivalent__c = 0;
                }
            }else if(cancelRequest.Outcome__c == 'In Progress' && cancelRequest.Outcome__c != oldCancelRequest.Outcome__c){
                cancelRequest.Day_Of_Next_SLA_Touch__c = '1';
                if(DateTime.now().hourGMT() < DateTime.newInstanceGmt(1, 1, 1, 22, 0, 0).hourGMT()){
                    cancelRequest.Day_SLA_Equivalent__c = 1;
                }else{
                    cancelRequest.Day_SLA_Equivalent__c = 0;
                }
            }

            if(String.isNotBlank(cancelRequest.Day_Of_Next_SLA_Touch__c) && Double.valueof(cancelRequest.Day_Of_Next_SLA_Touch__c) < cancelRequest.Day_SLA_Equivalent__c){
                cancelRequest.Within_SLA__c = 'No';
            }else if(String.isNotBlank(cancelRequest.Day_Of_Next_SLA_Touch__c) && Double.valueof(cancelRequest.Day_Of_Next_SLA_Touch__c) >= cancelRequest.Day_SLA_Equivalent__c){
                cancelRequest.Within_SLA__c = 'Yes';
            }
        }
    }

    public static void afterUpdate(Map<Id, Cancellation_Request__c> newMapValues,  Map<Id, Cancellation_Request__c> oldMapValues){
        updateCustomAutomationRecordsAndCheckIfAccountInPauseMode(newMapValues, oldMapValues);
    }

    public static void afterInsert(Map<Id, Cancellation_Request__c> newMapValues){
        Set<Id> accountIdSet = relatedAccountIdList(newMapValues.values());

        if(accountIdSet.isEmpty()){
            return;
        }

        Map<Id, Account> accountTORCHXandLBWMap = AccountObjectHelper.getTORCHXandLBWAccountMap(accountIdSet);

        if(accountTORCHXandLBWMap.isEmpty()){
            return;
        }

        createCustomAutomationRecords(newMapValues, accountTORCHXandLBWMap);
    }

    public static Set<Id> relatedAccountIdList(List<Cancellation_Request__c> cancelRequestList){
        Set<Id> accountIdSet = new Set<Id>();

        for(Cancellation_Request__c record : cancelRequestList){
            if(String.isNotBlank(record.Account_Name__c)){
                accountIdSet.add(record.Account_Name__c);
            }
        }

        return accountIdSet;
    }

    /*public static Map<Id, Account> getTORCHXandLBWAccountMap(Set<Id> accountIdSet){
        Map<Id, Account> accountTORCHXandLBWMap = new Map<Id, Account>();
        for(Account record : (List<Account>)Database.query(Label.AccountTORCHXandLBWMapQuery)){
            accountTORCHXandLBWMap.put(record.Id, record);
        }

        return accountTORCHXandLBWMap;
    }*/

    public static void createCustomAutomationRecords(Map<Id, Cancellation_Request__c> newMapValues, Map<Id, Account> accountTORCHXandLBWMap){
        List<Custom_Automation__c> customAutomationList = new List<Custom_Automation__c>();

        List<Account> updateCSCCompleteDateOnAccountList = new List<Account>();

        for(Cancellation_Request__c record : newMapValues.values()){
            if(accountTORCHXandLBWMap.containsKey(record.Account_Name__c)){
                Account acctRecord = accountTORCHXandLBWMap.get(record.Account_Name__c);
                acctRecord.Pause_Touchplan__c = true;

                Custom_Automation__c newCustomAutomation = new Custom_Automation__c();
                newCustomAutomation.Account__c = record.Account_Name__c;
                newCustomAutomation.Cancellation_Request__c = record.Id;
                newCustomAutomation.Automation_Status__c = 'Waiting on Outcome';

                if(acctRecord.Product_Type_Transactional__c.containsIgnoreCase('Leads By Web') || acctRecord.Product_Type_Transactional__c.containsIgnoreCase('Lead Stream ATV')){
                    newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c = acctRecord.Days_Since_Live__c;
                }else if(acctRecord.Product_Type_Transactional__c.containsIgnoreCase('TORCHx') && !acctRecord.Cases.isEmpty()){
                    //newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c = acctRecord.Cases[0].ClosedDate.date().daysBetween(Date.today());
                    if(acctRecord.Days_Live_Equivalent__c != null){
                        newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c = acctRecord.Days_Live_Equivalent__c;
                    }else{
                        newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c = acctRecord.Cases[0].ClosedDate.date().daysBetween(Date.today());

                        if(acctRecord.CSC_Completed_Date__c == null){
                            acctRecord.CSC_Completed_Date__c = acctRecord.Cases[0].ClosedDate.date();
                            //updateCSCCompleteDateOnAccountList.add(acctRecord);
                        }

                        //newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c = acctRecord.Cases[0].Auto_Close_Date__c.daysBetween(Date.today());
                    }
                }

                if(newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c == null || newCustomAutomation.Days_Since_Live_Equivalent_on_Request__c == 0){
                    continue;
                }

                customAutomationList.add(newCustomAutomation);
                updateCSCCompleteDateOnAccountList.add(acctRecord);
            }
        }

        if(!customAutomationList.isEmpty()){
            insert customAutomationList;

                if(!updateCSCCompleteDateOnAccountList.isEmpty()){
                    Database.update(updateCSCCompleteDateOnAccountList, false);
                }
        }
    }

    private static void updateCustomAutomationRecordsAndCheckIfAccountInPauseMode(Map<Id, Cancellation_Request__c> newMapValues,  Map<Id, Cancellation_Request__c> oldMapValues){
        List<Cancellation_Request__c> cancellationRequestWithChangedOutcome = new List<Cancellation_Request__c>();
        Set<Id> accountIdSetForPauseModeCheck = new Set<Id>();

        for(Cancellation_Request__c record : newMapValues.values()){
            Cancellation_Request__c oldRecord = oldMapValues.get(record.Id);

            if(String.isNotBlank(record.Outcome__c) && String.isNotBlank(oldRecord.Outcome__c) && record.Outcome__c != oldRecord.Outcome__c/* && oldRecord.Outcome__c.equalsIgnoreCase('In Progress')*/){
                cancellationRequestWithChangedOutcome.add(record);
            }

            if(String.isNotBlank(record.Account_Name__c) && record.Outcome__c != oldRecord.Outcome__c){
                accountIdSetForPauseModeCheck.add(record.Account_Name__c);
            }
        }

        if(!cancellationRequestWithChangedOutcome.isEmpty()){
            CustomAutomationObjectHelper.setAutomationStatusFromCancellationRequest(cancellationRequestWithChangedOutcome);
        }

        if(!accountIdSetForPauseModeCheck.isEmpty()){
            AccountObjectHelper.checkIfAccountListInPauseMode(accountIdSetForPauseModeCheck);
        }
    }

    /* Subba Gadhamsetty, Added for YO-62417 Start */
    public static Map<Id, Account> getCRAccntsMap(Map<Id, Cancellation_Request__c> newMapValues){       
        Set<String> accountNameSet = New Set<String>();
        // Initialize all related Accounts, if not Blank
        for(Cancellation_Request__c cr : newMapValues.values()){
            if ( String.isNotBlank(cr.Account_Name__c))
            accountNameSet.add(cr.Account_Name__c); 
        }           
        //Create Account Map for the Identified Accounts
        Map<Id, Account> accountCancelRequestMap = new Map<Id, Account>([
            SELECT Id, Client_Type__c, Service_Model_Local__c FROM Account WHERE Id IN :accountNameSet]);       
        return  accountCancelRequestMap;
    } 

    public static Map<String, Event> getExistingEventsMap(Map<Id, Cancellation_Request__c> newMapValues){               
        List<Event> existingEventsList = new List<Event>([select WhatId,Id,RecordTypeId,Subject,Status__c,StartDateTime,OwnerId  from Event where WhatId in :newMapValues.keySet() 
            and RecordType.ID = :Schema.SObjectType.Event.getRecordTypeInfosByName().get('Calendar Blocker').getRecordTypeId() and Subject = 'CR Follow Up' and Status__c = 'Scheduled']);
        Map<String, Event> existingEventsMap = new Map<String, Event>();
        for(Event eventRecord : existingEventsList){
            existingEventsMap.put(eventRecord.WhatId,eventRecord);      
        }       
        return  existingEventsMap;
    } 
    
    public static Event getCREvent(Cancellation_Request__c cancelRequest) {
        //Create New Event Instance
        Event e = new Event();
        e.RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Calendar Blocker').getRecordTypeId();
        e.internal_external_activity__c = 'External';
        e.ShowAs = 'Busy';
        e.Subject = 'CR Follow Up';
        e.Status__c = 'Scheduled';
        e.StartDateTime = cancelRequest.Next_Scheduled_Contact_Date__c;
        e.DurationInMinutes = 30;        
        e.WhatId = cancelRequest.Id;
        e.OwnerId = cancelRequest.ownerId;
        return e;    
    }

    public static void createNewEvents(Map<Id, Cancellation_Request__c> newMapValues,  Map<Id, Cancellation_Request__c> oldMapValues) {
        Map<Id, Account> accountCancelRequestMap = getCRAccntsMap(newMapValues);
        //  For the Mathching Cancellation Requests Create Events
        List<Event> newEventList = new List<Event>();
        for(Cancellation_Request__c cancelRequest : newMapValues.values()){         
            // If Accont exists and meets specified criteria and NextScheduled Date populated and OwnerId is a User, not a Queue(start with 005) 
            if(String.isNotBlank(cancelRequest.Account_Name__c) && cancelRequest.Next_Scheduled_Contact_Date__c != null && String.valueof(cancelRequest.ownerId).startsWith('005')              
                && accountCancelRequestMap.get(cancelRequest.Account_Name__c).Client_Type__c=='Local' && accountCancelRequestMap.get(cancelRequest.Account_Name__c).Service_Model_Local__c=='Dedicated'){               
                Event e =  getCREvent(cancelRequest);   
                newEventList.add(e);                                
            }
        }
        
        if(!newEventList.isEmpty()){
            insert newEventList;
        }       
    }

    public static void processUpdateEvents(Map<Id, Cancellation_Request__c> newMapValues,  Map<Id, Cancellation_Request__c> oldMapValues) {     
        Map<Id, Account> accountCancelRequestMap = getCRAccntsMap(newMapValues);
        Map<String, Event> existingEventsMap = getExistingEventsMap(newMapValues);      
        List<Event> newEventList = new List<Event>();
        List<Event> updateEventList = new List<Event>();
        List<Event> deleteEventList = new List<Event>();
        for(Cancellation_Request__c cancelRequest : newMapValues.values()){         
            if(String.isNotBlank(cancelRequest.Account_Name__c) 
                && accountCancelRequestMap.get(cancelRequest.Account_Name__c).Client_Type__c=='Local' 
                && accountCancelRequestMap.get(cancelRequest.Account_Name__c).Service_Model_Local__c=='Dedicated'){
                Event exstngEvnt = existingEventsMap.get(cancelRequest.Id);
                // If NextScheduled Date not populated or CR OwnerId is Queue, delete if there is an existing event
                if( (cancelRequest.Next_Scheduled_Contact_Date__c == null || !String.valueof(cancelRequest.ownerId).startsWith('005')))
                {
                        if(exstngEvnt != null && String.isNotBlank((exstngEvnt).Id))
                            deleteEventList.add(exstngEvnt);
                }
                else if(cancelRequest.Next_Scheduled_Contact_Date__c != null    //Check if CancllationRequest.Next_Scheduled_Contact_Date__c or Owner Changed , then only trigger
                    && ((cancelRequest.Next_Scheduled_Contact_Date__c != oldMapValues.get(cancelRequest.Id).Next_Scheduled_Contact_Date__c) || (cancelRequest.OwnerId != oldMapValues.get(cancelRequest.Id).OwnerId))){
                        Datetime existingEventStartDateTime = null;
                        if (exstngEvnt != null)
                            existingEventStartDateTime = exstngEvnt.StartDateTime;
                        if(existingEventStartDateTime == null)
                        {
                            //No Event exists, so, create new event
                            Event e =  getCREvent(cancelRequest);   
                            newEventList.add(e);
                        }
                        else if(cancelRequest.Next_Scheduled_Contact_Date__c != existingEventStartDateTime || cancelRequest.ownerId != exstngEvnt.OwnerId){
                            //Event exists and if has different Schedule Date or different Owner Id than Cancel Request, then, update it.
                            Event e =  exstngEvnt; 
                            e.StartDateTime = cancelRequest.Next_Scheduled_Contact_Date__c;  
                            e.OwnerId = cancelRequest.ownerId; 
                            updateEventList.add(e);
                        }
                }               
            }
        }

        if(!newEventList.isEmpty()){
            insert newEventList;
        }   
        if(!updateEventList.isEmpty()){
            update updateEventList;
        }   
        if(!deleteEventList.isEmpty()){
            delete deleteEventList;
        }           
    }
    /* Subba Gadhamsetty, Added for YO-62417 ,End */
}