objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Interaction</fullName>
        <active>true</active>
        <label>Interaction</label>
    </recordTypes>
</CustomObject>

classes/TaskTriggerTest.cls
@isTest
private class TaskTriggerTest {
	
	/*@isTest static void test_LiveOpsCallLogging() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.CallDurationInSeconds = 50;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt2() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.CallDurationInSeconds = 50;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt3() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		caseRecord.X2nd_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.CallDurationInSeconds = 50;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt4() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		caseRecord.X2nd_Attempt_By__c = 'Testing Test';
		caseRecord.X3rd_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.CallDurationInSeconds = 50;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingUpdate() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		tk.CallDurationInSeconds = 50;
		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt2Update() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		tk.CallDurationInSeconds = 50;
		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt3Update() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		caseRecord.X2nd_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		tk.CallDurationInSeconds = 50;
		update tk;
		Test.stopTest();
	}

	@isTest static void test_LiveOpsCallLoggingAttempt4Update() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status, X1st_Attempt_By__c from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];
		caseRecord.X1st_Attempt_By__c = 'Testing Test';
		caseRecord.X2nd_Attempt_By__c = 'Testing Test';
		caseRecord.X3rd_Attempt_By__c = 'Testing Test';
		update caseRecord;

		Test.startTest();
		Task tk = new Task();
		tk.WhatId = caseRecord.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;

		tk.CallDurationInSeconds = 50;
		update tk;
		Test.stopTest();
	}*/

	@isTest static void test_SLACall(){
		Account newAccount = new Account();
		newAccount.Name = 'Tset Account';
		insert newAccount;

		Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
		newCancellationRequest.Account_Name__c = newAccount.Id;
		insert newCancellationRequest;

		Task tk = new Task();
		tk.WhatId = newCancellationRequest.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.CallType = 'Outbound';
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;
	}

	@isTest static void test_SLAEmail(){
		Account newAccount = new Account();
		newAccount.Name = 'Tset Account';
		insert newAccount;

		Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
		newCancellationRequest.Account_Name__c = newAccount.Id;
		insert newCancellationRequest;

		Task tk = new Task();
		tk.WhatId = newCancellationRequest.Id;
		tk.Send_Email_Alert_to_SD_AD__c = false;
		tk.TaskSubtype = 'Email';
		tk.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Interaction').getRecordTypeId();
		insert tk;
	}
	
}