objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Status_Change_Log__c.object
<CustomObject><fields>
        <fullName>CaseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Id of the related Case record</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Status Change Logs</relationshipLabel>
        <relationshipName>Case_Status_Change_Logs_CaseId</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Case_Status__c</fullName>
        <description>Case Status at the time of the log entry</description>
        <label>Case Status</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Notification_Sent_Date__c</fullName>
        <description>Date the a notification was sent based on the business logic; 3 days not changed</description>
        <label>Notification Sent Date</label>
        <type>DateTime</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Used for logging when a notification is sent to internal users related to Case/ Account when the Status does not change (based on business criteria)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableChangeDataCapture>false</enableChangeDataCapture><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Case Status Change Log</label><nameField>
        <displayFormat>CSCL-{0000000}</displayFormat>
        <label>Case Status Change Log Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Status Change Logs</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

classes/wbnNationalNCSStatusNotificationBatch.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 19-Jun-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 19-Jun-2018
  Description ........: Sends a notification to specified internal users if the status of a
  National - New Client Setup Case has not changed within the last 3 days
*****************************************************************************/
global class wbnNationalNCSStatusNotificationBatch implements Database.Batchable<sObject> 
{
    public Set<String> acctIdsExcludeSet = new Set<String>{'0013200001ASiCOAA1', '0013200001CEoFOAA1', '0013200001IypE7AAJ'}; // Test Accounts
    public Set<String> statusExcludeSet = new Set<String>{'Client Problem', 'Never Launched', 'LIVE', 'On Hold'};
    public Set<String> recordTypeNameIncludeSet = new Set<String>{'National - New Client Setup'};
    public Set<String> ownerTypeIncludeSet = new Set<String>{'User'};
    public Set<String> profileExcludeSet = new Set<String>{'System Administrator', 'API Integration Read/Write'};
    public String query = 'SELECT Id, CreatedDate, Owner.Name, Owner.Email, Account.IMS_Rep__r.Name, Account.IMS_Rep__r.Email, Account.IMS_Rep__r.Manager.Name, Account.IMS_Rep__r.Manager.Email,' +
                          'AccountId, Account.Name, CaseNumber, Status, RecordType.Name ' +
                          'FROM Case ' +
                          'WHERE RecordType.Name IN :recordTypeNameIncludeSet AND ' +
                          'IsClosed = false AND ' +
                          'Status NOT IN :statusExcludeSet AND ' +
                          'Owner.Type IN :ownerTypeIncludeSet AND ' +
                          'AccountId NOT IN :acctIdsExcludeSet AND ' +
                          'Owner.Profile.Name NOT IN :profileExcludeSet AND ' +
                          'AccountId != NULL AND ' +
                          'CreatedDate = :Date.TODAY().addDays(-3)';
    
    global database.querylocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        List<Case_Status_Change_Log__c> dmlChangeLogs = new List<Case_Status_Change_Log__c>();
        
        // put Case History data into Map
        Map<Id, CaseHistory> caseHistMap = new Map<Id, CaseHistory>();
        for(CaseHistory ch :
            [SELECT Id, 
                    CreatedDate, 
                    CaseId, 
                    Case.CaseNumber, 
                    Case.AccountId, 
                    Field, 
                    OldValue, 
                    NewValue 
               FROM CaseHistory 
              WHERE Field = 'Status' AND 
                    CreatedDate = LAST_N_DAYS: 30 AND 
                    Case.RecordType.Name = 'National - New Client Setup' 
           ORDER BY CreatedDate DESC]){
        
            caseHistMap.put(ch.CaseId, ch);
        }
        
        // put Case History data into Map
        Map<Id, Case_Status_Change_Log__c> caseChangeLogMap = new Map<Id, Case_Status_Change_Log__c>();
        for(Case_Status_Change_Log__c cl :
            [SELECT Id,
                    CaseId__c,
                    Case_Status__c,
                    Notification_Sent_Date__c
               FROM Case_Status_Change_Log__c
              WHERE Notification_Sent_Date__c = :Date.TODAY().addDays(-3)]){
            
            caseChangeLogMap.put(cl.CaseId__c, cl);
        }
        
        if(scope.size() > 0){
        
            // compare National NCS Cases to Case History & Case Change Log
            for(Case c : (List<Case>) scope){
                if(!caseHistMap.containsKey(c.Id) || (caseChangeLogMap.get(c.Id).CaseId__c == c.Id && caseChangeLogMap.get(c.Id).Case_Status__c == c.Status)){
                
                    Case_Status_Change_Log__c newChangeLog = new Case_Status_Change_Log__c();
                    newChangeLog.CaseId__c = c.Id;
                    newChangeLog.Case_Status__c = c.Status;
                    newChangeLog.Notification_Sent_Date__c = System.Now();
                    dmlChangeLogs.add(newChangeLog);
                }
            }
        }
    }
   
    global void finish(Database.BatchableContext BC) 
    {
        // send notifications from change log from current day
    }

}