objects/Account_Marketo_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Attribute__c</fullName>
        <label>Activity Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Id__c</fullName>
        <externalId>true</externalId>
        <label>Activity Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Type</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipLabel>Account's Marketo Activity</relationshipLabel>
        <relationshipName>Account_s_Marketo_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Activity_Timestamp__c</fullName>
        <label>Marketo Activity Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Marketo_Lead_ID__c</fullName>
        <label>Marketo Lead ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Account Marketo Activity</label>
    <nameField>
        <displayFormat>AMA-{0000000}</displayFormat>
        <label>Account Marketo Activity  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account's Marketo Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AdjustCustomCodeLimit__c.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to adjust limits in code</description>
    <label>AdjustCustomCodeLimit</label>
</CustomObject>

classes/AccountMarketoActivityQueueable.cls
public class AccountMarketoActivityQueueable implements Queueable, Database.AllowsCallouts {

	DateTime dateTimeParameter;
	String tokenValue;

	public AccountMarketoActivityQueueable(DateTime sinceDateTime, String passedTokenValue){
		dateTimeParameter = sinceDateTime;
		tokenValue = passedTokenValue;
	}

	public void execute(QueueableContext context) {
        List<String> activityIdList = new List<String>();
        for(Activity_Type__c record : [select Id, Activity_Type_ID__c from Activity_Type__c where Activity_Type_ID__c != '']){
        	activityIdList.add(record.Activity_Type_ID__c);
        }

		//String jsonResponse = MarketoSyncService.getLeadActivities(activityIdList, '', new List<String>(), dateTimeParameter);

		Boolean moreResult = true;
		Integer calloutCount = 1;
		//String tokenValue = '';

		List<Account_Marketo_Activity__c> accountMarketoActivityList = new List<Account_Marketo_Activity__c>();

		while(moreResult && calloutCount <= AdjustCustomCodeLimit__c.getValues('AccountMarketoActivityQueueableLimit').Limit__c){
			String jsonResponse = MarketoSyncService.getLeadActivities(activityIdList, '', new List<String>(), dateTimeParameter, tokenValue);

			Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);

			for(Object obj : (List<Object>)responseMap.get('result')){
				Map<String, Object> activityObjMap = (Map<String, Object>)obj;

				Account_Marketo_Activity__c accountMarketoActivity = new Account_Marketo_Activity__c();
				accountMarketoActivity.Activity_Id__c = String.valueof(activityObjMap.get('id'));
				accountMarketoActivity.Campaign_ID__c = String.valueof(activityObjMap.get('campaignId'));
				accountMarketoActivity.Marketo_Lead_ID__c = String.valueof(activityObjMap.get('leadId'));
				accountMarketoActivity.Activity_Type_ID__c = String.valueof(activityObjMap.get('activityTypeId'));
				accountMarketoActivity.Activity_Attribute__c = String.valueof(activityObjMap.get('primaryAttributeValue'));
				accountMarketoActivity.Marketo_Activity_Timestamp__c = DateTime.valueofGMT(String.valueof(activityObjMap.get('activityDate')).replace('T',' ').replace('Z', ''));
				accountMarketoActivityList.add(accountMarketoActivity);
			}

			tokenValue = (String)responseMap.get('nextPageToken');
			moreResult = (Boolean)responseMap.get('moreResult');
			calloutCount++;
		}

		upsert accountMarketoActivityList Activity_Id__c;

		if(moreResult){
			System.enqueueJob(new AccountMarketoActivityQueueable(dateTimeParameter, tokenValue));
		}

		if(!Test.isRunningTest() && !moreResult){
			Database.executeBatch(new MarketoCampaignSyncBatch());
		}
	}
}