objects/Account.object
<CustomObject>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/icServiceOptimizeAccountsDay7.cls
/**
 * Created by Francois Poirier on 2018-07-20.
 */

public with sharing class icServiceOptimizeAccountsDay7 {

    public static void optimizeAccountAtDay7(){

        Date sevenDaysAgo = Date.today().addDays(-7);

        List<Account> accountsLive7Days = new List<Account>();
        List<Case> casesToInsert = new List<Case>();

        List<RecordType> recordTypes = new List<RecordType>();
        Id optimizationRTId;

        List<Group> groups = new List<Group>();
        Id actPerfQueueId;

        recordTypes = [
                SELECT  Id
                FROM    RecordType
                WHERE   Name = 'Optimization'
                AND     SobjectType = 'Case'
        ];

        if(recordTypes.size()>0){
            optimizationRTId = recordTypes[0].Id;
        }

        groups = [
                SELECT  Id
                FROM    Group
                WHERE   Name = 'Account performance Queue'
        ];

        if(groups.size()>0){
            actPerfQueueId = groups[0].Id;
        }
        List<Case> cases7DaysOpt = [
                SELECT  Id,
                        AccountId
                FROM    Case
                WHERE   RecordTypeId =: optimizationRTId
                AND     Subject = '7 day New Launch QA'
                AND     Account.Live_Date__c =: sevenDaysAgo
        ];

        List<Id> accountWith7DayCase = new List<Id>();

        for(Case c : cases7DaysOpt){
            accountWith7DayCase.add(c.AccountId);
        }


        accountsLive7Days = [
                SELECT  Id,
                        Name
                FROM    Account
                WHERE   Live_Date__c =: sevenDaysAgo
                AND     Product_Type_Transactional__c like '%Lead%'
                AND     Id NOT IN : accountWith7DayCase
        ];


        for(Account a : accountsLive7Days){
            Case newCase = new Case();

            newCase.AccountId = a.Id;
            newCase.Subject = '7 day New Launch QA';
            newCase.Reason2__c = 'Proactive by Analyst';
            newCase.RecordTypeId = optimizationRTId;
            newCase.OwnerId = actPerfQueueId;


            casesToInsert.add(newCase);

        }

        if(casesToInsert.size()>0){
            insert casesToInsert;
        }
    }
}