objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>Field Sales Rep Email Address</description>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Name_YL__c</fullName>
        <description>Sales Rep synced from Yodle Live Integration; must be a Text field and not a Lookup because the Sync may send a Sales Rep that is not a current Salesforce User</description>
        <inlineHelpText>Sales Rep Name is case-sensitive and must have the proper case to associate the User email address (Sales Rep Email) and populate properly. If all these conditions are met and the Email address is still blank, the Sales Rep is not a licensed SFDC user.</inlineHelpText>
        <label>Sales Rep Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountSalesRepEmailUpdateTest.cls
@isTest(seeAllData=true)
private class AccountSalesRepEmailUpdateTest
{
    private static testMethod void updateSalesRepEmailTest()
    {
       // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<Id> acctIds = new List<Id>();
        List<Account> dmlAccounts = new List<Account>();
        
        String salesRepName = [SELECT Name FROM User WHERE IsActive = true LIMIT 1].Name;
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        String acctName = acct.Name;
        String acctClientId = '123456799';
        string acctClientType = 'Local';
        
        acct.Sales_Rep_Email__c = 'test123@test.com';
        acct.Sales_Rep_Name_YL__c = salesRepName;
        acct.Client_Type__c = acctClientType;
        acct.Client_Id__c = acctClientId;
        dmlAccounts.add(acct);
        
        System.Debug('Account from (Account): ' + acctName);
        
        if(dmlAccounts.size() > 0){
            update dmlAccounts;
            
            for(Account a : dmlAccounts){
                acctIds.add(a.Id);
            }
        }
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        AccountSalesRepEmailUpdate.UpdateSalesRepEmail(acctIds);
        
        Test.stopTest();
    }
}