objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSC_Completed_Date__c</fullName>
        <label>CSC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Children_Accounts_Live__c</fullName>
        <label>Children Accounts Live</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>CSC_Completed_Date__c</fullName>
        <label>CSC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSC Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Install_Date__c</fullName>
        <label>Install Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Practice_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>Post Install Ready</fullName>
                </value>
                <value>
                    <fullName>Post Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Logo Complete</fullName>
                </value>
                <value>
                    <fullName>Logo Ready</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Escalated (Bolt On)</fullName>
                </value>
                <value>
                    <fullName>Backed Out Sale</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>BOT Feature Request</fullName>
                </value>
                <value>
                    <fullName>Escalated (Dev)</fullName>
                </value>
                <value>
                    <fullName>Escalated (Internal)</fullName>
                </value>
                <value>
                    <fullName>MA-1 Ready</fullName>
                </value>
                <value>
                    <fullName>MA-2 Pending Review</fullName>
                </value>
                <value>
                    <fullName>MA-3 Pending Config</fullName>
                </value>
                <value>
                    <fullName>MA-4 Pending Input</fullName>
                </value>
                <value>
                    <fullName>MA-5 Config Done Pending Approval</fullName>
                </value>
                <value>
                    <fullName>MA-6 Ready/Config Complete</fullName>
                </value>
                <value>
                    <fullName>MA-7 Suspended for Fix</fullName>
                </value>
                <value>
                    <fullName>MA-8 Multi Location Split</fullName>
                </value>
                <value>
                    <fullName>Messages Activated</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Retention</fullName>
                </value>
                <value>
                    <fullName>RFC</fullName>
                </value>
                <value>
                    <fullName>S. Consultant Assistance Needed</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MyAccountSummaryController.cls
global without sharing class MyAccountSummaryController {
	// hardcode an account id for demo purposes
	static String accountId;
	private static User currentUser = [select Id, AccountId from User where Id =: UserInfo.getUserId()];

	public Boolean displayAccountSummary {get; set;}

	public MyAccountSummaryController(){
		displayAccountSummary = false;
		if(String.isNotBlank(currentUser.AccountId)){
			displayAccountSummary = true;
		}else if(String.isNotBlank(ApexPages.currentPage().getParameters().get('clientAccountId'))){
			displayAccountSummary = true;
		}
	}

	global static String getAccount() {
		if(String.isNotBlank(currentUser.AccountId)){
			accountId = currentUser.AccountId;
		}else if(String.isNotBlank(ApexPages.currentPage().getParameters().get('clientAccountId'))){
			accountId = ApexPages.currentPage().getParameters().get('clientAccountId');
		}else{
			accountId = [select Id, Name from Account where RecordType.Name = 'Partner Master Account' and Partner_Status__c = 'Customer' order by Name limit 1].Id;
		}

		return JSON.serialize([select name, Client_ID__c, Phone, Children_Accounts_Live__c, BillingStreet, BillingState, BillingCity, billingpostalcode, Partner_Status__c from account where id = :accountId][0]);
	}    

	global static String getChildAccounts() {
		List<ChildAccountWrapper> newChildAccountWrapper = new List<ChildAccountWrapper>();
		for(Account record : [select name, Phone, Client_ID__c, Status__c, Order_Date__c, Live_Date__c, (select Install_Date__c, RecordType.Name, CSC_Completed_Date__c, Status__c from Lighthouse_Worksheets__r where RecordType.Name in ('Installation Worksheet', 'CSC Worksheet - Dental') order by CreatedDate DESC) from Account where ParentId = :accountId and (NOT Name like '%TEST') order by Name]){
			ChildAccountWrapper newChildWrapper = new ChildAccountWrapper();
			newChildWrapper.name = record.Name;
			newChildWrapper.phone = record.Phone;
			newChildWrapper.clientId = record.Client_ID__c;
			newChildWrapper.status = record.Status__c;
			newChildWrapper.orderDate = record.Order_Date__c;
			newChildWrapper.liveDate = record.Live_Date__c;

			for(Lighthouse_Worksheets__c lw : record.Lighthouse_Worksheets__r){
				if(lw.RecordType.Name == 'Installation Worksheet' && newChildWrapper.installCompleted == null && lw.Install_Date__c != null){
					newChildWrapper.installCompleted = lw.Install_Date__c;
				}else if(lw.RecordType.Name == 'CSC Worksheet - Dental' && String.isBlank(newChildWrapper.cscStatus)){
					newChildWrapper.cscStatus = lw.Status__c;
					newChildWrapper.cscCompleted = lw.CSC_Completed_Date__c;
				}
			}


			newChildAccountWrapper.add(newChildWrapper);
		}
		return JSON.serialize(newChildAccountWrapper);
	}

	private Class ChildAccountWrapper {
		private String name;
		private String phone;
		private String clientId;
		private String status;
		private Date orderDate;
		private Date liveDate;
		private Date installCompleted;
		private Date cscCompleted;
		private String cscStatus;
	}
}