objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Name_YL__c</fullName>
        <description>Sales Rep synced from Yodle Live Integration; must be a Text field and not a Lookup because the Sync may send a Sales Rep that is not a current Salesforce User</description>
        <inlineHelpText>Sales Rep Name is case-sensitive and must have the proper case to associate the User email address (Sales Rep Email) and populate properly. If all these conditions are met and the Email address is still blank, the Sales Rep is not a licensed SFDC user.</inlineHelpText>
        <label>Sales Rep Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked when Process Builder - WBN IL Contract Creation runs.</description>
        <label>Contract Auto Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <inlineHelpText>What products are being purchased in this opportunity?</inlineHelpText>
        <label>Products Sold</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Miner</fullName>
                </value>
                <value>
                    <fullName>Centermark</fullName>
                </value>
                <value>
                    <fullName>Centermark Lite</fullName>
                </value>
                <value>
                    <fullName>Client Side Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Display</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded PPC</fullName>
                </value>
                <value>
                    <fullName>Corporate Website</fullName>
                </value>
                <value>
                    <fullName>Corp Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Custom Implementation</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Email (Integrated)</fullName>
                </value>
                <value>
                    <fullName>Email (Non-Integrated)</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Foundations</fullName>
                </value>
                <value>
                    <fullName>Get Found</fullName>
                </value>
                <value>
                    <fullName>Google 360</fullName>
                </value>
                <value>
                    <fullName>IL Paid Foundations</fullName>
                </value>
                <value>
                    <fullName>IL Paid PPC</fullName>
                </value>
                <value>
                    <fullName>IL Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Leads by Web / G1</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Local Business Listings</fullName>
                </value>
                <value>
                    <fullName>Local SEO</fullName>
                </value>
                <value>
                    <fullName>National SEO</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>PPC</fullName>
                </value>
                <value>
                    <fullName>PPC Location Adoption</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractLength__c</fullName>
        <inlineHelpText>Use this for WBN Corporate Opportunities</inlineHelpText>
        <label>Contract Length (Mth)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductChargeType__c</fullName>
        <label>Product Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProductChargeType</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Create_NCS_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Decides wether an NCS Case should be created based on the Product</description>
        <inlineHelpText>Decides wether an NCS Case should be created based on the Product; if checked, code will look at the Family as well to decide what attributes to add to the Case</inlineHelpText>
        <label>Create NCS Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductChargeType__c</fullName>
        <label>Product Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProductChargeType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ProductChargeType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring</fullName>
    </customValue>
    <customValue>
        <fullName>PPC Seasonal</fullName>
    </customValue>
    <customValue>
        <fullName>PPC Monthly</fullName>
        <isActive>false</isActive>
        <label>PPC Monthly</label>
    </customValue>
    <masterLabel>Product Charge Type</masterLabel>
</GlobalValueSet>

classes/OpportunityClosedWonContractTest.cls
@isTest
private class OpportunityClosedWonContractTest 
{

    private static testMethod void contractAndLinesTest()
    {
        // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<SObject> oppList = Test.LoadData(Opportunity.sObjectType, 'testOpportunities');
        List<Id> oppIds = new List<Id>();
        Date todayDt = Date.Today();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('YBN - Individual Location').getRecordTypeId();
        Id oppOwner =  [SELECT Id FROM User WHERE IsActive = true AND Profile.Name = 'Nationally Certified Sales Executive' LIMIT 1].Id;
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        acct.IMS_Rep__c = oppOwner;
        acct.Sales_Rep_Name_YL__c = 'Eugene Ross';
        update acct;
        
        Opportunity opp = (Opportunity)oppList[0];
        Id oppId = opp.Id;
        opp.RecordTypeId = oppRecordTypeId;
        opp.OwnerId = oppOwner;
        opp.AccountId = acctId;
        opp.StageName = 'New Opportunity';
        opp.CloseDate = todayDt.addDays(-3);
        opp.Contract_Auto_Created__c = false;
        update opp;
        
        oppIds.add(oppId);
        
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prod1 = new Product2(
             Name = 'Facebook Addition',
             ProductCode = 'FBA',
             isActive = true,
             Family = 'Facebook',
             Create_NCS_Case__c = true,
             ProductChargeType__c = 'Recurring'
        );
        insert prod1;
        
        //Create your pricebook entry
        PricebookEntry pbEntry1 = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod1.Id,
             UnitPrice = 0.00,
             IsActive = true
        );
        insert pbEntry1;
        
        OpportunityLineItem oli1 = new OpportunityLineItem(
            OpportunityId = oppId,
            Quantity = 1,
            PricebookEntryId = pbEntry1.Id,
            TotalPrice = 1 * pbEntry1.UnitPrice,
            ContractLength__c = 1
        );
        insert oli1;
        
        //opp.StageName = 'Closed Won';
        //opp.Products__c = 'PPC Addition';
        //update opp;
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        OpportunityClosedWonContract.wbnClosedWonContracts(oppIds);
        
        Test.stopTest();
    }

}