objects/Account.object
<CustomObject>
    <fields>
        <fullName>Days_Since_Live__c</fullName>
        <formula>today()- Live_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Live</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_in_Save_Mode__c</fullName>
        <inlineHelpText>Used for Accounts going into Save Mode from Cancellation Request Forms!</inlineHelpText>
        <label>Days in Save Mode</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Custom_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Account_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Automation_Status__c</fullName>
        <label>Automation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Outcome</fullName>
                    <default>true</default>
                    <label>Waiting on Outcome</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Trigger_Date__c</fullName>
        <label>Automation Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Automation_Type_API_Name_External_ID__c</fullName>
        <inlineHelpText>Use the Touchplan API Name for Custom Metadata Types or the assigned External ID for Marketo Email Campaign</inlineHelpText>
        <label>Automation Type API Name/External ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create_Day_40_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>Create_Monthly_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_7</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_27</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_DAY_40</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_EVERY_30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Type__c</fullName>
        <label>Automation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketo_Email_Campaign__c</fullName>
                </value>
                <value>
                    <fullName>Daily_Scheduled_Record_Auto_Create__mdt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancellation_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cancellation Request</label>
        <referenceTo>Cancellation_Request__c</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Cancellation_Request_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Since_Live_Equivalent_on_Request__c</fullName>
        <inlineHelpText>Days Since Live when a Cancellation Request was created for LBW and the number of days since the CSC was created and the Cancellation Request was created for TORCHx.</inlineHelpText>
        <label>Days Since Live Equivalent on Request</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_in_Cancellation__c</fullName>
        <label>Days in Cancellation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Custom Automation</label>
    <nameField>
        <displayFormat>AAN-{0000000}</displayFormat>
        <label>Custom Automation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Daily_Scheduled_Record_Auto_Create__mdt.object
<CustomObject>
    <label>Daily Scheduled Record Auto Create</label>
    <pluralLabel>Daily Scheduled Record Auto Create</pluralLabel><visibility>Public</visibility>
</CustomObject>

objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketo Email Campaigns</relationshipLabel>
        <relationshipName>Marketo_Email_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomAutomationObjectHelper.cls
public without sharing class CustomAutomationObjectHelper {
    private static Map<Id, Account> torchxAccountMap = new Map<Id, Account>();
    private static Map<Id, Account> lbwAccountMap = new Map<Id, Account>();

    private static Map<Id, Account> accountTORCHXandLBWMap = new Map<Id, Account>();

    private static Set<Id> accountIdSet = new Set<Id>();

    public static void afterInsert(Map<Id, Custom_Automation__c> newMapValues){
        accountIdSet = relatedAccountIdList(newMapValues.values());

        if(accountIdSet.isEmpty()){
            return;
        }

        accountTORCHXandLBWMap = AccountObjectHelper.getTORCHXandLBWAccountMap(accountIdSet);

        for(Account acct : accountTORCHXandLBWMap.values()){
            if(acct.Product_Type_Transactional__c.containsIgnoreCase('Leads By Web') || acct.Product_Type_Transactional__c.containsIgnoreCase('Lead Stream ATV')){
                lbwAccountMap.put(acct.Id, acct);
            }else if(acct.Product_Type_Transactional__c.containsIgnoreCase('TORCHX')){
                torchxAccountMap.put(acct.Id, acct);
            }
        }

        if(!lbwAccountMap.isEmpty()){
            updateCaseLBWSaveMode();
        }

        if(!torchxAccountMap.isEmpty()){
            updateCaseTORCHXSaveMode();
        }
    }

    public static void beforeUpdate(Map<Id, Custom_Automation__c> newMapValues, Map<Id, Custom_Automation__c> oldMapValues){
        accountIdSet = relatedAccountIdList(newMapValues.values());

        if(accountIdSet.isEmpty()){
            return;
        }

        accountTORCHXandLBWMap = AccountObjectHelper.getTORCHXandLBWAccountMap(accountIdSet);

        for(Account acct : accountTORCHXandLBWMap.values()){
            if(acct.Product_Type_Transactional__c.containsIgnoreCase('Leads By Web') || acct.Product_Type_Transactional__c.containsIgnoreCase('Lead Stream ATV')){
                lbwAccountMap.put(acct.Id, acct);
            }else if(acct.Product_Type_Transactional__c.containsIgnoreCase('TORCHX')){
                torchxAccountMap.put(acct.Id, acct);
            }
        }

        if(!lbwAccountMap.isEmpty()){
            evaluateLBWSaveMode(newMapValues, oldMapValues);
        }

        if(!torchxAccountMap.isEmpty()){
            evaluateTORCHXSaveMode(newMapValues, oldMapValues);
        }
    }

    public static void afterUpdate(Map<Id, Custom_Automation__c> newMapValues, Map<Id, Custom_Automation__c> oldMapValues){
        List<Account> updateAccountDaysInCancellationField = new List<Account>();

        for(Custom_Automation__c record : newMapValues.values()){
            Custom_Automation__c oldRecord = oldMapValues.get(record.Id);
            if(String.isNotBlank(record.Account__c) && record.Days_In_Cancellation__c != null && record.Days_In_Cancellation__c != oldRecord.Days_In_Cancellation__c){
                Account updateAcct = new Account();
                updateAcct.Id = record.Account__c;
                updateAcct.Days_in_Save_Mode__c = record.Days_In_Cancellation__c;

                updateAccountDaysInCancellationField.add(updateAcct);
            }
        }

        if(!updateAccountDaysInCancellationField.isEmpty()){
            Database.update(updateAccountDaysInCancellationField, false);
        }
    }

    public static void setAutomationStatusFromCancellationRequest(List<Cancellation_Request__c> cancellationRequestList){
        Set<String> cancellationSavedOutcomeSet = getCancellationSavedOutcomeSet();
        Set<String> cancellationAbortOutcomeSet = getCancellationAbortOutcomeSet();
        
        List<Custom_Automation__c> updateCustomAutomationStatusList = new List<Custom_Automation__c>();

        for(Custom_Automation__c record : [select Id, Automation_Status__c, Cancellation_Request__c, Cancellation_Request__r.Outcome__c from Custom_Automation__c where Cancellation_Request__c in : cancellationRequestList]){
            if(cancellationSavedOutcomeSet.contains(record.Cancellation_Request__r.Outcome__c)){
                record.Automation_Status__c = 'Evaluating';
            }else if(cancellationAbortOutcomeSet.contains(record.Cancellation_Request__r.Outcome__c)){
                record.Automation_Status__c = 'Aborted';
            }else if(record.Cancellation_Request__r.Outcome__c.equalsIgnoreCase('In Progress')){
                record.Automation_Status__c = 'Waiting on Outcome';
            }/*else if(record.Cancellation_Request__r.Outcome__c.equalsIgnoreCase('Duplicate Retention Case')){
                record.Automation_Status__c = 'No Action Needed';
            }*/else{
                continue;
            }

            updateCustomAutomationStatusList.add(record);
        }

        if(!updateCustomAutomationStatusList.isEmpty()){
            update updateCustomAutomationStatusList;
        }
    }

    private static Set<String> getCancellationSavedOutcomeSet(){
        Set<String> cancellationSavedOutcomeSet = new Set<String>();
        for(String str : Label.CancellationSavedOutcome.split(';')){
            cancellationSavedOutcomeSet.add(str.trim());
        }

        return cancellationSavedOutcomeSet;
    }

    private static Set<String> getCancellationAbortOutcomeSet(){
        Set<String> cancellationAbortOutcomeSet = new Set<String>();
        for(String str : Label.CancellationOutcome2AbortAutomation.split(';')){
            cancellationAbortOutcomeSet.add(str.trim());
        }

        return cancellationAbortOutcomeSet;
    }

    private static void evaluateTORCHXSaveMode(Map<Id, Custom_Automation__c> newMapValues, Map<Id, Custom_Automation__c> oldMapValues){
        // UPDATE THE STATUS FOR TORCHX !!! MAYBE MAKE IT CUSTOM SETTING OR CUSTOM LABEL!!~!!!!!!!!!
        Set<Id> accountWithRecentlyCreatedMonthlyCaseSet = new Set<Id>();
        for(Account record : [select Id from Account where Id in (select AccountId from Case where Subject like '%Schedule your next call: Monthly Review%' and CreatedDate = LAST_N_DAYS:26) and Id in :torchxAccountMap.keySet()]){
            accountWithRecentlyCreatedMonthlyCaseSet.add(record.Id);
        }

        for(Custom_Automation__c record : newMapValues.values()){
            if(String.isBlank(record.Automation_Status__c) || !record.Automation_Status__c.equalsIgnoreCase('Evaluating')){
                continue;
            }
            if(torchxAccountMap.containsKey(record.Account__c)){
                record.Days_In_Cancellation__c = saveModeDaysCalc(record.CreatedDate.date());

                Integer effectiveDaysSinceLive = (Integer)record.Days_Since_Live_Equivalent_on_Request__c;

                if(effectiveDaysSinceLive <= 37 || accountWithRecentlyCreatedMonthlyCaseSet.contains(record.Account__c)){
                    record.Automation_Status__c = 'Aborted';
                    record.Automation_Type_API_Name_External_ID__c = '';
                }else{
                    Integer daysSinceFirstTP = effectiveDaysSinceLive - 37;

                    Integer remainder = math.mod(daysSinceFirstTP, 30);

                    Integer noDaysNeeded = (remainder < 0) ? remainder * (-1) : 30 - remainder;
                    record.Automation_Trigger_Date__c = Date.today().addDays(noDaysNeeded);
                    record.Automation_Type_API_Name_External_ID__c = 'TORCHX_MONTHLY_REVIEW_EVERY_30';
                    record.Automation_Type__c = 'Marketo_Email_Campaign__c';
                    record.Automation_Status__c = 'Scheduled';
                }
            }
        }
    }

    private static void evaluateLBWSaveMode(Map<Id, Custom_Automation__c> newMapValues, Map<Id, Custom_Automation__c> oldMapValues){
        Set<Id> accountWithRecentlyCreatedMonthlyCaseSet = new Set<Id>();
        for(Account record : [select Id from Account where Id in (select AccountId from Case where Subject like '%LBW Monthly Touchplan%' and CreatedDate = LAST_N_DAYS:29) and Id in :lbwAccountMap.keySet()]){
            accountWithRecentlyCreatedMonthlyCaseSet.add(record.Id);
        }

        for(Custom_Automation__c record : newMapValues.values()){
            if(!record.Automation_Status__c.equalsIgnoreCase('Evaluating')){
                continue;
            }
            if(lbwAccountMap.containsKey(record.Account__c)){
                record.Days_In_Cancellation__c = saveModeDaysCalc(record.CreatedDate.date());

                Integer daysSinceFirstTP = (Integer)lbwAccountMap.get(record.Account__c).Days_Since_Live__c - 27;

                if(daysSinceFirstTP <= 0 || accountWithRecentlyCreatedMonthlyCaseSet.contains(record.Account__c)){
                    record.Automation_Status__c = 'Aborted';
                    record.Automation_Type_API_Name_External_ID__c = '';
                    continue;
                }

                Integer remainder = math.mod(daysSinceFirstTP, 30);

                Integer noDaysNeeded = (remainder < 0) ? remainder * (-1) : 30 - remainder;
                record.Automation_Trigger_Date__c = Date.today().addDays(noDaysNeeded);
                record.Automation_Type_API_Name_External_ID__c = 'Create_Monthly_LBW_Account_Performance';
                record.Automation_Status__c = 'Scheduled';
                record.Automation_Type__c = 'Daily_Scheduled_Record_Auto_Create__mdt';
            }
        }
    }

    private static Integer saveModeDaysCalc(Date requestCreatedDate){
        return requestCreatedDate.daysBetween(Date.today());
    }

    private static void updateCaseTORCHXSaveMode(){
        List<Case> updateCaseList = new List<Case>();

        for(Case record : [select Id, Status from Case where AccountId in :torchxAccountMap.keySet() and IsClosed = false and RecordType.Name = 'Outbound Call' and Subject IN ('Schedule your next call: Managing Relationships', 'Schedule your next call: Monthly Review', 'Schedule your next call: Advanced Features') and Reason = 'CS Touch Plan']){
            record.Status = 'Did Not Complete';
            updateCaseList.add(record);
        }

        if(!updateCaseList.isEmpty()){
            Database.update(updateCaseList, false);
        }
    }

    private static void updateCaseLBWSaveMode(){
        List<Case> updateCaseList = new List<Case>();

        for(Case record : [select Id, Status from Case where AccountId in :lbwAccountMap.keySet() and IsClosed = false and RecordType.Name = 'Outbound Call' and Subject like 'LBW Monthly Touchplan%' and Reason = 'CS Touch Plan']){
            record.Status = 'Churned';
            updateCaseList.add(record);
        }

        if(!updateCaseList.isEmpty()){
            Database.update(updateCaseList, false);
        }
    }

    private static Set<Id> relatedAccountIdList(List<Custom_Automation__c> customAutomationList){
        Set<Id> acctIdSet = new Set<Id>();

        for(Custom_Automation__c record : customAutomationList){
            if(String.isNotBlank(record.Account__c)){
                acctIdSet.add(record.Account__c);
            }
        }

        return acctIdSet;
    }

}