objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>Field Sales Rep Email Address</description>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>if( 
or( 
ispickval( Outcome__c , "Churned"), 
ispickval( Outcome__c , "Saved with No Concessions"), 
ispickval( Outcome__c , "Saved with Hard Concessions"), 
ispickval( Outcome__c , "Saved with Soft Concessions"), 
ispickval( Outcome__c , "Saved with Upsell"), 
ispickval( Outcome__c , "Saved By Sales"), 
ispickval( Outcome__c , "Saved With Free Time"),
ispickval( Outcome__c , "Saved With Winback"),
ispickval( Outcome__c , "Cancelled"), 
ispickval( Outcome__c , "Saved - Bailout Pricing - Standard"), 
ispickval( Outcome__c , "Saved - Bailout Pricing - Custom"), 
ispickval( Outcome__c , "Saved with Discount"), 
ispickval( Outcome__c , "Saved with OBC Package"), 
ispickval( Outcome__c , "Downsold to LH Only"), 
ispickval( Outcome__c , "Downsold to LH+ProPack"), 
ispickval( Outcome__c , "Downsold to LH+ProPack+Mobile Manager"), 
ispickval( Outcome__c , "Ad Station Credit"), 
ispickval( Outcome__c, "Duplicate Retention Case") 
), 
true, 
false)</formula>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendCancellationDMCNotifcation.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 26-Apr-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 26-Apr-2018
  Description ........: Class contains invocable method to send notification emails to DMC where email address is 
                        from cross object Account email field (Sales Rep Email).
*****************************************************************************/
public class SendCancellationDMCNotifcation
{
    @InvocableMethod
    public static void SendDMCNotification(List<Id> cancelRequestIds)
    {
        try{
        
            if(cancelRequestIds.size() > 0){
            
                Set<Id> acctIdSet = new Set<Id>();
                Map<Id, Cancellation_Request__c> cancelRequestDetailsMap = new Map<Id, Cancellation_Request__c>();
                List<Messaging.SingleEmailMessage> notificationsLst = new List<Messaging.SingleEmailMessage>();
                OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'sfdc@yodle.com'];
                
                // get Account Ids and add to set
                for(Cancellation_Request__c c :
                    [SELECT Id,
                            Account_Name__c,
                            CreatedDate,
                            Closed_Date__c,
                            Outcome__c,
                            IsClosed__c,
                            Name
                       FROM Cancellation_Request__c
                      WHERE Id IN :cancelRequestIds]){
                
                    // check to ensure AccountId is populated on Cancellation Request
                    if(c.Account_Name__c != null){
                    
                        // add AccountId from Cancellation Request to set
                        acctIdSet.add(c.Account_Name__c);
                        cancelRequestDetailsMap.put(c.Account_Name__c, c);
                    }
                }
                
                if(acctIdSet.size() > 0){
                    
                    // get Email Address from associated Account
                    for(Account a:
                        [SELECT Id,
                                Sales_Rep_Email__c,
                                Name
                           FROM Account
                          WHERE Id IN :acctIdSet]){
                    
                        if(a.Sales_Rep_Email__c != null){
                        
                            // send notification to DMC
                            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                        
                            List<String> toAddress = new List<String>();
                            String subjectStatus = (cancelRequestDetailsMap.get(a.Id).Outcome__c == 'New' ? 'Cancel Request Created' : 'Cancel Request Status Update');
                            String fromAddress = 'sfdc@yodle.com';
                            String fromDisplayName = 'Salesforce Notifications';
                            String subjectLine = a.Name + ' - ' + subjectStatus;
                            toAddress.add(a.Sales_Rep_Email__c);
                            String body = 'Below are the Account details related to Cancellation Request ' + cancelRequestDetailsMap.get(a.Id).Name + ': <br/><br/> ';
                            body += '<b>Account:</b> ' + a.Name + '<br/><br/>';
                            body += '<b>Create Date:</b> ' + cancelRequestDetailsMap.get(a.Id).CreatedDate + '<br/><br/>';
                            body += '<b>Status:</b> ' + cancelRequestDetailsMap.get(a.Id).Outcome__c + '<br/><br/>';
                            body += '<b>Close Date:</b> ' + (cancelRequestDetailsMap.get(a.Id).IsClosed__c == true ? String.valueOf(cancelRequestDetailsMap.get(a.Id).Closed_Date__c) : 'Not Yet Closed') + '<br/><br/>';
     
                            // set message content
                            message.setToAddresses(toAddress);
                            message.setReplyTo(fromAddress);
                            message.setOrgWideEmailAddressId(owea.get(0).Id);
                            message.setSubject(subjectLine);
                            message.setHtmlBody(body);

                            notificationsLst.add(message);
                        }
                    }
                    
                    if(notificationsLst.size() > 0){
                        
                        // send notifications
                        Messaging.sendEmail(notificationsLst);
                    }
                }
            }
        }
        catch(Exception e){
            System.Debug('An error occurred: ' + e.getMessage());
        }
    }
}