objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Marketing_Development_Fund__c.object
<CustomObject>
    <fields>
        <fullName>MDF_Date_Submitted__c</fullName>
        <label>MDF Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Marketing Development Funds</relationshipLabel>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Marketing Development Fund</label>
    <nameField>
        <displayFormat>PMDF-{0000000}</displayFormat>
        <label>Partner MDF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Marketing Development Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MDFRequestFormController.cls
public with sharing class MDFRequestFormController {
	public Partner_Marketing_Development_Fund__c pmdf {get; set;}

	private User currentUser;

	public MDFRequestFormController() {
		pmdf = new Partner_Marketing_Development_Fund__c();

		if(UserInfo.getUserType() == 'Standard'){
			currentUser = [select Id, Name, AccountId, IsPortalEnabled from User where Id =: UserInfo.getUserId()];
		}else{
			currentUser = [select Id, Name, AccountId, IsPortalEnabled, Account.Name, ContactId, Contact.Name, Account.OwnerId from User where Id =: UserInfo.getUserId()];
		}

		if(String.isNotBlank(currentUser.AccountId)){
			pmdf.Partner_Account__c = currentUser.AccountId;
			pmdf.OwnerId = currentUser.Account.OwnerId;
		}else if(String.isNotBlank(ApexPages.currentPage().getParameters().get('clientAccountId'))){
			pmdf.Partner_Account__c = ApexPages.currentPage().getParameters().get('clientAccountId');
			pmdf.OwnerId = [select OwnerId from Account where Id = :ApexPages.currentPage().getParameters().get('clientAccountId')].OwnerId;
		}
		pmdf.Requested_By__c = currentUser.Id;
		pmdf.MDF_Date_Submitted__c = Date.today();
	}

	public void refreshRerender(){

	}

	public PageReference submitMDFRequestForm(){
		try{
			insert pmdf;

			PageReference pageRef = Page.PartnerMarketingDevelopmentFundsTab;
			pageRef.getParameters().put('selectedTab', 'name3');
			pageRef.getParameters().put('initialSelectedId', pmdf.Id);
			pageRef.setRedirect(true);
			return pageRef;
		}catch(Exception E){
			return null;
		}
	}
}