objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmailMessage.object
<CustomObject>
    <fields>
        <fullName>ClonedEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Designates if an email was cloned via Apex Code.</description>
        <label>Cloned Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OriginalEmailId__c</fullName>
        <label>Original Email Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
<enableFeeds>false</enableFeeds></CustomObject>

classes/UTest_CloneEmailAttachment.cls
@isTest
private class UTest_CloneEmailAttachment {
    private static final id rtAccStandard = Utilities.GetRecTypeId('Account', 'Standard');
    private static final id rtCasLHmaster = Utilities.GetRecTypeId('Case', 'LH Master');
    
    static testMethod void test_cloneEmailAttach(){
        Account a = new Account(Name='UnitTest Account', recordtypeId=rtAccStandard);
        insert a;
        
        Case c = new Case(Status = 'New', AccountId = a.Id, RecordTypeId = rtCasLHmaster);
        insert c;
        
        EmailMessage em = new EmailMessage(FromAddress = 'test@abc.org', 
                                           Incoming = True, 
                                           ToAddress='unittestingsalesforce@unittestingsalesforce.com', 
                                           Subject = 'UnitTest Email', 
                                           TextBody = '23456 ', 
                                           ParentId = c.Id); 
        
        insert em; 
        
        EmailMessage emClone = new EmailMessage(FromAddress = 'test@abc.org', 
                                           Incoming = True, 
                                           ToAddress='unittestingsalesforce@unittestingsalesforce.com', 
                                           Subject = 'UnitTest Email', 
                                           TextBody = '23456 ', 
                                           ParentId = c.Id,
                                           ClonedEmail__c = true,
                                           OriginalEmailId__c = em.Id); 
        
        insert emClone; 
        
        system.assertEquals(0, [SELECT count() FROM Attachment WHERE ParentId = :emClone.Id]);
        
        Attachment att = new Attachment();
        att.Name = 'UnitTest Attachment';
        att.Body = Blob.valueOf('UnitTest Body Blob');
        att.ParentId = em.Id;
        insert att;
        
        system.assertEquals(1, [SELECT count() FROM Attachment WHERE ParentId = :emClone.Id]);
    }
}