objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Score__c</fullName>
        <label>Partner Score</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Community_HTML__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Bindings__c</fullName>
        <label>Field Bindings</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HTML__c</fullName>
        <label>HTML</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Partner Community HTML</label>
    <nameField>
        <label>Partner Community HTML Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Community HTML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PartnerTrainingController.cls
public without sharing class PartnerTrainingController {
	public Partner_Community_HTML__c htmlInfo {get; set;}
	
	public PartnerTrainingController() {
		htmlInfo = [select Id, Name, HTML__c, Field_Bindings__c from Partner_Community_HTML__c where Name = 'LighthouseTraining' and Active__c = true limit 1];

		User currentUser = [select Id, Name, AccountId, IsPortalEnabled, Account.Partner_Score__c from User where Id =: UserInfo.getUserId()];

		if(currentUser.IsPortalEnabled && String.isNotBlank(currentUser.AccountId)){
			currentUser = [select Id, Name, AccountId, Account.OwnerId, IsPortalEnabled, ContactId, Account.Partner_Score__c from User where Id =: UserInfo.getUserId()];

			User acctOwner = [select Id, Name, Title, Phone, Email from User where Id =: currentUser.Account.OwnerId];
			system.debug(acctOwner);
			htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Owner.Name}', acctOwner.Name);
			if(String.isNotBlank(acctOwner.Title)){
				htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Owner.Title}', acctOwner.Title);
			}
			if(String.isNotBlank(acctOwner.Phone)){
				htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Owner.Phone}', acctOwner.Phone);
			}
			if(String.isNotBlank(acctOwner.Email)){
				htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Owner.Email}', acctOwner.Email);
			}

			Account acct = [select Id, Name, Partner_Score__c from Account where Id =: currentUser.AccountId];
			htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Account.Name}', acct.Name);

			if(String.isNotBlank(currentUser.ContactId)){
				Contact cont = [select Id, Name from Contact where Id = :currentUser.ContactId];
				htmlInfo.HTML__c = htmlInfo.HTML__c.replace('{Contact.Name}', cont.Name);
			}
		}

	}
}