objects/Account.object
<CustomObject>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Marketo_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account's Marketo Activity</relationshipLabel>
        <relationshipName>Account_s_Marketo_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Type</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipLabel>Account's Marketo Activity</relationshipLabel>
        <relationshipName>Account_s_Marketo_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketo Campaign</label>
        <referenceTo>Marketo_Campaign__c</referenceTo>
        <relationshipLabel>Account's Marketo Activity</relationshipLabel>
        <relationshipName>Account_s_Marketo_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketo_Lead_ID__c</fullName>
        <label>Marketo Lead ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Account Marketo Activity</label>
    <nameField>
        <displayFormat>AMA-{0000000}</displayFormat>
        <label>Account Marketo Activity  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account's Marketo Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Marketo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Marketo's Campaign ID field.</description>
        <externalId>true</externalId>
        <label>Campaign ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Marketo Campaign</label>
    <nameField>
        <label>Marketo Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountMarketoActivityTriggerHandler.cls
public without sharing class AccountMarketoActivityTriggerHandler {

	public static void beforeInsert(List<Account_Marketo_Activity__c> newList){
		acctMarketoActivityDataFill(newList);
	}

	public static void beforeUpdate(Map<Id, Account_Marketo_Activity__c> newValueMap, Map<Id, Account_Marketo_Activity__c> oldValueMap){
		List<Account_Marketo_Activity__c> amaListWithNoAccount = new List<Account_Marketo_Activity__c>();
		for(Account_Marketo_Activity__c record : newValueMap.values()){
			if(String.isBlank(record.Account__c)){
				amaListWithNoAccount.add(record);
			}
		}
		acctMarketoActivityDataFill(amaListWithNoAccount);
	}

	public static List<Account_Marketo_Activity__c> acctMarketoActivityDataFill(List<Account_Marketo_Activity__c> amaList){
		Set<String> accountIDsToSearch = new Set<String>();
		Set<String> marketoCampaignIDsToSearch = new Set<String>();
		Map<String, Set<String>> allPairings = new Map<String, Set<String>>();
		Map<String, Set<String>> usablePairings = new Map<String, Set<String>>();
		Set<String> marketoCampaignsToCreate = new Set<String>();

		for (Account_Marketo_Activity__c accountMarketoActivity : amaList) {
			if (String.isNotBlank(accountMarketoActivity.Marketo_Lead_ID__c) && String.isNotBlank(accountMarketoActivity.Campaign_ID__c)) {
				accountIDsToSearch.add(accountMarketoActivity.Marketo_Lead_ID__c);
				marketoCampaignIDsToSearch.add(accountMarketoActivity.Campaign_ID__c);
				Set<String> tempSet = allPairings.get(accountMarketoActivity.Marketo_Lead_ID__c);
				if (tempSet == null) {
					tempSet = new Set<String>();
				}
				tempSet.add(accountMarketoActivity.Campaign_ID__c);
				allPairings.put(accountMarketoActivity.Marketo_Lead_ID__c, tempSet);
			}
		}

		Map<String, Account> accountsThatExist = new Map<String, Account>();
		for (Account acct : [select Id, Marketo_ID__c from Account where Marketo_ID__c in :accountIDsToSearch]){
			accountsThatExist.put(acct.Marketo_ID__c, acct);
			usablePairings.put(acct.Marketo_ID__c, allPairings.get(acct.Marketo_ID__c));
		}

		Map<String, Marketo_Campaign__c> marketoCampaignsThatExist = new Map<String, Marketo_Campaign__c>();
		for (Marketo_Campaign__c markCam : [select Id, Campaign_ID__c from Marketo_Campaign__c where Campaign_ID__c in :marketoCampaignIDsToSearch]) {
			marketoCampaignsThatExist.put(markCam.Campaign_ID__c, markCam);
		}

		for (String leadId : usablePairings.keySet()) {
			for (String key : usablePairings.get(leadId)) {
				if (!marketoCampaignsThatExist.containsKey(key)) {
					marketoCampaignsToCreate.add(key);
				}
			}
		}

		List<Marketo_Campaign__c> mktCampaignList = new List<Marketo_Campaign__c>();
		for(String campaignId : marketoCampaignsToCreate){
			Marketo_Campaign__c newCampaign = new Marketo_Campaign__c();
			newCampaign.Campaign_ID__c = campaignId;
			marketoCampaignsThatExist.put(campaignId, newCampaign);
			mktCampaignList.add(newCampaign);
		}

		insert mktCampaignList;

		Map<String, Activity_Type__c> activityTypeMap = new Map<String, Activity_Type__c>();
		for (Activity_Type__c activityType : [select Id, Activity_Type_ID__c from Activity_Type__c]) {
			activityTypeMap.put(activityType.Activity_Type_ID__c, activityType);
		}

		for (Account_Marketo_Activity__c accountMarketoActivity : amaList) {
			accountMarketoActivity.Activity_Type__c = activityTypeMap.get(accountMarketoActivity.Activity_Type_ID__c).Id;
			if (accountsThatExist.containsKey(accountMarketoActivity.Marketo_Lead_ID__c) && String.isNotBlank(accountMarketoActivity.Marketo_Lead_ID__c) && String.isNotBlank(accountMarketoActivity.Campaign_ID__c)) {
				accountMarketoActivity.Account__c = accountsThatExist.get(accountMarketoActivity.Marketo_Lead_ID__c).Id;
				accountMarketoActivity.Marketo_Campaign__c = marketoCampaignsThatExist.get(accountMarketoActivity.Campaign_ID__c).Id;
			}
		}
		return amaList;
	}
}