objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Google_Listing_Status__c</fullName>
        <label>Google Listing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Listing</fullName>
                </value>
                <value>
                    <fullName>Active Listing - Read Only</fullName>
                </value>
                <value>
                    <fullName>Awaiting PIN</fullName>
                </value>
                <value>
                    <fullName>Awaiting Verification</fullName>
                </value>
                <value>
                    <fullName>Client Refuses Claim</fullName>
                </value>
                <value>
                    <fullName>Error Message</fullName>
                </value>
                <value>
                    <fullName>Migrated To Bulk Account</fullName>
                </value>
                <value>
                    <fullName>Needs Re-Verification</fullName>
                </value>
                <value>
                    <fullName>No Listing</fullName>
                </value>
                <value>
                    <fullName>Owner-Verified/Managed</fullName>
                </value>
                <value>
                    <fullName>Owner-Verified/Pending Management</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected - PO Box Used</fullName>
                </value>
                <value>
                    <fullName>Rejected Unknown</fullName>
                </value>
                <value>
                    <fullName>Restarted</fullName>
                </value>
                <value>
                    <fullName>Un-Claimable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AutoClosePANOrganicCasesTest.cls
@isTest(seeAllData=true)
private class AutoClosePANOrganicCasesTest
{
    private static testMethod void ClosePANOrganicCasesTest()
    {
        Id micCaseRecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        Id panCaseRecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('PIN Action Needed').getRecordTypeId();
        List<Id> micCaseIds = new List<Id>();
        
        Account acct = new Account();
        acct.Name = 'Test Account';
        insert acct;
        
        Organic_Analysis__c micCase = new Organic_Analysis__c();
        micCase.Account_Name__c = acct.Id;
        micCase.RecordTypeId = micCaseRecordTypeId;
        micCase.IsClosed__c = true;
        micCase.Google_Listing_Status__c = 'Owner-Verified/Managed';
        insert micCase;                 
        micCaseIds.add(micCase.Id);
        
        Organic_Analysis__c panCase = new Organic_Analysis__c();
        panCase.Account_Name__c = acct.Id;
        panCase.RecordTypeId = panCaseRecordTypeId;
        panCase.IsClosed__c = false;
        insert panCase;              
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        AutoClosePANOrganicCases.ClosePANOrganicCases(micCaseIds);
        
        Test.stopTest();
        
        panCase = [select Id, IsClosed__c, OwnerId, Status__c from Organic_Analysis__c where Id = :panCase.Id];
        
        
        system.assertEquals(true, panCase.IsClosed__c);         
        //system.assertEquals('Completed', panCase.Status);
    }
}