objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Client First Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Client Last Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Important_Account_Notes__c</fullName>
        <label>Important Account Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Completed_YBN_TP__c</fullName>
        <label>Last Completed YBN TP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Multi_Location_Owner_Primary_CID__c</fullName>
        <description>Client ID for which all communication gets logged - CS Managers allowed to access also</description>
        <label>Multi-Location Owner Primary CID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Billing_Date__c</fullName>
        <label>Next Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Multi_Location_Owner_For_TP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>- CS Managers allowed to access also</description>
        <label>Primary Multi-Location Owner For TP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Management__c</fullName>
        <label>Test Management</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>wrenBilling__c</fullName>
        <defaultValue>false</defaultValue>
        <label>wrenBilling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Franchise_Influencer__c</fullName>
        <inlineHelpText>(VIP) accounts within a network</inlineHelpText>
        <label>Franchise Influencer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <description>- CS Managers allowed to access also</description>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A+</fullName>
                </value>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account.Client_ID__c</formula>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <formula>Account.Client_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <formula>Account.Client_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
                <value>
                    <fullName>Service Level F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

classes/OppHLPanelControllerTest.cls
@isTest
public class OppHLPanelControllerTest {
    
    public static testMethod void loadOppHLPanelTest() {
    
        // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<SObject> oppList = Test.LoadData(Opportunity.sObjectType, 'testOpportunities');
        Id userId = [SELECT Id FROM User WHERE IsActive = true LIMIT 1].Id;
        Date nextBillDt = Date.Today().addDays(30);
        Date tpLastCompleted = Date.Today().addDays(-10);
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        acct.Client_First_Name__c = 'John';
        acct.Client_Last_Name__c = 'Doe';
        acct.Email__c = 'johnd@testcompany.com';
        acct.Phone = '5552134567';
        acct.Status__c = 'LIVE';
        acct.IMS_Rep__c = userId;
        acct.Product_Type__c = 'TORCHX';
        acct.Next_Billing_Date__c = nextBillDt;
        acct.Client_ID__c = '909999';
        acct.Website = 'www.testcompany.com';
        acct.Test_Management__c = 'Testing...';
        acct.Individual_Location_Service_Level__c = 'Service Level B';
        acct.Primary_Multi_Location_Owner_For_TP__c = false;
        acct.Multi_Location_Owner_Primary_CID__c = '99887766';
        acct.Last_Completed_YBN_TP__c = tpLastCompleted;
        acct.wrenBilling__c = false;
        acct.BillingCountry = 'USA';
        acct.Franchise_Influencer__c = 'No';
        acct.Important_Account_Notes__c = 'Test Notes...';
        update acct;
        
        Opportunity opp = (Opportunity)oppList[0];
        Id oppId = opp.Id;
        opp.AccountId = acctId;
        update opp;
        
        ApexPages.currentPage().getParameters().put('id', String.valueOf(oppId));
    
        OppHLPanelController controller = new OppHLPanelController();
        controller.onPageLoad();
    }
}