objects/Account.object
<CustomObject>
    <fields>
        <fullName>Pause_Touchplan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pause Touchplan</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountObjectHelper.cls
public without sharing class AccountObjectHelper {
	public static Boolean accountObjectHelperAlreadyFired = false;

	public static Map<Id, Account> getTORCHXandLBWAccountMap(Set<Id> accountIdSet){
		Map<Id, Account> accountTORCHXandLBWMap = new Map<Id, Account>();
		for(Account record : (List<Account>)Database.query(Label.AccountTORCHXandLBWMapQuery)){
			accountTORCHXandLBWMap.put(record.Id, record);
		}

		return accountTORCHXandLBWMap;
	}

	public static void checkIfAccountListInPauseMode(Set<Id> accountIdSet){
		//Map<Id, Boolean> acctIdInPauseModeMap = new Map<Id, Boolean>();
		List<Account> updateAccountList = new List<Account>();

		//maybe move to custom label - the query
		for(Account record : [select Id, Pause_Touchplan__c, (select Account_Name__c from Cancellation_Requests__r where Outcome__c = 'In Progress') from Account where Id in :accountIdSet]){
			if(record.Pause_Touchplan__c != (!record.Cancellation_Requests__r.isEmpty())){
				record.Pause_Touchplan__c = !record.Cancellation_Requests__r.isEmpty();
				updateAccountList.add(record);
			}
		}

		update updateAccountList;
	}
}