objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <inlineHelpText>What products are being purchased in this opportunity?</inlineHelpText>
        <label>Products Sold</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Miner</fullName>
                </value>
                <value>
                    <fullName>Centermark</fullName>
                </value>
                <value>
                    <fullName>Centermark Lite</fullName>
                </value>
                <value>
                    <fullName>Client Side Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Display</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded PPC</fullName>
                </value>
                <value>
                    <fullName>Corporate Website</fullName>
                </value>
                <value>
                    <fullName>Corp Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Custom Implementation</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Email (Integrated)</fullName>
                </value>
                <value>
                    <fullName>Email (Non-Integrated)</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Foundations</fullName>
                </value>
                <value>
                    <fullName>Get Found</fullName>
                </value>
                <value>
                    <fullName>Google 360</fullName>
                </value>
                <value>
                    <fullName>IL Paid Foundations</fullName>
                </value>
                <value>
                    <fullName>IL Paid PPC</fullName>
                </value>
                <value>
                    <fullName>IL Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Leads by Web / G1</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Local Business Listings</fullName>
                </value>
                <value>
                    <fullName>Local SEO</fullName>
                </value>
                <value>
                    <fullName>National SEO</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>PPC</fullName>
                </value>
                <value>
                    <fullName>PPC Location Adoption</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ContractLength__c</fullName>
        <inlineHelpText>Use this for WBN Corporate Opportunities</inlineHelpText>
        <label>Contract Length (Mth)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Create_NCS_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Decides wether an NCS Case should be created based on the Product</description>
        <inlineHelpText>Decides wether an NCS Case should be created based on the Product; if checked, code will look at the Family as well to decide what attributes to add to the Case</inlineHelpText>
        <label>Create NCS Case</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityClosedWonAssetsTest.cls
@isTest
private class OpportunityClosedWonAssetsTest 
{

    private static testMethod void assetsOnlyTest()
    {
        // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<SObject> oppList = Test.LoadData(Opportunity.sObjectType, 'testOpportunities');
        List<Id> oppIds = new List<Id>();
        Date todayDt = Date.Today();
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('YBN - Renewal').getRecordTypeId();
        Id oppOwner =  [SELECT Id FROM User WHERE IsActive = true AND Profile.Name = 'Nationally Certified Sales Executive' LIMIT 1].Id;
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        acct.IMS_Rep__c = oppOwner;
        update acct;
        
        Opportunity opp = (Opportunity)oppList[0];
        Id oppId = opp.Id;
        opp.RecordTypeId = oppRecordTypeId;
        opp.OwnerId = oppOwner;
        opp.AccountId = acctId;
        opp.StageName = 'Adoption';
        opp.CloseDate = todayDt.addDays(-3);
        update opp;
        
        oppIds.add(oppId);
        
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prod1 = new Product2(
             Name = 'Facebook Addition',
             ProductCode = 'FBA',
             isActive = true,
             Family = 'Facebook',
             Create_NCS_Case__c = true
        );
        insert prod1;
        
        //Create your product
        Product2 prod2 = new Product2(
             Name = 'PPC Addition',
             ProductCode = 'PPCA',
             isActive = true,
             Family = 'Pay per Click',
             Create_NCS_Case__c = true
        );
        insert prod2;
        
        //Create your product
        Product2 prod3 = new Product2(
             Name = 'Foundations',
             ProductCode = 'FNDS',
             isActive = true,
             Family = 'Foundations',
             Create_NCS_Case__c = true
        );
        insert prod3;
        
        //Create your product
        Product2 prod4 = new Product2(
             Name = 'Product X',
             ProductCode = 'Pro-X',
             isActive = true,
             Family = 'Yodle Ads',
             Create_NCS_Case__c = false
        );
        insert prod4;
        
        //Create your pricebook entry
        PricebookEntry pbEntry1 = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod1.Id,
             UnitPrice = 0.00,
             IsActive = true
        );
        insert pbEntry1;
        
        //Create your pricebook entry
        PricebookEntry pbEntry2 = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod2.Id,
             UnitPrice = 123.00,
             IsActive = true
        );
        insert pbEntry2;
        
        //Create your pricebook entry
        PricebookEntry pbEntry3 = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod3.Id,
             UnitPrice = 0.00,
             IsActive = true
        );
        insert pbEntry3;
        
        //Create your pricebook entry
        PricebookEntry pbEntry4 = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod4.Id,
             UnitPrice = 0.00,
             IsActive = true
        );
        insert pbEntry4;
        
        OpportunityLineItem oli1 = new OpportunityLineItem(
            OpportunityId = oppId,
            Quantity = 1,
            PricebookEntryId = pbEntry1.Id,
            TotalPrice = 1 * pbEntry1.UnitPrice,
            ContractLength__c = 1
        );
        insert oli1;
        
        opp.StageName = 'Closed Won';
        opp.Products__c = 'PPC Addition';
        update opp;
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        OpportunityClosedWonAssets.closedWonAssets(oppIds);
        
        Test.stopTest();
    }

}