objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AdjustCustomCodeLimit__c.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to adjust limits in code</description>
    <label>AdjustCustomCodeLimit</label>
</CustomObject>

objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>CSC_Date__c</fullName>
        <label>CSC/AR Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSC_Time__c</fullName>
        <description>last edit 03/07/2017</description>
        <label>CSC/AR Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>8:00am EST</fullName>
                </value>
                <value>
                    <fullName>8:15am EST</fullName>
                </value>
                <value>
                    <fullName>8:30am EST</fullName>
                </value>
                <value>
                    <fullName>8:45am EST</fullName>
                </value>
                <value>
                    <fullName>9:00am EST</fullName>
                </value>
                <value>
                    <fullName>9:15am EST</fullName>
                </value>
                <value>
                    <fullName>9:30am EST</fullName>
                </value>
                <value>
                    <fullName>9:45am EST</fullName>
                </value>
                <value>
                    <fullName>10:00am EST</fullName>
                </value>
                <value>
                    <fullName>10:15am EST</fullName>
                </value>
                <value>
                    <fullName>10:30am EST</fullName>
                </value>
                <value>
                    <fullName>10:45am EST</fullName>
                </value>
                <value>
                    <fullName>11:00am EST</fullName>
                </value>
                <value>
                    <fullName>11:15am EST</fullName>
                </value>
                <value>
                    <fullName>11:30am EST</fullName>
                </value>
                <value>
                    <fullName>11:45am EST</fullName>
                </value>
                <value>
                    <fullName>12:00pm EST</fullName>
                </value>
                <value>
                    <fullName>12:15pm EST</fullName>
                </value>
                <value>
                    <fullName>12:30pm EST</fullName>
                </value>
                <value>
                    <fullName>12:45pm EST</fullName>
                </value>
                <value>
                    <fullName>1:00pm EST</fullName>
                </value>
                <value>
                    <fullName>1:15pm EST</fullName>
                </value>
                <value>
                    <fullName>1:30pm EST</fullName>
                </value>
                <value>
                    <fullName>1:45pm EST</fullName>
                </value>
                <value>
                    <fullName>2:00pm EST</fullName>
                </value>
                <value>
                    <fullName>2:15pm EST</fullName>
                </value>
                <value>
                    <fullName>2:30pm EST</fullName>
                </value>
                <value>
                    <fullName>2:45pm EST</fullName>
                </value>
                <value>
                    <fullName>3:00pm EST</fullName>
                </value>
                <value>
                    <fullName>3:15pm EST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Practice_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleTORCHxOBCallControllerTest.cls
@isTest
private class ScheduleTORCHxOBCallControllerTest {
	
	@isTest static void test_ScheduleTORCHxOBCallController() {
		List<AdjustCustomCodeLimit__c> limitList = new List<AdjustCustomCodeLimit__c>();
		AdjustCustomCodeLimit__c txLimit = new AdjustCustomCodeLimit__c();
		txLimit.Name = 'TORCHxMedicalOBCallLimit:01:00 PM';
		txLimit.Limit__c = 1;
		limitList.add(txLimit);

		AdjustCustomCodeLimit__c txLimit1 = new AdjustCustomCodeLimit__c();
		txLimit1.Name = 'TORCHxMedicalOBCallLimit:12:00 PM';
		txLimit1.Limit__c = 1;
		limitList.add(txLimit1);

		AdjustCustomCodeLimit__c txLimit2 = new AdjustCustomCodeLimit__c();
		txLimit2.Name = 'TORCHxMedicalOBCallLimit:11:00 AM';
		txLimit2.Limit__c = 1;
		limitList.add(txLimit2);

		AdjustCustomCodeLimit__c txLimit3 = new AdjustCustomCodeLimit__c();
		txLimit3.Name = 'TORCHxMedicalOBCallLimit:10:00 AM';
		txLimit3.Limit__c = 1;
		limitList.add(txLimit3);

		insert limitList;

		Account testAccount = new Account();
		testAccount.Name = 'Test Name';
		testAccount.Product_Type__c = 'TORCHX';
		testAccount.Secondary_Segments__c = 'Dentist';
		insert testAccount;

		Case testCase = new Case();
		testCase.AccountId = testAccount.Id;
		testCase.Scheduled_Call__c = DateTime.newInstance(Date.today().addDays(10).toStartOfWeek().addDays(2), Time.newInstance(12, 0, 0, 0));
		testCase.Subject = 'TORCHx CSC - Setup Call';
		insert testCase;

		Lighthouse_Worksheets__c lhws = new Lighthouse_Worksheets__c();
		lhws.Practice_Name__c = testAccount.Id;
		lhws.CSC_Date__c = Date.today().addDays(10).toStartOfWeek().addDays(2);
		lhws.CSC_Time__c = '2:00pm EST';
		lhws.RecordTypeId = Schema.SObjectType.Lighthouse_Worksheets__c.getRecordTypeInfosByName().get('CSC Worksheet - Dental').getRecordTypeId();
		insert lhws;

		Test.startTest();

		PageReference pageRef = Page.ScheduleTORCHxOBCall;
		Test.setCurrentPage(pageRef);

		ApexPages.currentPage().getParameters().put('salesforceAccountId', testAccount.Id);

		ScheduleTORCHxOBCallController contr = new ScheduleTORCHxOBCallController();
		contr.getSupportedTimeZone();
		contr.getOpenCases();

		contr.dateCaseWorkAround.StartDate__c = Date.today().addDays(10);
		contr.selectDateFilter();

		contr.selectedAvailableTime = contr.selectTempIdToAvailableDateTimeMap.values()[0].selectDateTimeId;
		contr.scheduleDateTime();

		Test.stopTest();
	}
	
}