objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Google_Maps_URL__c</fullName>
        <label>Google Review URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Marketo_Sync_Token__c</fullName>
        <label>Marketo Sync Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Token_Expiration__c</fullName>
        <label>Marketo Token Expiration</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Salesforce_Incoming_Service_authToken__c</fullName>
        <inlineHelpText>Auth token for Salesforce-Incoming-Service</inlineHelpText>
        <label>Salesforce-Incoming-Service authToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Account_Data_With_Marketo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Account Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Organic_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Organic Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Integration Settings</label>
</CustomObject>

objects/Outbound_Call_Case_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Script_URL__c</fullName>
        <label>Script URL</label>
        <type>Url</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Outbound Call Case Automation</label>
</CustomObject>

objects/SF2YLFieldMapping__c.object
<CustomObject>
    <fields>
        <fullName>Fields_to_Monitor_Changes__c</fullName>
        <inlineHelpText>Fields that we monitor that if it changes, send to YodleLive. Delimit the fields by ';'</inlineHelpText>
        <label>Fields to Monitor Changes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fields_to_Return__c</fullName>
        <inlineHelpText>List the fields to send to Queue delimited by ';'</inlineHelpText>
        <label>Fields to Return</label>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Salesforce fields that are sent to Yodle Live through the Queue</description>
    <label>SF2YLFieldMapping</label>
</CustomObject>

objects/SFDC_Account_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>SFDC Account to Marketo Field Mappings</label>
</CustomObject>

objects/Touchplan__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Ads_Minimum__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Budget Ads Minimum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client_Type_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Monthly_Spend_Threshold__c</fullName>
        <inlineHelpText>Maximum monthly spend before account is taken out of Experience</inlineHelpText>
        <label>Monthly Spend Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Allocation__c</fullName>
        <label>Percent Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Touchplan_Type__c</fullName>
        <label>Touchplan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Test Group</fullName>
                </value>
                <value>
                    <fullName>Control</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Touchplan</label>
    <nameField>
        <label>Touchplan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Touchplans</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Touchplan_Section__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <inlineHelpText>If an email campaign needs to be sent, set this with the Campaign ID value</inlineHelpText>
        <label>Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Record_Type_Name__c</fullName>
        <label>Case Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Case_Criteria__c</fullName>
        <label>Create Case Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Yodle Path Assignment</fullName>
                    <default>true</default>
                    <label>On Yodle Path Assignment</label>
                </value>
                <value>
                    <fullName>On Last Section Any Close Status</fullName>
                </value>
                <value>
                    <fullName>On Last Section Complete Status</fullName>
                </value>
                <value>
                    <fullName>On Last Section Did Not Complete Status</fullName>
                </value>
                <value>
                    <fullName>On Last Section Complete Status Create Case on Days Live: 38</fullName>
                </value>
                <value>
                    <fullName>On Last Section Any Close Status Create Case on Days Live: 68</fullName>
                </value>
                <value>
                    <fullName>Do not create Case</fullName>
                </value>
                <value>
                    <fullName>Case Create on Days Live: 35</fullName>
                </value>
                <value>
                    <fullName>Case Create on Days Live: 38</fullName>
                </value>
                <value>
                    <fullName>Case Create on Days Live: 65</fullName>
                </value>
                <value>
                    <fullName>Case Create on Days Live: 68</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Order__c</fullName>
        <label>Section Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Touchplan__c</fullName>
        <label>Touchplan</label>
        <referenceTo>Touchplan__c</referenceTo>
        <relationshipLabel>Touchplan Sections</relationshipLabel>
        <relationshipName>Touchplan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Validate_If_Case_Already_Exist__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used for Validating if a Case of this type already exists, if it does, use that Case and relate it to this record.</inlineHelpText>
        <label>Validate If Case Already Exist</label>
        <type>Checkbox</type>
    </fields>
    <label>Touchplan Section</label>
    <nameField>
        <label>Touchplan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Touchplan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Touchplan_Section_Campaign_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touchplan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Touchplan Section</label>
        <referenceTo>Touchplan_Section__c</referenceTo>
        <relationshipLabel>Touchplan Section Campaign Automations</relationshipLabel>
        <relationshipName>Touchplan_Section_Campaign_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trigger_Automation_Event__c</fullName>
        <label>Trigger Automation Event</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Case Create</fullName>
                </value>
                <value>
                    <fullName>On Days Live: 40</fullName>
                </value>
                <value>
                    <fullName>On Days Live: 70</fullName>
                </value>
                <value>
                    <fullName>On Case Complete</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call Reminder in Hours: 1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Touchplan Section Campaign Automation</label>
    <nameField>
        <label>Marketo Campaign Automation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Touchplan Section Campaign Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Client_Type_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yodle Path Email</fullName>
    </customValue>
    <customValue>
        <fullName>Yodle Core</fullName>
    </customValue>
    <customValue>
        <fullName>Yodle Submit</fullName>
    </customValue>
    <customValue>
        <fullName>National Account</fullName>
    </customValue>
    <customValue>
        <fullName>OEM Account</fullName>
    </customValue>
    <customValue>
        <fullName>National Master Account</fullName>
    </customValue>
    <customValue>
        <fullName>OEM National</fullName>
    </customValue>
    <customValue>
        <fullName>Service Task</fullName>
    </customValue>
    <customValue>
        <fullName>Local</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Lighthouse</fullName>
    </customValue>
    <customValue>
        <fullName>YBN</fullName>
    </customValue>
    <description>Global Picklist for Client Type</description>
    <masterLabel>Client Type Picklist</masterLabel>
</GlobalValueSet>

classes/TestCustomSettingInitializer.cls
public with sharing class TestCustomSettingInitializer {
	public TestCustomSettingInitializer() {
		Try{
			Integration_Settings__c integrationSetting = new Integration_Settings__c();
			integrationSetting.Salesforce_Incoming_Service_authToken__c = 'testada';
			integrationSetting.Sync_Account_Data_With_Marketo__c = true;
			integrationSetting.Sync_Organic_Case_Data_With_Marketo__c = true;
			integrationSetting.Sync_Case_Data_With_Marketo__c = true;
			insert integrationSetting;

			List<SF2YLFieldMapping__c> fieldMapList = new List<SF2YLFieldMapping__c>();

			SF2YLFieldMapping__c accountFieldMap = new SF2YLFieldMapping__c();
			accountFieldMap.Name = 'Account';
			accountFieldMap.Fields_to_Monitor_Changes__c = 'Google_Maps_URL__c';
			accountFieldMap.Fields_to_Return__c = 'Google_Maps_URL__c;Client_ID__c';
			fieldMapList.add(accountFieldMap);

			SF2YLFieldMapping__c leadFieldMap = new SF2YLFieldMapping__c();
			leadFieldMap.Name = 'Lead';
			leadFieldMap.Fields_to_Monitor_Changes__c = 'Company';
			leadFieldMap.Fields_to_Return__c = 'Company';
			fieldMapList.add(leadFieldMap);

			insert fieldMapList;


			List<SFDC_Account_to_Marketo_Field_Mappings__c> sfdcAcctToMktoFieldMappingList = new List<SFDC_Account_to_Marketo_Field_Mappings__c>();
			sfdcAcctToMktoFieldMappingList.add(new SFDC_Account_to_Marketo_Field_Mappings__c(Name='company', SFDC_Field_API_Name__c='Name', Sync_Field__c=true));
			sfdcAcctToMktoFieldMappingList.add(new SFDC_Account_to_Marketo_Field_Mappings__c(Name='Client_ID', SFDC_Field_API_Name__c='Client_ID__c', Sync_Field__c=true));
			sfdcAcctToMktoFieldMappingList.add(new SFDC_Account_to_Marketo_Field_Mappings__c(Name='Email', SFDC_Field_API_Name__c='Email__c', Sync_Field__c=true));
			sfdcAcctToMktoFieldMappingList.add(new SFDC_Account_to_Marketo_Field_Mappings__c(Name='id', SFDC_Field_API_Name__c='Marketo_ID__c', Sync_Field__c=true));
			insert sfdcAcctToMktoFieldMappingList;

			Integration_Settings__c testSetting = Integration_Settings__c.getOrgDefaults();
			testSetting.Marketo_Sync_Token__c = 'adfa3222';
			testSetting.Marketo_Token_Expiration__c = DateTime.now().addSeconds(50000);
			upsert testSetting;

			Outbound_Call_Case_Automation__c newOCCA = new Outbound_Call_Case_Automation__c();
			newOCCA.Name = 'Test Name';
			newOCCA.Case_Reason__c = 'CSC';
			newOCCA.Script_URL__c = 'www.yodle.com';
			insert newOCCA;
		}catch(Exception E){
			
		}
	}

	public static Map<String, SObject> createTouchPlanTemplates(){
		Map<String, SObject> touchplanRecordMap = new Map<String, SObject>();
		/*Touchplan__c newTouchplan = new Touchplan__c();
		newTouchplan.RecordTypeId = Schema.SObjectType.Touchplan__c.getRecordTypeInfosByName().get('Template').getRecordTypeId();
		newTouchplan.Active__c = true;
		newTouchplan.Name = 'Test Template';
		newTouchplan.Client_Type__c = 'Local';
		newTouchplan.Percent_Allocation__c = 100;
		newTouchplan.Budget_Ads_Minimum__c = 100;
		newTouchplan.Touchplan_Type__c = 'Control';
		newTouchplan.Monthly_Spend_Threshold__c = 1000;
		insert newTouchplan;


		Touchplan_Section__c newTPS = new Touchplan_Section__c();
		newTPS.Name = 'Test Section';
		newTPS.Touchplan__c = newTouchplan.Id;
		newTPS.Section_Order__c = 1;
		newTPS.Case_Record_Type_Name__c = 'Outbound Call';
		newTPS.Case_Reason__c = 'CSC';
		newTPS.Create_Case_Criteria__c = 'On Yodle Path Assignment';
		newTPS.Validate_If_Case_Already_Exist__c = true;
		insert newTPS;

		Touchplan_Section__c newTPS2 = new Touchplan_Section__c();
		newTPS2.Name = 'Test Section';
		newTPS2.Touchplan__c = newTouchplan.Id;
		newTPS2.Section_Order__c = 2;
		newTPS2.Case_Record_Type_Name__c = 'Outbound Call';
		newTPS2.Case_Reason__c = 'CS Touch Plan';
		newTPS2.Create_Case_Criteria__c = 'On Yodle Path Assignment';
		insert newTPS2;

		Touchplan_Section_Campaign_Automation__c newTPSCA = new Touchplan_Section_Campaign_Automation__c();
		newTPSCA.Name = 'Test Automation';
		newTPSCA.Touchplan_Section__c = newTPS2.Id;
		newTPSCA.Campaign_ID__c = '45';
		newTPSCA.Trigger_Automation_Event__c = 'On Case Complete';
		insert newTPSCA;

		touchplanRecordMap.put('Touchplan__c', newTouchplan);
		touchplanRecordMap.put('Touchplan_Section__c:CSC', newTPS);
		touchplanRecordMap.put('Touchplan_Section__c:Touchplan', newTPS2);
		touchplanRecordMap.put('Touchplan_Section_Campaign_Automation__c', newTPSCA);*/

		return touchplanRecordMap;
	}
}