objects/Account.object
<CustomObject>
    <fields>
        <fullName>PMS__c</fullName>
        <label>PMS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abeldent</fullName>
                </value>
                <value>
                    <fullName>Ace</fullName>
                </value>
                <value>
                    <fullName>ACOM Health</fullName>
                </value>
                <value>
                    <fullName>ALLDATA</fullName>
                </value>
                <value>
                    <fullName>AllScripts</fullName>
                </value>
                <value>
                    <fullName>Autumn8</fullName>
                </value>
                <value>
                    <fullName>BRS</fullName>
                </value>
                <value>
                    <fullName>Chiro 8000</fullName>
                </value>
                <value>
                    <fullName>Chirotouch</fullName>
                </value>
                <value>
                    <fullName>Compulink/ChiroAdvantage</fullName>
                </value>
                <value>
                    <fullName>Curve</fullName>
                </value>
                <value>
                    <fullName>DentalMate</fullName>
                </value>
                <value>
                    <fullName>DentalVision</fullName>
                </value>
                <value>
                    <fullName>Dentech</fullName>
                </value>
                <value>
                    <fullName>Denticon</fullName>
                </value>
                <value>
                    <fullName>Dentisoft</fullName>
                </value>
                <value>
                    <fullName>Dentrix</fullName>
                </value>
                <value>
                    <fullName>Dolphin</fullName>
                </value>
                <value>
                    <fullName>DoX</fullName>
                </value>
                <value>
                    <fullName>DSN</fullName>
                </value>
                <value>
                    <fullName>Eaglesoft</fullName>
                </value>
                <value>
                    <fullName>Easy Dental</fullName>
                </value>
                <value>
                    <fullName>Eclipse/BestNotes</fullName>
                </value>
                <value>
                    <fullName>EDDSON</fullName>
                </value>
                <value>
                    <fullName>EndoVision</fullName>
                </value>
                <value>
                    <fullName>EON TPS Chiro 2000</fullName>
                </value>
                <value>
                    <fullName>EZ-bis</fullName>
                </value>
                <value>
                    <fullName>EZDent</fullName>
                </value>
                <value>
                    <fullName>First Pacific Pro</fullName>
                </value>
                <value>
                    <fullName>Future Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>Practice_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>Post Install Ready</fullName>
                </value>
                <value>
                    <fullName>Post Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Logo Complete</fullName>
                </value>
                <value>
                    <fullName>Logo Ready</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Escalated (Bolt On)</fullName>
                </value>
                <value>
                    <fullName>Backed Out Sale</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>BOT Feature Request</fullName>
                </value>
                <value>
                    <fullName>Escalated (Dev)</fullName>
                </value>
                <value>
                    <fullName>Escalated (Internal)</fullName>
                </value>
                <value>
                    <fullName>MA-1 Ready</fullName>
                </value>
                <value>
                    <fullName>MA-2 Pending Review</fullName>
                </value>
                <value>
                    <fullName>MA-3 Pending Config</fullName>
                </value>
                <value>
                    <fullName>MA-4 Pending Input</fullName>
                </value>
                <value>
                    <fullName>MA-5 Config Done Pending Approval</fullName>
                </value>
                <value>
                    <fullName>MA-6 Ready/Config Complete</fullName>
                </value>
                <value>
                    <fullName>MA-7 Suspended for Fix</fullName>
                </value>
                <value>
                    <fullName>MA-8 Multi Location Split</fullName>
                </value>
                <value>
                    <fullName>Messages Activated</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Retention</fullName>
                </value>
                <value>
                    <fullName>RFC</fullName>
                </value>
                <value>
                    <fullName>S. Consultant Assistance Needed</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>AR_Request_Form</fullName>
        <active>true</active>
        <label>AR Request Form</label>
    </recordTypes>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_URL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_Submission__c</fullName>
        <label>Reason for Submission</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Citation Network Escalation</fullName>
                </value>
                <value>
                    <fullName>Client Request Tasks</fullName>
                </value>
                <value>
                    <fullName>Custom Domain Request</fullName>
                </value>
                <value>
                    <fullName>G&amp;B Login Issues</fullName>
                </value>
                <value>
                    <fullName>Google/Bing Maps Listing Issue</fullName>
                </value>
                <value>
                    <fullName>Indexing Circuit Breaker – Google</fullName>
                </value>
                <value>
                    <fullName>Listing Keyword Update (SDB Only)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Poor Performance - Ranking Issues</fullName>
                </value>
                <value>
                    <fullName>Product &amp; Strategy Questions/Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SL_Test_CaseHandler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SL_Test_CaseHandler {

   // test method for trigger on Case
    static testMethod void CaseTrigger() {
        SL_CaseHandler obj = new SL_CaseHandler();
        List<Account> LstAccnt  = new List<Account>{new Account(Name = 'TestAccount1'), new Account(Name = 'TestAccount2')};
        insert LstAccnt;
        
        Test.startTest();
        List<Case> lstParCases = new List<Case>();
        Case objCase = new Case(AccountId = LstAccnt[0].Id,Status='In Progress',Reason = 'Quality Team');
        lstParCases.add(objCase);
        
        Case objCase2 = new Case(AccountId = LstAccnt[1].Id,Status='In Progress',Reason = 'Quality Team');
        lstParCases.add(objCase2);
        insert lstParCases;
        
        List<Case> lstCase = new List<Case>{ new Case(AccountId = LstAccnt[0].Id,ParentId= objCase.Id, Status='Closed',Reason = 'Quality Team'),
                                             new Case(AccountId = LstAccnt[0].Id,ParentId= objCase.Id, Status='Closed',Reason = 'Quality Team'),
                                             new Case(AccountId = LstAccnt[0].Id,ParentId= objCase2.Id,Status='Closed',Reason = 'Quality Team'),
                                             new Case(AccountId = LstAccnt[0].Id,ParentId= objCase2.Id,Status='In Progress',Reason = 'Quality Team')};
        insert lstCase;
        //system.assertEquals([Select Id, Status FROM Case Where Id=: objCase.Id ].Status,'All Work Completed – Contact Client');
        Test.StopTest();
        // For Coverage 
        delete lstCase;
        undelete lstCase;
    
    }
    // Test method for trigger on Organic_Analysis__c Trigger
     static testMethod void OrganicCase()
     {
        List<Account> LstAccnt  = new List<Account>{new Account(Name = 'TestAccount1'), new Account(Name = 'TestAccount2')};
                                                                            
        insert LstAccnt;
        
        Test.startTest();
        List<Case> lstCase = new List<Case>{ new Case(AccountId = LstAccnt[0].Id,Status='Closed',Reason = 'Quality Team'),
                                             new Case(AccountId = LstAccnt[0].Id,Status='In Progress',Reason = 'Quality Team')};
        insert lstCase;
        
        List<Organic_Analysis__c>lstOrganicCase = new List<Organic_Analysis__c>{new Organic_Analysis__c (Account_Name__c =LstAccnt[0].Id,Channel_Type__c='Local', Reason_for_Submission__c = 'Client Request Tasks', Status__c = 'InProgress',Case_URL__c = lstCase[0].Id),
                                                                                new Organic_Analysis__c (Account_Name__c =LstAccnt[0].Id,Channel_Type__c='Local', Reason_for_Submission__c = 'Client Request Tasks', Status__c = 'InProgress',Case_URL__c = lstCase[1].Id),
                                                                                new Organic_Analysis__c (Account_Name__c =LstAccnt[0].Id,Channel_Type__c='Local', Reason_for_Submission__c = 'Client Request Tasks', Status__c = 'Closed',Case_URL__c = lstCase[1].Id)};
        insert  lstOrganicCase;                                                             
        Test.StopTest();
        //system.assertEquals([Select Id, Status FROM Case Where Id=: lstCase[1].Id ].Status,'All Work Completed – Contact Client');
        //For Coverage
        delete lstOrganicCase;
        undelete lstOrganicCase;
     }
     // Test method for trigger on Lighthouse_Worksheets__c
     static testMethod void LightHouse()
     {
        List<Account> LstAccnt  = new List<Account>{new Account(Name = 'TestAccount1'), new Account(Name = 'TestAccount2')};
                                                                            
        insert LstAccnt;
        
        Test.startTest();
        List<Case> lstCase = new List<Case>{ new Case(AccountId = LstAccnt[0].Id,Status='Closed',Reason = 'Quality Team'),
                                             new Case(AccountId = LstAccnt[0].Id,Status='In Progress',Reason = 'Quality Team')};
        insert lstCase;
        
        RecordType lhRT = [SELECT Id FROM RecordType WHERE DeveloperName = 'AR_Request_Form' LIMIT 1];
        List<Lighthouse_Worksheets__c>lstLightHouse = new List<Lighthouse_Worksheets__c>{new Lighthouse_Worksheets__c(Practice_Name__c =LstAccnt[0].Id,PMS__c = 'BRS',Status__c = 'RFC',Case__c = lstCase[0].Id, RecordTypeId = lhRT.Id ),
                                                                                         new Lighthouse_Worksheets__c(Practice_Name__c =LstAccnt[0].Id,PMS__c = 'BRS',Status__c = 'RFC',Case__c = lstCase[1].Id, RecordTypeId = lhRT.Id),
                                                                                         new Lighthouse_Worksheets__c(Practice_Name__c =LstAccnt[0].Id,PMS__c = 'BRS',Status__c = 'Complete',Case__c = lstCase[1].Id, RecordTypeId = lhRT.Id)};
        insert lstLightHouse;
        Test.StopTest();
        //system.assertEquals([Select Id, Status FROM Case Where Id=: lstCase[1].Id ].Status,'All Work Completed – Contact Client'); 
        //For Coverage
        delete lstLightHouse;
        undelete lstLightHouse;
     }
  
    
}