objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account.Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPP_Lead_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Close_Date__c</fullName>
        <label>Expected Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gold_Nugget_Client_ID__c</fullName>
        <label>Gold Nugget Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Phone_Number__c</fullName>
        <label>Lead Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Lead_Registration_Status__c</fullName>
        <label>Lead Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Newly Registered</fullName>
                    <default>true</default>
                    <label>Newly Registered</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Master Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>CPP_Leads_Registration</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lead Registration</relationshipLabel>
        <relationshipName>Lead_Registration</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lead Registration</label>
    <nameField>
        <label>Lead Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Registration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPPLeadRegistrationChildSchedAndBatch.cls
@isTest
private class CPPLeadRegistrationChildSchedAndBatch {
	
	@isTest static void test_CPPLeadRegistrationChildAcctLinkSchedule() {
		Account partnerAccount = new Account();
		partnerAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner Master Account').getRecordTypeId();
		partnerAccount.Name = 'Test Partner Account';
		insert partnerAccount;

		Contact testContact = new Contact();
		testContact.FirstName = 'Test Name';
		testContact.LastName = 'Last Name';
		testContact.AccountId = partnerAccount.Id;
		insert testContact;

		CPP_Lead_Registration__c cppLead = new CPP_Lead_Registration__c();
		cppLead.Submitted_By__c = testContact.Id;
		cppLead.Partner_Account__c = partnerAccount.Id;
		cppLead.Date_Submitted__c = Date.today();
		cppLead.Name = 'Test Company Name';
		cppLead.Lead_Phone_Number__c = '343334333';
		cppLead.Expected_Close_Date__c = Date.today().addDays(5);
		insert cppLead;

		cppLead.Lead_Registration_Status__c = 'Approved';
		cppLead.Gold_Nugget_Client_ID__c = '4343';
		update cppLead;

		Account childAccount = new Account();
		childAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
		childAccount.Name = 'Test Partner Account';
		childAccount.Client_ID__c = '4343';
		insert childAccount;

		Test.startTest();
		CPPLeadRegistrationChildAcctLinkSchedule sched = new CPPLeadRegistrationChildAcctLinkSchedule();
		sched.execute(null);
		Test.stopTest();
	}
	
}