objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Auto_Renewal__c</fullName>
        <label>Auto-Renewal</label>
        
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account.Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Oppty__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract-Oppty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>.</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Term__c</fullName>
        <description>Auto Renewal Term</description>
        <label>Renewal Term</label>
        
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date for the Contract Line Item.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LineDescription__c</fullName>
        <description>Description of the Contract Line.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Opportunity associated to the Contract Line.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Lines</relationshipLabel>
        <relationshipName>Contract_Lines_OppId</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Product2 object.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Lines</relationshipLabel>
        <relationshipName>Contract_Lines_Prod2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Quantity of the Contract Line.</description>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date for the Contract Line Item.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Total Price of the Contract Line.</description>
        <label>Total Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Contract Line Item based on the End Date.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <description>Relationship Id to the Contract Object</description>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Lines</relationshipLabel>
        <relationshipName>Contract_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Product lines associated to the Contract which originated from the Closed Won Opportunity</description>
    <label>Contract Line</label>
    <nameField>
        <displayFormat>CL-{000000000}</displayFormat>
        <label>Contract Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auto_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Renewal?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account.Client_ID__c</formula>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked when Process Builder - WBN IL Contract Creation runs.</description>
        <label>Contract Auto Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Detail__c</fullName>
        <label>Opportunity Detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Customer</fullName>
                </value>
                <value>
                    <fullName>Win Back</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Upsell</fullName>
                </value>
                <value>
                    <fullName>YBN Corporate Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YBN_Sub_Type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Opportunity_Detail__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Proof of Value</fullName>
                </value>
                <value>
                    <fullName>Full Rollout</fullName>
                </value>
                <value>
                    <fullName>Low Influence- Preferred Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Exclusive Preferred Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Premier Preferred Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>Seasonal Fixed Length Campaign</fullName>
                </value>
                <value>
                    <fullName>Project Campaign</fullName>
                </value>
                <value>
                    <fullName>Initial Rollout</fullName>
                </value>
                <value>
                    <fullName>Location Expansion</fullName>
                </value>
                <value>
                    <fullName>Product Expansion</fullName>
                </value>
                <value>
                    <fullName>Additional Funds</fullName>
                </value>
                <value>
                    <fullName>Influence/ Bottoms Up</fullName>
                </value>
                <value>
                    <fullName>Preferred Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>New Full Roll Out</fullName>
                </value>
                <value>
                    <fullName>New Exclusive Preferred Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>New Premier Partner Agreement</fullName>
                </value>
                <value>
                    <fullName>New Seasonal Fixed Length Campaign</fullName>
                </value>
                <value>
                    <fullName>New Project Campaign</fullName>
                </value>
                <value>
                    <fullName>Corporate Paid Contract</fullName>
                </value>
                <value>
                    <fullName>Network Communications Portal</fullName>
                </value>
                <value>
                    <fullName>New Product Added</fullName>
                </value>
                <value>
                    <fullName>Budget Increase</fullName>
                </value>
                <value>
                    <fullName>Winback Campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Converted_to_Asset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Converted to Asset?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>PricebookEntry.Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Create_NCS_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Decides wether an NCS Case should be created based on the Product</description>
        <inlineHelpText>Decides wether an NCS Case should be created based on the Product; if checked, code will look at the Family as well to decide what attributes to add to the Case</inlineHelpText>
        <label>Create NCS Case</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityClosedWonContract.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 20-Oct-2017
  Last Modified By ...: E. Ross
  Last Modified Date .: 20-Oct-2017
  Description ........: Apex invocable method which creates Contracts and Contract Lines when
  an Opportunity is Closed Won.
*****************************************************************************/

public class OpportunityClosedWonContract
{
    @InvocableMethod
    public static void wbnClosedWonContracts(List<Id> oppIds)
    {
        if(oppIds.size() > 0){
         
            Id contractRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByName().get('Service Agreement').getRecordTypeId();
            Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('YBN - Individual Location').getRecordTypeId();
            Map<Id, Opportunity> oppsMap = new Map<Id, Opportunity>();
            Map<Id, OpportunityLineItem> oppLinesMap = new Map<Id, OpportunityLineItem>();
            Map<Id, Integer> maxQuantityMap = new Map<Id, Integer>();
            Map<Id, Contract> newContractsMap = new Map<Id, Contract>();
            List<echosign_dev1__SIGN_Agreement__c> dmlAgreements = new List<echosign_dev1__SIGN_Agreement__c>();
            List<Contract> dmlContracts = new List<Contract>();
            List<ContractLineItem__c> dmlContractLines = new List<ContractLineItem__c>();
            Date todayDt = Date.today();
        
            // Opportunity Data
            for(Opportunity o : 
                [SELECT Id,
                        AccountId,
                        Account.Name,
                        Account.Parent.Name,
                        Account.Client_Id__c,
                        Name,
                        StageName,
                        OwnerId,
                        Owner.Name,
                        IsWon,
                        RecordTypeId,
                        CloseDate,
                        Amount,
                        Contract_Auto_Created__c,
                        Opportunity_Detail__c,
                        YBN_Sub_Type__c
                   FROM Opportunity
                  WHERE IsWon = true AND
                        Id in: oppIds AND
                        RecordTypeId = :oppRecordTypeId AND
                        Contract_Auto_Created__c = false]){
                        
                // add Opportunity to Map
                oppsMap.put(o.Id, o);
            }
            
            if(oppsMap.size() > 0){
            
                // Opportunity Line Items
                for(OpportunityLineItem oli : 
                    [SELECT Id, 
                            OpportunityId,
                            Opportunity.OwnerId,
                            Quantity, 
                            UnitPrice, 
                            ProductName__c, 
                            Description, 
                            Product2Id,
                            Product2.Family,
                            Product2.Create_NCS_Case__c,
                            Converted_to_Asset__c
                       FROM OpportunityLineItem 
                      WHERE OpportunityId IN :oppsMap.keySet()]){
        
                    // add Line Items to Map
                    oppLinesMap.put(oli.OpportunityId, oli);   
                }
            
                if(oppLinesMap.size() > 0){
                
                    // get max Quantity from Line Items for Opportunties
                    for(AggregateResult mq :
                        [SELECT OpportunityId,
                                MAX(Quantity) mQuantity
                           FROM OpportunityLineItem
                          WHERE OpportunityId IN :oppsMap.keySet()
                       GROUP BY OpportunityId]){
                    
                        // add aggregate results to Map
                        maxQuantityMap.put((Id) mq.get('OpportunityId'), Integer.valueOf(mq.get('mQuantity')));
                    }
                    
                    // loop through Opportunities and create New Contract
                    for(Opportunity o : oppsMap.values()){
                    
                        Contract nc = new Contract();
                        nc.Name = o.Name + ' ' + o.CloseDate.format();
                        nc.AccountId = o.AccountId;
                        nc.RecordTypeId = contractRecordTypeId;
                        nc.Opportunity__c = o.Id;
                        nc.StartDate = o.CloseDate;
                        nc.ContractTerm = (maxQuantityMap.get(o.Id) > 1 ? maxQuantityMap.get(o.Id) : Integer.valueOf('1'));
                        nc.Renewal_Term__c = (maxQuantityMap.get(o.Id) > 1 ? String.valueOf(maxQuantityMap.get(o.Id)) : '1');
                        nc.Description = o.Account.Name + ' | ' + o.Opportunity_Detail__c + ' - ' + o.YBN_Sub_Type__c + ' | $' + String.valueOf(o.Amount);
                        nc.Auto_Renewal__c = 'Yes';
                        nc.Contract_Oppty__c = true;
                        nc.OwnerId = o.OwnerId;
                        nc.Status = 'Draft';
                        
                        // add new Contract to Insert list
                        dmlContracts.add(nc);
                        
                        o.Contract_Auto_Created__c = true;
                    }
                    
                    if(dmlContracts.size() > 0){
                    
                        // INSERT CONTRACTS
                        insert dmlContracts;
                        
                        // Update Opportunity Contract Auto Created
                        update oppsMap.values();
                    
                        for(Contract nc :
                            [SELECT Id,
                                    ContractNumber,
                                    AccountId,
                                    Opportunity__c,
                                    Status,
                                    StartDate,
                                    EndDate
                               FROM Contract
                              WHERE Opportunity__c in: oppsMap.keySet()]){
                            
                            nc.Status = 'Activated';
                            
                            // add to New Contracts Map to add to associate Contract Lines
                            newContractsMap.put(nc.Opportunity__c, nc);
                        }
                        
                        // Create Contract Lines
                        for(OpportunityLineItem olic : 
                            [SELECT Id, 
                                OpportunityId,
                                Opportunity.OwnerId,
                                Quantity, 
                                UnitPrice, 
                                ProductName__c, 
                                Description, 
                                Product2Id,
                                Product2.Family,
                                Product2.Create_NCS_Case__c,
                                Converted_to_Asset__c
                           FROM OpportunityLineItem 
                          WHERE OpportunityId IN :oppsMap.keySet()]){
                        
                            if(olic.OpportunityId == newContractsMap.get(olic.OpportunityId).Opportunity__c){
                            
                                ContractLineItem__c cli = new ContractLineItem__c();
                                cli.Contract__c = newContractsMap.get(olic.OpportunityId).Id;
                                cli.LineDescription__c = olic.ProductName__c;
                                cli.Opportunity__c = olic.OpportunityId;
                                cli.Product2__c = olic.Product2Id;
                                cli.Quantity__c = olic.Quantity;
                                cli.Total_Price__c = olic.Quantity * olic.UnitPrice;
                                cli.Start_Date__c = newContractsMap.get(olic.OpportunityId).StartDate;
                                cli.End_Date__c = newContractsMap.get(olic.OpportunityId).EndDate;
                                cli.Status__c = (newContractsMap.get(olic.OpportunityId).EndDate > todayDt ? 'Active' : 'Inactive');
                                    
                                // add Contract Line to insert list
                                dmlContractLines.add(cli);
                            }
                        }
                        
                        if(dmlContractLines.size() > 0){
                        
                            // INSERT CONTRACT LINES
                            insert dmlContractLines;
                                
                            // UPDATE CONTRACT STATUS
                            update newContractsMap.values();
                            
                            // Associate newly created Contracts with any related Agreements
                            for(echosign_dev1__SIGN_Agreement__c ag :
                            [SELECT Id, 
                                    Name, 
                                    echosign_dev1__Account__c, 
                                    echosign_dev1__Opportunity__c,
                                    echosign_dev1__Contract__c
                               FROM echosign_dev1__SIGN_Agreement__c
                              WHERE echosign_dev1__Opportunity__c IN :oppsMap.keySet()]){
                            
                                if(ag.echosign_dev1__Opportunity__c != null && ag.echosign_dev1__Contract__c == null && newContractsMap.get(ag.echosign_dev1__Opportunity__c).Opportunity__c == ag.echosign_dev1__Opportunity__c){
                                    
                                    ag.echosign_dev1__Contract__c = newContractsMap.get(ag.echosign_dev1__Opportunity__c).Id;
                                    
                                    // Add to Agreement update list
                                    dmlAgreements.add(ag);
                                }
                            }
                            
                            if(dmlAgreements.size() > 0){
                            
                                // UPDATE AGREEMENT/ ASSOCIATE TO CONTRACT
                                update dmlAgreements;
                            }
                        }
                    }
                }
            } 
        } 
    }
}