objects/Account.object
<CustomObject>
    <fields>
        <fullName>Failed_to_Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed to Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketo_ID_For_Touchplan__c</fullName>
        <inlineHelpText>Used for WBN Touchplan if the Email is different</inlineHelpText>
        <label>Marketo ID For Touchplan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Custom_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Account_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Automation_Status__c</fullName>
        <label>Automation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Outcome</fullName>
                    <default>true</default>
                    <label>Waiting on Outcome</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Trigger_Date__c</fullName>
        <label>Automation Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Automation_Type_API_Name_External_ID__c</fullName>
        <inlineHelpText>Use the Touchplan API Name for Custom Metadata Types or the assigned External ID for Marketo Email Campaign</inlineHelpText>
        <label>Automation Type API Name/External ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create_Day_40_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>Create_Monthly_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_7</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_27</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_DAY_40</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_EVERY_30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Automation</label>
    <nameField>
        <displayFormat>AAN-{0000000}</displayFormat>
        <label>Custom Automation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <description>Debug Data</description>
        <label>Debug Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Debug Info</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Debug Info Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID_Field_Name__c</fullName>
        <label>Account ID Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketo Email Campaigns</relationshipLabel>
        <relationshipName>Marketo_Email_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Marketo Email Campaigns</relationshipLabel>
        <relationshipName>Marketo_Email_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Create_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Automation_API_Reference__c</fullName>
        <label>Custom Automation API Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Field_to_Update_on_Request_Sent__c</fullName>
        <label>Date Field to Update on Request Sent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Campaign_ID__c</fullName>
        <label>Marketo Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Email_Campaign_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketo Email Campaign Template</label>
        <referenceTo>Marketo_Email_Campaign__c</referenceTo>
        <relationshipLabel>Marketo Email Campaigns</relationshipLabel>
        <relationshipName>Marketo_Email_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketo_Request_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Marketo Request Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Record_Default_Values__c</fullName>
        <label>New Record Default Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Use_Marketo_ID_For_Touchplan__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>*WARNING* - only use this if you want to use the Marketo ID for Touchplan instead of the Marketo ID as the Marketo Lead ID value. Currently only used for WBN Touchplans. If you aren't sure, talk to a developer!</inlineHelpText>
        <label>Use Marketo ID For Touchplan</label>
        <type>Checkbox</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketoEmailCampaignBatch.cls
public class MarketoEmailCampaignBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    private String query;
    private String parentTemplateId;
    
    public MarketoEmailCampaignBatch(String passedQuery, String passedParentTemplateId) {
        query = passedQuery;
        parentTemplateId = passedParentTemplateId;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        system.debug(scope);
        system.debug(parentTemplateId);
        Marketo_Email_Campaign__c parentTemplate = [select Id, Name, Custom_Automation_API_Reference__c, Use_Marketo_ID_For_Touchplan__c, Marketo_Campaign_ID__c, Account_ID_Field_Name__c, Marketo_Request_Sent__c, Criteria__c, Date_Field_to_Update_on_Request_Sent__c, Create_Case__c, New_Record_Default_Values__c from Marketo_Email_Campaign__c where Id =: parentTemplateId];
        Boolean updateScopeDateField = false;

        Map<Id, Marketo_Email_Campaign__c> marketoEmailRecordMap = new Map<Id, Marketo_Email_Campaign__c>();
		Map<Id, Case> accountIdNewCaseMap = new Map<Id, Case>();

        List<DebugInfo__c> debugInfoList = new List<DebugInfo__c>();

        List<String> marketoLeadIdList = new List<String>();
        Set<String> failedMarketoIdSet = new Set<String>();

        for(SObject record : scope){
            Account acct = new Account();
            if(String.isBlank(parentTemplate.Account_ID_Field_Name__c) || parentTemplate.Account_ID_Field_Name__c.equalsIgnoreCase('id') || (query.containsIgnoreCase('Custom_Automation__c') && String.isNotBlank(parentTemplate.Custom_Automation_API_Reference__c) && parentTemplate.Custom_Automation_API_Reference__c.equalsIgnoreCase('TORCHX_MONTHLY_REVIEW_EVERY_30'))){
                acct = (Account)record;
            }else{
                acct = (Account)record.getSObject(parentTemplate.Account_ID_Field_Name__c);
            }
            Marketo_Email_Campaign__c mec = parentTemplate.clone(false, true);
            mec.Account__c = acct.Id;
            mec.Marketo_Request_Sent__c = true;
            mec.Marketo_Email_Campaign_Template__c = parentTemplate.Id;
			marketoEmailRecordMap.put(acct.Id, mec);
            if(parentTemplate.Use_Marketo_ID_For_Touchplan__c){
                marketoLeadIdList.add(acct.Marketo_ID_For_Touchplan__c);
            }else{
                marketoLeadIdList.add(acct.Marketo_ID__c);
            }

            if(parentTemplate.Create_Case__c && String.isNotBlank(parentTemplate.New_Record_Default_Values__c)){
				Case newCase = (Case)JSON.deserialize(parentTemplate.New_Record_Default_Values__c, Case.class);
				newCase.AccountId = acct.Id;
				accountIdNewCaseMap.put(acct.Id, newCase);
			}

            if(String.isNotBlank(mec.Date_Field_to_Update_on_Request_Sent__c)){
                updateScopeDateField = true;
                record.put(mec.Date_Field_to_Update_on_Request_Sent__c, Date.today());
            }

            if(marketoLeadIdList.size() == 100){
                String responseData = MarketoSyncService.requestCampaignWithResponse(parentTemplate.Marketo_Campaign_ID__c, marketoLeadIdList, new List<MarketoSyncService.MarketoSyncServiceToken>());

                Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(responseData);
                //system.debug(responseMap);
                //system.debug(responseMap.get('success') == false);
                if(responseMap.get('success') == false){
                    DebugInfo__c di = new DebugInfo__c();
                    di.DebugData__c = JSON.serializePretty('Campaign Id: ' + parentTemplate.Id + ' | Request: ' + marketoLeadIdList + ' | Response: ' + responseData);
                    debugInfoList.add(di);

                    List<Object> errorList = (List<Object>)responseMap.get('errors');
                    for(Integer i = 0; i < errorList.size(); i++){
                        Map<String, Object> errorMap = (Map<String, Object>)errorList[i];
                        if(String.valueof(errorMap.get('code')) == '1004'){
                            system.debug(String.valueof(errorMap.get('message')));
                            Set<String> failedMarketoIDs = (Set<String>)JSON.deserialize(String.valueof(errorMap.get('message')).remove('Lead').remove('not found').trim(), Set<String>.class);
                            system.debug(failedMarketoIDs);

                            Set<String> marketoLeadIdSet = new Set<String>();
                            marketoLeadIdSet.addAll(marketoLeadIdList);
                            marketoLeadIdSet.removeAll(failedMarketoIDs);

                            marketoLeadIdList.clear();
                            marketoLeadIdList.addAll(marketoLeadIdSet);

                            responseData = MarketoSyncService.requestCampaignWithResponse(parentTemplate.Marketo_Campaign_ID__c, marketoLeadIdList, new List<MarketoSyncService.MarketoSyncServiceToken>());

                            DebugInfo__c diRetry = new DebugInfo__c();
                            diRetry.DebugData__c = JSON.serializePretty('Retry | Campaign Id: ' + parentTemplate.Id + ' | Request: ' + marketoLeadIdList + ' | Response: ' + responseData);
                            debugInfoList.add(diRetry);

                            failedMarketoIdSet.addAll(failedMarketoIDs);
                        }
                    }
                }

                marketoLeadIdList.clear();
            }

        }

        if(!marketoLeadIdList.isEmpty()){
		    String responseData = MarketoSyncService.requestCampaignWithResponse(parentTemplate.Marketo_Campaign_ID__c, marketoLeadIdList, new List<MarketoSyncService.MarketoSyncServiceToken>());
            Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(responseData);
            if(responseMap.get('success') == false){
                DebugInfo__c di = new DebugInfo__c();
                di.DebugData__c = JSON.serializePretty('Campaign Id: ' + parentTemplate.Id + ' | Request: ' + marketoLeadIdList + ' | Response: ' + responseData);
                debugInfoList.add(di);

                List<Object> errorList = (List<Object>)responseMap.get('errors');
                for(Integer i = 0; i < errorList.size(); i++){
                    Map<String, Object> errorMap = (Map<String, Object>)errorList[i];
                    if(String.valueof(errorMap.get('code')) == '1004'){
                        system.debug(String.valueof(errorMap.get('message')));
                        Set<String> failedMarketoIDs = (Set<String>)JSON.deserialize(String.valueof(errorMap.get('message')).remove('Lead').remove('not found').trim(), Set<String>.class);
                        system.debug(failedMarketoIDs);

                        Set<String> marketoLeadIdSet = new Set<String>();
                        marketoLeadIdSet.addAll(marketoLeadIdList);
                        marketoLeadIdSet.removeAll(failedMarketoIDs);

                        marketoLeadIdList.clear();
                        marketoLeadIdList.addAll(marketoLeadIdSet);

                        responseData = MarketoSyncService.requestCampaignWithResponse(parentTemplate.Marketo_Campaign_ID__c, marketoLeadIdList, new List<MarketoSyncService.MarketoSyncServiceToken>());

                        DebugInfo__c diRetry = new DebugInfo__c();
                        diRetry.DebugData__c = JSON.serializePretty('Retry | Campaign Id: ' + parentTemplate.Id + ' | Request: ' + marketoLeadIdList + ' | Response: ' + responseData);
                        debugInfoList.add(diRetry);

                        failedMarketoIdSet.addAll(failedMarketoIDs);
                    }
                }
            }
        }

        List<Account> failedToSyncAccountList = new List<Account>();
        if(parentTemplate.Use_Marketo_ID_For_Touchplan__c){
            for(Account record : [select Id, Failed_to_Sync_to_Marketo__c from Account where Marketo_ID_For_Touchplan__c in: failedMarketoIdSet]){
                record.Failed_to_Sync_to_Marketo__c = true;
                failedToSyncAccountList.add(record);
                if(!accountIdNewCaseMap.isEmpty()){
                    accountIdNewCaseMap.remove(record.Id);
                }
                marketoEmailRecordMap.remove(record.Id);
            }
        }else{
            for(Account record : [select Id, Failed_to_Sync_to_Marketo__c from Account where Marketo_ID__c in: failedMarketoIdSet]){
                record.Failed_to_Sync_to_Marketo__c = true;
                failedToSyncAccountList.add(record);
                if(!accountIdNewCaseMap.isEmpty()){
                    accountIdNewCaseMap.remove(record.Id);
                }
                marketoEmailRecordMap.remove(record.Id);
            }
        }

        if(!failedToSyncAccountList.isEmpty()){
            Database.update(failedToSyncAccountList, false);
        }

        if(!debugInfoList.isEmpty()){
            insert debugInfoList;
        }

        if(!accountIdNewCaseMap.isEmpty()){
			Database.insert(accountIdNewCaseMap.values(), false);
			for(Marketo_Email_Campaign__c mec : marketoEmailRecordMap.values()){
				mec.Case__c = accountIdNewCaseMap.get(mec.Account__c).Id;
			}

            if(query.containsIgnoreCase('Custom_Automation__c') && String.isNotBlank(parentTemplate.Custom_Automation_API_Reference__c) && parentTemplate.Custom_Automation_API_Reference__c.equalsIgnoreCase('TORCHX_MONTHLY_REVIEW_EVERY_30')){
                List<Custom_Automation__c> updateCustomAutomationList = new List<Custom_Automation__c>();

                for(Custom_Automation__c ca : [select Id, Automation_Status__c from Custom_Automation__c where Account__c in :accountIdNewCaseMap.keySet() and Automation_Status__c = 'Scheduled' and Automation_Trigger_Date__c = TODAY and Automation_Type_API_Name_External_ID__c = 'TORCHX_MONTHLY_REVIEW_EVERY_30']){
                    ca.Automation_Status__c = 'Completed';
                    updateCustomAutomationList.add(ca);
                }

                if(!updateCustomAutomationList.isEmpty()){
                    Database.update(updateCustomAutomationList, false);
                }
            }
		}

        insert marketoEmailRecordMap.values();

        if(updateScopeDateField){
            Database.update(scope, false);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
        
}