objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prospect_ID__c</fullName>
        <label>Prospect ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Categories_Inputted_into_BLocal__c</fullName>
        <label>Business Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <formula>TEXT(Account_Name__r.Client_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>Case_Reason_Criteria__c</fullName>
        <inlineHelpText>Put the Case Reason criteria to sync this fields to Marketo!</inlineHelpText>
        <label>Case Reason Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Only supported for Record Type 'Outbound Call' with Case Reason 'CSC'!</description>
    <label>SFDC Case to Marketo Field Mappings</label>
</CustomObject>

objects/SFDC_Org_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>SFDC Org Case to Marketo Field Mappings</label>
</CustomObject>

classes/OnDemandSF2MarketoRecordSyncContrTest.cls
@isTest
private class OnDemandSF2MarketoRecordSyncContrTest {
	
	@isTest static void test_OnDemandSF2MarketoRecordSyncControllerAccount() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":52,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Client_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Prospect_ID__c = '205';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@te3443st.co4443m';
		newAccount.Client_Type__c = 'Local';
		newAccount.Marketo_ID__c = '52';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Test.startTest();

		PageReference currentPage = Page.OnDemandSF2MarketoRecordSync;
		Test.setCurrentPage(currentPage);

		ApexPages.currentPage().getParameters().put('recordId', newAccount.Id);
		ApexPages.currentPage().getParameters().put('objectType', 'Account');

		OnDemandSF2MarketoRecordSyncController contr = new OnDemandSF2MarketoRecordSyncController();


		Test.stopTest();
	}

	@isTest static void test_OnDemandSF2MarketoRecordSyncControllerCase() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		List<SFDC_Case_to_Marketo_Field_Mappings__c> sfdcCaseToMarketoFieldList = new List<SFDC_Case_to_Marketo_Field_Mappings__c>();
		sfdcCaseToMarketoFieldList.add(new SFDC_Case_to_Marketo_Field_Mappings__c(Name='TestMarketoField', SFDC_Field_API_Name__c='Status', Sync_Field__c=true, Case_Reason_Criteria__c='CS Touch Plan'));
		sfdcCaseToMarketoFieldList.add(new SFDC_Case_to_Marketo_Field_Mappings__c(Name='Next_Scheduled_CSC', SFDC_Field_API_Name__c='Scheduled_Call__c', Sync_Field__c=true, Case_Reason_Criteria__c='CSC'));
		sfdcCaseToMarketoFieldList.add(new SFDC_Case_to_Marketo_Field_Mappings__c(Name='nextScheduledCall', SFDC_Field_API_Name__c='Scheduled_Call__c', Sync_Field__c=true, Case_Reason_Criteria__c='CS Touch Plan'));
		insert sfdcCaseToMarketoFieldList;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@tes788664778t.co5445m';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Case newCase = new Case();
		newCase.AccountId = newAccount.Id;
		newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
		newCase.Reason = 'CS Touch Plan';
		newCase.Status = 'New';
		newCase.OwnerId = UserInfo.getUserId();
		newCase.Scheduled_Call__c = DateTime.now().addHours(10);
		insert newCase;

		Test.startTest();
		PageReference currentPage = Page.OnDemandSF2MarketoRecordSync;
		Test.setCurrentPage(currentPage);

		ApexPages.currentPage().getParameters().put('recordId', newCase.Id);
		ApexPages.currentPage().getParameters().put('objectType', 'Case');

		OnDemandSF2MarketoRecordSyncController contr = new OnDemandSF2MarketoRecordSyncController();
		Test.stopTest();
	}

	@isTest static void test_OnDemandSF2MarketoRecordSyncControllerOrganicCase() {
		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		SFDC_Org_Case_to_Marketo_Field_Mappings__c fieldMapping = new SFDC_Org_Case_to_Marketo_Field_Mappings__c();
		fieldMapping.Name = 'TestField';
		fieldMapping.Sync_Field__c = true;
		fieldMapping.SFDC_Field_API_Name__c = 'Categories_Inputted_into_BLocal__c';
		insert fieldMapping;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Secondary_Segments__c = 'Locksmith';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        insert newOrganicAnalysis;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('recordId', newOrganicAnalysis.Id);
		ApexPages.currentPage().getParameters().put('objectType', 'Organic_Analysis__c');

		OnDemandSF2MarketoRecordSyncController contr = new OnDemandSF2MarketoRecordSyncController();
        Test.stopTest();
	}
	
}