objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_Lead_Volume_Per_Month__c</fullName>
        <label>Actual Lead Volume Per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_New_Customers_Per_Month__c</fullName>
        <label>Actual New Customers Per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_PPl__c</fullName>
        <label>Actual PPl</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_ROI__c</fullName>
        <label>Actual ROI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ybnTestTriggerEventRelationshipStats.cls
@isTest
private class ybnTestTriggerEventRelationshipStats {

    static testMethod void test() {
    	
		Account a = ybnTestUtils.getAccount();
		
		Event e = new Event(Subject = 'Test', WhatId = a.Id);
		e.Actual_PPL__c = 1;
		e.Actual_ROI__c = 1;
		e.Actual_Lead_Volume_Per_Month__c = 2;
		e.Actual_New_Customers_Per_Month__c = 3;
		e.DurationInMinutes = 1;
		e.ActivityDateTime = System.today();
		insert e;
		
		//a = [
		//	SELECT Id, Actual_PPL__c, Actual_ROI__c, Actual_Lead_Volume_Per_Month__c, Actual_New_Customers_Per_Month__c 
		//	FROM Account WHERE Id = :a.Id];
		//System.assertEquals(1, a.Actual_PPL__c);
		//System.assertEquals(1, a.Actual_ROI__c);
		//System.assertEquals(2, a.Actual_Lead_Volume_Per_Month__c);
		//System.assertEquals(3, a.Actual_New_Customers_Per_Month__c);	

		e = new Event(Subject = 'Test', WhatId = a.Id);
		e.Actual_PPL__c = 2;
		e.Actual_Lead_Volume_Per_Month__c = 4;
		e.DurationInMinutes = 1;
		e.ActivityDateTime = System.today();
		insert e;
		
		//a = [
		//	SELECT Id, Actual_PPL__c, Actual_ROI__c, Actual_Lead_Volume_Per_Month__c, Actual_New_Customers_Per_Month__c 
		//	FROM Account WHERE Id = :a.Id];
		//System.assertEquals(2, a.Actual_PPL__c);
		//System.assertEquals(1, a.Actual_ROI__c);
		//System.assertEquals(4, a.Actual_Lead_Volume_Per_Month__c);
		//System.assertEquals(3, a.Actual_New_Customers_Per_Month__c);	
		
    }
}