objects/Account.object
<CustomObject>
    <fields>
        <fullName>New_Customers_Per_Month_Goal__c</fullName>
        <label>New Customers Per Month Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mutually_Agreed_Upon_Success_Metrics__c</fullName>
        <label>Mutually Agreed Upon Success Metrics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead Volume</fullName>
                </value>
                <value>
                    <fullName>PPL</fullName>
                </value>
                <value>
                    <fullName>ROI</fullName>
                </value>
                <value>
                    <fullName>New Customers Per Month</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Forecasted_Revenue__c</fullName>
        <inlineHelpText>Total annual projected revenue for specific opportunity, including all onetime and reoccurring fees/budgets.</inlineHelpText>
        <label>Forecasted Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Customers_per_Month_Goal__c</fullName>
        <inlineHelpText>Example - 5</inlineHelpText>
        <label>New Customers per Mth Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mutually_Agreed_Upon_Success_Metrics__c</fullName>
        <label>Mutually Agreed Upon Success Metrics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead Volume</fullName>
                </value>
                <value>
                    <fullName>PPL</fullName>
                </value>
                <value>
                    <fullName>ROI</fullName>
                </value>
                <value>
                    <fullName>New Customers per Mth</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

classes/ybnTestTriggerOpportunityToAccountFields.cls
@isTest
public with sharing class ybnTestTriggerOpportunityToAccountFields {
	static testMethod void testInsertUpdateOpp() {
		
		Id recordTypeId = 
			[SELECT Id 
			FROM RecordType 
			WHERE SobjectType = 'Opportunity' AND Name = 'YBN - Initial Transaction' LIMIT 1].Id;
		
		
        Account acc = new Account(Name = 'My Account');
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'My Opp');
        opp.AccountId = acc.Id;
        opp.StageName = 'Qualification';
        opp.CloseDate = date.today().addDays(1);
        opp.RecordTypeId = recordTypeId;
        opp.Mutually_Agreed_Upon_Success_Metrics__c = 'Test 123';
        opp.Forecasted_Revenue__c = 1.0;
        insert opp;

        //acc = [SELECT Id, Mutually_Agreed_Upon_Success_Metrics__c FROM Account WHERE Id = :acc.Id];
        //System.assert(opp.Mutually_Agreed_Upon_Success_Metrics__c == acc.Mutually_Agreed_Upon_Success_Metrics__c);
        
        opp.New_Customers_per_Month_Goal__c =  321;
        update opp;
        
        //acc = [SELECT Id, New_Customers_per_Month_Goal__c FROM Account WHERE Id = :acc.Id];
        //System.assert(opp.New_Customers_per_Month_Goal__c == acc.New_Customers_per_Month_Goal__c);
        
    }
}