objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please Update this Field in Yodle Live. User Roles: National Interactive Marketing Manager</inlineHelpText>
        <label>Customer Success Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bulk_Bing_AccountPL__c</fullName>
        <label>Bulk Bing Account?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bulk_Google_AccountPL__c</fullName>
        <label>Bulk Google Account?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <description>- CS Managers allowed to access also</description>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A+</fullName>
                </value>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WBNChildAcctUpdateForMasterFutureTest.cls
@isTest(seeAllData=true)
private class WBNChildAcctUpdateForMasterFutureTest
{
    private static testMethod void accountUpdateTest()
    {
       // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<Id> acctIds = new List<Id>();
        List<Account> dmlMasterAccounts = new List<Account>();
        List<Account> dmlAccounts = new List<Account>();
        Date todayDt = Date.Today();
        Id acctMasterTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('YBN Master Account').getRecordTypeId();
        Id acctStandardTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        Id acctDirectorId = [SELECT Id FROM User WHERE Alias = 'sauto' LIMIT 1].Id;
        String clientType = 'YBN';
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        String acctName = acct.Name;
        
        acct.RecordTypeId = acctMasterTypeId;
        acct.Individual_Location_Service_Level__c = 'Service Level C';
        acct.Bulk_Bing_AccountPL__c = 'No';
        acct.Bulk_Google_AccountPL__c = 'Yes';
        acct.Account_Director__c = acctDirectorId;
        dmlMasterAccounts.add(acct);
        
        if(dmlMasterAccounts.size() > 0){
            update dmlMasterAccounts;
        }
        
        Account newChildAcct = new Account();
        newChildAcct.Name = 'WBN Test Child';
        newChildAcct.RecordTypeId = acctStandardTypeId;
        newChildAcct.ParentId = acctId;
        newChildAcct.Client_Type__c = clientType;
        newChildAcct.Individual_Location_Service_Level__c = '';
        dmlAccounts.add(newChildAcct);
        
        if(dmlAccounts.size() > 0){
            insert dmlAccounts;
        }
        
        for(Account ma : dmlMasterAccounts){
            ma.Bulk_Bing_AccountPL__c = 'Yes';
            
            acctIds.add(ma.Id);
        }
        
        update dmlMasterAccounts;
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        WBNChildAcctUpdateForMasterFuture.updatedFieldsForParent(acctIds);
        
        Test.stopTest();
    }
}