objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DreamforcePortalHomeController.cls
public with sharing class DreamforcePortalHomeController {

    public String clientId {get; set;}
    public String accountId {get; set;}
    
    public DreamforcePortalHomeController() {
    
        clientId = apexpages.currentpage().getparameters().get('clientId');
    }

    public PageReference onPageLoad(){
        
        // get Salesforce Account Id based on Client Id from method
        getAccountIdByClientId(clientId);
        
        if(!String.isBlank(accountId)){
        
            getAccountDetails(accountId);
            getAccountCaseList(accountId);
        
        }
        
        return null;
    }
    
    // method to return Salesforce Account Id based on the Client Id passed
    public Id getAccountIdByClientId(String clientIdParam){
    
        accountId = [SELECT Id FROM Account WHERE Client_ID__c = :clientIdParam LIMIT 1].Id;
        
        if(String.isBlank(accountId)){
            accountId = '';
        }
        
        return accountId;
    }
    
    // method to return JSON response of Account Details
    public static String getAccountDetails(Id accountId){
    
        // return JSON for API client UI
        return JSON.serialize( 
            [SELECT Id,
                    Client_Id__c,
                    Name,
                    RecordType.Name,
                    IMS_Rep__r.Name,
                    Client_Type__c,
                    Sales_Person__c,
                    Product_Type_Transactional__c
               FROM Account
              WHERE Id = :accountId
              LIMIT 1]);
    }
    
    // method to return JSON response of Case List based on Account Id
    public static String getAccountCaseList(Id accountId){
    
        // return JSON for API client UI
        return JSON.serialize( 
            [SELECT Id,
                    CaseNumber,
                    RecordType.Name,
                    Account.Name,
                    Owner.Name,
                    Subject,
                    Status,
                    Sub_Status__c,
                    Reason,
                    Origin,
                    Description,
                    Parent.CaseNumber,
                    CreatedDate,
                    ClosedDate
               FROM Case
              WHERE AccountId = :accountId
           ORDER BY CreatedDate DESC]);
    }
    
    // method to return the viewing user's IP address
    public static String getUserIpAddress() {
    
        string returnValue = '';
        
        returnValue = ApexPages.currentPage().getHeaders().get('True-Client-IP');
        
        if (String.IsBlank(returnValue)) {
        
            returnValue = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        }
        
        System.Debug('USER IP ADDRESS: ' + returnValue);
        
        return returnValue;
    }
    
    // Class for parsing and validating IP address
    public class IpAddress{
    
        private String sIp; //ip as string
        private Double dIp; //ip as double
    
        private Double ipFromString(){
            String[] elts = sIp.split('\\.');
            return      Double.valueOf(elts[0]) * Math.pow(255, 3) + 
                        Double.valueOf(elts[1]) * Math.pow(255, 2) +
                        Double.valueOf(elts[2]) * Math.pow(255, 1) + //=*255
                        Double.valueOf(elts[3]) * Math.pow(255, 0);  //=*1 
        }
    
        public IpAddress(String ip){
            sIp = ip;
            dIp = this.ipFromString();
        }
    
        public Double asDouble(){
            return dIp;
        }
    
        public Boolean isInRange(IpAddress lowBoundary, IpAddress highBoundary){
            return (this.asDouble() >= lowBoundary.asDouble()) && (this.asDouble() <= highBoundary.asDouble());
        }
    }
}