objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Executed_Clause_For_Flagging_E2C__c</fullName>
        <label>Executed Clause For Flagging-E2C</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Executed_Clause_For_Flagging__c</fullName>
        <label>Executed Clause For Flagging</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Most_Eligible_E2C__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Most Eligible-E2C</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Most Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Account_E2C__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Account-E2C</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Target Account-E2C)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ResetContactLiveOpsAttributesBatch.cls
global class ResetContactLiveOpsAttributesBatch implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id FROM Contact WHERE Account.RecordType.Name = \'YBN Master Account\' OR Account.Client_Type__c = \'YBN\'');
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
        List<Contact> lstContactsToUpdate = new List<Contact>();
        
        for(sObject sObj : scope){
            Contact con = (Contact)sObj;
            
            con.Target_Account__c = NULL;
            con.Most_Eligible__c = FALSE;
            con.Executed_Clause_For_Flagging__c = NULL;
            
            con.Target_Account_E2C__c = NULL;
            con.Most_Eligible_E2C__c = FALSE;
            con.Executed_Clause_For_Flagging_E2C__c = NULL;
            
            lstContactsToUpdate.add(con);
        }
        
        Database.update(lstContactsToUpdate);
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
}