objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Experience_Key__c</fullName>
        <label>Client Experience Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Days_Since_Live__c</fullName>
        <formula>today()- Live_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Live</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Plan_Id__c</fullName>
        <label>Product Plan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Batch_Automation_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Default_Values__c</fullName>
        <inlineHelpText>Enter the values ex: &lt;Field_API_Name__c&gt;:&lt;Value&gt; and separate with a ','</inlineHelpText>
        <label>Default Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Criteria__c</fullName>
        <label>SOQL Criteria</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Batch Automation Settings</label>
</CustomObject>

classes/OrganicCustomContentSetupCaseBatchTest.cls
@isTest
private class OrganicCustomContentSetupCaseBatchTest {
	
	@isTest static void test_OrganicCustomContentSetupCaseBatch() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		Batch_Automation_Settings__c batchSetting = new Batch_Automation_Settings__c();
		batchSetting.Name = 'Organic Custom Content Setup Case';
		batchSetting.SOQL_Criteria__c = 'select Id, Client_ID__c from Account where Status__c = \'LIVE\' and Product_Plan_Id__c = \'LEADS_BY_WEB\' and Client_Experience_Key__c = \'web.com-main\' and Days_Since_Live__c = 3';
		batchSetting.Default_Values__c = 'RecordTypeId:' + Schema.SObjectType.Case.getRecordTypeInfosByName().get('LBW Content Organic Setup').getRecordTypeId() + ', OwnerId:00G60000001kt6g, Subject:Organic Custom Content Setup, Description:Please write custom content for the homepage and all listed service pages outlined in this case';
		insert batchSetting;

		String responseExample = '{"235470": { "clientId": 235470, "businessName": "Court\'s Snaggle Tooth DDS", "servingAreaTagline": "Austin, TX", "segmentName": "Dentist", "sellingPropositions": ["Highly trained staff", "Comfortable, relaxing environment", "Friendly and helpful office staff" ], "serviceGroups": [{"id": 177239071, "name": "General Dentistry","keyword": "dental care" },{ "id": 225193704, "name": "Emergency Dentistry", "keyword": "emergency dentist"}]}}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Client_ID__c = '235470';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*0.05) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Status__c = 'LIVE';
		newAccount.Marketo_ID__c = '235470';
		newAccount.Product_Plan_Id__c = 'LEADS_BY_WEB';
		newAccount.Client_Experience_Key__c = 'web.com-main';
		newAccount.Live_Date__c = Date.today().addDays(-3);
		insert newAccount;

		Test.startTest();
		OrganicCustomContentSetupCaseSchedule s = new OrganicCustomContentSetupCaseSchedule();
		s.execute(null);
		Test.stopTest();
	}

	@isTest static void test_OrganicCustomContentSetupCaseBatchError() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		Batch_Automation_Settings__c batchSetting = new Batch_Automation_Settings__c();
		batchSetting.Name = 'Organic Custom Content Setup Case';
		batchSetting.SOQL_Criteria__c = 'select Id, Client_ID__c from Account where Status__c = \'LIVE\' and Product_Plan_Id__c = \'LEADS_BY_WEB\' and Client_Experience_Key__c = \'web.com-main\' and Days_Since_Live__c = 3';
		batchSetting.Default_Values__c = 'RecordTypeId:' + Schema.SObjectType.Case.getRecordTypeInfosByName().get('LBW Content Organic Setup').getRecordTypeId() + ', OwnerId:00G60000001kt6g, Subject:Organic Custom Content Setup, Description:Please write custom content for the homepage and all listed service pages outlined in this case';
		insert batchSetting;

		String responseExample = '{"235470": { "clientId": 235470, "businessName": "Court\'s Snaggle Tooth DDS", "servingAreaTagline": "Austin, TX", "segmentName": "Dentist", "sellingPropositions": ["Highly trained staff", "Comfortable, relaxing environment", "Friendly and helpful office staff" ], "serviceGroups": [{"id": 177239071, "name": "General Dentistry","keyword": "dental care" },{ "id": 225193704, "name": "Emergency Dentistry", "keyword": "emergency dentist"}]}}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Client_ID__c = '3';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*0.08) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Status__c = 'LIVE';
		newAccount.Marketo_ID__c = '23547430';
		newAccount.Product_Plan_Id__c = 'LEADS_BY_WEB';
		newAccount.Client_Experience_Key__c = 'web.com-main';
		newAccount.Live_Date__c = Date.today().addDays(-3);
		insert newAccount;

		Test.startTest();
		OrganicCustomContentSetupCaseSchedule s = new OrganicCustomContentSetupCaseSchedule();
		s.execute(null);
		Test.stopTest();
	}
	
}