objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_MLS__c.object
<CustomObject>
    <fields>
        <fullName>MLS__c</fullName>
        <label>MLS</label>
        <referenceTo>MLS__c</referenceTo>
        <relationshipLabel>Account MLS's</relationshipLabel>
        <relationshipName>Account_MLS_s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account MLS's</relationshipLabel>
        <relationshipName>Account_MLS_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account MLS</label>
    <nameField>
        <displayFormat>AM-{0}</displayFormat>
        <label>Account MLS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account MLS'</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MLS__c.object
<CustomObject>
    <fields>
        <fullName>MLS_Code__c</fullName>
        <label>MLS Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State</valueSetName>
        </valueSet>
    </fields>
    <label>MLS</label>
    <nameField>
        <label>MLS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MLS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>MLS</fullName>
        <active>true</active>
        <label>MLS</label>
    </recordTypes>
</CustomObject>

objects/Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Worksheets</relationshipLabel>
        <relationshipName>Worksheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Account_MLS_Have_Been_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Account MLS' Have Been Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MLS__c</fullName>
        <label>MLS</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Worksheets</relationshipLabel>
        <relationshipName>Worksheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pre Setup Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Backed Out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Worksheets</label>
    <nameField>
        <displayFormat>WK-{0000}</displayFormat>
        <label>Worksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/State.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>TX</fullName>
    </customValue>
    <description>The List of US States</description>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

classes/WorksheetsTriggerTest.cls
@isTest
private class WorksheetsTriggerTest {
    
    @isTest static void test_beforeTriggerWithCompleteStatus() {
        TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

        List<Account> newAccountList = new List<Account>();
        List<Account> updateAccountList = new List<Account>();
        List<Case> newCaseList = new List<Case>();
        List<MLS__c> newMlsList = new List<MLS__c>();
        List<Account_MLS__c> newAcctMlsList = new List<Account_MLS__c>();
        List<Worksheets__c> newWkshtList = new List<Worksheets__c>();

        Account testAccount = new Account();
        testAccount.Name = 'Test Name';
        newAccountList.add(testAccount);
        insert newAccountList;

        Case testCase = new Case();
        testCase.RecordTypeId = Case.sObjectType.getDescribe().getRecordTypeInfosByName().get('NCS - AutoLaunch').getRecordTypeId();
        testCase.AccountId = testAccount.Id;
        newCaseList.add(testCase);
        insert newCaseList;

        MLS__c testMLS = new MLS__c();
        testMLS.Name = 'Test Name';
        testMLS.MLS_Code__c = 'tasdfdaf';
        //testMLS.State__c = 'TX';
        newMlsList.add(testMLS);
        insert newMlsList;

        Account_MLS__c testAcctMLS = new Account_MLS__c();
        testAcctMLS.Account__c = testAccount.Id;
        testAcctMLS.MLS__c = testMLS.Id;
        newAcctMlsList.add(testAcctMLS);
        insert newAcctMlsList;

        Test.startTest();
        Worksheets__c testWorksheet = new Worksheets__c();
        testWorksheet.RecordTypeId = Worksheets__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('MLS Worksheet').getRecordTypeId();
        testWorksheet.Parent_Case__c = testCase.Id;
        testWorksheet.Account_Name__c = testAccount.Id;
        testWorksheet.Status__c = 'Complete';
        testWorksheet.All_Account_MLS_Have_Been_Activated__c = true;
        newWkshtList.add(testWorksheet);
        insert newWkshtList;

        testAccount.Status__c = 'PROVISIONING';
        updateAccountList.add(testAccount);
        update updateAccountList;
        Test.stopTest();
    }
    
    @isTest static void test_afterTrigger() {
        TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

        List<Account> newAccountList = new List<Account>();
        List<Account> updateAccountList = new List<Account>();
        List<Case> newCaseList = new List<Case>();
        List<MLS__c> newMlsList = new List<MLS__c>();
        List<Account_MLS__c> newAcctMlsList = new List<Account_MLS__c>();
        List<Worksheets__c> newWkshtList = new List<Worksheets__c>();

        Account testAccount = new Account();
        testAccount.Name = 'Test Name';
        newAccountList.add(testAccount);
        insert newAccountList;

        Case testCase = new Case();
        testCase.RecordTypeId = Case.sObjectType.getDescribe().getRecordTypeInfosByName().get('NCS - AutoLaunch').getRecordTypeId();
        testCase.AccountId = testAccount.Id;
        newCaseList.add(testCase);
        insert newCaseList;

        MLS__c testMLS = new MLS__c();
        testMLS.Name = 'Test Name';
        testMLS.MLS_Code__c = 'tasdfdaf';
        //testMLS.State__c = 'TX';
        newMlsList.add(testMLS);
        insert newMlsList;

        Account_MLS__c testAcctMLS = new Account_MLS__c();
        testAcctMLS.Account__c = testAccount.Id;
        testAcctMLS.MLS__c = testMLS.Id;
        newAcctMlsList.add(testAcctMLS);
        insert newAcctMlsList;

        Worksheets__c testWorksheet = new Worksheets__c();
        testWorksheet.RecordTypeId = Worksheets__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('MLS Worksheet').getRecordTypeId();
        testWorksheet.Parent_Case__c = testCase.Id;
        testWorksheet.Account_Name__c = testAccount.Id;
        testWorksheet.Status__c = 'New';
        testWorksheet.All_Account_MLS_Have_Been_Activated__c = true;
        newWkshtList.add(testWorksheet);
        insert newWkshtList;

        testWorksheet.Status__c = 'Complete';
        updateAccountList.add(testAccount);
        update updateAccountList;
    }
}