objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Experience_Key__c</fullName>
        <label>Client Experience Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Scheduled_Touchpoint__c</fullName>
        <label>Next Scheduled Touchpoint</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Plan_Id__c</fullName>
        <label>Product Plan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Cancellation_Request__c</fullName>
        <label>Date of Cancellation Request</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_Product__c</fullName>
        <label>Initial Product</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Future_Product__c</fullName>
        <description>The future product client will have moving forward after cancel/save.</description>
        <label>Future Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Centermark</fullName>
                </value>
                <value>
                    <fullName>Centermark Enhanced SEO</fullName>
                </value>
                <value>
                    <fullName>Centermark Integrated Email</fullName>
                </value>
                <value>
                    <fullName>Centermark Lite</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Essentials</fullName>
                </value>
                <value>
                    <fullName>Essentials Lite</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Leads By Web</fullName>
                </value>
                <value>
                    <fullName>Lead Stream ATV</fullName>
                </value>
                <value>
                    <fullName>Lead Stream - Platform Only</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>PPC</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
                <value>
                    <fullName>TORCHx Agent</fullName>
                </value>
                <value>
                    <fullName>TORCHx Agent Ads</fullName>
                </value>
                <value>
                    <fullName>TORCHx Broker</fullName>
                </value>
                <value>
                    <fullName>TORCHx Broker Ads</fullName>
                </value>
                <value>
                    <fullName>TORCHx Team</fullName>
                </value>
                <value>
                    <fullName>TORCHx Team Ads</fullName>
                </value>
                <value>
                    <fullName>Yodle Ads</fullName>
                </value>
                <value>
                    <fullName>Yodle Max</fullName>
                </value>
                <value>
                    <fullName>Yodle Organic</fullName>
                </value>
                <value>
                    <fullName>Yodle Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Account_Data_With_Marketo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Account Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Organic_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Organic Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Integration Settings</label>
</CustomObject>

classes/CustomAutomationObjectHelperTest.cls
/*
//Reason : “BeaconHS1Migration” : Inactivated the complete class , as this is not needed for LH Product.
//By : Mahesh Bogila , 7/3/2019
//*/
@isTest
private class CustomAutomationObjectHelperTest {
    
    static testMethod void test_CustomAutomationObjectHelper() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CustomAutomationObjectHelper  obj = new CustomAutomationObjectHelper();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
  
    /**@isTest static void test_AbortAutomation() {
        TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
        Integration_Settings__c integrationSetting = Integration_Settings__c.getOrgDefaults();
        integrationSetting.Sync_Account_Data_With_Marketo__c = false;
        integrationSetting.Sync_Organic_Case_Data_With_Marketo__c = false;
        integrationSetting.Sync_Case_Data_With_Marketo__c = false;
        update integrationSetting;

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT()*0.4454);
        newAccount.Status__c = 'LIVE';
        newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*0.3544) + '@t3esf78438778t.4co4f454asm';
        newAccount.Client_Type__c = 'Local';
        newAccount.Product_Plan_ID__c = 'LEADS_BY_WEB';
        newAccount.Client_Experience_Key__c = 'web.com-main';
        //newAccount.Budget_Ads__c = 700;
        newAccount.Live_Date__c = Date.today().addDays(-54);
        newAccount.Sync_to_Marketo__c = true;
        newAccount.Next_Scheduled_Touchpoint__c = Date.today().addDays(40);
        insert newAccount;

        Case tpCase = new Case();
        tpCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
        tpCase.Subject = 'LBW Monthly Touchplan';
        tpCase.Reason = 'CS Touch Plan';
        tpCase.AccountId = newAccount.Id;
        insert tpCase;

        Test.startTest();

        Cancellation_Request__c cancelRequest = new Cancellation_Request__c();
        cancelRequest.Account_Name__c = newAccount.Id;
        cancelRequest.Date_of_Cancellation_Request__c = date.today();
        cancelRequest.Initial_Product__c = 'Leads By Web';
        cancelRequest.Future_Product__c = 'Leads By Web';
        cancelRequest.Case__c = tpCase.Id;
        insert cancelRequest;

        cancelRequest = TestDataFactory.setOutcomeToSavedWithNoConcessions(cancelRequest);
        cancelRequest.Outcome__c = 'Cancelled';
        update cancelRequest;

        cancelRequest.Outcome__c = 'In Progress';
        update cancelRequest;

        Test.stopTest();
    }**/
    
}