objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Quarterly_Managed_Account_Count__c.object
<CustomObject>
    <fields>
        <fullName>Child_Accounts_End_of_Quarter_Count__c</fullName>
        <label>Child Accounts End of Quarter Count</label>
        <summaryForeignKey>Partner_Quarterly_Managed_Child_Account__c.Partner_Quarterly_Managed_Account_Count__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_of_Quarter_Date__c</fullName>
        <label>End of Quarter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Account Count</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Account_Count</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Quarterly Managed Account Count</label>
    <nameField>
        <displayFormat>PQMAC-{0000000}</displayFormat>
        <label>Partner Quarterly Managed Account Count</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Account Count</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Quarterly_Managed_Child_Account__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Quarterly_Managed_Account_Count__c</fullName>
        <label>Partner Quarterly Managed Account Count</label>
        <referenceTo>Partner_Quarterly_Managed_Account_Count__c</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Quarterly Managed Child Account</label>
    <nameField>
        <displayFormat>PQAMN-{0000000}</displayFormat>
        <label>Partner Quarterly Account Managed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Child Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PartnerQuarterlyManagedAccountsCalc.cls
public class PartnerQuarterlyManagedAccountsCalc implements Database.Batchable<sObject> {
	
	//String query;

	private static Date endOfQuarterDate = [Select EndDate From Period Where type = 'Quarter' and StartDate = THIS_FISCAL_QUARTER].EndDate;
	
	public PartnerQuarterlyManagedAccountsCalc() {
		
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([select Id, (select Id from ChildAccounts where Status__c = 'LIVE' and (NOT Name like '%TEST')) from Account where RecordType.Name = 'Partner Master Account' and Partner_Status__c = 'Customer']);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
   		Map<Id, Map<Id, Set<Id>>> parentIdQuarterlyManagedIdchildAccountIdSetMap = new Map<Id, Map<Id, Set<Id>>>();
		for(Partner_Quarterly_Managed_Account_Count__c quarterlyRecord : [select Id, Parent_Account__c, End_of_Quarter_Date__c, Child_Accounts_End_of_Quarter_Count__c, (select Id, Child_Account__c, Child_Account__r.Status__c from Partner_Quarterly_Managed_Child_Accounts__r where (NOT Child_Account__r.Name like '%TEST')) from Partner_Quarterly_Managed_Account_Count__c where End_of_Quarter_Date__c =: endOfQuarterDate]){
			Set<Id> childAccountIdSet = new Set<Id>();
			Map<Id, Set<Id>> quarterlyManagedIdChildSet = new Map<Id, Set<Id>>();
			quarterlyManagedIdChildSet.put(quarterlyRecord.Id, childAccountIdSet);
			parentIdQuarterlyManagedIdchildAccountIdSetMap.put(quarterlyRecord.Parent_Account__c, quarterlyManagedIdChildSet);

			for(Partner_Quarterly_Managed_Child_Account__c quarterlyChildAccount : quarterlyRecord.Partner_Quarterly_Managed_Child_Accounts__r){
				parentIdQuarterlyManagedIdchildAccountIdSetMap.get(quarterlyRecord.Parent_Account__c).get(quarterlyRecord.Id).add(quarterlyChildAccount.Child_Account__c);
			}
		}

		if(parentIdQuarterlyManagedIdchildAccountIdSetMap.isEmpty() || parentIdQuarterlyManagedIdchildAccountIdSetMap.size() != scope.size()){
			List<Partner_Quarterly_Managed_Account_Count__c> newQuarterlyRecords = new List<Partner_Quarterly_Managed_Account_Count__c>();
			for(Account parentAccount : (List<Account>)scope){
				if(!parentIdQuarterlyManagedIdchildAccountIdSetMap.containsKey(parentAccount.Id)){
					Partner_Quarterly_Managed_Account_Count__c quarterlyRecord = new Partner_Quarterly_Managed_Account_Count__c();
					quarterlyRecord.End_of_Quarter_Date__c = endOfQuarterDate;
					quarterlyRecord.Parent_Account__c = parentAccount.Id;
					newQuarterlyRecords.add(quarterlyRecord);
				}
			}
			if(!newQuarterlyRecords.isEmpty()){
				insert newQuarterlyRecords;

				for(Partner_Quarterly_Managed_Account_Count__c quarterlyRecord : newQuarterlyRecords){
					Map<Id, Set<Id>> quarterlyManagedIdChildSet = new Map<Id, Set<Id>>();
					quarterlyManagedIdChildSet.put(quarterlyRecord.Id, new Set<Id>());
					parentIdQuarterlyManagedIdchildAccountIdSetMap.put(quarterlyRecord.Parent_Account__c, quarterlyManagedIdChildSet);
				}
			}
		}

		Map<Id, Set<Id>> parentIdChildAccountSetMap = new Map<Id, Set<Id>>();
		List<Partner_Quarterly_Managed_Child_Account__c> newPQMCAList = new List<Partner_Quarterly_Managed_Child_Account__c>();
		for(Account parentAccount : (List<Account>)scope){
			for(Id quarterlyManagedId : parentIdQuarterlyManagedIdchildAccountIdSetMap.get(parentAccount.Id).keySet()){
				for(Account childAccount : parentAccount.ChildAccounts){
					if(!parentIdQuarterlyManagedIdchildAccountIdSetMap.get(parentAccount.Id).get(quarterlyManagedId).contains(childAccount.Id)){
						Partner_Quarterly_Managed_Child_Account__c newPQMCA = new Partner_Quarterly_Managed_Child_Account__c();
						newPQMCA.Child_Account__c = childAccount.Id;
						newPQMCA.Partner_Quarterly_Managed_Account_Count__c = quarterlyManagedId;
						newPQMCAList.add(newPQMCA);
					}
				}
			}
		}

		if(!newPQMCAList.isEmpty()){
			insert newPQMCAList;
		}

		List<Partner_Quarterly_Managed_Child_Account__c> deleteChildAccountRelationshipList = new List<Partner_Quarterly_Managed_Child_Account__c>();
		for(Partner_Quarterly_Managed_Child_Account__c childAccountRelationship : [select Id from Partner_Quarterly_Managed_Child_Account__c where (Child_Account__r.Status__c != 'LIVE' or Child_Account__r.Name like '%TEST') and Partner_Quarterly_Managed_Account_Count__r.End_of_Quarter_Date__c =: endOfQuarterDate]){
			deleteChildAccountRelationshipList.add(childAccountRelationship);
		}
		if(!deleteChildAccountRelationshipList.isEmpty()){
			delete deleteChildAccountRelationshipList;
		}
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}