objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AutoClearDataCustomSetting__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_API_Name_To_Clear_Out__c</fullName>
        <label>Field API Name To Clear Out</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOQL__c</fullName>
        <label>SOQL</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to clear out data values for records</description>
    <label>AutoClearDataCustomSetting</label>
</CustomObject>

classes/AutoClearDataBatchTest.cls
@isTest
private class AutoClearDataBatchTest {
	
	@isTest static void test_AutoClearDataBatch() {
		AutoClearDataCustomSetting__c autoClear = new AutoClearDataCustomSetting__c();
		autoClear.Name = 'Test Auto Clear';
		autoClear.Active__c = true;
		autoClear.SOQL__c = 'Select Id from Account';
		autoClear.Field_API_Name_To_Clear_Out__c = 'Client_ID__c';
		insert autoClear;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Client_ID__c = '332233351';
		insert newAccount;

		Test.startTest();
		AutoClearDataSchedule sched = new AutoClearDataSchedule();
		sched.execute(null);
		Test.stopTest();
	}
	
}