objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id / Data</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>A Custom Object to hold Logs of type Error and Information created from various other Apex Classes. Unlike the native Debug Logs, the data or log created here are mere records and hence they're persistent.

Please employ the Apex Class named "ApexDebugLog" to utilize this Custom Object to save or log Errors or Information. There are also methods to create logs even via JavaScript.</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{0}</displayFormat>
        <label>Apex Debug Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Notification_Log__c.object
<CustomObject>
    <description>Object used to store metadata about automated notifications sent through custom logic. Can be leveraged for any sObject and/ or Record Type</description>
    <fields>
        <fullName>Notification_Sent_Date__c</fullName>
        <description>Date the notification associated to the record was sent</description>
        <label>Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Unique Id of the record associated to the SObject Name</description>
        <label>Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>Associated Record Type of the SObject Record</description>
        <label>Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Name__c</fullName>
        <description>Name of the Salesforce Standard or custom object the log record logic is related to</description>
        <label>SObject Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Field_Name__c</fullName>
        <description>Name of the associated record's field that stores the trigger value for logic to execute</description>
        <label>Trigger Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NL-{00000000}</displayFormat>
        <label>Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/wbnNationalNCSCreateNotificationSchedule.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 17-Jul-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 17-Jul-2018
  Description ........: Schedulable class to execute WBN Notifications on a daily schedule.
*****************************************************************************/
global class wbnNationalNCSCreateNotificationSchedule Implements Schedulable {

    global void execute(SchedulableContext sc) {
  
        sendWBNNotification();
    
    }
    
    public void sendWBNNotification(){
    
        Id wbnLogRecordTypeId = Schema.SObjectType.Notification_Log__c.getRecordTypeInfosByName().get('WBN Log').getRecordTypeId();
        Set<Id> caseIds = new Set<Id>();
        List<Messaging.SingleEmailMessage> notificationsLst = new List<Messaging.SingleEmailMessage>();
        //Set<String> toAddressSet = new Set<String>();
        List<String> toAddress = new List<String>();
        List<Apex_Debug_Log__c> dmlDebugLog = new List<Apex_Debug_Log__c>();
        Map<Id, User> ownerMgrsMap = new Map<Id, User>();
        String fromAddress = 'sfdc@yodle.com';
        String fromDisplayName = 'Salesforce Notifications';
        String subjectLine = '';
        String sfdcURL = System.Url.getSalesforceBaseURL().toExternalForm() + '/';
        OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'sfdc@yodle.com'];
        //Id emailTemplateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'WBN_NCS_Status_Has_Not_Changed' LIMIT 1].Id;
        
        // get records in Notification Log for WBN Log Record Type, Case object, National NCS Cases, 
        // based on Created Date, and for the current day only
        for(Notification_Log__c nl :
            [SELECT Record_Id__c
               FROM Notification_Log__c
              WHERE RecordTypeId = :wbnLogRecordTypeId AND
                    Record_Type_Name__c = 'National - New Client Setup' AND
                    SObject_Name__c = 'Case' AND
                    Trigger_Field_Name__c = 'CreatedDate' AND
                    Notification_Sent_Date__c = TODAY]){
            
            caseIds.add(nl.Record_Id__c);
        }
        
        try{
        
            if(caseIds.size() > 0){
                for(Case c :
                    [SELECT Id,
                            CreatedDate, 
                            OwnerId,
                            Owner.Name, 
                            Owner.Email, 
                            Account.IMS_Rep__r.Name, 
                            Account.IMS_Rep__r.Email, 
                            Account.Name,
                            Account.Client_ID__c,
                            CaseNumber,
                            Subject,
                            Status,
                            Sub_Status__c,
                            Next_Action_Date__c,
                            SEO_Product__c,
                            Status_Notes__c,
                            Account.IMS_Rep__c,
                            Sales_Person__c,
                            Sales_Person__r.Name
                       FROM Case
                      WHERE Id IN :caseIds]){
                          
                    // build list of email addresses to send to
                    if(!String.isBlank(c.Owner.Email)){
                        toAddress.add(c.Owner.Email);
                    }
                    
                     // check to ensure there are recipients to send notification to
                    if(toAddress.size() > 0){
                    
                        // send notifications
                        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                        String body = 'Hello, <br/><br/>';
                        body += 'This NCS Case # ' + c.CaseNumber + ' is still owned by you. Please change the Ownership.<br/><br/>';
                        body += '<b>Account:</b> ' + c.Account.Client_ID__c + ' - ' + c.Account.Name + '<br/>';
                        body += '<b>Subject:</b> ' + c.Subject + '<br/>';
                        body += '<b>Product:</b> ' + c.SEO_Product__c + '<br/><br/>';
                        body += '<b>Status:</b> ' + c.Status + '<br/>';
                        body += '<b>Sub Status:</b> ' + (String.isBlank(c.Sub_Status__c) ? null : c.Sub_Status__c) + '<br/></br>';
                        body += '<b>Status Notes:</b> ' + c.Status_Notes__c + '<br/></br>';
                        body += '<b>Case Owner:</b> ' + c.Owner.Name + '<br/>';
                        body += '<b>IMS Rep:</b> ' + c.Account.IMS_Rep__r.Name + '<br/>';
                        body += '<b>Sales Person:</b> ' + c.Sales_Person__r.Name + '<br/></br></br>';
                        body += '<b>Link to Case:</b> ' + sfdcURL + c.Id + '<br/>';
                        
                        // Dynamic Subject Line
                        subjectLine =  'NCS - Ownership Change Needed: # ' + c.CaseNumber;
                        
                        // set message content
                        message.setToAddresses(toAddress);
                        message.setReplyTo(fromAddress);
                        message.setOrgWideEmailAddressId(owea.get(0).Id);
                        //message.setTemplateId(emailTemplateId);
                        message.setSubject(subjectLine);
                        message.setHtmlBody(body);
                        
                        // add message to notification list
                        notificationsLst.add(message);
                        
                        // ensure there are messages to be sent
                        if(notificationsLst.size() > 0){
                        
                            // send notifications
                            Messaging.sendEmail(notificationsLst);
                        }
                    }
                }
            }
        }
        catch (Exception e){
        
            Apex_Debug_Log__c newDebugLog = new Apex_Debug_Log__c();
            newDebugLog.Apex_Class__c = 'wbnNationalNCSCreateNotificationSchedule';
            newDebugLog.Message__c = e.getMessage();
            newDebugLog.Method__c = 'sendWBNNotification';
            newDebugLog.Record_Id__c = 'Notification Log Records for ' + String.valueOf(System.TODAY());
            newDebugLog.Stack_Trace__c = e.getMessage();
            newDebugLog.Type__c = 'Error';
            dmlDebugLog.add(newDebugLog);
        
            if(dmlDebugLog.size() > 0){
                insert dmlDebugLog;
            }
        }
    }
}