objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                </value>
                <value>
                    <fullName>Opportunity Milestone - Transaction</fullName>
                </value>
                <value>
                    <fullName>Opportunity Milestone - Implementation</fullName>
                </value>
                <value>
                    <fullName>Lifecycle Milestone</fullName>
                </value>
                <value>
                    <fullName>Sales Activity</fullName>
                </value>
                <value>
                    <fullName>Client Services Activity - Individual Location</fullName>
                </value>
                <value>
                    <fullName>Network Communications Portal Notification</fullName>
                </value>
                <value>
                    <fullName>Account Transition Milestone</fullName>
                </value>
                <value>
                    <fullName>Client Services Activity - Corporate</fullName>
                </value>
                <value>
                    <fullName>Customer Call - Escalation</fullName>
                </value>
                <value>
                    <fullName>Customer Call - Performance Review</fullName>
                </value>
                <value>
                    <fullName>Customer Call - Exec to Exec</fullName>
                </value>
                <value>
                    <fullName>Customer In Person Meeting</fullName>
                </value>
                <value>
                    <fullName>Internal Meeting</fullName>
                </value>
                <value>
                    <fullName>Account Support</fullName>
                </value>
                <value>
                    <fullName>External Customer Activity</fullName>
                </value>
                <value>
                    <fullName>Internal YBN Activities</fullName>
                </value>
                <value>
                    <fullName>Service Level Touch Points</fullName>
                </value>
                <value>
                    <fullName>Presale</fullName>
                </value>
                <value>
                    <fullName>Bulk Onboarding</fullName>
                </value>
                <value>
                    <fullName>Internal YBN Sales Activities</fullName>
                </value>
                <value>
                    <fullName>Retention</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
                <value>
                    <fullName>Multi-Account Support</fullName>
                </value>
                <value>
                    <fullName>Internal Initiatives</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Connected with Gatekeeper</fullName>
                </value>
                <value>
                    <fullName>Connected with Target</fullName>
                </value>
                <value>
                    <fullName>LifeCycle Milestone Completed</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>internal_external_activity__c</fullName>
        <inlineHelpText>Is this an activity for an internal meeting/call or external customer facing meeting/call</inlineHelpText>
        <label>Internal or External Activity?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                    <default>true</default>
                    <label>External</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <inlineHelpText>What meeting/call/activity are you logging here?</inlineHelpText>
        <label>Activity Detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Activity_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>M000 - Conversation Initiation</fullName>
                </value>
                <value>
                    <fullName>M001 – Discovery Call</fullName>
                </value>
                <value>
                    <fullName>M002 – Internal Download Call</fullName>
                </value>
                <value>
                    <fullName>M003 - Demo/Value Presentation</fullName>
                </value>
                <value>
                    <fullName>M004 - Detailed Audit Discovery</fullName>
                </value>
                <value>
                    <fullName>M005 –  Audit Download</fullName>
                </value>
                <value>
                    <fullName>M006 - Implementation &amp; ROI Investigation Call</fullName>
                </value>
                <value>
                    <fullName>M006 - ROI info gathering</fullName>
                </value>
                <value>
                    <fullName>M006 - Custom Implementation Investigation</fullName>
                </value>
                <value>
                    <fullName>Review Initial SOW with Customer</fullName>
                </value>
                <value>
                    <fullName>M007 - Product Assessment &amp; Strategy Internal Stakeholder Meeting</fullName>
                </value>
                <value>
                    <fullName>M008 - Solutions in Action Presentation</fullName>
                </value>
                <value>
                    <fullName>M008 - ROI Analysis Presentation</fullName>
                </value>
                <value>
                    <fullName>M009 - Proposal Creation &amp; Update SOW</fullName>
                </value>
                <value>
                    <fullName>M009 – Solutions in Action Presentation</fullName>
                </value>
                <value>
                    <fullName>M010 - Present Proposal &amp; SOW</fullName>
                </value>
                <value>
                    <fullName>M10.5 Network Adoption</fullName>
                </value>
                <value>
                    <fullName>M011 - Moving to Close</fullName>
                </value>
                <value>
                    <fullName>M012 - Proof of Value Agreement</fullName>
                </value>
                <value>
                    <fullName>M013 - Contract Creation</fullName>
                </value>
                <value>
                    <fullName>M013– Proof of Value Agreement</fullName>
                </value>
                <value>
                    <fullName>M014 - Deliver Contract to the Customer</fullName>
                </value>
                <value>
                    <fullName>M015– Deliver Contract</fullName>
                </value>
                <value>
                    <fullName>Custom Implementation Discovery Call</fullName>
                </value>
                <value>
                    <fullName>M100 - Deal Closes</fullName>
                </value>
                <value>
                    <fullName>M101 - Create Detailed Project Plan</fullName>
                </value>
                <value>
                    <fullName>M104- Design consultation</fullName>
                </value>
                <value>
                    <fullName>M104 - Introduction call</fullName>
                </value>
                <value>
                    <fullName>M105 - Custom Template Creation</fullName>
                </value>
                <value>
                    <fullName>M106 - Bulk Account Setup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <sharingModel>ControlledByParent</sharingModel>

</CustomObject>

objects/Activity_Type__c.object
<CustomObject>
    <label>Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
</CustomObject>

classes/ybnUtilsEvents.cls
global class ybnUtilsEvents {

    private static ybnUtilsEvents self;
    private static Id ybnCorporateRelationshipAccountRecordTypeId;
    private static Id ybnCorporateRelationshipTaskRecordTypeId;
    private static Id ybnCorporateRelationshipEventRecordTypeId;
    
    private ybnUtilsEvents() {
    }
    
    public static ybnUtilsEvents getInstance() {
        if (self != null) return self;
        self = new ybnUtilsEvents();
        return self;
    }
    
    public Id getYbnCorporateRelationshipAccountRecordTypeId() {
        if (ybnCorporateRelationshipAccountRecordTypeId != null) {
            return ybnCorporateRelationshipAccountRecordTypeId;
        }
        ybnCorporateRelationshipAccountRecordTypeId = [SELECT Id 
            FROM RecordType 
            WHERE SobjectType = 'Account' AND Name = 'YBN Master Account' LIMIT 1].Id;
        return ybnCorporateRelationshipAccountRecordTypeId;
    }
    
    public Id getYbnCorporateRelationshipTaskRecordTypeId() {
        if (ybnCorporateRelationshipTaskRecordTypeId != null) {
            return ybnCorporateRelationshipTaskRecordTypeId;
        }
        ybnCorporateRelationshipTaskRecordTypeId =  [SELECT Id 
            FROM RecordType 
            WHERE SobjectType = 'Task' AND Name = 'YBN Corporate Relationship' LIMIT 1].Id;
        return ybnCorporateRelationshipTaskRecordTypeId;
    }
    
    public Id getYbnCorporateRelationshipEventRecordTypeId() {
        if (ybnCorporateRelationshipEventRecordTypeId != null) {
            return ybnCorporateRelationshipEventRecordTypeId;
        }
        ybnCorporateRelationshipEventRecordTypeId =  [SELECT Id 
            FROM RecordType 
            WHERE SobjectType = 'Event' AND Name = 'YBN: Corporate Location' LIMIT 1].Id;
        return ybnCorporateRelationshipEventRecordTypeId;
    }
    
    public static Event getServiceEvent(String subject) {
        Event e = new Event();
        e.Activity_Type__c = 'Client Services Activity';
        e.Subject = subject;
        e.Milestone__c = subject;
        e.Status__c = 'Not Started';
        e.internal_external_activity__c = 'External';
        e.ActivityDate = System.today().addDays(7);
        return e;
    }
}