objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Experience_Key__c</fullName>
        <label>Client Experience Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Scheduled_Touchpoint__c</fullName>
        <label>Next Scheduled Touchpoint</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Plan_Id__c</fullName>
        <label>Product Plan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Segment_Optimization_Case_Assignment__c.object
<CustomObject>
    <description>Currently only used for Local</description>
    <label>Segment Optimization Case Assignment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segment Optimization Case Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Touchplan_Section__c.object
<CustomObject>
    <fields>
        <fullName>Set_Next_Section_Evaluation_Date__c</fullName>
        <inlineHelpText>Number of days to set next section's evaluation date when this section's Case is closed.</inlineHelpText>
        <label>Set Next Section Evaluation Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Touchplan Section</label>
    <nameField>
        <label>Touchplan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Touchplan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TP_Section_Auto_Evaluate_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Evaluate_Date_Field__c</fullName>
        <defaultValue>"Evaluation_Date__c"</defaultValue>
        <label>Auto Evaluate Date Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_Date_Field__c</fullName>
        <label>Base Date Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Added_to_Base_Date__c</fullName>
        <label>Days Added to Base Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Trigger_Old_Value__c</fullName>
        <label>Field Trigger Old Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Trigger_Value__c</fullName>
        <label>Field Trigger Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Trigger__c</fullName>
        <label>Field Trigger</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touchplan_Section__c</fullName>
        <label>Touchplan Section</label>
        <referenceTo>Touchplan_Section__c</referenceTo>
        <relationshipLabel>Touchplan Section Auto Evaluate Criterias</relationshipLabel>
        <relationshipName>TP_Section_Auto_Evaluate_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>TP Section Auto Evaluate Criteria</label>
    <nameField>
        <label>Touchplan Section Auto Evaluate Criteria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TP Section Auto Evaluate Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CaseTriggerTest.cls
@isTest
private class CaseTriggerTest {
	
	@isTest static void testWebToCaseTriggerFromLHFSAndoidApp() {
		Account testAccount = new Account();
		testAccount.Name = 'Test Account Name';
		testAccount.Client_ID__c = 'TestId';
		insert testAccount;

		Case newCase = new Case();
		newCase.Client_ID__c = testAccount.Client_ID__c;
		newCase.Origin = 'LHFS Android App';
		insert newCase;

		Case newCaseData = [select Id, AccountId, Reason, Reason_Detail__c from Case where Id =: newCase.Id];

		system.assertEquals(newCaseData.AccountId, testAccount.Id);
		system.assertEquals(newCaseData.Reason, 'Inbound Inquiry');
		system.assertEquals(newCaseData.Reason_Detail__c, 'Other');
	}

	@isTest static void testWebToCaseTriggerFromLHFSiOSApp() {
		Account testAccount = new Account();
		testAccount.Name = 'Test Account Name';
		testAccount.Client_ID__c = 'TestId';
		insert testAccount;

		Case newCase = new Case();
		newCase.Client_ID__c = testAccount.Client_ID__c;
		newCase.Origin = 'LHFS iOS App';
		insert newCase;

		Case newCaseData = [select Id, AccountId, Reason, Reason_Detail__c from Case where Id =: newCase.Id];

		system.assertEquals(newCaseData.AccountId, testAccount.Id);
		system.assertEquals(newCaseData.Reason, 'Inbound Inquiry');
		system.assertEquals(newCaseData.Reason_Detail__c, 'Other');
	}

	@isTest static void test_LBWNextScheduledTouchpointTest() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@t3esf788778t.4co4fasm';
		newAccount.Client_Type__c = 'Local';
		newAccount.Product_Type__c = 'LBW';
		//newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Sync_to_Marketo__c = true;
		newAccount.Next_Scheduled_Touchpoint__c = Date.today().addDays(40);
		insert newAccount;

		Test.startTest();
		Case newCase = new Case();
		newCase.AccountId = newAccount.Id;
		newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
		newCase.Reason = 'CS Touch Plan';
		newCase.Status = 'New';
		newCase.OwnerId = UserInfo.getUserId();
		insert newCase;
		Test.stopTest();
	}

	@isTest static void test_OrganicSetupCaseTaskID() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*.01) + '@t3esf788778t.4co4fasm';
		newAccount.Client_Type__c = 'Local';
		newAccount.Product_Type__c = 'LBW';
		//newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Sync_to_Marketo__c = true;
		newAccount.Product_Plan_Id__c = 'LEADS_BY_WEB';
		newAccount.Client_Experience_Key__c = 'web.com-main';
		insert newAccount;

		Test.startTest();
		Case newCase = new Case();
		newCase.AccountId = newAccount.Id;
		newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('LBW Content Organic Setup').getRecordTypeId();
		insert newCase;
		Test.stopTest();
	}

	@isTest static void test_OptimizationAssignment() {
		Segment_Optimization_Case_Assignment__c segAssign = new Segment_Optimization_Case_Assignment__c();
		segAssign.Name = 'Dentist';
		segAssign.OwnerId = [select Id from User where IsActive = true and Profile.Name = 'System Administrator' and Id != :UserInfo.getUserId() limit 1].Id;
		insert segAssign;

		Account acct = new Account();
		acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
		acct.Name = 'Test Account';
		acct.Client_Type__c = 'Local';
		acct.Secondary_Segments__c = 'Dentist';
		insert acct;

		Case cs = new Case();
		cs.AccountId = acct.Id;
		cs.Reason2__c = 'Client Requested';
		cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Optimization').getRecordTypeId();
		insert cs;
	}

	/*@isTest static void testCaseResolution(){
		Case cscCase = new Case();
		cscCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
		cscCase.Reason = 'CSC';
		insert cscCase;

		cscCase.Resolution_Attempt_Status_1__c = 'Completed';
		update cscCase;

		cscCase.Attempt_2_Result__c = 'Completed';
		update cscCase;

		cscCase.Attempt_3_Result__c = 'Completed';
		update cscCase;

		cscCase.Attempt_4_Result__c = 'Completed';
		update cscCase;
	}*/

	/*
	@isTest static void testTPSectionAutoEvaluateCriteriaCase1(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'today';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Value__c = 'Unscheduled - Reattempt';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase2(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'today';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase3(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'CreatedDate';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase4(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = '';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase5(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'CreatedDate';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Value__c = 'Unscheduled - Reattempt';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase6(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = '';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Value__c = 'Unscheduled - Reattempt';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase7(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = '';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Old_Value__c = 'New';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase8(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'today';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Old_Value__c = 'New';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase9(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'CreatedDate';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Old_Value__c = 'New';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Unscheduled - Reattempt';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase10(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'CreatedDate';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Old_Value__c = 'New';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CS Touch Plan' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Complete';
		caseRecord.Client_Satisfaction__c = 'Red';
		update caseRecord;

		Test.stopTest();
	}

	@isTest static void testTPSectionAutoEvaluateCriteriaCase11(){
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Map<String, SObject> touchplanRecordMap = TestCustomSettingInitializer.createTouchPlanTemplates();

		Touchplan_Section__c tps = (Touchplan_Section__c)touchplanRecordMap.get('Touchplan_Section__c:CSC');
		tps.Set_Next_Section_Evaluation_Date__c = 10;
		update tps;

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC.Name = 'Test Criteria';
		newTPAEC.Base_Date_Field__c = 'CreatedDate';
		newTPAEC.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC.Days_Added_to_Base_Date__c = 10;
		newTPAEC.Field_Trigger__c = 'Status';
		newTPAEC.Field_Trigger_Old_Value__c = 'In Progress';
		newTPAEC.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:CSC').Id;
		insert newTPAEC;

		TP_Section_Auto_Evaluate_Criteria__c newTPAEC2 = new TP_Section_Auto_Evaluate_Criteria__c();
		newTPAEC2.Name = 'Test Criteria';
		newTPAEC2.Base_Date_Field__c = 'CreatedDate';
		newTPAEC2.Auto_Evaluate_Date_Field__c = 'Auto_Close_Date__c';
		newTPAEC2.Days_Added_to_Base_Date__c = 10;
		newTPAEC2.Field_Trigger__c = 'Status';
		newTPAEC2.Field_Trigger_Old_Value__c = 'In Progress';
		newTPAEC2.Touchplan_Section__c = touchplanRecordMap.get('Touchplan_Section__c:Touchplan').Id;
		insert newTPAEC2;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Case caseRecord = [select Id, Status from Case where Reason = 'CSC' and AccountId = :newAccount.Id limit 1];

		Test.startTest();

		CaseTouchplanTriggerHandler.alreadyTriggered = false;

		caseRecord.Status = 'Complete';
		update caseRecord;

		Test.stopTest();
	}
	*/
}