objects/Account.object
<CustomObject>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Account_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>SFDC Account to Marketo Field Mappings</label>
</CustomObject>

objects/SFDC_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Only supported for Record Type 'Outbound Call' with Case Reason 'CSC'!</description>
    <label>SFDC Case to Marketo Field Mappings</label>
</CustomObject>

objects/SFDC_Org_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>SFDC Org Case to Marketo Field Mappings</label>
</CustomObject>

classes/OnDemandSF2MarketoRecordSyncController.cls
public without sharing class OnDemandSF2MarketoRecordSyncController {
	private String query;
    private Id recordId;
    private String objectType;

    public String marketoResponse {get; set;}

	public OnDemandSF2MarketoRecordSyncController() {
		recordId = ApexPages.currentPage().getParameters().get('recordId');
        objectType = ApexPages.currentPage().getParameters().get('objectType');

        if(objectType.equalsIgnoreCase('Case')){
        	Set<String> caseFieldForQuerySet = new Set<String>();
			for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : SFDC_Case_to_Marketo_Field_Mappings__c.getAll().values()){
				if(sfdcCaseMarketoFieldMap.Sync_Field__c){
					caseFieldForQuerySet.add(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c.toUpperCase());
				}
			}
			if(!caseFieldForQuerySet.isEmpty()){
				caseFieldForQuerySet.add('REASON');
				caseFieldForQuerySet.add('ACCOUNTID');
				caseFieldForQuerySet.add('RECORDTYPEID');
				List<String> caseFieldForQueryList = new List<String>();
				caseFieldForQueryList.addAll(caseFieldForQuerySet);
				query = 'select ' + String.join(caseFieldForQueryList, ', ') + ' from Case where Id = :recordId and Account.Marketo_ID__c != \'\' and Sync_to_Marketo__c = true';
			}
        }else if(objectType.equalsIgnoreCase('Account')){
        	Set<String> accountFieldForQuerySet = new Set<String>();
			for(SFDC_Account_to_Marketo_Field_Mappings__c sfdcAcctMarketoFieldMap : SFDC_Account_to_Marketo_Field_Mappings__c.getAll().values()){
				if(sfdcAcctMarketoFieldMap.Sync_Field__c){
					accountFieldForQuerySet.add(sfdcAcctMarketoFieldMap.SFDC_Field_API_Name__c.toUpperCase());
				}
			}
			if(!accountFieldForQuerySet.isEmpty()){
				accountFieldForQuerySet.add('MARKETO_ID__C');
				accountFieldForQuerySet.add('ID');
				accountFieldForQuerySet.add('RECORDTYPEID');
				List<String> accountFieldForQueryList = new List<String>();
				accountFieldForQueryList.addAll(accountFieldForQuerySet);
				query = 'select ' + String.join(accountFieldForQueryList, ', ') + ' from Account where Id = :recordId and Marketo_ID__c != \'\' and Sync_to_Marketo__c = true';
			}
        }else if(objectType.equalsIgnoreCase('Organic_Analysis__c')){
        	Set<String> caseFieldForQuerySet = new Set<String>();
			for(SFDC_Org_Case_to_Marketo_Field_Mappings__c sfdcOrganicCaseMarketoFieldMap : SFDC_Org_Case_to_Marketo_Field_Mappings__c.getAll().values()){
				if(sfdcOrganicCaseMarketoFieldMap.Sync_Field__c){
					caseFieldForQuerySet.add(sfdcOrganicCaseMarketoFieldMap.SFDC_Field_API_Name__c.toUpperCase());
				}
			}
			if(!caseFieldForQuerySet.isEmpty()){
				caseFieldForQuerySet.add('ACCOUNT_NAME__C');
				caseFieldForQuerySet.add('RECORDTYPEID');
				List<String> caseFieldForQueryList = new List<String>();
				caseFieldForQueryList.addAll(caseFieldForQuerySet);
				query = 'select ' + String.join(caseFieldForQueryList, ', ') + ' from Organic_Analysis__c where Id = :recordId and Account_Name__r.Marketo_ID__c != \'\' and Sync_to_Marketo__c = true';
			}
        }

        List<sObject> queryReturn = Database.query(query);

        if(objectType.equalsIgnoreCase('Case') && !queryReturn.isEmpty()){
			marketoResponse = CaseObjectHelper.caseUpdateLeadsNotFuture('', '', JSON.serialize((List<Case>)queryReturn), false, '');
		}else if(objectType.equalsIgnoreCase('Account') && !queryReturn.isEmpty()){
			marketoResponse = MarketoSyncService.createUpdateLeads('updateOnly', 'id', (List<Account>)queryReturn, false, '');
		}else if(objectType.equalsIgnoreCase('Organic_Analysis__c') && !queryReturn.isEmpty()){
			marketoResponse = OrganicCaseObjectHelper.organicCaseUpdateLeadsNotFuture('', '', JSON.serialize((List<Organic_Analysis__c>)queryReturn), false, '');
		}
	}
}