objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please Update this Field in Yodle Live. User Roles: National Interactive Marketing Manager</inlineHelpText>
        <label>Customer Success Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsSG51</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <description>- CS Managers allowed to access also</description>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A+</fullName>
                </value>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ybnTestTriggerAccountServiceLevel.cls
@isTest
public with sharing class ybnTestTriggerAccountServiceLevel {
	static testMethod void test() {
        Account parent = new Account(Name = 'P1', Individual_Location_Service_Level__c = 'b');
        insert parent;
        
        Account child1 = new Account(Name = 'C1', ParentId = parent.Id);
        Account child2 = new Account(Name = 'C2', ParentId = parent.Id);
        insert child1; insert child2;
        
        parent.Individual_Location_Service_Level__c = 'a';
        update parent;
        
        /*
        System.assertEquals(
        	'a', 
        	[SELECT Individual_Location_Service_Level__c 
        	FROM Account 
        	WHERE Name = 'C1' LIMIT 1].Individual_Location_Service_Level__c);
        System.assertEquals(
        	'a', 
        	[SELECT Individual_Location_Service_Level__c 
        	FROM Account 
        	WHERE Name = 'C2' LIMIT 1].Individual_Location_Service_Level__c);
        */
        //parent.Individual_Location_Service_Level__c = 'b';
        //update parent;
        
        //User user = [SELECT Id FROM User LIMIT 1];
        //parent.Account_Director__c = user.Id;
        //parent.Lead_Analyst__c = user.Id;
        //parent.Sales_Director__c = user.Id;
        //update parent;
        
        
        /*
        System.assertEquals(
        	'b', 
        	[SELECT Individual_Location_Service_Level__c 
        	FROM Account 
        	WHERE Name = 'C1' LIMIT 1].Individual_Location_Service_Level__c);
        System.assertEquals(
        	'b', 
        	[SELECT Individual_Location_Service_Level__c 
        	FROM Account 
        	WHERE Name = 'C2' LIMIT 1].Individual_Location_Service_Level__c);
        */
    }
}