objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Client First Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Client Last Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Best_Practice_Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Best Practice Evaluations</relationshipLabel>
        <relationshipName>Best_Practice_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Used to evaluate best practices for Analysts in regards to New Client Setups and Optimizations.</description>
    <label>Best Practice Evaluation</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Evaluation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Best Practice Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>Client_Email__c</fullName>
        <formula>Practice_Name__r.Client_E_mail__c</formula>
        <label>Client Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Quality_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account_Name__r.Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDCToCTSAsynchRequest__c.object
<CustomObject>
    <description>Stores DE-normalized CTS Ticket data to be executed by BULK job on a schedule to create CTS Tickets</description>
    <fields>
        <fullName>API_Identifier__c</fullName>
        <description>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</description>
        <inlineHelpText>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</inlineHelpText>
        <label>API Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTS_Email_Address__c</fullName>
        <description>Email address used to send object data to for creating CTS ticket when the Integration type is Email; required when Integration type is Email</description>
        <inlineHelpText>Email address used to send object data to for creating CTS ticket when the Integration type is Email; required when Integration type is Email</inlineHelpText>
        <label>CTS Email Address</label>
        <type>Email</type>
    </fields>
    <label>SFDCToCTSAsynchRequest</label>
    <nameField>
        <displayFormat>AR-{000000000}</displayFormat>
        <label>Asynch Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDCToCTSAsynchRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSSFDCObjectBase.cls
public virtual class CTSSFDCObjectBase
{
    public Id Id { get; set; }
    public String ObjectName { get; set; }
    public string Status { get; set; }
    public String Subject { get; set; }
    public String Detail { get; set; }
    public string ContactFirstName { get; set; }
    public string ContactLastName { get; set; }
    public string ContactEmailAddress { get; set; } 
    public string ContactPhone { get; set; }
    public string ReferenceAccountId { get; set; }
    public string ReferenceCustomerId { get; set; }
    public string ReferenceProductInstanceId { get; set; }
    public string ReferenceProductCodes { get; set; }
    public string Domain { get; set; }  
    public string ApiIdentifier { get; set; } 
    public string AlternateContactEmailAddress { get; set; } 
    public string CRMOrderNumber { get; set; }
    public string CTSEmailAddress { get; set; }
    
    private void CTSSFDCObjectBase(Id objId, String objName, SFDCToCTSAsynchRequest__c requestInstance, Messaging.SingleEmailMessage mail)
    {
        this.Id = objId;
        this.ObjectName = objName;
        this.ApiIdentifier = requestInstance.API_Identifier__c;
        this.CTSEmailAddress = requestInstance.CTS_Email_Address__c; 
        this.Status = 'Open';
        this.Subject = mail.getSubject();
        this.Detail = mail.getPlainTextBody();        
        //Manually append Account level info to Detail field
        this.Detail = this.Detail + '\r\n Client Id: ' + ReferenceCustomerId;
        this.Detail = this.Detail + '\r\n Client First Name: ' + ContactFirstName;
        this.Detail = this.Detail + '\r\n Client Last Name: ' + ContactLastName;
        this.Detail = this.Detail + '\r\n Client Email: ' + ContactEmailAddress;        
        this.Detail = this.Detail + '\r\n Client Phone: ' + ContactPhone;
        this.Detail = this.Detail + '\r\n Product Code: ' + ReferenceProductCodes;
        this.Detail += '\r\n';
                
              
        /*system.debug('email subject: ' + this.Subject);
        system.debug('email body: ' + this.Detail); */  
                 
    }
    
    public CTSSFDCObjectBase(Case sfCase, String objName, SFDCToCTSAsynchRequest__c requestInstance, Messaging.SingleEmailMessage mail)
    {        
        this.ContactFirstName = sfCase.Account.Client_First_Name__c;
        this.ContactLastName = sfCase.Account.Client_Last_Name__c;
        this.ContactEmailAddress = sfCase.Account.Email__c;
        this.ContactPhone = sfCase.Account.Phone;
        this.ReferenceAccountId = sfCase.Account.Id;
        this.ReferenceCustomerId = sfCase.Account.Client_ID__c;  
        this.ReferenceProductInstanceId = sfCase.Id;                                  
        this.Domain = sfCase.Account.Website;
        this.ReferenceProductCodes = sfCase.Account.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = sfCase.Client_Email__c;
        this.CRMOrderNumber = sfCase.CaseNumber;  
        CTSSFDCObjectBase(sfCase.Id, objName, requestInstance, mail);          
    }
    
    
    public CTSSFDCObjectBase(Organic_Analysis__c organicCase, String objName, SFDCToCTSAsynchRequest__c requestInstance,  Messaging.SingleEmailMessage mail)
    {        
        this.ContactFirstName = organicCase.Account_Name__r.Client_First_Name__c;
        this.ContactLastName = organicCase.Account_Name__r.Client_Last_Name__c;
        this.ContactEmailAddress = organicCase.Account_Name__r.Email__c; 
        this.ContactPhone = organicCase.Account_Name__r.Phone;
        this.ReferenceAccountId = organicCase.Account_Name__r.Id;
        this.ReferenceCustomerId = organicCase.Account_Name__r.Client_ID__c;  
        this.ReferenceProductInstanceId = organicCase.Id;                                
        this.Domain = organicCase.Account_Name__r.Website;
        this.ReferenceProductCodes = organicCase.Account_Name__r.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = organicCase.Account_Name__r.Email__c;  
        this.CRMOrderNumber = organicCase.Name;         
        CTSSFDCObjectBase(organicCase.Id, objName, requestInstance, mail);
    }
    
    public CTSSFDCObjectBase(Quality_Case__c qualityCase, String objName, SFDCToCTSAsynchRequest__c requestInstance,  Messaging.SingleEmailMessage mail)
    {        
        this.ContactFirstName = qualityCase.Account_Name__r.Client_First_Name__c;
        this.ContactLastName = qualityCase.Account_Name__r.Client_Last_Name__c;
        this.ContactEmailAddress = qualityCase.Account_Name__r.Email__c;     
        this.ContactPhone = qualityCase.Account_Name__r.Phone;
        this.ReferenceAccountId = qualityCase.Account_Name__r.Id;
        this.ReferenceCustomerId = qualityCase.Account_Name__r.Client_ID__c;   
        this.ReferenceProductInstanceId = qualityCase.Id;                                
        this.Domain = qualityCase.Account_Name__r.Website;
        this.ReferenceProductCodes = qualityCase.Account_Name__r.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = qualityCase.Account_Name__r.Email__c;
        this.CRMOrderNumber = qualityCase.Name; 
        CTSSFDCObjectBase(qualityCase.Id, objName, requestInstance, mail);             
    }
    
    public CTSSFDCObjectBase(Best_Practice_Evaluation__c bpe, String objName, SFDCToCTSAsynchRequest__c requestInstance,  Messaging.SingleEmailMessage mail)
    {        
        this.ContactFirstName = bpe.Account_Name__r.Client_First_Name__c;
        this.ContactLastName = bpe.Account_Name__r.Client_Last_Name__c;
        this.ContactEmailAddress = bpe.Account_Name__r.Email__c;    
        this.ContactPhone = bpe.Account_Name__r.Phone;
        this.ReferenceAccountId = bpe.Account_Name__r.Id;
        this.ReferenceCustomerId = bpe.Account_Name__r.Client_ID__c;
        this.ReferenceProductInstanceId = bpe.Id;                                   
        this.Domain = bpe.Account_Name__r.Website;
        this.ReferenceProductCodes = bpe.Account_Name__r.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = bpe.Account_Name__r.Email__c;  
        this.CRMOrderNumber = bpe.Name;  
        CTSSFDCObjectBase(bpe.Id, objName, requestInstance, mail);          
    }
    
    public CTSSFDCObjectBase(Customer_Surveys__c customerSurvey, String objName, SFDCToCTSAsynchRequest__c requestInstance,  Messaging.SingleEmailMessage mail)
    {        
        this.ContactFirstName = customerSurvey.Account__r.Client_First_Name__c;
        this.ContactLastName = customerSurvey.Account__r.Client_Last_Name__c;
        this.ContactEmailAddress = customerSurvey.Account__r.Email__c;    
        this.ContactPhone = customerSurvey.Account__r.Phone;
        this.ReferenceAccountId = customerSurvey.Account__r.Id;
        this.ReferenceCustomerId = customerSurvey.Account__r.Client_ID__c;  
        this.ReferenceProductInstanceId = customerSurvey.Id;                                 
        this.Domain = customerSurvey.Account__r.Website;
        this.ReferenceProductCodes = customerSurvey.Account__r.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = customerSurvey.Account__r.Email__c; 
        this.CRMOrderNumber = customerSurvey.Name;           
        CTSSFDCObjectBase(customerSurvey.Id, objName, requestInstance, mail);
    }
    
    /*public CTSSFDCObjectBase(Id objId, String objName, SFDCToCTSAsynchRequest__c requestInstance, Lighthouse_Worksheets__c sheet)
    {        
        this.ContactFirstName = sheet.Practice_Name__r.Client_First_Name__c;
        this.ContactLastName = sheet.Practice_Name__r.Client_Last_Name__c;
        this.ContactPhone = sheet.Practice_Name__r.Phone;
        this.ReferenceAccountId = sheet.Practice_Name__r.Id;
        this.ReferenceCustomerId = sheet.Practice_Name__r.Client_ID__c;                                   
        this.Domain = sheet.Practice_Name__r.Website;
        this.ReferenceProductCodes = sheet.Practice_Name__r.Product_Type_Transactional__c;        
        this.AlternateContactEmailAddress = sheet.Practice_Name__r.Email__c;  
        CTSSFDCObjectBase(objId, objName, requestInstance);           
    }
    */
    
    
    //Will be moved to CTSSyncServie
    /*private Messaging.SingleEmailMessage PopulateEmailSubjectBody(String emailTemplateId)
    {    
         //renderStoredEmailTemplate has the issue of SOQL governor limit
         //Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateId, null, Id, Messaging.AttachmentRetrievalOption.NONE);
                  
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         String[] toAddresses = new String[]{'YodleSFDC@fake.com'};
         mail.setToAddresses(toAddresses);
         mail.setUseSignature(false);
         mail.setSaveAsActivity(false);
         mail.setSenderDisplayName('YodleSFDC');         
         mail.setWhatId(This.Id); 
         mail.setTemplateId(emailTemplateId);
         Savepoint sp = Database.setSavepoint();
         Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
         Database.rollback(sp);
         return mail;                      
    }*/
}