objects/Account_Marketo_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Id__c</fullName>
        <externalId>true</externalId>
        <label>Activity Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity Type</label>
        <referenceTo>Activity_Type__c</referenceTo>
        <relationshipLabel>Account's Marketo Activity</relationshipLabel>
        <relationshipName>Account_s_Marketo_Activity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Lead_ID__c</fullName>
        <label>Marketo Lead ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Account Marketo Activity</label>
    <nameField>
        <displayFormat>AMA-{0000000}</displayFormat>
        <label>Account Marketo Activity  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account's Marketo Activity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeleteNoneAcctMarketoActivityBatchTest.cls
@isTest
private class DeleteNoneAcctMarketoActivityBatchTest {
	private static Map<String, String> activityTypeMap = new Map<String, String>{'6' => 'Send Email', '7' => 'Delivered Email', '8' => 'Bounced Email', '9' => 'Unsubscribed Email', '10' => 'Open Email', '11' => 'Click Email'};

	@isTest static void test_DeleteNoneAccountMarketoActivityBatch() {
		List<Activity_Type__c> activityTypeList = new List<Activity_Type__c>();
		for(String mapKey : activityTypeMap.keySet()){
			Activity_Type__c act = new Activity_Type__c();
			act.Name = activityTypeMap.get(mapKey);
			act.Activity_Type_ID__c = mapKey;
			activityTypeList.add(act);
		}
		insert activityTypeList;

		Account_Marketo_Activity__c acctMktAct = new Account_Marketo_Activity__c();
		acctMktAct.Activity_ID__c = '538';
		acctMktAct.Activity_Type_ID__c = '6';
		acctMktAct.Campaign_ID__c = '6052';
		acctMktAct.Marketo_Lead_ID__c = '70';
		insert acctMktAct;

		Test.startTest();
		DeleteNoneAccountMarketoActivitySchedule sched = new DeleteNoneAccountMarketoActivitySchedule();
		sched.execute(null);
		Test.stopTest();

		system.assert([select Id from Account_Marketo_Activity__c].size() == 0);
	}
	
}