objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Email_Sent__c</fullName>
        <label>ENG - Date Last Email Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Offer_Created__c</fullName>
        <label>ENG - Date Last Offer Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Review_Requested__c</fullName>
        <label>ENG - Date Last Review Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Triggered_Email__c</fullName>
        <label>ENG - Date Last Triggered Email Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Has_Active_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ENG - Has Active Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Has_Completed_Bulk_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ENG - Has Completed Bulk Contact Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Automated_Email_Activated__c</fullName>
        <label>ENG - Num Automated Emails Activated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Contacts__c</fullName>
        <label>ENG - Number of Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Emails_Sent__c</fullName>
        <label>ENG - Number of Emails Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Offers__c</fullName>
        <label>ENG - Number of Offers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Review_Request_Last_7_Day__c</fullName>
        <label>ENG - Num Review Requests Last 7 Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/YL_SyncClientEngagementDataRestAPITest.cls
@isTest
private class YL_SyncClientEngagementDataRestAPITest {
	
	@isTest static void syncEngagementDataTest() {
		Account newAccount = new Account();
		newAccount.Name = 'Test Name';
		newAccount.Client_ID__c = 'test1';
		insert newAccount;

		RestRequest req = new RestRequest();
	  	RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/clients/engagement';  //Request URL
		req.httpMethod = 'POST';//HTTP Request Type
		req.requestBody = Blob.valueof('[{"Engagement_Has_Active_Offer__c":"true","Engagement_Num_Contacts__c":"5","Engagement_Num_Emails_Sent__c":"10","Engagement_Num_Offers__c":null,"Engagement_Date_Last_Review_Requested__c":null,"Engagement_Has_Completed_Bulk_Import__c":"false","Engagement_Num_Automated_Email_Activated__c":null,"Engagement_Date_Last_Email_Sent__c":null,"Engagement_Date_Last_Offer_Created__c":null,"Client_ID__c":"test1","Engagement_Date_Last_Triggered_Email__c":null,"Engagement_Num_Review_Request_Last_7_Day__c":null}]');
		RestContext.request = req;
		RestContext.response= res;

		YL_SyncClientEngagementDataRestAPI.syncEngagementData();
	}
	
}