objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Engagement_Data_Last_Update__c</fullName>
        <inlineHelpText>Date/Time of when the Engagement Data was last updated!</inlineHelpText>
        <label>Engagement Data Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Email_Sent__c</fullName>
        <label>ENG - Date Last Email Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Offer_Created__c</fullName>
        <label>ENG - Date Last Offer Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Review_Requested__c</fullName>
        <label>ENG - Date Last Review Requested</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Date_Last_Triggered_Email__c</fullName>
        <label>ENG - Date Last Triggered Email Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Engagement_Has_Active_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ENG - Has Active Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Has_Completed_Bulk_Import__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ENG - Has Completed Bulk Contact Import</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Automated_Email_Activated__c</fullName>
        <label>ENG - Num Automated Emails Activated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Contacts__c</fullName>
        <label>ENG - Number of Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Emails_Sent__c</fullName>
        <label>ENG - Number of Emails Sent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Offers__c</fullName>
        <label>ENG - Number of Offers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Num_Review_Request_Last_7_Day__c</fullName>
        <label>ENG - Num Review Requests Last 7 Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EngagementDataViewController.cls
public with sharing class EngagementDataViewController {

	public Account acct {get; set;}

    private ApexPages.StandardController sContr;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public EngagementDataViewController(ApexPages.StandardController stdController) {
        //acct = (Account)stdController.getRecord();
        sContr = stdController;
        retrieveAcctData();
    }

    private void retrieveAcctData(){
        acct = [select Id, Client_ID__c, Engagement_Has_Active_Offer__c, Engagement_Num_Contacts__c, Engagement_Num_Emails_Sent__c, Engagement_Num_Offers__c, Engagement_Date_Last_Review_Requested__c, Engagement_Has_Completed_Bulk_Import__c, Engagement_Num_Automated_Email_Activated__c, Engagement_Date_Last_Email_Sent__c, Engagement_Date_Last_Offer_Created__c, Engagement_Date_Last_Triggered_Email__c, Engagement_Num_Review_Request_Last_7_Day__c, Engagement_Data_Last_Update__c from Account where Id =: sContr.getId()];
    }

    public void updateEngagementData(){
        if(String.isNotBlank(acct.Client_ID__c)){
            YodleLiveSyncClientEngagementDataHelper.reqClientEngagementData(new List<Integer>{Integer.valueof(acct.Client_ID__c)});
            sContr.getRecord();
        }
        retrieveAcctData();
    }

}