objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please Update this Field in Yodle Live. User Roles: National Interactive Marketing Manager</inlineHelpText>
        <label>Customer Success Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bulk_Google_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This should be checked when there is a bulk google account that will be used for maps claiming</inlineHelpText>
        <label>Bulk Google Account (do not use)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testParentAccountFields.cls
@isTest
 private class testParentAccountFields{
 static testMethod void testParentAccountFields(){
 User u = [select name, Id from User where Name = 'Chris Cormier'];
      
Account a = new Account(
            Name = 'Testerson Corp.'
            );
            
       insert a;
    

Account b = new Account(
            Name = 'Child 1',
           ParentId = a.Id                    
            );
            insert b;
            
Contact c = new Contact(
        FirstName = 'Dave',
        LastName = 'Thomas',
        AccountId = a.Id
);           
insert c;
a.Account_Director__c = u.Id;
a.Bulk_Google_Account__c = TRUE;


       Test.startTest(); 
  update a;         
    test.stopTest();  
 }
 }