objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M001 - Discovery call</fullName>
                </value>
                <value>
                    <fullName>M002 - Internal download call</fullName>
                </value>
                <value>
                    <fullName>M003 - Demo/Value Presentation</fullName>
                </value>
                <value>
                    <fullName>M004 - Detailed Audit Discovery</fullName>
                </value>
                <value>
                    <fullName>M005 - Audit download</fullName>
                </value>
                <value>
                    <fullName>M006 - Implementation &amp; ROI Investigation Call</fullName>
                </value>
                <value>
                    <fullName>M007 - Product Assessment &amp; Strategy</fullName>
                </value>
                <value>
                    <fullName>M008 - Solutions in Action Presentation</fullName>
                </value>
                <value>
                    <fullName>M009 - Proposal Creation &amp; Update SOW</fullName>
                </value>
                <value>
                    <fullName>M010 - Present Proposal &amp; SOW</fullName>
                </value>
                <value>
                    <fullName>M011 - Moving to Close</fullName>
                </value>
                <value>
                    <fullName>M012 - Proof of Value Agreement</fullName>
                </value>
                <value>
                    <fullName>M013 - Contract Creation</fullName>
                </value>
                <value>
                    <fullName>M014 - Deliver Contract to the Customer</fullName>
                </value>
                <value>
                    <fullName>M001 - Set local demo (IL)</fullName>
                </value>
                <value>
                    <fullName>M002 - Complete local demo (IL)</fullName>
                </value>
                <value>
                    <fullName>M003 - Contract (IL)</fullName>
                </value>
                <value>
                    <fullName>M100 - Deal closes</fullName>
                </value>
                <value>
                    <fullName>CLOSED LOST</fullName>
                </value>
                <value>
                    <fullName>M1 - Discovery</fullName>
                </value>
                <value>
                    <fullName>M2 - Demo &amp; Value Presentation</fullName>
                </value>
                <value>
                    <fullName>M3 - Executive Review</fullName>
                </value>
                <value>
                    <fullName>M4 - Solutions Review</fullName>
                </value>
                <value>
                    <fullName>M5 - Proposal</fullName>
                </value>
                <value>
                    <fullName>M6 - Contract</fullName>
                </value>
                <value>
                    <fullName>Client Discovery</fullName>
                </value>
                <value>
                    <fullName>Demo/Value Prop</fullName>
                </value>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Local</label>
        
    </recordTypes>
</CustomObject>

classes/wbn_UpdateOppStageOnScheduledEventTest.cls
@isTest
private class wbn_UpdateOppStageOnScheduledEventTest 
{
    private static testMethod void upsertEventTest()
    {
        // load test data from static resources
        List<SObject> acctList = Test.LoadData(Account.sObjectType, 'testAccounts');
        List<SObject> oppList = Test.LoadData(Opportunity.sObjectType, 'testOpportunities');
        Set<Id> oppIds = new Set<Id>();
        List<Event> evtsToUpdate = new List<Event>();
        Date todayDt = Date.Today();
        
        Account acct = (Account)acctList[0];
        Id acctId = acct.Id;
        
        Opportunity opp = (Opportunity)oppList[0];
        Id oppId = opp.Id;
        
        opp.AccountId = acctId;
        opp.StageName = 'New Opportunity';
        opp.CloseDate = todayDt;
        update opp;
        
        oppIds.add(oppId);
        
        Test.startTest();
        
        Event evt = new Event();
        evt.ActivityDate = todayDt;
        evt.ActivityDateTime = DateTime.Now();
        evt.EndDateTime = DateTime.Now().addHours(7);
        evt.EventSubtype = 'Event';
        evt.Status__c = 'Scheduled';
        evt.Milestone__c = 'IL Demo Scheduled';
        evt.Subject = 'IL Demo';
        evt.WhatId = oppId;
        evt.IsRecurrence = false;
        evt.IsAllDayEvent = false;
        insert evt;
        
        evtsToUpdate.add(evt);
        
        for(Opportunity o : [SELECT Id, StageName FROM Opportunity WHERE Id IN :oppIds]){
            System.assertEquals(o.StageName, 'M001 - Set Local Demo');
        }
        
        for(Event e : evtsToUpdate){
            e.Status__c = 'Completed';
        }
        
        update evtsToUpdate;
        
        for(Opportunity o : [SELECT Id, StageName FROM Opportunity WHERE Id IN :oppIds]){
            System.assertEquals(o.StageName, 'M002 - Complete local demo (IL)');
        }
        
        Test.stoptest();
    }
}