objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSC_Completed_Date__c</fullName>
        <label>CSC Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Experience_Key__c</fullName>
        <label>Client Experience Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Scheduled_Touchpoint__c</fullName>
        <label>Next Scheduled Touchpoint</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Plan_Id__c</fullName>
        <label>Product Plan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Custom_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Account_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Automation_Status__c</fullName>
        <label>Automation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Outcome</fullName>
                    <default>true</default>
                    <label>Waiting on Outcome</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Trigger_Date__c</fullName>
        <label>Automation Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Automation_Type_API_Name_External_ID__c</fullName>
        <inlineHelpText>Use the Touchplan API Name for Custom Metadata Types or the assigned External ID for Marketo Email Campaign</inlineHelpText>
        <label>Automation Type API Name/External ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create_Day_40_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>Create_Monthly_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_7</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_27</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_DAY_40</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_EVERY_30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Type__c</fullName>
        <label>Automation Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketo_Email_Campaign__c</fullName>
                </value>
                <value>
                    <fullName>Daily_Scheduled_Record_Auto_Create__mdt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Automation</label>
    <nameField>
        <displayFormat>AAN-{0000000}</displayFormat>
        <label>Custom Automation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Daily_Scheduled_Record_Auto_Create__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Daily Scheduled Record Auto Create</label>
    <pluralLabel>Daily Scheduled Record Auto Create</pluralLabel><visibility>Public</visibility>
</CustomObject>

objects/Integration_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Sync_Account_Data_With_Marketo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Account Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Organic_Case_Data_With_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Organic Case Data With Marketo</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Integration Settings</label>
</CustomObject>

objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marketo Email Campaigns</relationshipLabel>
        <relationshipName>Marketo_Email_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Automation_API_Reference__c</fullName>
        <label>Custom Automation API Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_Campaign_ID__c</fullName>
        <label>Marketo Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomAutomationScheduleBatchesTest.cls
@isTest
private class CustomAutomationScheduleBatchesTest {
	
	@isTest static void test_CustomAutomationScheduleBatches() {
		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();
		Integration_Settings__c integrationSetting = Integration_Settings__c.getOrgDefaults();
		integrationSetting.Sync_Account_Data_With_Marketo__c = false;
		integrationSetting.Sync_Organic_Case_Data_With_Marketo__c = false;
		integrationSetting.Sync_Case_Data_With_Marketo__c = false;
		update integrationSetting;

		Marketo_Email_Campaign__c marketoEmailCampaignTemplate = new Marketo_Email_Campaign__c();
		marketoEmailCampaignTemplate.RecordTypeId = Schema.SObjectType.Marketo_Email_Campaign__c.getRecordTypeInfosByName().get('Template').getRecordTypeId();
		marketoEmailCampaignTemplate.Name = 'Test Template';
		marketoEmailCampaignTemplate.Marketo_Campaign_ID__c = '5332';
		marketoEmailCampaignTemplate.Criteria__c = 'select Id, Marketo_ID__c from Account';
		marketoEmailCampaignTemplate.Active__c = true;
		marketoEmailCampaignTemplate.Custom_Automation_API_Reference__c = 'TORCHX_MONTHLY_REVIEW_EVERY_30';
		marketoEmailCampaignTemplate.Create_Case__c = true;
		insert marketoEmailCampaignTemplate;

		List<Account> newAccountList = new List<Account>();

		Account lbwAccount = new Account();
		lbwAccount.Name = 'Test Account';
		lbwAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT()*0.444564);
		lbwAccount.Status__c = 'LIVE';
		lbwAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*0.343) + '@t3esf784338778t.4co4f444asm';
		lbwAccount.Client_Type__c = 'Local';
		lbwAccount.Product_Plan_ID__c = 'LEADS_BY_WEB';
		lbwAccount.Client_Experience_Key__c = 'web.com-main';
		//newAccount.Budget_Ads__c = 700;
		lbwAccount.Live_Date__c = Date.today().addDays(-54);
		lbwAccount.Sync_to_Marketo__c = true;
		lbwAccount.Next_Scheduled_Touchpoint__c = Date.today().addDays(40);
		newAccountList.add(lbwAccount);

		Account torchxAccount = new Account();
		torchxAccount.Name = 'Test Account';
		torchxAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT()*0.4443);
		torchxAccount.Status__c = 'LIVE';
		torchxAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()*0.3334) + '@t3esf7844348778t.4co4f4444asm';
		torchxAccount.Client_Type__c = 'Local';
		torchxAccount.Product_Type__c = 'TORCHX';
		//newAccount.Budget_Ads__c = 700;
		torchxAccount.Live_Date__c = Date.today().addDays(-54);
		torchxAccount.Sync_to_Marketo__c = true;
		torchxAccount.CSC_Completed_Date__c = Date.today().addDays(-40);
		newAccountList.add(torchxAccount);

		insert newAccountList;

		Custom_Automation__c lbwCA = new Custom_Automation__c();
		lbwCA.Account__c = newAccountList[0].Id;
		lbwCA.Automation_Type__c = 'Daily_Scheduled_Record_Auto_Create__mdt';
		lbwCA.Automation_Trigger_Date__c = Date.today();
		lbwCA.Automation_Status__c = 'Scheduled';
		lbwCA.Automation_Type_API_Name_External_ID__c = 'Create_Monthly_LBW_Account_Performance';
		insert lbwCA;

		Custom_Automation__c torchxCA = new Custom_Automation__c();
		torchxCA.Account__c = newAccountList[1].Id;
		torchxCA.Automation_Type__c = 'Marketo_Email_Campaign__c';
		torchxCA.Automation_Trigger_Date__c = Date.today();
		torchxCA.Automation_Status__c = 'Scheduled';
		torchxCA.Automation_Type_API_Name_External_ID__c = 'TORCHX_MONTHLY_REVIEW_EVERY_30';
		insert torchxCA;

		Test.startTest();
		CustomAutomationScheduleBatches sched = new CustomAutomationScheduleBatches();
		sched.execute(null);
		Test.stopTest();
	}
	
}