objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_Live_Date__c</fullName>
        <description>Live Date that never gets reset if an Account goes from OFF to LIVE</description>
        <inlineHelpText>Live Date that never gets reset if an Account goes from OFF to LIVE</inlineHelpText>
        <label>Initial Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Vertical__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Acupuncture</fullName>
                </value>
                <value>
                    <fullName>Alternative Medicine</fullName>
                </value>
                <value>
                    <fullName>Apartment Rentals</fullName>
                </value>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Appraiser</fullName>
                </value>
                <value>
                    <fullName>Arborist</fullName>
                </value>
                <value>
                    <fullName>Architects &amp; Engineers</fullName>
                </value>
                <value>
                    <fullName>Auctioneers</fullName>
                </value>
                <value>
                    <fullName>Auto Body Shop</fullName>
                </value>
                <value>
                    <fullName>Auto Dealer</fullName>
                </value>
                <value>
                    <fullName>Auto Glass</fullName>
                </value>
                <value>
                    <fullName>Auto Painting</fullName>
                </value>
                <value>
                    <fullName>Auto repair</fullName>
                </value>
                <value>
                    <fullName>Bail Bonds</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Banquet Rooms</fullName>
                </value>
                <value>
                    <fullName>Beauty and Salon Training</fullName>
                </value>
                <value>
                    <fullName>Blinds</fullName>
                </value>
                <value>
                    <fullName>Boat Charters</fullName>
                </value>
                <value>
                    <fullName>Bridal</fullName>
                </value>
                <value>
                    <fullName>Car Parts</fullName>
                </value>
                <value>
                    <fullName>Carpenter</fullName>
                </value>
                <value>
                    <fullName>Carpet - Install &amp; Cleaning</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Ceilings</fullName>
                </value>
                <value>
                    <fullName>Child Care</fullName>
                </value>
                <value>
                    <fullName>Chimney</fullName>
                </value>
                <value>
                    <fullName>Chiropractic</fullName>
                </value>
                <value>
                    <fullName>Cleaning Services</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Combo 1.0</fullName>
                </value>
                <value>
                    <fullName>Combo 2.0</fullName>
                </value>
                <value>
                    <fullName>SEO Only</fullName>
                </value>
                <value>
                    <fullName>YO 1.0</fullName>
                </value>
                <value>
                    <fullName>YO 2.0</fullName>
                </value>
                <value>
                    <fullName>YO 3.0</fullName>
                </value>
                <value>
                    <fullName>OR 1.0</fullName>
                </value>
                <value>
                    <fullName>OR 2.0</fullName>
                </value>
                <value>
                    <fullName>OR 3.0</fullName>
                </value>
                <value>
                    <fullName>OR+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Quality_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                    <isActive>false</isActive>
                    <label>Delete Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>For Closing Script - Auto Launch Case</description>
        <label>Product Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSAsyncRequestCreateTest.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 28-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 28-Jan-2019
  Description ........: Test Class for CTSAsyncRequestCreate
*****************************************************************************/
@isTest(seeAllData=true)
private class CTSAsyncRequestCreateTest
{
    
    private static testMethod void createAsyncCase()
    {
        List<Id> caseIds = new List<Id>();
        List<Account> dmlAccounts = new List<Account>();
        Id acctId;
        List<Case> dmlCases = new List<Case>();
        Date todayDt = Date.Today();
        Date liveDate = todayDt.addDays(-10);
        Id IMSRepId = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1].Id;
        Id businessHrsId = [SELECT Id FROM BusinessHours WHERE Name = 'Local Business' LIMIT 1].Id;
        Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
        
        Account acct = new Account();
        acct.Name = 'Test Class Account 1';
        acct.Product_Type__c = 'LBW';
        acct.Secondary_Segments__c = 'Lawyer';
        acct.Status__c = 'LIVE';
        acct.Email__c = 'fake@faketest.com';
        acct.Initial_Live_Date__c = liveDate;
        acct.Live_Date__c = liveDate;
        dmlAccounts.add(acct);
        
        if(dmlAccounts.size() > 0){
        
            insert dmlAccounts;
            
            for(Account a : dmlAccounts){
                
                acctId = a.Id;
            }
        }
        
        System.Debug('Account from (Account): ' + acct.Name);
        
        Case caseData = new Case();
        caseData.RecordTypeId = caseRecordTypeId;
        caseData.AccountId = acctId;
        caseData.Reason = 'CS Touch Plan';
        caseData.Origin = 'Touch Plan 1';
        caseData.OwnerId = IMSRepId;
        caseData.Status = 'New';
        caseData.Priority = 'Major';
        caseData.Subject = 'Lead Stream TP 1';
        dmlCases.add(caseData);
        
        System.Debug('Account from (Case): ' + caseData.Account.Name);
        
        if(dmlCases.size() > 0){
            insert dmlCases;
            
            for(Case c : dmlCases){
                
                caseIds.add(c.Id);
            }
        }
        
        // start test
        Test.StartTest();
        
        // execute Invocable method
        CTSAsyncRequestCreate.CreateNewAsyncRequest(caseIds);
        
        Test.stopTest();
    }
    
    private static testMethod void createAsyncOrganicCase()
    {
        List<Account> dmlAccounts = new List<Account>();
        Id acctId;
        List<Id> orgCaseIds = new List<Id>();
        List<Organic_Analysis__c> dmlOrgCases = new List<Organic_Analysis__c>();
        Date todayDt = Date.Today();
        Date liveDate = todayDt.addDays(-10);
        Id orgCaseRecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('PIN Action Needed').getRecordTypeId();
        
        Account acct = new Account();
        acct.Name = 'Test Class Account 1';
        acct.Product_Type__c = 'LBW';
        acct.Secondary_Segments__c = 'Lawyer';
        acct.Status__c = 'LIVE';
        acct.Email__c = 'fake@faketest.com';
        acct.Initial_Live_Date__c = liveDate;
        acct.Live_Date__c = liveDate;
        dmlAccounts.add(acct);
        
        if(dmlAccounts.size() > 0){
        
            insert dmlAccounts;
            
            for(Account a : dmlAccounts){
                
                acctId = a.Id;
            }
        }
        
        System.Debug('Account from (Account): ' + acct.Name);
        
        Organic_Analysis__c orgCaseData = new Organic_Analysis__c();
        orgCaseData.RecordTypeId = orgCaseRecordTypeId;
        orgCaseData.Account_Name__c = acctId;
        orgCaseData.Subject__c = 'PAN - Maps Contact - Comanage';
        orgCaseData.Status__c = 'New';
        dmlOrgCases.add(orgCaseData);
        
        System.Debug('Account from (Organic Case): ' + orgCaseData.Account_Name__r.Name);
        
        if(dmlOrgCases.size() > 0){
            insert dmlOrgCases;
            
            for(Organic_Analysis__c oc : dmlOrgCases){
                
                orgCaseIds.add(oc.Id);
            }
        }
        
        // start test
        Test.StartTest();
        
        // execute Invocable method
        CTSAsyncRequestCreate.CreateNewAsyncRequest(orgCaseIds);
        
        Test.stopTest();
    }
    
    private static testMethod void createAsyncQualityCase()
    {
        List<Account> dmlAccounts = new List<Account>();
        Id acctId;
        List<Id> qualityCaseIds = new List<Id>();
        List<Quality_Case__c> dmlQualityCases = new List<Quality_Case__c>();
        Date todayDt = Date.Today();
        Date liveDate = todayDt.addDays(-10);
        Id qualityCaseRecordTypeId = Schema.SObjectType.Quality_Case__c.getRecordTypeInfosByName().get('Closing Script - Auto Launch').getRecordTypeId();
        
        Account acct = new Account();
        acct.Name = 'Test Class Account 1';
        acct.Product_Type__c = 'LBW';
        acct.Secondary_Segments__c = 'Lawyer';
        acct.Status__c = 'LIVE';
        acct.Email__c = 'fake@faketest.com';
        acct.Initial_Live_Date__c = liveDate;
        acct.Live_Date__c = liveDate;
        dmlAccounts.add(acct);
        
        if(dmlAccounts.size() > 0){
        
            insert dmlAccounts;
            
            for(Account a : dmlAccounts){
                
                acctId = a.Id;
            }
        }
        
        System.Debug('Account from (Account): ' + acct.Name);
        
        Quality_Case__c qualityCaseData = new Quality_Case__c();
        qualityCaseData.RecordTypeId = qualityCaseRecordTypeId;
        qualityCaseData.Account_Name__c = acctId;
        qualityCaseData.Subject__c = 'QA Closing Script TEST';
        qualityCaseData.Status__c = 'New';
        dmlQualityCases.add(qualityCaseData);
        
        System.Debug('Account from (Quality Case): ' + qualityCaseData.Account_Name__r.Name);
        
        if(dmlQualityCases.size() > 0){
            insert dmlQualityCases;
            
            for(Quality_Case__c qc : dmlQualityCases){
                
                qualityCaseIds.add(qc.Id);
            }
        }
        
        // start test
        Test.StartTest();
        
        // execute Invocable method
        CTSAsyncRequestCreate.CreateNewAsyncRequest(qualityCaseIds);
        
        Test.stopTest();
    }
    
    private static testMethod void createAsyncCustomerSurvey()
    {
        List<Account> dmlAccounts = new List<Account>();
        Id acctId;
        List<Id> custSurveyIds = new List<Id>();
        List<Customer_Surveys__c> dmlCustSurveys = new List<Customer_Surveys__c>();
        Date todayDt = Date.Today();
        Date liveDate = todayDt.addDays(-10);
        Id custSurveyRecordTypeId = Schema.SObjectType.Customer_Surveys__c.getRecordTypeInfosByName().get('NPS Survey LBW').getRecordTypeId();
        
        Account acct = new Account();
        acct.Name = 'Test Class Account 1';
        acct.Product_Type__c = 'LBW';
        acct.Secondary_Segments__c = 'Lawyer';
        acct.Status__c = 'LIVE';
        acct.Email__c = 'fake@faketest.com';
        acct.Initial_Live_Date__c = liveDate;
        acct.Live_Date__c = liveDate;
        dmlAccounts.add(acct);
        
        if(dmlAccounts.size() > 0){
        
            insert dmlAccounts;
            
            for(Account a : dmlAccounts){
                
                acctId = a.Id;
            }
        }
        
        System.Debug('Account from (Account): ' + acct.Name);
        
        Customer_Surveys__c custSurveyData = new Customer_Surveys__c();
        custSurveyData.RecordTypeId = custSurveyRecordTypeId;
        custSurveyData.Account__c = acctId;
        custSurveyData.Status__c = 'New';
        dmlCustSurveys.add(custSurveyData);
        
        System.Debug('Account from (Customer Survey): ' + custSurveyData.Account__r.Name);
        
        if(dmlCustSurveys.size() > 0){
            insert dmlCustSurveys;
            
            for(Customer_Surveys__c cs : dmlCustSurveys){
                
                custSurveyIds.add(cs.Id);
            }
        }
        
        // start test
        Test.StartTest();
        
        // execute Invocable method
        CTSAsyncRequestCreate.CreateNewAsyncRequest(custSurveyIds);
        
        Test.stopTest();
    }
}