objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type_ID__c</fullName>
        <label>Activity Type ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AdjustCustomCodeLimit__c.object
<CustomObject>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to adjust limits in code</description>
    <label>AdjustCustomCodeLimit</label>
</CustomObject>

classes/AccountMarketoActivityQueueableTest.cls
@isTest
private class AccountMarketoActivityQueueableTest {

	private static Map<String, String> activityTypeMap = new Map<String, String>{'6' => 'Send Email', '7' => 'Delivered Email', '8' => 'Bounced Email', '9' => 'Unsubscribed Email', '10' => 'Open Email', '11' => 'Click Email'};
	
	@isTest static void test_AccountMarketoActivityQueueable() {	
		AdjustCustomCodeLimit__c calloutLimit = new AdjustCustomCodeLimit__c();
		calloutLimit.Name = 'AccountMarketoActivityQueueableLimit';
		calloutLimit.Limit__c = 5;
		insert calloutLimit;

		List<Account> testAccountList = new List<Account>();

		Account testAccount1 = new Account();
		testAccount1.Name = 'Test Name';
		testAccount1.Marketo_ID__c = '70';
		testAccount1.Email__c = 'testaccount1@testemail.com';
		testAccountList.add(testAccount1);

		Account testAccount2 = new Account();
		testAccount2.Name = 'Test Name';
		testAccount2.Marketo_ID__c = '11142';
		testAccount2.Email__c = 'testAccount2@testemail.com';
		testAccountList.add(testAccount2);

		Account testAccount3 = new Account();
		testAccount3.Name = 'Test Name';
		testAccount3.Marketo_ID__c = '11136';
		testAccount3.Email__c = 'testAccount3@testemail.com';
		testAccountList.add(testAccount3);

		Account testAccount4 = new Account();
		testAccount4.Name = 'Test Name';
		testAccount4.Marketo_ID__c = '11086';
		testAccount4.Email__c = 'testAccount4@testemail.com';
		testAccountList.add(testAccount4);

		insert testAccountList;

		List<Activity_Type__c> activityTypeList = new List<Activity_Type__c>();
		for(String mapKey : activityTypeMap.keySet()){
			Activity_Type__c act = new Activity_Type__c();
			act.Name = activityTypeMap.get(mapKey);
			act.Activity_Type_ID__c = mapKey;
			activityTypeList.add(act);
		}
		insert activityTypeList;

		String responseExample = [SELECT Id, Body FROM StaticResource WHERE Name = 'AccountMarketoActivityTestDataJSON' LIMIT 1].Body.toString();
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Test.startTest();
		AccountMarketoActivitySchedule sched = new AccountMarketoActivitySchedule();
		sched.execute(null);
		Test.stopTest();
	}

}