objects/Account.object
<CustomObject>
    <fields>
        <fullName>Days_Since_Live__c</fullName>
        <formula>today()- Live_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Live</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tz__Timezone_IANA__c</fullName>
        <description>Timezone as defined by Internet Assigned Numbers Authority (IANA).</description>
        <inlineHelpText>Timezone as defined by Internet Assigned Numbers Authority (IANA).</inlineHelpText>
        <label>Timezone (IANA)</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>Case_Reason_Criteria__c</fullName>
        <inlineHelpText>Put the Case Reason criteria to sync this fields to Marketo!</inlineHelpText>
        <label>Case Reason Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Blank_Values__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When a value is changed from a value to blank, update the Marketo field value to null.</description>
        <inlineHelpText>When a value is changed from a value to blank, update the Marketo field value to null.</inlineHelpText>
        <label>Sync Blank Values</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Only supported for Record Type 'Outbound Call' with Case Reason 'CSC'!</description>
    <label>SFDC Case to Marketo Field Mappings</label>
</CustomObject>

classes/CaseObjectHelper.cls
public without sharing class CaseObjectHelper {
	public static Boolean alreadyFiredCaseObjectHelper = false;
	public static Set<Id> recordTypeIdSet = new Set<Id>{Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId()};
	private static Id ncsCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('NCS - AutoLaunch').getRecordTypeId();
	//public static Set<String> caseReasonSet = new Set<String>{'CSC'};
	private static Id caseMasterRecordTypeId = [select Id, Name, DeveloperName, SobjectType from RecordType where Name = 'Master' and SObjectType = 'Case'].Id;
	private static Id syncUserId = [select Id, Name from User where Name = 'SFDC Sync'].Id;
	private static List<String> reasonAndReasonDetailExclusionList = new List<String>{'Free Time', 'Training', 'CSC', 'Quality Team', 'Other', 'Out of Sync', 'Charge', 'Adoption', 'Maps Verification', 'Unknown', 'Cancel', 'Touch', 'Setup', 'Upsell', 'Pin Collection', 'Downsell', 'Invoice', 'Proactive', 'Taxonomy', 'Escalation', 'Communication', 'Billing'};
	private static List<String> originExclusionList = new List<String>{'phone', 'chat', 'email', '@lighthousepmg.com', '@web.com', '@torchx'};

	public static Boolean alreadyFiredCalendarBlockerForCase = false;

	private static final Map<Id, User> activeStandardUserIdMap = new Map<Id, User>([select Id from User where IsActive = true and UserType = 'Standard']);

	private static Set<String> supportedCaseReasonSet(){
		Set<String> stringSet = new Set<String>();
		for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : SFDC_Case_to_Marketo_Field_Mappings__c.getAll().values()){
			if(sfdcCaseMarketoFieldMap.Sync_Field__c){
				if(String.isNotBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) && !stringSet.contains(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c)){
					//stringSet.addAll(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.replace(',  ', ',').replace(', ', ',').split(','));
					for(String str : sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.split(',')){
						stringSet.add(str.trim());
					}
				}
			}
		}
		return stringSet;
	}

	public static void syncCaseRecordLogic(List<Case> newValue, Map<Id, Case> oldValue){
		Set<Id> accountIdSet = new Set<Id>();
		for(Case cs : newValue){
			if(!cs.Sync_to_Marketo__c && String.isNotBlank(cs.AccountId) && recordTypeIdSet.contains(cs.RecordTypeId) && supportedCaseReasonSet().contains(cs.Reason)){
				accountIdSet.add(cs.AccountId);
			}else if(!cs.Sync_to_Marketo__c && String.isNotBlank(cs.AccountId) && !oldValue.isEmpty() && issueResolutionCriteriaMet(cs, oldValue.get(cs.Id))){
				accountIdSet.add(cs.AccountId);
			}else if(!cs.Sync_to_Marketo__c && cs.RecordTypeId == ncsCaseRecordTypeId){
				accountIdSet.add(cs.AccountId);
			}
		}

		if(!accountIdSet.isEmpty()){
			Map<Id, Account> accountRecordMap = new Map<Id, Account>([select Id, Marketo_ID__c, Sync_to_Marketo__c, Days_Since_Live__c, Secondary_Segments__c, Client_Type__c, Product_Type_Transactional__c from Account where Id in :accountIdSet and Marketo_ID__c != '' and Sync_to_Marketo__c = true]);
			for(Case cs : newValue){
				if(accountRecordMap.containsKey(cs.AccountId)){
					Account acct = accountRecordMap.get(cs.AccountId);
					if(!cs.Sync_to_Marketo__c && oldValue.isEmpty() && /*acct.Client_Type__c == 'Local' &&*/ ((recordTypeIdSet.contains(cs.RecordTypeId) && supportedCaseReasonSet().contains(cs.Reason)) || (cs.RecordTypeId == ncsCaseRecordTypeId && cs.Next_Scheduled_CSC2__c != null))){
						cs.Sync_to_Marketo__c = true;
					}else if(!cs.Sync_to_Marketo__c && /*acct.Client_Type__c == 'Local' &&*/ recordTypeIdSet.contains(cs.RecordTypeId) && supportedCaseReasonSet().contains(cs.Reason) && (acct.Days_Since_Live__c == null || acct.Days_Since_Live__c <= 30)){
						cs.Sync_to_Marketo__c = true;
					}else if(!cs.Sync_to_Marketo__c && !oldValue.isEmpty() && cs.RecordTypeId == caseMasterRecordTypeId && cs.OwnerId != syncUserId){// && accountRecordMap.get(cs.AccountId).Client_Type__c.containsIgnoreCase('Lighthouse') && !accountRecordMap.get(cs.AccountId).Product_Type_Transactional__c.equalsIgnoreCase('Yodle Web')){
						cs.Sync_to_Marketo__c = issueResolutionCriteriaMet(cs, oldValue.get(cs.Id));
					}
				}
			}
		}
	}

	public static void caseMarketoSyncHelper(Map<Id, Case> newValue, Map<Id, Case> oldValue){
		List<SFDC_Case_to_Marketo_Field_Mappings__c> sfdcAPINameSFDCMarketoFieldMappingList = new List<SFDC_Case_to_Marketo_Field_Mappings__c>();
		for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : SFDC_Case_to_Marketo_Field_Mappings__c.getAll().values()){
			if(sfdcCaseMarketoFieldMap.Sync_Field__c){
				sfdcAPINameSFDCMarketoFieldMappingList.add(sfdcCaseMarketoFieldMap);
			}
		}

		List<Case> caseSyncList = new List<Case>();
		List<Case> issueResolutionCaseSyncList = new List<Case>();
		List<Case> ncsCaseScheduledCSCList = new List<Case>();

		for(Case record : newValue.values()){
			Boolean syncToMarketo = false;
			if(record.Sync_to_Marketo__c && oldValue.isEmpty() && recordTypeIdSet.contains(record.RecordTypeId) && supportedCaseReasonSet().contains(record.Reason)){
				syncToMarketo = true;
			}else if(record.Sync_to_Marketo__c && !oldValue.isEmpty() && recordTypeIdSet.contains(record.RecordTypeId) && supportedCaseReasonSet().contains(record.Reason)){
				Case oldRecord = oldValue.get(record.Id);
				for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : sfdcAPINameSFDCMarketoFieldMappingList){
					if(record.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != oldRecord.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase(record.Reason)) && (sfdcCaseMarketoFieldMap.Sync_Blank_Values__c || (!sfdcCaseMarketoFieldMap.Sync_Blank_Values__c && record.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != null))) {
						syncToMarketo = true;
						break;
					}
				}
			}

			if(syncToMarketo){
				caseSyncList.add(record);
			}

			if(record.Sync_to_Marketo__c && !oldValue.isEmpty() && record.RecordTypeId == caseMasterRecordTypeId && record.OwnerId != syncUserId && issueResolutionCriteriaMet(record, oldValue.get(record.Id))){
				system.debug(issueResolutionCriteriaMet(record, oldValue.get(record.Id)));
				issueResolutionCaseSyncList.add(record);
			}

			if(record.Sync_to_Marketo__c && oldValue.isEmpty() && record.RecordTypeId == ncsCaseRecordTypeId && record.Next_Scheduled_CSC2__c != null){
				ncsCaseScheduledCSCList.add(record);
			}
		}

		if(!caseSyncList.isEmpty()){
			caseUpdateLeads('', '', JSON.serialize(caseSyncList), false, '');
			CaseObjectHelper.alreadyFiredCaseObjectHelper = true;
		}

		if(!issueResolutionCaseSyncList.isEmpty()){
			issueResolutionCaseUpdateLeads('', '', JSON.serialize(issueResolutionCaseSyncList), false, '');
			CaseObjectHelper.alreadyFiredCaseObjectHelper = true;
		}

		if(!ncsCaseScheduledCSCList.isEmpty()){
			ncsCaseUpdateMarketoCSCSchedule('', '', JSON.serialize(ncsCaseScheduledCSCList), false, '');
		}
	}

	private static Boolean issueResolutionCriteriaMet(Case newValue, Case oldValue){
		if(!activeStandardUserIdMap.containsKey(newValue.OwnerId)){
			return false;
		}else if(!newValue.IsClosed){
			return false;
		}else if(newValue.ClosedDate.date() != Date.today()){
			return false;
		}/*else if(newValue.Status != 'Closed'){
			return false;
		}else if(newValue.Status == 'Closed' && newValue.Status == oldValue.Status){
			return false;
		}*/else if(String.isNotBlank(newValue.Reason) && newValue.Reason.containsIgnoreCase('Product')){
			return false;
		}else if(String.isNotBlank(newValue.Origin) && newValue.Origin.containsIgnoreCase('yodle.com')){
			return false;
		}

		for(String record : reasonAndReasonDetailExclusionList){
			if(String.isNotBlank(newValue.Reason) && newValue.Reason.containsIgnoreCase(record)){
				return false;
			}else if(String.isNotBlank(newValue.Reason_Detail__c) && newValue.Reason_Detail__c.containsIgnoreCase(record)){
				return false;
			}
		}

		Boolean originMatch = false;
		for(String record : originExclusionList){
			if(String.isNotBlank(newValue.Origin) && newValue.Origin.containsIgnoreCase(record)){
				originMatch = true;
				break;
			}
		}
		if(!originMatch){
			return false;
		}
		return true;
	}

	@future(callout=true)
	public static void issueResolutionCaseUpdateLeads(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
        issueResolutionCaseUpdateLeadsCallout(action, lookupField, sObjectListJSON, asyncProcessing, partitionName);
	}

	public static void issueResolutionCaseUpdateLeadsCallout(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
		List<SObject> sObjectList = (List<SObject>)JSON.deserialize(sObjectListJSON, List<SObject>.class);

		Map<Id, Account> accountMap = new Map<Id, Account>([select Id, Marketo_ID__c, tz__Timezone_IANA__c from Account where Id in (select AccountId from Case where Id in : sObjectList) and Marketo_ID__c != '' and Sync_to_Marketo__c = true]);
		Map<Id, User> userMap = new Map<Id, User>([select Id, FirstName from User where Id in (select OwnerId from Case where Id in : sObjectList)]);

		JSONGenerator bodyJSON = JSON.createGenerator(false); 
        bodyJSON.writeStartObject();
            bodyJSON.writeObjectField('action', (String.isNotBlank(action) ? action : 'updateOnly'));
        	bodyJSON.writeObjectField('lookupField', (String.isNotBlank(lookupField) ? lookupField : 'id'));
        	bodyJSON.writeObjectField('asyncProcessing', asyncProcessing);
        	if(String.isNotBlank(partitionName)){
        		bodyJSON.writeObjectField('partitionName', partitionName);
        	}
        	bodyJSON.writeFieldName('input');
            bodyJSON.writeStartArray();
            	for(SObject inputValue : sObjectList){
            		bodyJSON.writeStartObject();
            			bodyJSON.writeObjectField('id', accountMap.get((id)inputValue.get('AccountId')).Marketo_ID__c);
            			bodyJSON.writeObjectField('issueResolutionCaseOwnerFirstName', userMap.get((id)inputValue.get('OwnerId')).FirstName);
            			bodyJSON.writeObjectField('issueResolutionCaseID', (id)inputValue.get('Id'));
            		bodyJSON.writeEndObject();
            	}
            bodyJSON.writeEndArray();	
        bodyJSON.writeEndObject();
        HttpResponse res = MarketoSyncService.calloutToMarketoPOST('/rest/v1/leads.json', bodyJSON.getAsString(), '', true);
        system.debug(res.getBody());
	}

	@future(callout=true)
	public static void ncsCaseUpdateMarketoCSCSchedule(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
		ncsCaseUpdateMarketoCSCScheduleCallout(action, lookupField, sObjectListJSON, asyncProcessing, partitionName);
	}

	public static String ncsCaseUpdateMarketoCSCScheduleCallout(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
		List<SObject> sObjectList = (List<SObject>)JSON.deserialize(sObjectListJSON, List<SObject>.class);

		Map<Id, Account> accountMap = new Map<Id, Account>([select Id, Marketo_ID__c, tz__Timezone_IANA__c from Account where Id in (select AccountId from Case where Id in : sObjectList) and Marketo_ID__c != '' and Sync_to_Marketo__c = true]);

		JSONGenerator bodyJSON = JSON.createGenerator(false); 
        bodyJSON.writeStartObject();
            bodyJSON.writeObjectField('action', (String.isNotBlank(action) ? action : 'updateOnly'));
        	bodyJSON.writeObjectField('lookupField', (String.isNotBlank(lookupField) ? lookupField : 'id'));
        	bodyJSON.writeObjectField('asyncProcessing', asyncProcessing);
        	if(String.isNotBlank(partitionName)){
        		bodyJSON.writeObjectField('partitionName', partitionName);
        	}
        	bodyJSON.writeFieldName('input');
            bodyJSON.writeStartArray();
            	for(SObject inputValue : sObjectList){
					String timeZone = (String.isNotBlank(accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c)) ? accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c : 'America/New_York';
            		bodyJSON.writeStartObject();
            			bodyJSON.writeObjectField('id', accountMap.get((id)inputValue.get('AccountId')).Marketo_ID__c);
						bodyJSON.writeObjectField('Next_Scheduled_CSC', DateTime.valueof(inputValue.get('Next_Scheduled_CSC2__c')).format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'));
            			bodyJSON.writeObjectField('dateofNextScheduledCSC', DateTime.valueof(inputValue.get('Next_Scheduled_CSC2__c')).format('yyyy-MM-dd'));
						bodyJSON.writeObjectField('timeofNextScheduledCSC', DateTime.valueof(inputValue.get('Next_Scheduled_CSC2__c')).format('hh:mm a', timeZone));
            		bodyJSON.writeEndObject();
            	}
            bodyJSON.writeEndArray();	
        bodyJSON.writeEndObject();
        HttpResponse res = MarketoSyncService.calloutToMarketoPOST('/rest/v1/leads.json', bodyJSON.getAsString(), '', true);
        system.debug(res.getBody());
        return res.getBody();
	}

	@future(callout=true)
	public static void caseUpdateLeads(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
		List<SObject> sObjectList = (List<SObject>)JSON.deserialize(sObjectListJSON, List<SObject>.class);

		Map<Id, Account> accountMap = new Map<Id, Account>([select Id, Marketo_ID__c, tz__Timezone_IANA__c from Account where Id in (select AccountId from Case where Id in : sObjectList) and Marketo_ID__c != '' and Sync_to_Marketo__c = true]);

		List<SFDC_Case_to_Marketo_Field_Mappings__c> sfdcAPINameSFDCMarketoFieldMappingList = new List<SFDC_Case_to_Marketo_Field_Mappings__c>();
		for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : SFDC_Case_to_Marketo_Field_Mappings__c.getAll().values()){
			if(sfdcCaseMarketoFieldMap.Sync_Field__c){
				sfdcAPINameSFDCMarketoFieldMappingList.add(sfdcCaseMarketoFieldMap);
			}
		}

		Set<String> caseDateTimeFieldSet = new Set<String>();

		for(Schema.SObjectField field : Case.getSobjectType().getDescribe().fields.getMap().values())
		{
		    if(Schema.DisplayType.DATETIME == field.getDescribe().getType()){
		        caseDateTimeFieldSet.add(field.getDescribe().getName());
		    }
		}

		JSONGenerator bodyJSON = JSON.createGenerator(false); 
        bodyJSON.writeStartObject();
            bodyJSON.writeObjectField('action', (String.isNotBlank(action) ? action : 'updateOnly'));
        	bodyJSON.writeObjectField('lookupField', (String.isNotBlank(lookupField) ? lookupField : 'id'));
        	bodyJSON.writeObjectField('asyncProcessing', asyncProcessing);
        	if(String.isNotBlank(partitionName)){
        		bodyJSON.writeObjectField('partitionName', partitionName);
        	}
        	bodyJSON.writeFieldName('input');
            bodyJSON.writeStartArray();
            	for(SObject inputValue : sObjectList){
            		bodyJSON.writeStartObject();
            			bodyJSON.writeObjectField('id', accountMap.get((id)inputValue.get('AccountId')).Marketo_ID__c);
            			for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : sfdcAPINameSFDCMarketoFieldMappingList){
            				system.debug(sfdcCaseMarketoFieldMap);
            				if(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != null && !caseDateTimeFieldSet.contains(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
            					bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, String.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)));
            				}else if(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != null && caseDateTimeFieldSet.contains(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
								// This sets it as YODLE TIME ZONE!!! FYI FYI FYI!!!
								bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'));

								String timeZone = (String.isNotBlank(accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c)) ? accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c : 'America/New_York';

								if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('Next_Scheduled_CSC')){
									bodyJSON.writeObjectField('dateofNextScheduledCSC', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd'));
									bodyJSON.writeObjectField('timeofNextScheduledCSC', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('hh:mm a', timeZone));
								}else if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('nextScheduledCall')){
									bodyJSON.writeObjectField('dateofNextScheduledCall', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd'));
									bodyJSON.writeObjectField('timeofNextScheduledCall', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('hh:mma', timeZone));
									if(String.valueof(inputValue.get('Reason')).equalsIgnoreCase('CS Touch Plan')){
										bodyJSON.writeObjectField('nextScheduledCallType', 'CS Touch Plan');
									}
								}

							}else if(sfdcCaseMarketoFieldMap.Sync_Blank_Values__c && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
            					system.debug('testing test');
            					bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, '');

            					if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('Next_Scheduled_CSC')){
									bodyJSON.writeObjectField('dateofNextScheduledCSC', '');
									bodyJSON.writeObjectField('timeofNextScheduledCSC', '');
								}else if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('nextScheduledCall')){
									bodyJSON.writeObjectField('dateofNextScheduledCall', '');
									bodyJSON.writeObjectField('timeofNextScheduledCall', '');
								}
            				}
            			}
            		bodyJSON.writeEndObject();
            	}
            bodyJSON.writeEndArray();	
        bodyJSON.writeEndObject();
        HttpResponse res = MarketoSyncService.calloutToMarketoPOST('/rest/v1/leads.json', bodyJSON.getAsString(), '', true);
        system.debug(res.getBody());
	}

	public static String caseUpdateLeadsNotFuture(String action,  String lookupField, String sObjectListJSON, Boolean asyncProcessing, String partitionName){
		List<SObject> sObjectList = (List<SObject>)JSON.deserialize(sObjectListJSON, List<SObject>.class);

		Map<Id, Account> accountMap = new Map<Id, Account>([select Id, Marketo_ID__c, tz__Timezone_IANA__c from Account where Id in (select AccountId from Case where Id in : sObjectList) and Marketo_ID__c != '' and Sync_to_Marketo__c = true]);

		List<SFDC_Case_to_Marketo_Field_Mappings__c> sfdcAPINameSFDCMarketoFieldMappingList = new List<SFDC_Case_to_Marketo_Field_Mappings__c>();
		for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : SFDC_Case_to_Marketo_Field_Mappings__c.getAll().values()){
			if(sfdcCaseMarketoFieldMap.Sync_Field__c){
				sfdcAPINameSFDCMarketoFieldMappingList.add(sfdcCaseMarketoFieldMap);
			}
		}

		Set<String> caseDateTimeFieldSet = new Set<String>();

		for(Schema.SObjectField field : Case.getSobjectType().getDescribe().fields.getMap().values())
		{
		    if(Schema.DisplayType.DATETIME == field.getDescribe().getType()){
		        caseDateTimeFieldSet.add(field.getDescribe().getName());
		    }
		}

		JSONGenerator bodyJSON = JSON.createGenerator(false); 
        bodyJSON.writeStartObject();
            bodyJSON.writeObjectField('action', (String.isNotBlank(action) ? action : 'updateOnly'));
        	bodyJSON.writeObjectField('lookupField', (String.isNotBlank(lookupField) ? lookupField : 'id'));
        	bodyJSON.writeObjectField('asyncProcessing', asyncProcessing);
        	if(String.isNotBlank(partitionName)){
        		bodyJSON.writeObjectField('partitionName', partitionName);
        	}
        	bodyJSON.writeFieldName('input');
            bodyJSON.writeStartArray();
            	for(SObject inputValue : sObjectList){
            		bodyJSON.writeStartObject();
            			bodyJSON.writeObjectField('id', accountMap.get((id)inputValue.get('AccountId')).Marketo_ID__c);
            			for(SFDC_Case_to_Marketo_Field_Mappings__c sfdcCaseMarketoFieldMap : sfdcAPINameSFDCMarketoFieldMappingList){
            				system.debug(sfdcCaseMarketoFieldMap);
            				if(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != null && !caseDateTimeFieldSet.contains(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
            					bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, String.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)));
            				}else if(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) != null && caseDateTimeFieldSet.contains(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c) && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
								// This sets it as YODLE TIME ZONE!!! FYI FYI FYI!!!
								bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'));

								String timeZone = (String.isNotBlank(accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c)) ? accountMap.get((id)inputValue.get('AccountId')).tz__Timezone_IANA__c : 'America/New_York';

								if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('Next_Scheduled_CSC')){
									bodyJSON.writeObjectField('dateofNextScheduledCSC', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd'));
									bodyJSON.writeObjectField('timeofNextScheduledCSC', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('hh:mm a', timeZone));
								}else if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('nextScheduledCall')){
									bodyJSON.writeObjectField('dateofNextScheduledCall', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('yyyy-MM-dd'));
									bodyJSON.writeObjectField('timeofNextScheduledCall', DateTime.valueof(inputValue.get(sfdcCaseMarketoFieldMap.SFDC_Field_API_Name__c)).format('hh:mma', timeZone));
									if(String.valueof(inputValue.get('Reason')).equalsIgnoreCase('CS Touch Plan')){
										bodyJSON.writeObjectField('nextScheduledCallType', 'CS Touch Plan');
									}
								}

							}else if(sfdcCaseMarketoFieldMap.Sync_Blank_Values__c && (String.isBlank(sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c) || sfdcCaseMarketoFieldMap.Case_Reason_Criteria__c.containsIgnoreCase((String)inputValue.get('Reason')))){
            					bodyJSON.writeObjectField(sfdcCaseMarketoFieldMap.Name, '');

            					if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('Next_Scheduled_CSC')){
									bodyJSON.writeObjectField('dateofNextScheduledCSC', '');
									bodyJSON.writeObjectField('timeofNextScheduledCSC', '');
								}else if(sfdcCaseMarketoFieldMap.Name.equalsIgnoreCase('nextScheduledCall')){
									bodyJSON.writeObjectField('dateofNextScheduledCall', '');
									bodyJSON.writeObjectField('timeofNextScheduledCall', '');
								}
            				}
            			}
            		bodyJSON.writeEndObject();
            	}
            bodyJSON.writeEndArray();	
        bodyJSON.writeEndObject();
        HttpResponse res = MarketoSyncService.calloutToMarketoPOST('/rest/v1/leads.json', bodyJSON.getAsString(), '', true);
        system.debug(res.getBody());
        return res.getBody();
	}
}