objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hourly_Reminder_DateTime_Field__c</fullName>
        <label>Hourly Reminder DateTime Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_Many_Random_Records__c</fullName>
        <inlineHelpText>How many random records to return</inlineHelpText>
        <label>How Many Random Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketo_Campaign_ID__c</fullName>
        <label>Marketo Campaign ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Record_Default_Values__c</fullName>
        <label>New Record Default Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Randomize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Randomize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Hours_For_Reminder__c</fullName>
        <label># of Hours For Reminder</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketoHourlyEmailCampaignBatchTest.cls
@isTest
private class MarketoHourlyEmailCampaignBatchTest {
	
	@isTest static void test_MarketoHourlyEmailCampaignBatch() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		//newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		insert newAccount;

		Marketo_Email_Campaign__c marketoEmailCampaignTemplate = new Marketo_Email_Campaign__c();
		marketoEmailCampaignTemplate.RecordTypeId = Schema.SObjectType.Marketo_Email_Campaign__c.getRecordTypeInfosByName().get('Hourly Template').getRecordTypeId();
		marketoEmailCampaignTemplate.Name = 'Test Template';
		marketoEmailCampaignTemplate.Marketo_Campaign_ID__c = '5332';
		marketoEmailCampaignTemplate.Hourly_Reminder_DateTime_Field__c = 'LastModifiedDate';
		marketoEmailCampaignTemplate.of_Hours_For_Reminder__c = -2;
		marketoEmailCampaignTemplate.Create_Case__c = true;
		marketoEmailCampaignTemplate.Active__c = true;
		marketoEmailCampaignTemplate.New_Record_Default_Values__c = '{"attributes":{"type":"Case"},"Reason":" Proactive Touch", "RecordTypeId":"012320000009ect","Reason_Detail__c":"Month 1 Check In","Priority":"Major","Status":"New"}';
		insert marketoEmailCampaignTemplate;

		Database.executeBatch(new MarketoHourlyEmailCampaignBatch('select Id, Marketo_ID__c from Account', marketoEmailCampaignTemplate.Id, DateTime.now()));
	}

	@isTest static void test_SchedulableJob() {
		Marketo_Email_Campaign__c marketoEmailCampaignTemplate = new Marketo_Email_Campaign__c();
		marketoEmailCampaignTemplate.RecordTypeId = Schema.SObjectType.Marketo_Email_Campaign__c.getRecordTypeInfosByName().get('Hourly Template').getRecordTypeId();
		marketoEmailCampaignTemplate.Name = 'Test Template';
		marketoEmailCampaignTemplate.Marketo_Campaign_ID__c = '5332';
		marketoEmailCampaignTemplate.Hourly_Reminder_DateTime_Field__c = 'LastModifiedDate';
		marketoEmailCampaignTemplate.of_Hours_For_Reminder__c = -2;
		marketoEmailCampaignTemplate.Create_Case__c = true;
		marketoEmailCampaignTemplate.Active__c = true;
		marketoEmailCampaignTemplate.Criteria__c = 'select Id, Marketo_ID__c from Account where Id != \'\'';
		marketoEmailCampaignTemplate.New_Record_Default_Values__c = '{"attributes":{"type":"Case"},"Reason":" Proactive Touch", "RecordTypeId":"012320000009ect","Reason_Detail__c":"Month 1 Check In","Priority":"Major","Status":"New"}';
		insert marketoEmailCampaignTemplate;

		Marketo_Email_Campaign__c marketoEmailCampaignTemplateRandomize = new Marketo_Email_Campaign__c();
		marketoEmailCampaignTemplateRandomize.RecordTypeId = Schema.SObjectType.Marketo_Email_Campaign__c.getRecordTypeInfosByName().get('Hourly Template').getRecordTypeId();
		marketoEmailCampaignTemplateRandomize.Name = 'Test Template Random';
		marketoEmailCampaignTemplateRandomize.Marketo_Campaign_ID__c = '5332';
		marketoEmailCampaignTemplateRandomize.Criteria__c = 'select Id, Marketo_ID__c from Account where Id != \'\'';
		marketoEmailCampaignTemplateRandomize.Active__c = true;
		marketoEmailCampaignTemplateRandomize.Randomize__c = true;
		marketoEmailCampaignTemplateRandomize.How_Many_Random_Records__c = 2;
		marketoEmailCampaignTemplateRandomize.Hourly_Reminder_DateTime_Field__c = 'LastModifiedDate';
		marketoEmailCampaignTemplateRandomize.of_Hours_For_Reminder__c = -2;
		insert marketoEmailCampaignTemplateRandomize;

		Test.startTest();
		MarketoHourlyEmailCampaignSchedule m = new MarketoHourlyEmailCampaignSchedule();
		m.execute(null);
		Test.stopTest();
	}
	
}