objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_E_mail__c</fullName>
        <label>Client E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Client First Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Client Last Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Best_Practice_Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Best Practice Evaluations</relationshipLabel>
        <relationshipName>Best_Practice_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Used to evaluate best practices for Analysts in regards to New Client Setups and Optimizations.</description>
    <label>Best Practice Evaluation</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Evaluation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Best Practice Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CTS_Salesforce_Object_Ref__mdt.object
<CustomObject>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Salesforce Object API Name</description>
        <inlineHelpText>Salesforce Object API Name</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Salesforce objects referenced and used within the CTS Integration</description>
    <label>CTS Salesforce Object Ref</label>
    <pluralLabel>CTS Salesforce Object Refs</pluralLabel>
</CustomObject>

objects/CTSObjectTriggerMap__mdt.object
<CustomObject>
    <fields>
        <fullName>CTSEmailAddress__c</fullName>
        <description>CTS Email Address referenced for CTS Ticket creation (if Email Integration Type)</description>
        <inlineHelpText>CTS Email Address referenced for CTS Ticket creation (if Email Integration Type)</inlineHelpText>
        <label>CTS Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DetailsTemplateName__c</fullName>
        <description>Salesforce Email Template Name corresponding to the Details Template Id</description>
        <inlineHelpText>Salesforce Email Template Name corresponding to the Details Template Id</inlineHelpText>
        <label>Details Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationType__c</fullName>
        <description>Integration Type referenced for what process is used to create the CTS Ticket (Email or API)</description>
        <inlineHelpText>Integration Type referenced for what process is used to create the CTS Ticket (Email or API)</inlineHelpText>
        <label>Integration Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                    <default>true</default>
                    <label>API</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTSAPIIdentifier__c</fullName>
        <description>CTS API Identifier referenced for CTS Ticket creation (if API Integration Type)</description>
        <inlineHelpText>CTS API Identifier referenced for CTS Ticket creation (if API Integration Type)</inlineHelpText>
        <label>CTS API Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object Reference Metadata Type Lookup Relationship</description>
        <inlineHelpText>Object Reference Metadata Type Lookup Relationship</inlineHelpText>
        <label>Object Reference</label>
        <referenceTo>CTS_Salesforce_Object_Ref__mdt</referenceTo>
        <relationshipLabel>CTSObjectTriggerMaps</relationshipLabel>
        <relationshipName>CTSObjectTriggerMaps_SFDCObjectRef</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <description>Name of the Salesforce Object Record Type referenced for CTS Ticket creation</description>
        <inlineHelpText>Name of the Salesforce Object Record Type referenced for CTS Ticket creation</inlineHelpText>
        <label>Record Type Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Update</fullName>
                    <default>true</default>
                    <label>Account Update</label>
                </value>
                <value>
                    <fullName>Charge Failure</fullName>
                </value>
                <value>
                    <fullName>Closing Script - Auto Launch</fullName>
                </value>
                <value>
                    <fullName>Installation Worksheet</fullName>
                </value>
                <value>
                    <fullName>LBW Content Organic Setup</fullName>
                </value>
                <value>
                    <fullName>LH Closing Script – Auto Launch</fullName>
                </value>
                <value>
                    <fullName>LH Master</fullName>
                </value>
                <value>
                    <fullName>LH OOS</fullName>
                </value>
                <value>
                    <fullName>Maps Initial Claiming</fullName>
                </value>
                <value>
                    <fullName>Master</fullName>
                </value>
                <value>
                    <fullName>NCS - AutoLaunch</fullName>
                </value>
                <value>
                    <fullName>NPS Survey LBW</fullName>
                </value>
                <value>
                    <fullName>NPS Survey Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Optimization</fullName>
                </value>
                <value>
                    <fullName>Organic Setup</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>PIN Action Needed</fullName>
                </value>
                <value>
                    <fullName>QA Audit</fullName>
                </value>
                <value>
                    <fullName>TORCHx Master</fullName>
                </value>
                <value>
                    <fullName>TORCHx NCS - AutoLaunch</fullName>
                </value>
                <value>
                    <fullName>Yodle Gold Service</fullName>
                </value>
                <value>
                    <fullName>CATCHALL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used as reference to determine how a CTS Ticket should be created, what data elements should be included and the source of the ticket data from Salesforce data</description>
    <label>CTSObjectTriggerMap</label>
    <pluralLabel>CTSObjectTriggerMaps</pluralLabel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Email_Address__c</fullName>
        <label>Client's Primary Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Quality_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account_Name__r.Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDCToCTSAsynchRequest__c.object
<CustomObject>
    <description>Stores DE-normalized CTS Ticket data to be executed by BULK job on a schedule to create CTS Tickets</description>
    <fields>
        <fullName>API_Identifier__c</fullName>
        <description>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</description>
        <inlineHelpText>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</inlineHelpText>
        <label>API Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTS_Email_Address__c</fullName>
        <description>Email address used to send object data to for creating CTS ticket when the Integration type is Email; required when Integration type is Email</description>
        <inlineHelpText>Email address used to send object data to for creating CTS ticket when the Integration type is Email; required when Integration type is Email</inlineHelpText>
        <label>CTS Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <description>The Id of the Email Template being used to pass data elements to CTS</description>
        <inlineHelpText>The Id of the Email Template being used to pass data elements to CTS</inlineHelpText>
        <label>Email Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SFDCToCTSAsynchRequest</label>
    <nameField>
        <displayFormat>AR-{000000000}</displayFormat>
        <label>Asynch Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDCToCTSAsynchRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSSyncService_ERWorking.cls
/****************************************************************************
  Eugene Ross Working copy
*****************************************************************************/
public without sharing class CTSSyncService_ERWorking{

    public class CTSTicket{
    
        public String apiIdentifier {get; set;}
        public String contactFirstName {get; set;}
        public String contactLastName {get; set;}
        public String contactPhone {get; set;}
        public String contactEmailAddress {get; set;}
        public String referenceAccountId {get; set;}
        public String referenceCustomerId {get; set;}
        public String referenceProductInstanceId {get; set;}
        public String domain {get; set;}
        public String subject {get; set;}
        public String detail {get; set;}
        public String referenceProductCode {get; set;}
        public String status {get; set;}
        public string alternateContactEmailAddress {get; set;}
        public Id sfdcTemplateIdForDetails {get; set;}
    
    }

    public static List<CTSTicket> GetCTSTicket(string objectName, List<Id> objectIds, Map<Id, CTSObjectTriggerMap__mdt> routingTableObjectInstance){
 
        CTSTicket ctsTicketInstance;
        List<CTSTicket> ctsTicketList = new List<CTSTicket>();
        Map<String, EmailTemplate> emailTemplateMap = new Map<String, EmailTemplate>();
        
        String ticketDetails;
        Id emailTemplateId;
        String integrationType;
        String apiIdentifier;
        String templateName;
        String recordTypeName;
        
        // retrieved from GetConfigValue private method
        String ctsTemplateFolder = GetConfigValue('CTSTemplatesFolder');
        String initStatus = GetConfigValue('CTSTicketStatusDefault').toUppercase();
        
        for(EmailTemplate e:
            [SELECT Id,
                    Name
               FROM EmailTemplate 
              WHERE Folder.Name = :ctsTemplateFolder]){
        
            emailTemplateMap.put(e.Name, e);    
        
        }
        
        for(CTSObjectTriggerMap__mdt rt : routingTableObjectInstance.values()){
            
            if(emailTemplateMap.size() > 0){
                
                for(EmailTemplate et : emailTemplateMap.values()){
                    
                    if(et.Name == emailTemplateMap.get(rt.DetailsTemplateName__c).Name){
                    
                        templateName = emailTemplateMap.get(rt.DetailsTemplateName__c).Name;
                        break;
                    }
                }
                
                integrationType = rt.IntegrationType__c;
                apiIdentifier = rt.CTSAPIIdentifier__c;
                recordTypeName = rt.RecordTypeName__c;
                
                // default ticket values
                ctsTicketInstance.apiIdentifier = apiIdentifier;
                ctsTicketInstance.status = initStatus;
                
                switch on objectName{
                    when 'Case' {
                        for(Case c : 
                            [SELECT Id,
                                    Account.Client_First_Name__c,
                                    Account.Client_Last_Name__c,
                                    Account.Phone,
                                    Account.Email__c,
                                    Client_Email__c,
                                    Account.Name,
                                    Account.Client_ID__c,
                                    Account.Website,
                                    Subject,
                                    CaseNumber,
                                    Account.Product_Type_Transactional__c,
                                    RecordType.Name
                               FROM Case
                              WHERE Id IN :objectIds]){
                            
                            if (c.RecordType.Name == recordTypeName)
                            {
                                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateMap.get(rt.DetailsTemplateName__c).Id, null, c.Id);
                                ticketDetails = mail.getPlainTextBody();
                                emailTemplateId = emailTemplateMap.get(rt.DetailsTemplateName__c).Id;
                                    
                                ctsTicketInstance.contactFirstName = c.Account.Client_First_Name__c;
                                ctsTicketInstance.contactLastName = c.Account.Client_Last_Name__c;
                                ctsTicketInstance.contactPhone = c.Account.Phone;
                                ctsTicketInstance.contactEmailAddress = c.Client_Email__c;
                                ctsTicketInstance.referenceAccountId = c.Account.Name;
                                ctsTicketInstance.referenceCustomerId = c.Account.Client_ID__c;
                                ctsTicketInstance.referenceProductInstanceId = c.CaseNumber;
                                ctsTicketInstance.domain = c.Account.Website;
                                ctsTicketInstance.subject = c.Subject;
                                ctsTicketInstance.detail = ticketDetails;
                                ctsTicketInstance.referenceProductCode = c.Account.Product_Type_Transactional__c;
                                ctsTicketInstance.alternateContactEmailAddress = c.Account.Email__c;
                                ctsTicketInstance.sfdcTemplateIdForDetails = emailTemplateId;
                                
                                ctsTicketList.add(ctsTicketInstance);
                            }   
                        }
                    }
                    when 'Organic_Analysis__c' {
                       for(Organic_Analysis__c oc :
                           [SELECT Id,
                                   Name,
                                   Account_Name__r.Client_First_Name__c,
                                   Account_Name__r.Client_Last_Name__c,
                                   Account_Name__r.Phone,
                                   Account_Name__r.Email__c,
                                   Client_Email_Address__c,
                                   Account_Name__r.Id,
                                   Account_Name__r.Client_ID__c,
                                   Account_Name__r.Product_Type_Transactional__c,
                                   Account_Name__r.Name,
                                   RecordType.Name
                              FROM Organic_Analysis__c 
                             WHERE Id IN :objectIds]){
                                
                            if (oc.RecordType.Name == recordTypeName)
                            {
                                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateMap.get(rt.DetailsTemplateName__c).Id, null, oc.Id);
                                ticketDetails = mail.getPlainTextBody();
                                emailTemplateId = emailTemplateMap.get(rt.DetailsTemplateName__c).Id;
                                    
                                ctsTicketInstance.contactFirstName = oc.Account_Name__r.Client_First_Name__c;
                                ctsTicketInstance.contactLastName = oc.Account_Name__r.Client_Last_Name__c;
                                ctsTicketInstance.contactPhone = oc.Account_Name__r.Phone;
                                ctsTicketInstance.contactEmailAddress = oc.Client_Email_Address__c;
                                ctsTicketInstance.referenceAccountId = oc.Account_Name__r.Name;
                                ctsTicketInstance.referenceCustomerId = oc.Account_Name__r.Client_ID__c;
                                ctsTicketInstance.referenceProductInstanceId = oc.Name;
                                ctsTicketInstance.domain = oc.Account_Name__r.Website;
                                ctsTicketInstance.subject = recordTypeName + ' | ' + oc.Account_Name__r.Name;
                                ctsTicketInstance.detail = ticketDetails;
                                ctsTicketInstance.referenceProductCode = oc.Account_Name__r.Product_Type_Transactional__c;
                                ctsTicketInstance.alternateContactEmailAddress = oc.Account_Name__r.Email__c;
                                ctsTicketInstance.sfdcTemplateIdForDetails = emailTemplateId;
                                
                                ctsTicketList.add(ctsTicketInstance);
                            }
                        }             
                    }
                    when 'Quality_Case__c' {
                       for(Quality_Case__c qc :
                           [SELECT Id,
                                   Name,
                                   Subject__c,
                                   Account_Name__r.Client_First_Name__c,
                                   Account_Name__r.Client_Last_Name__c,
                                   Account_Name__r.Phone,
                                   Account_Name__r.Email__c,
                                   Account_Name__r.Client_E_mail__c,
                                   Account_Name__r.Id,
                                   Account_Name__r.Client_ID__c,
                                   Account_Name__r.Product_Type_Transactional__c,
                                   Account_Name__r.Name,
                                   RecordType.Name
                              FROM Quality_Case__c
                             WHERE Id IN :objectIds]){
                                
                            if (qc.RecordType.Name == recordTypeName)
                            {
                                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateMap.get(rt.DetailsTemplateName__c).Id, null, qc.Id);
                                ticketDetails = mail.getPlainTextBody();
                                emailTemplateId = emailTemplateMap.get(rt.DetailsTemplateName__c).Id;
                                    
                                ctsTicketInstance.contactFirstName = qc.Account_Name__r.Client_First_Name__c;
                                ctsTicketInstance.contactLastName = qc.Account_Name__r.Client_Last_Name__c;
                                ctsTicketInstance.contactPhone = qc.Account_Name__r.Phone;
                                ctsTicketInstance.contactEmailAddress = qc.Account_Name__r.Client_E_mail__c;
                                ctsTicketInstance.referenceAccountId = qc.Account_Name__r.Name;
                                ctsTicketInstance.referenceCustomerId = qc.Account_Name__r.Client_ID__c;
                                ctsTicketInstance.referenceProductInstanceId = qc.Name;
                                ctsTicketInstance.domain = qc.Account_Name__r.Website;
                                ctsTicketInstance.subject = qc.Subject__c + ' | ' + qc.Account_Name__r.Name;
                                ctsTicketInstance.detail = ticketDetails;
                                ctsTicketInstance.referenceProductCode = qc.Account_Name__r.Product_Type_Transactional__c;
                                ctsTicketInstance.alternateContactEmailAddress = qc.Account_Name__r.Email__c;
                                ctsTicketInstance.sfdcTemplateIdForDetails = emailTemplateId;
                                
                                ctsTicketList.add(ctsTicketInstance);
                            }
                        }             
                    }
                    when 'Best_Practice_Evaluation__c' {
                       for(Best_Practice_Evaluation__c bpe :
                           [SELECT Id,
                                   Name,
                                   Account_Name__r.Client_First_Name__c,
                                   Account_Name__r.Client_Last_Name__c,
                                   Account_Name__r.Phone,
                                   Account_Name__r.Email__c,
                                   Account_Name__r.Client_E_mail__c,
                                   Account_Name__r.Id,
                                   Account_Name__r.Client_ID__c,
                                   Account_Name__r.Product_Type_Transactional__c,
                                   Account_Name__r.Name,
                                   RecordType.Name
                              FROM Best_Practice_Evaluation__c
                             WHERE Id IN :objectIds]){
                                
                            if (bpe.RecordType.Name == recordTypeName)
                            {
                                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateMap.get(rt.DetailsTemplateName__c).Id, null, bpe.Id);
                                ticketDetails = mail.getPlainTextBody();
                                emailTemplateId = emailTemplateMap.get(rt.DetailsTemplateName__c).Id;
                                    
                                ctsTicketInstance.contactFirstName = bpe.Account_Name__r.Client_First_Name__c;
                                ctsTicketInstance.contactLastName = bpe.Account_Name__r.Client_Last_Name__c;
                                ctsTicketInstance.contactPhone = bpe.Account_Name__r.Phone;
                                ctsTicketInstance.contactEmailAddress = bpe.Account_Name__r.Client_E_mail__c;
                                ctsTicketInstance.referenceAccountId = bpe.Account_Name__r.Name;
                                ctsTicketInstance.referenceCustomerId = bpe.Account_Name__r.Client_ID__c;
                                ctsTicketInstance.referenceProductInstanceId = bpe.Name;
                                ctsTicketInstance.domain = bpe.Account_Name__r.Website;
                                ctsTicketInstance.subject = '';
                                ctsTicketInstance.detail = ticketDetails;
                                ctsTicketInstance.referenceProductCode = bpe.Account_Name__r.Product_Type_Transactional__c;
                                ctsTicketInstance.alternateContactEmailAddress = bpe.Account_Name__r.Email__c;
                                ctsTicketInstance.sfdcTemplateIdForDetails = emailTemplateId;
                                
                                ctsTicketList.add(ctsTicketInstance);
                            }
                       }             
                    }
                    when 'Customer_Surveys__c' {
                       for(Customer_Surveys__c cs :
                           [SELECT Id,
                                   Name,
                                   Client_Email_Survey__c,
                                   Client_ID__c,
                                   Customer_Survey_Name__c,
                                   Account__r.Client_First_Name__c,
                                   Account__r.Client_Last_Name__c,
                                   Account__r.Phone,
                                   Account__r.Email__c,
                                   Account__r.Client_E_mail__c,
                                   Account__r.Id,
                                   Account__r.Client_ID__c,
                                   Account__r.Product_Type_Transactional__c,
                                   Account__r.Name,
                                   RecordType.Name
                              FROM Customer_Surveys__c
                             WHERE Id IN :objectIds]){
                                
                            if (cs.RecordType.Name == recordTypeName)
                            {
                                Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(emailTemplateMap.get(rt.DetailsTemplateName__c).Id, null, cs.Id);
                                ticketDetails = mail.getPlainTextBody();
                                emailTemplateId = emailTemplateMap.get(rt.DetailsTemplateName__c).Id;
                                    
                                ctsTicketInstance.contactFirstName = cs.Account__r.Client_First_Name__c;
                                ctsTicketInstance.contactLastName = cs.Account__r.Client_Last_Name__c;
                                ctsTicketInstance.contactPhone = cs.Account__r.Phone;
                                ctsTicketInstance.contactEmailAddress = cs.Client_Email_Survey__c;
                                ctsTicketInstance.referenceAccountId = cs.Account__r.Name;
                                ctsTicketInstance.referenceCustomerId = cs.Client_ID__c;
                                ctsTicketInstance.referenceProductInstanceId = cs.Name;
                                ctsTicketInstance.domain = cs.Account__r.Website;
                                ctsTicketInstance.subject = cs.Customer_Survey_Name__c + ' | ' + cs.Account__r.Name;
                                ctsTicketInstance.detail = ticketDetails;
                                ctsTicketInstance.referenceProductCode = cs.Account__r.Product_Type_Transactional__c;
                                ctsTicketInstance.alternateContactEmailAddress = cs.Account__r.Email__c;
                                ctsTicketInstance.sfdcTemplateIdForDetails = emailTemplateId;
                                
                                ctsTicketList.add(ctsTicketInstance);
                            }
                        }             
                    }
                }
            }
        }
        
        return ctsTicketList;
    }
    
    public void CallOutCTSForEmail(String objectId, String emailTemplateId, String ctsEmailAddress)
    {
        try{
        
            List<Messaging.SingleEmailMessage> ctsNotificationsLst = new List<Messaging.SingleEmailMessage>();
            OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'sfdc@yodle.com'];
            String sfdcEmailAddress = GetConfigValue('SFDC_Case_Email');
            Set<String> uniqueEmailAddressesSet = new Set<String>();
            String messageSubject;
            String messageBody;
            
            // Render template data and bind elements to variables
            Messaging.SingleEmailMessage renderedDetails = Messaging.renderStoredEmailTemplate(emailTemplateId, null, objectId);
            messageSubject = renderedDetails.getSubject();
            messageBody = renderedDetails.getPlainTextBody();
            
            // set message content from email template for CTS
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            List<String> toAddress = new List<String>();
            String fromAddress = GetConfigValue('ServiceAddressEmail_sfdc');
            String fromDisplayName = 'Salesforce Notifications';
            uniqueEmailAddressesSet.add(ctsEmailAddress);
            uniqueEmailAddressesSet.add(sfdcEmailAddress);
            for(String s : uniqueEmailAddressesSet){
                toAddress.add(s);
            }
         
            message.setToAddresses(toAddress);
            message.setReplyTo(fromAddress);
            message.setOrgWideEmailAddressId(owea.get(0).Id);
            message.setSubject(messageSubject);
            message.setHtmlBody(messageBody);
    
            ctsNotificationsLst.add(message);
            
            if(ctsNotificationsLst.size() > 0){
                            
                // send notifications
                Messaging.sendEmail(ctsNotificationsLst);
            }
        
        }
        catch(Exception e){
        
            // log error
            System.Debug('* An error occurred: ' + e.getMessage());
        }
    }
    
    public void CreateSFDCToCTSAsynchRequest(string integrationType, string objectName, List<Id> objectIds, Map<Id, CTSObjectTriggerMap__mdt> routingTableObjectInstance){
    
        List<CTSTicket> ctsTicket = GetCTSTicket(objectName, objectIds, routingTableObjectInstance);
        List<SFDCToCTSAsynchRequest__c> newAsyncRecordsList = new List<SFDCToCTSAsynchRequest__c>();
        
        for(CTSTicket t : ctsTicket){
        
            for(CTSObjectTriggerMap__mdt rt : routingTableObjectInstance.values()){
            
                if(rt.Object__r.Object_API_Name__c == objectName){
                        
                    for(Id objectId : objectIds){
                            
                        SFDCToCTSAsynchRequest__c asyncRecord = new SFDCToCTSAsynchRequest__c();
                        asyncRecord.API_Identifier__c = rt.CTSAPIIdentifier__c;
                        asyncRecord.CTS_Email_Address__c = rt.CTSEmailAddress__c;
                        asyncRecord.EmailTemplateId__c = t.sfdcTemplateIdForDetails;
                        asyncRecord.Integration_Type__c = integrationType;
                        asyncRecord.NumberOfRetryAttempts__c = 0;
                        asyncRecord.ObjectId__c = objectId;
                        asyncRecord.Object_Name__c = objectName;
                        asyncRecord.ScheduledDateTime__c = System.Now();
                        asyncRecord.Status__c = t.status;
                        
                        newAsyncRecordsList.add(asyncRecord);
                    }
                }
            }   
        }
        
        if(newAsyncRecordsList.size() > 0){
            insert newAsyncRecordsList;
        }
    }
    
    private static String GetConfigValue(string configLabel)
    {
        String configValue = 
            [SELECT Id, 
                    External_System_Name__c, 
                    MasterLabel, 
                    Configuration_Label__c, 
                    Data_Type__c, 
                    Configuration_Value__c 
               FROM Integration_Configuration__mdt 
              WHERE Is_Active__c = true AND
                    External_System_Name__c = 'CTS' AND
                    Configuration_Label__c = :configLabel
              LIMIT 1].Configuration_Value__c;
              
         return configValue;
    }
}