objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <inlineHelpText>Shows all of the products a customer is using</inlineHelpText>
        <label>Product Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id / Data</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>A Custom Object to hold Logs of type Error and Information created from various other Apex Classes. Unlike the native Debug Logs, the data or log created here are mere records and hence they're persistent.

Please employ the Apex Class named "ApexDebugLog" to utilize this Custom Object to save or log Errors or Information. There are also methods to create logs even via JavaScript.</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{0}</displayFormat>
        <label>Apex Debug Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AutoCreateCaseCSC.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 20-Nov-2017
  Last Modified By ...: E. Ross
  Last Modified Date .: 20-Nov-2017
  Description ........: Class contains invocable method to create CSC Cases based on business criteria 
  and logic when met.
*****************************************************************************/

public class AutoCreateCaseCSC
{
    @InvocableMethod
    public static void CreateCasesCSC(List<Id> caseIds)
    {
        try{
        
            if(caseIds.size() > 0){
            
                Id ncsCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('NCS - AutoLaunch').getRecordTypeId();    
                Id cscCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
                Id cscQueueId = [SELECT Id FROM Group WHERE DeveloperName = 'Outbound_Touch' LIMIT 1].Id;
                String[] prodExcludeSet = new String[]{'%Lighthouse%', '%YBN%'};
                String[] clientExcludeSet = new String[]{'%Lighthouse%', '%YBN%'};
                Map<Id, Case> ncsCaseMap = new Map<Id, Case>();
                Map<Id, Integer> cscCaseCntMap = new Map<Id, Integer>();
                List<Case> dmlCasesCSC = new List<Case>();
                
                // Check for valid Open NCS Cases by Account Id key
                for(Case ncs : 
                    [SELECT Id,
                            AccountId,
                            CaseNumber,
                            Created_Outbound_Call_Case__c,
                            Next_Scheduled_Call__c,
                            Sales_Notes__c,
                            Winback_CSC_Script__c,
                            X3_Day_Approval__c,
                            Channel_Type__c,
                            MA_Notes__c,
                            Budget__c, 
                            Website_Type2__c,
                            Account.Product_Type_Transactional__c
                       FROM Case
                      WHERE Id IN :caseIds AND
                            RecordTypeId = :ncsCaseRecordTypeId AND
                            IsClosed = false AND
                            (NOT Product_Type__c LIKE :prodExcludeSet) AND
                            (NOT Client_Type__c LIKE :clientExcludeSet) AND
                            Next_Scheduled_Call__c != NULL AND
                            Next_Scheduled_Call__c >= TODAY AND
                            Created_Outbound_Call_Case__c = false]){
                
                    // add data to Map
                    if(ncs.Id != NULL){
                        ncsCaseMap.put(ncs.AccountId, ncs);
                    }
                    
                    //System.Debug('Case Number added: ' + ncs.CaseNumber);
                    //System.Debug('NCS Map Size: ' + ncsCaseMap.size());
                }
                
                if(ncsCaseMap.size() > 0){
                
                    // check for existing Open CSC Cases
                    for(AggregateResult cscCnt :
                        [SELECT AccountId,
                                COUNT(Id) cscCount
                           FROM Case
                          WHERE RecordTypeId = :cscCaseRecordTypeId AND
                                IsClosed = false AND
                                AccountId IN :ncsCaseMap.keySet()
                       GROUP BY AccountId]){
                    
                        // add aggregate results to Map
                        cscCaseCntMap.put((Id) cscCnt.get('AccountId'), Integer.valueOf(cscCnt.get('cscCount'))); 
                    }
                    
                    // Create CSC Cases for Accounts meeting logic
                    for(Case c : ncsCaseMap.values()){
                    
                        //System.Debug('CSC Open Case Count: ' + String.valueOf(cscCaseCntMap.get(c.AccountId)));
                    
                        // if no existing CSC Case, create one
                        if(cscCaseCntMap.get(c.AccountId) == 0 || cscCaseCntMap.get(c.AccountId) == null){
                        
                            Case newCaseCSC = new Case();
                            newCaseCSC.RecordTypeId = cscCaseRecordTypeId;
                            newCaseCSC.AccountId = c.AccountId;
                            newCaseCSC.Reason = 'CSC';
                            newCaseCSC.OwnerId = cscQueueId; // Outbound Touch queue
                            newCaseCSC.Scheduled_Call__c = c.Next_Scheduled_Call__c;
                            newCaseCSC.ParentId = c.Id;
                            newCaseCSC.X3_Day_Approval__c = c.X3_Day_Approval__c;
                            newCaseCSC.Sales_Notes__c = c.Sales_Notes__c;
                            newCaseCSC.Winback_CSC_Script__c = c.Winback_CSC_Script__c;
                            newCaseCSC.Channel_Type__c = (c.Channel_Type__c == 'Transactional' ? 'Local' : c.Channel_Type__c);
                            newCaseCSC.MA_Notes__c = c.MA_Notes__c;
                            newCaseCSC.Budget__c = c.Budget__c;
                            newCaseCSC.Website_Type2__c = c.Website_Type2__c;
                            
                            // update boolean value on NCS Case
                            c.Created_Outbound_Call_Case__c = true;
                            
                            // add new CSC case to DML list
                            dmlCasesCSC.add(newCaseCSC);
                        }
                    }
                    
                    // check if there are CSC Cases to create
                    if(dmlCasesCSC.size() > 0){
                    
                        // INSERT CSC CASES
                        insert dmlCasesCSC;
                        
                        // UPDATE NCS CASE Created Outbound Case field on Parent Case
                        update ncsCaseMap.values();
                    }
                }
            }
        }
        catch(Exception e){
        
            System.Debug('An error occurred: ' + e.getMessage());
            Apex_Debug_Log__c dbLog = new Apex_Debug_Log__c();
            dbLog.Apex_Class__c = 'CreateCasesCSC';
            dbLog.Message__c = e.getMessage();
            dbLog.Method__c = 'CreateCasesCSC(Invocable)';
            dbLog.Record_Id__c = '';
            dbLog.Stack_Trace__c = e.getMessage();
            dbLog.Type__c = 'Error';
            
            insert dbLog;
        }
    }
}