objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tz__Timezone_IANA__c</fullName>
        <description>Timezone as defined by Internet Assigned Numbers Authority (IANA).</description>
        <inlineHelpText>Timezone as defined by Internet Assigned Numbers Authority (IANA).</inlineHelpText>
        <label>Timezone (IANA)</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleTouchpointControllerTest.cls
@isTest
private class ScheduleTouchpointControllerTest {
    
    @isTest static void test_ScheduleTouchpointController() {
        List<Account> newAccountList = new List<Account>();
        List<Case> newCaseList = new List<Case>();
        List<Event> newEventList = new List<Event>();
        
        Account acct = new Account();
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        acct.Name = 'Partner Account Test Name';
        acct.Partner_Status__c = 'Customer';
        acct.Client_Type__c = 'Local';
        acct.Marketo_ID__c = '32232';
        acct.Status__c = 'LIVE';
        acct.IMS_Rep__c = UserInfo.getUserId();
        newAccountList.add(acct);
        insert newAccountList;

        Case newCase = new Case();
        newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
        newCase.Reason = 'CS Touch Plan';
        newCase.AccountId = acct.Id;
        newCaseList.add(newCase);
        insert newCaseList;

        Event newEvent = new Event();
        newEvent.OwnerId = UserInfo.getUserId();
        newEvent.Subject = 'OOO';
        newEvent.StartDateTime = DateTime.now().addDays(1);
        newEvent.DurationInMinutes = 30;
        newEvent.Status__c = 'Scheduled';
        newEvent.RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Calendar Blocker').getRecordTypeId();
        newEventList.add(newEvent);
        insert newEventList;

        Test.startTest();

        PageReference pageRef = Page.SchedulePerformanceReviewCall;
        Test.setCurrentPage(pageRef);
        //ApexPages.currentPage().getParameters().put('salesforceAccountId', partnerAccount.Id);

        ScheduleTouchpointController contr = new ScheduleTouchpointController();
        contr.getAvailableAccounts();
        contr.getSupportedTimeZone();

        contr.selectedAccountId = acct.Id;
        contr.dateCaseWorkAround.StartDate__c = Date.today().addDays(7);

        contr.populateUserAvailability();
        contr.selectedAvailableTime = contr.userAvailableDateTimeMap.values()[0][0].temporaryId;
        contr.scheduleTime();

        Test.stopTest();
    }
    
    @isTest static void test_method_two() {
        List<Account> newAccountList = new List<Account>();
        List<Case> newCaseList = new List<Case>();
        List<Event> newEventList = new List<Event>();
    
        Account acct = new Account();
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
        acct.Name = 'Partner Account Test Name';
        acct.Partner_Status__c = 'Customer';
        acct.Client_Type__c = 'Local';
        acct.Marketo_ID__c = '32232';
        acct.Status__c = 'LIVE';
        acct.IMS_Rep__c = UserInfo.getUserId();
        acct.tz__Timezone_IANA__c = 'America/Chicago';
        newAccountList.add(acct);
        insert newAccountList;

        Case newCase = new Case();
        newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
        newCase.Reason = 'CS Touch Plan';
        newCase.AccountId = acct.Id;
        newCaseList.add(newCase);
        insert newCaseList;

        Event newEvent = new Event();
        newEvent.OwnerId = UserInfo.getUserId();
        newEvent.Subject = 'OOO';
        newEvent.StartDateTime = DateTime.now().addDays(1);
        newEvent.DurationInMinutes = 30;
        newEvent.Status__c = 'Scheduled';
        newEvent.RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Calendar Blocker').getRecordTypeId();
        newEventList.add(newEvent);
        insert newEventList;

        PageReference pageRef = Page.SchedulePerformanceReviewCall;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('salesforceAccountId', acct.Id);

        ScheduleTouchpointController contr = new ScheduleTouchpointController();
        contr.getAvailableAccounts();
        contr.getSupportedTimeZone();

        contr.selectedAccountId = acct.Id;
        contr.dateCaseWorkAround.StartDate__c = Date.today().addDays(7);

        //contr.populateUserAvailability();
        //contr.unscheduleCurrentTouchpoint();
    }
    
}