objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services_Offered__c</fullName>
        <inlineHelpText>List of all services offered</inlineHelpText>
        <label>Services Offered</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Services_Offered__c</fullName>
        <label>Services Offered</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <label>Vertical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Business and Professional Services</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Health and Medicine</fullName>
                </value>
                <value>
                    <fullName>Home and Garden</fullName>
                </value>
                <value>
                    <fullName>Legal and Financial Services</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Real Estate</fullName>
                </value>
                <value>
                    <fullName>Travel and Lifestyle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Offering_to_Vertical_Map__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag/ indicator signifying if the record is actively used</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offering_Name__c</fullName>
        <description>Name of the Service Offered</description>
        <label>Offering Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical_Name__c</fullName>
        <description>Name of the associated Vertical</description>
        <label>Vertical Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Mapping of Services Offered to Verticals from Aquisio custom sync</description>
    <label>Offering to Vertical Map</label>
    <nameField>
        <displayFormat>OVM-{000000}</displayFormat>
        <label>Offering to Vertical Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offerings to Verticals Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Services_Offered_Vertical__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Services Offered Verticals</relationshipLabel>
        <relationshipName>Services_Offered_Verticals_CaseId</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Offered__c</fullName>
        <description>Service Offered by Client</description>
        <label>Service Offered</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <description>Vertical associated to the Service Offered</description>
        <label>Vertical</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Organic Case website content setup Services Offered to Verticals related list - LS ATV</description>
    <label>Services Offered Vertical</label>
    <nameField>
        <displayFormat>SOV-{0000000000}</displayFormat>
        <label>Services Offered Vertical Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Offered Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
</CustomObject>

classes/OrganicCaseATVUpdates.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 27-Mar-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 08-May-2018
  Description ........: Class contains invocable method to update Case record type, add services offered and verticals to related list
  if the Case Account has an Account Product Type of LS ATV.
*****************************************************************************/
public without sharing class OrganicCaseATVUpdates
{
    @InvocableMethod
    public static void lsATVUpdates(List<Id> caseIds)
    {
        try{
        
             Id lsATVCaseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('LS ATV Organic Setup').getRecordTypeId();
             Set<Id> organicCaseRecordTypeIds = new Set<Id>{Schema.SObjectType.Case.getRecordTypeInfosByName().get('LBW Content Organic Setup').getRecordTypeId(), Schema.SObjectType.Case.getRecordTypeInfosByName().get('LS ATV Organic Setup').getRecordTypeId()};
             List<Services_Offered_Vertical__c> dmlServicesOffered = new List<Services_Offered_Vertical__c>();
             List<Case> dmlCases = new List<Case>();
             List<String> caseServicesOfferedList = new List<String>();
             Map<String, Offering_to_Vertical_Map__c> offeringMasterMap = new Map<String, Offering_to_Vertical_Map__c>();
             String acctProductType = 'Lead Stream ATV';
             String verticalsDescrText = '';
             Set<String> verticalsSet = new Set<String>();
             
             Id contentPilotOwner = [SELECT Id FROM Group WHERE DeveloperName = 'Content_Pilot' LIMIT 1].Id;
             //Id textbrokerUsrs = [SELECT Id FROM User WHERE Name = 'Textbroker Users' LIMIT 1].Id;
             
             // add current Services Offered to Verticals Master records to map
             for(Offering_to_Vertical_Map__c ovm :
                 [SELECT Offering_Name__c, 
                         Vertical_Name__c 
                    FROM Offering_to_Vertical_Map__c 
                   WHERE Is_Active__c = true]){
                 
                 offeringMasterMap.put(ovm.Offering_Name__c, ovm);
             }
             
             // get count of current Service Offerings/ Verticals (related list) on Case
             Integer relatedListCounts = 
                 [SELECT COUNT()
                    FROM Services_Offered_Vertical__c 
                   WHERE Case__c in :caseIds];
             
             System.Debug('Current related list count: ' + String.valueOf(relatedListCounts));
             
             if(relatedListCounts == 0){
             
                 // determine if the Case should be updated for LS ATV
                 for(Case c :
                     [SELECT Id,
                             RecordTypeId,
                             RecordType.Name,
                             AccountId,
                             Account.Product_Type_Transactional__c,
                             Services_Offered__c,
                             Number_of_Pages_Text__c,
                             IsClosed,
                             taskId__c,
                             Account.Client_ID__c,
                             Subject,
                             Description
                        FROM Case
                       WHERE Id IN: caseIds AND
                             RecordTypeId IN: organicCaseRecordTypeIds AND
                             Account.Product_Type_Transactional__c = :acctProductType AND
                             IsClosed = false]){
                     
                     // always update Task Id and owner for Textbroker
                     c.taskId__c = c.Account.Client_ID__c + '-002'; // 002 for LS ATV Accounts
                     c.OwnerId = contentPilotOwner;
                     c.Subject = 'LS ATV Content Setup';
                     
                     
                     // check to ensure the Case is not already the correct record type
                     if(c.RecordTypeId != lsATVCaseRecordTypeId){
                     
                         System.Debug('*** Adding Case to Update List for Record type change ***');
                     
                         // update Case to LS ATV Record Type
                         c.RecordTypeId = lsATVCaseRecordTypeId;
                     }
                        
                     if(!String.IsEmpty(c.Services_Offered__c)){
                     
                         System.Debug('*** Parsing Services Offered Text area field ***');
                     
                         // parse services offered text area and add to list
                         caseServicesOfferedList = c.Services_Offered__c.split('\r\n');
                         
                         System.Debug(caseServicesOfferedList);
                         
                         Integer count = 1;
                         
                         // loop through string list and begin adding lines to created list for Services Offered/ Vertical relationship
                         for(String s : caseServicesOfferedList){
                         
                             System.Debug('Offering to Vertical Mapping: ' + s);
                             Services_Offered_Vertical__c newSOV = new Services_Offered_Vertical__c();
                             count++;
                         
                             newSOV.Case__c = c.Id;
                             newSOV.Service_Offered__c = s;
                         
                             // has Mapped vertical; Offering is in master list
                             if(offeringMasterMap.containsKey(s) && offeringMasterMap.get(s).Vertical_Name__c != null){
                                 newSOV.Vertical__c = offeringMasterMap.get(s.trim()).Vertical_Name__c;
                             }
                             else{
                                 // No mapped Vertical; Offering is not in master list
                                 newSOV.Vertical__c = 'No Vertical Mapped';
                             }
                             
                             // add to update list
                             dmlServicesOffered.add(newSOV);
                             
                             verticalsSet.add(newSOV.Vertical__c);
                             
                         }
                         
                         for(String v : verticalsSet){
                             verticalsDescrText += v + ', ';
                         }
                         
                         System.Debug('*** vertical(s) Description: ' + verticalsDescrText.removeEnd(', '));
                         //System.Debug('*** Updating Number of Pages to : ' + String.valueOf(count) + ' ***');
                         
                         c.Number_of_Pages_Text__c = 1; // currently all segments for ATV are 1 page for Text Broker. In future will need to update logic to look at specific segments when business reqs change
                         verticalsDescrText = verticalsDescrText.removeEnd(', ');
                         verticalsDescrText = verticalsDescrText.replace('No Vertical Mapped, ', '');
                         c.Homepage__c = verticalsDescrText.replace('No Vertical Mapped', '');
                         c.Description = 'Please write custom content for the homepage only based on these Vertical(s): ' + c.Homepage__c;
                     }
                     
                     // add case to update list
                     dmlCases.add(c);
                 }
             }
             
             // CASE ATTRIBUTES
             if(dmlCases.size() > 0){
                 update dmlCases;
             }
             // SERVICES OFFERED/ VERTICALS
             if(dmlServicesOffered.size() > 0){
                 insert dmlServicesOffered;
             }
             
        }
        catch(Exception ex){
            System.Debug('An error occurred: ' + ex.getMessage());
        }
    }
}