objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Active_Cancel_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Active Cancel Form</label>
        <referenceTo>Cancellation_Request__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Temp_IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Temp IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5g3v</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id / Data</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>A Custom Object to hold Logs of type Error and Information created from various other Apex Classes. Unlike the native Debug Logs, the data or log created here are mere records and hence they're persistent.

Please employ the Apex Class named "ApexDebugLog" to utilize this Custom Object to save or log Errors or Information. There are also methods to create logs even via JavaScript.</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{0}</displayFormat>
        <label>Apex Debug Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>if( 
or( 
ispickval( Outcome__c , "Churned"), 
ispickval( Outcome__c , "Saved with No Concessions"), 
ispickval( Outcome__c , "Saved with Hard Concessions"), 
ispickval( Outcome__c , "Saved with Soft Concessions"), 
ispickval( Outcome__c , "Saved with Upsell"), 
ispickval( Outcome__c , "Saved By Sales"), 
ispickval( Outcome__c , "Saved With Free Time"),
ispickval( Outcome__c , "Saved With Winback"),
ispickval( Outcome__c , "Cancelled"), 
ispickval( Outcome__c , "Saved - Bailout Pricing - Standard"), 
ispickval( Outcome__c , "Saved - Bailout Pricing - Custom"), 
ispickval( Outcome__c , "Saved with Discount"), 
ispickval( Outcome__c , "Saved with OBC Package"), 
ispickval( Outcome__c , "Downsold to LH Only"), 
ispickval( Outcome__c , "Downsold to LH+ProPack"), 
ispickval( Outcome__c , "Downsold to LH+ProPack+Mobile Manager"), 
ispickval( Outcome__c , "Ad Station Credit"), 
ispickval( Outcome__c, "Duplicate Retention Case") 
), 
true, 
false)</formula>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>LH &amp; TORCHx Cancel Request</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Chiro</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Field Service</fullName>
                </value>
                <value>
                    <fullName>TORCHx</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateAccountFromCancelForm.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 06-Oct-2017
  Last Modified By ...: E. Ross
  Last Modified Date .: 06-Oct-2017
  Description ........: Class contains invocable method to assign/ remove Account Temp IMS Rep and Active 
  Cancel Form fields depending on criteria met.
*****************************************************************************/

public class UpdateAccountFromCancelForm
{
    @InvocableMethod
    public static void updateAccountCancelFormFields(List<Id> cancelFormIds)
    {
        /*try{
        
            if(cancelFormIds.size() > 0){
            
                Id cancelRecordTypeId = Schema.SObjectType.Cancellation_Request__c.getRecordTypeInfosByName().get('Cancellation Request').getRecordTypeId();
                Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Charge Failure').getRecordTypeId();
                Map<Id, Account> acctMap = new Map<Id, Account>();
                Map<Id, Cancellation_Request__c> crMap = new Map<Id, Cancellation_Request__c>();
                Map<Id, Case> acctCaseMap = new Map<Id, Case>();
                List<Account> dmlAccts = new List<Account>();
            
                // only get Cancellations that are owned by Users
                for(Cancellation_Request__c cr : 
                    [SELECT Id,
                            Account_Name__c,
                            Outcome__c,
                            OwnerId,
                            Owner.Type,
                            CreatedDate,
                            IsClosed__c
                       FROM Cancellation_Request__c
                      WHERE Id in :cancelFormIds AND
                            RecordTypeId = :cancelRecordTypeId AND
                            Account_Name__c != NULL]){
                            
                    // add record to Map
                    crMap.put(cr.Account_Name__c, cr);
                }
                
                if(crMap.size() > 0){
                
                    // only get Account records related to the Cancel Form
                    for(Account a :
                        [SELECT Id,
                                Temp_IMS_Rep__c,
                                Name,
                                Current_Active_Cancel_Form__c
                           FROM Account
                          WHERE Id in :crMap.keySet()]){
                    
                        // add record to Map
                        acctMap.put(a.Id, a);
                    }
                    
                    // only get Charge Failure Cases that are related to Account and are open
                    for(Case c :
                        [SELECT Id,
                                AccountId,
                                CaseNumber,
                                Status,
                                CreatedDate,
                                OwnerId,
                                IsClosed
                           FROM Case
                          WHERE RecordTypeId = :caseRecordTypeId AND
                                AccountId in :acctMap.keySet() AND
                                Owner.Type = 'User' AND
                                IsClosed = false]){
                                
                        // add record to Map
                        acctCaseMap.put(c.AccountId, c);
                    }
                    
                    // Assign Account Map values
                    for(Account a : acctMap.values()){
                        
                        // Assign Temp IMS Rep on Account; Chrg Failure Case Owner takes precedence over Cancel Form Owner
                        if(acctCaseMap.size() > 0){
                            
                            if(acctCaseMap.get(a.Id).AccountId == a.Id){
                            
                                // Assign Account IMS Temp Rep as Chrg Failure Case Owner
                                a.Temp_IMS_Rep__c = acctCaseMap.get(a.Id).OwnerId;
                                a.Current_Active_Cancel_Form__c = null;
                                
                                // Check for open Cancel Form to Assign Active Cancel Form on Account
                                if(crMap.get(a.Id).Account_Name__c == a.Id){
                                
                                    if(crMap.get(a.Id).IsClosed__c == false){
                                        a.Current_Active_Cancel_Form__c = crMap.get(a.Id).Id; 
                                    }
                                }
                                
                                // Add Account data to update list
                                dmlAccts.add(a);
                            }
                        }
                        else{
                        
                            // there are no open Chrg Failure Cases; check for Open Cancel Form
                            if(crMap.get(a.Id).Account_Name__c == a.Id){
                               
                                if(crMap.get(a.Id).IsClosed__c == false){
                                
                                    a.Temp_IMS_Rep__c = null;
                                    
                                    if(crMap.get(a.Id).Owner.Type == 'User'){
                                    
                                        // Cancel Form is Open; Assign Account IMS Temp Rep as Cancel Form Owner and Current Active Cancel Form Id
                                        a.Temp_IMS_Rep__c = crMap.get(a.Id).OwnerId;
                                    }
                                    
                                    a.Current_Active_Cancel_Form__c = crMap.get(a.Id).Id;
                                }
                                else{
                                    
                                    // No Open Chrg Failure Case or Cancel Form; clear fields
                                    a.Temp_IMS_Rep__c = null;
                                    a.Current_Active_Cancel_Form__c = null;
                                }
                                
                                // Add Account data to update list
                                dmlAccts.add(a);
                            }
                        }
                    }
                    
                    // perform DML operation in SFDC
                    if(dmlAccts.size() > 0){
                        update dmlAccts;
                    }
                }
            }
            
        }
        catch(Exception e){
        
            System.Debug('An error occurred: ' + e.getMessage());
            Apex_Debug_Log__c dbLog = new Apex_Debug_Log__c();
            dbLog.Apex_Class__c = 'UpdateAccountFromChrgFailureCase';
            dbLog.Message__c = e.getMessage();
            dbLog.Method__c = 'updateAccountCancelFormFields(Invocable)';
            dbLog.Record_Id__c = '';
            dbLog.Stack_Trace__c = e.getMessage();
            dbLog.Type__c = 'Error';
            
            insert dbLog;
        }*/
    }
}