objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Prospective</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Date_certification_complete__c</fullName>
        <label>Date certification complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <formula>Account.Parent.Name</formula>
        <label>Parent Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Products_Available_To_Sell__c</fullName>
        <label>Partner Products Available To Sell</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Essentials</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Yodle Max</fullName>
                </value>
                <value>
                    <fullName>Lighthouse Auto</fullName>
                </value>
                <value>
                    <fullName>Lighthouse Dental</fullName>
                </value>
                <value>
                    <fullName>Lighthouse Chiro</fullName>
                </value>
                <value>
                    <fullName>Lighthouse Field Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Received upon Signing</fullName>
                </value>
                <value>
                    <fullName>Charge at Training</fullName>
                </value>
                <value>
                    <fullName>Received at Training</fullName>
                </value>
                <value>
                    <fullName>Charge at Day 90</fullName>
                </value>
                <value>
                    <fullName>Received Post Day 90</fullName>
                </value>
                <value>
                    <fullName>Setup Fee Waived</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

objects/Partner_Community_HTML__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HTML__c</fullName>
        <label>HTML</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Partner Community HTML</label>
    <nameField>
        <label>Partner Community HTML Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Community HTML</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Marketing_Development_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Cost_of_Activity__c</fullName>
        <label>Estimated Cost of Activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Explain_activity_in_detail__c</fullName>
        <label>Explain activity in detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MDF_Date_Submitted__c</fullName>
        <label>MDF Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Request Denied</fullName>
                </value>
                <value>
                    <fullName>Request Expired</fullName>
                </value>
                <value>
                    <fullName>Claim Submitted</fullName>
                </value>
                <value>
                    <fullName>Claim In Review</fullName>
                </value>
                <value>
                    <fullName>Claim Needs More Information</fullName>
                </value>
                <value>
                    <fullName>Claim Approved</fullName>
                </value>
                <value>
                    <fullName>Claim Denied</fullName>
                </value>
                <value>
                    <fullName>Claim Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Marketing Development Funds</relationshipLabel>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Activity__c</fullName>
        <label>Type of Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Testimonial Videos</fullName>
                </value>
                <value>
                    <fullName>White Papers</fullName>
                </value>
                <value>
                    <fullName>Research Docs</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Promotional Items</fullName>
                </value>
                <value>
                    <fullName>Online Marketing</fullName>
                </value>
                <value>
                    <fullName>Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Direct Mail/Email</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_goal_of_the_activity__c</fullName>
        <label>What is the goal of the activity?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>When_will_the_activity_happen__c</fullName>
        <label>When will the activity happen</label>
        <type>Date</type>
    </fields>
    <label>Partner Marketing Development Fund</label>
    <nameField>
        <displayFormat>PMDF-{0000000}</displayFormat>
        <label>Partner MDF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Marketing Development Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Quarterly_Managed_Account_Count__c.object
<CustomObject>
    <fields>
        <fullName>End_of_Quarter_Date__c</fullName>
        <label>End of Quarter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Account Count</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Account_Count</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Quarterly Managed Account Count</label>
    <nameField>
        <displayFormat>PQMAC-{0000000}</displayFormat>
        <label>Partner Quarterly Managed Account Count</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Account Count</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Quarterly_Managed_Child_Account__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Quarterly_Managed_Account_Count__c</fullName>
        <label>Partner Quarterly Managed Account Count</label>
        <referenceTo>Partner_Quarterly_Managed_Account_Count__c</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Quarterly Managed Child Account</label>
    <nameField>
        <displayFormat>PQAMN-{0000000}</displayFormat>
        <label>Partner Quarterly Account Managed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Child Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MDFRequestStatusAndClaimFormContrTest.cls
@isTest
private class MDFRequestStatusAndClaimFormContrTest {

	@testSetup static void partnerUserTestSetup() {
		UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
		system.debug('portalRole is ' + portalRole);

		Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
		User portalAccountOwner1 = new User(
			UserRoleId = portalRole.Id,
			ProfileId = profile1.Id,
			Username = System.now().millisecond() + 'te43st2@teyodles44432t.com',
			Alias = 'batman',
			Email='bruce.wayne@wayneenterprises.com',
			EmailEncodingKey='UTF-8',
			Firstname='Bruce',
			Lastname='Wayne',
			LanguageLocaleKey='en_US',
			LocaleSidKey='en_US',
			TimeZoneSidKey='America/Chicago',
			Phone = '5555555555',
			Title = 'Test Title'
		);
		Database.insert(portalAccountOwner1);

		System.runAs ( portalAccountOwner1 ) {
			//Create account
			Account portalAccount1 = new Account(
				Name = 'TestAccount',
				OwnerId = portalAccountOwner1.Id,
				RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner Master Account').getRecordTypeId(),
				Partner_Status__c = 'Customer'
			);
			Database.insert(portalAccount1);

			//Create Child Account
			List<Account> childAccountList = new List<Account>();
			for(Integer i = 0; i <= 5; i++){
				Account childAccount1 = new Account(
					Name = 'TestAccount childAccount ' + String.valueof(i),
					OwnerId = portalAccountOwner1.Id,
					RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId(),
					Status__c = 'LIVE',
					ParentId = portalAccount1.Id
				);
				childAccountList.add(childAccount1);
			}

			Database.insert(childAccountList);

			//Create Last Quarter Count
			Partner_Quarterly_Managed_Account_Count__c lastQuarterManagedAccountCount = new Partner_Quarterly_Managed_Account_Count__c(
				OwnerId = portalAccountOwner1.Id,
				Parent_Account__c = portalAccount1.Id,
				End_of_Quarter_Date__c = [Select StartDate, EndDate From Period Where type = 'Quarter' and StartDate = LAST_FISCAL_QUARTER].EndDate
			);
			Database.insert(lastQuarterManagedAccountCount);

			//Create Last Quarter Child Account
			List<Partner_Quarterly_Managed_Child_Account__c> managedChildAccountList = new List<Partner_Quarterly_Managed_Child_Account__c>();
			for(Account record : childAccountList){
				Partner_Quarterly_Managed_Child_Account__c lastQuarterChildManagedAccount = new Partner_Quarterly_Managed_Child_Account__c(
					Child_Account__c = record.Id,
					Partner_Quarterly_Managed_Account_Count__c = lastQuarterManagedAccountCount.Id
				);
				managedChildAccountList.add(lastQuarterChildManagedAccount);
			}
			Database.insert(managedChildAccountList);

			//Create contact
			Contact contact1 = new Contact(
				FirstName = 'Test',
				Lastname = 'McTesty',
				AccountId = portalAccount1.Id,
				Email = System.now().millisecond() + 'test@test.com'
			);
			Database.insert(contact1);

			Opportunity opportunity1 = new Opportunity(
				Name = 'Test Opp',
				StageName = 'Closed Won',
				Date_certification_complete__c = Date.today(),
				Partner_Products_Available_To_Sell__c = 'Lighthouse Dental',
				AccountId = portalAccount1.Id,
				CloseDate = Date.today(),
				RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CPP - Initial Transaction').getRecordTypeId(),
				Payment_Status__c = 'Received upon Signing'
			);
			Database.insert(opportunity1);

			Partner_Community_HTML__c pchtml = new Partner_Community_HTML__c(
				Name = 'WelcomePage',
				HTML__c = '<div> '
					+ '<div class="h1">Welcome to your <br />Partner Portal</div>'
					+ '<div class="body1">Hi {Contact.Name}'
					+ '<p>'
					+ 'In this portal you have access to all of the sales, training, and marketing material you need to enable your clients to use Lighthouse 360. You also have access to the partner community.'
					+ '<p>'
					+ 'In the partner community you can chat with other partners about best practices, the industry, or feedback on any initiatives you are working on. The community is also a great place to form new relationships to help you expand your current reach.' 
					+ '<p>'
					+ 'As your Partner Account Manager, I\'ll be your single point of contact to help assist you with anything you need. Here is my contact info:'
					+ '<p>'
					+ 'Name: {Owner.Name}<br />'
					+ 'Title: {Owner.Title}<br />'
					+ 'Phone: {Owner.Phone}<br />'
					+ 'Email: {Owner.Email}<br />'
					+ '<p>'
					+ '<p>'
					+ 'I\'m looking forward to helping you succeed!'
					+ '<p>'
					+ '-{Owner.Name}</div>'
					+ '</div> ',
				Active__c = true
			);
			Database.insert(pchtml);

			//Create user
			Profile portalProfile = [SELECT Id FROM Profile where UserType = 'PowerPartner' Limit 1];
			User user1 = new User(
				Username = System.now().millisecond() + 'test12345@test.com',
				ContactId = contact1.Id,
				ProfileId = portalProfile.Id,
				Alias = 'test123',
				Email = 'test12345@test.com',
				EmailEncodingKey = 'UTF-8',
				LastName = 'McTesty',
				CommunityNickname = 'test12345',
				TimeZoneSidKey = 'America/Los_Angeles',
				LocaleSidKey = 'en_US',
				LanguageLocaleKey = 'en_US'
			);
			Database.insert(user1);
		}
	}
	
	@isTest static void test_MDFRequestStatusAndClaimFormContr() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		User user1 = [select Id, AccountId, Account.OwnerId from User where Email = 'test12345@test.com'];

		System.runAs (user1){
			//Test.setCurrentPage(Page.MDFRequestStatusAndClaimForm);
			MDFRequestStatusAndClaimFormController contr = new MDFRequestStatusAndClaimFormController();

			Partner_Marketing_Development_Fund__c pmdf = new Partner_Marketing_Development_Fund__c();
			pmdf.OwnerId = user1.Account.OwnerId;
			pmdf.Partner_Account__c = user1.AccountId;
			pmdf.Requested_By__c = user1.Id;
			pmdf.Estimated_Cost_of_Activity__c = 100;
			pmdf.Type_of_Activity__c = 'White Papers';
			pmdf.When_will_the_activity_happen__c = Date.today().addDays(5);
			pmdf.What_is_the_goal_of_the_activity__c = 'Test Test';
			pmdf.MDF_Date_Submitted__c = Date.today();
			pmdf.Explain_activity_in_detail__c = 'Test Teset TEset';
			insert pmdf;

			contr.refreshData();

			pmdf.MDF_Status__c = 'Request Approved';
			update pmdf;

			contr.refreshData();

			ApexPages.currentPage().getParameters().put('pmdfSelectedId', pmdf.Id);

			contr.selectedPMDF();

			contr.saveClaimForm();

			contr.attachFile();
		}
	}
	
}