objects/Account.object
<CustomObject>
    <fields>
        <fullName>IMS_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IMS Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Model_Local__c</fullName>
        <formula>if( 
IMS_Rep__r.Id = "00560000001HpEm", /* Customer Care */
"Pooled", 
if( 
or( 
contains( IMS_Rep_Role__c , "Local Consultant"),
 AND(
contains( IMS_Rep_Role__c , "Local CSM"),
contains( IMS_Rep__r.Department, "LeadStream")), 
IMS_Rep__r.Id = "005600000017MCh", /* JEnnifer Flanagan */
IMS_Rep__r.Id = "00532000005P6l3"), /*LeadStream Support*/
"Dedicated", ""))</formula>
        <label>Service Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <inlineHelpText>Please only use for final notes regarding cancellation outcome or notes regarding duplicate retention cases. All other notes should be put in comment section below</inlineHelpText>
        <label>Additional Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Scheduled_Contact_Date__c</fullName>
        <label>Next Scheduled Contact Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CancellationRequestTriggerTest.cls
@isTest
private class CancellationRequestTriggerTest {
    
    @isTest static void test_CancellationRequestTrigger() {
        Account newAccount = new Account();
        newAccount.Name = 'Tset Account';
        insert newAccount;

        Case newCase = new Case();
        newCase.Reason = 'CSC';
        newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Outbound Call').getRecordTypeId();
        newCase.AccountId = newAccount.Id;
        insert newCase;

        Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
        newCancellationRequest.Account_Name__c = newAccount.Id;
        insert newCancellationRequest;

        /*newCancellationRequest.Outcome__c = 'Duplicate Retention Case';
        newCancellationRequest.Additional_Notes__c = 'Test Notes';
        update newCancellationRequest;

        newCancellationRequest.Outcome__c = 'In Progress';
        update newCancellationRequest;*/
    }

    @isTest static void test_CancellationRequestTriggerHandler() {
        Account newAccount = new Account();
        newAccount.Name = 'Tset Account';
        insert newAccount;

        Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
        newCancellationRequest.Account_Name__c = newAccount.Id;
        insert newCancellationRequest;

        newCancellationRequest.Outcome__c = 'Duplicate Retention Case';
        newCancellationRequest.Additional_Notes__c = 'Test Notes';
        update newCancellationRequest;

        newCancellationRequest.Outcome__c = 'In Progress';
        update newCancellationRequest;
    }

    @isTest static void test_CancellationRequestTriggerEventCUDOperations() { 
        Id imsRepId = [SELECT Id FROM User WHERE Alias = 'sauto' LIMIT 1].Id;
        
        System.Debug('IMS Rep Id: ' + imsRepId);
        
        Account newAccount = new Account();
        newAccount.Name = 'Test Account for YO-62525 to span events for CancelRequest Updates';
        newAccount.Client_Type__c = 'Local';
        newAccount.IMS_Rep__c = imsRepId;  // To make Service_Model_Local__c ='Dedicated', populating underlying formula data
        insert newAccount;
        
        Account newAccount2 = new Account();
        newAccount2.Name = 'Test Account 2 for YO-62525 to span events for CancelRequest Updates';
        newAccount2.Client_Type__c = 'Local';
        newAccount2.IMS_Rep__c = imsRepId;  // To make Service_Model_Local__c ='Dedicated', populating underlying formula data
        insert newAccount2;

        Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
        newCancellationRequest.Account_Name__c = newAccount2.Id;
        newCancellationRequest.Next_Scheduled_Contact_Date__c = DateTime.valueOf('2017-05-22 10:00:00'); 
        newCancellationRequest.Additional_Notes__c = 'Test scenario to Create a New Event from New Cancel Request Create';
        insert newCancellationRequest;
        
        newCancellationRequest.Next_Scheduled_Contact_Date__c = DateTime.valueOf('2017-05-19 09:00:00'); 
        newCancellationRequest.Additional_Notes__c = 'Test scenario of Update the NextSchedule Date , to create New event as no associated Event';
        update newCancellationRequest;
                
        newCancellationRequest.Next_Scheduled_Contact_Date__c = DateTime.valueOf('2017-05-19 11:00:00');  
        newCancellationRequest.Additional_Notes__c = 'Test scenario of Update the NextSchedule Date to valid Date , to update the associated Event';
        update newCancellationRequest;

        newCancellationRequest.Additional_Notes__c = 'Test scenario of NextScheduleDate not changed, however, Additional_Notes__c change, should not trigger any Event related code';
        update newCancellationRequest;

        newCancellationRequest.Next_Scheduled_Contact_Date__c = null; 
        newCancellationRequest.Additional_Notes__c = 'Test scenario of Update the NextSchedule Date to Null , to delete the associated Event';
        update newCancellationRequest;
        
                
    }
    
}