objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Client First Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>from Yodle Live</inlineHelpText>
        <label>Client ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Client Last Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Important_Account_Notes__c</fullName>
        <label>Important Account Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Completed_YBN_TP__c</fullName>
        <label>Last Completed YBN TP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Multi_Location_Owner_Primary_CID__c</fullName>
        <description>Client ID for which all communication gets logged - CS Managers allowed to access also</description>
        <label>Multi-Location Owner Primary CID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Billing_Date__c</fullName>
        <label>Next Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_TP_Needed_By__c</fullName>
        <formula>IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level A"),
NOT(ISBLANK(Last_Completed_YBN_TP__c))), 
Last_Completed_YBN_TP__c + 31,

IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level B"),
NOT(ISBLANK(Last_Completed_YBN_TP__c))), 
Last_Completed_YBN_TP__c + 62,

IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level C"),
NOT(ISBLANK(Last_Completed_YBN_TP__c))), 
Last_Completed_YBN_TP__c + 93,

IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level A"),ISBLANK(Last_Completed_YBN_TP__c)), Live_Date__c + 62 + Month_1_Check_In_Date_Adjustment__c,

IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level B"),ISBLANK(Last_Completed_YBN_TP__c)), Live_Date__c + 93 + Month_1_Check_In_Date_Adjustment__c,

IF(AND(ISPICKVAL(Individual_Location_Service_Level__c,"Service Level C"),ISBLANK(Last_Completed_YBN_TP__c)), Live_Date__c + 124 + Month_1_Check_In_Date_Adjustment__c,

Null))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next TP Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Multi_Location_Owner_For_TP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>- CS Managers allowed to access also</description>
        <label>Primary Multi-Location Owner For TP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type_Transactional__c</fullName>
        <formula>if( 
OR(
AND(
    contains(Product_Type__c,"TORCHX"),
    contains(Product_Type__c,"SEM")), 
AND(
  contains(Product_Plan_Id__c,"TORCHX"), 
  contains(Product_Plan_Id__c,"ADS"), 
  contains(Client_Experience_Key__c, "torchx-main"))),
  "TORCHx Ads",


if( 
OR(contains(Product_Type__c,"TORCHX"), 
AND( contains(Product_Plan_Id__c,"TORCHX"), contains(Client_Experience_Key__c, "torchx-main"))),
"TORCHx",


if( 
OR( 
contains(Product_Plan_Id__c,"LEADS_BY_WEB"),
contains(Product_Type__c, "LBW")), 
"Leads By Web",

if( 
OR(contains(Product_Type__c,"FIELD_SERVICE_TEAM"),contains(Product_Type__c,"FIELD_SERVICE")), 
"Lighthouse Field Service", 

if( 
AND(contains(Product_Type__c,"WELCOME_STATION"),contains(Product_Type__c,"MOBILE_MANAGER")), 
"Lighthouse + PP + WS + MM", 

if( 
contains(Product_Type__c,"MOBILE_MANAGER"), 
"Lighthouse + PP + MM", 

if( 
contains(Product_Type__c,"WELCOME_STATION"), 
"Lighthouse + PP + WS", 

if( 
contains(Product_Type__c,"PRO_PACK"), 
"Lighthouse + PP", 

if( 
and( 
contains(Product_Type__c, "LIGHTHOUSE"), 
contains(Product_Type__c, "SEM")), 
"Lighthouse Ads", 

if( 
contains(Product_Type__c, "LIGHTHOUSE"), 
"Lighthouse", 

if(
OR(
contains(Product_Plan_Id__c, "ATV"),
contains(Product_Type__c, "ATV")),
"Lead Stream ATV",

if( 
and( 
contains(Product_Type__c , "SEM"), 
or( 
contains(Product_Type__c, "ORGANIC"), 
contains(Product_Type__c, "OUTRANK"))), 
"Yodle Max", 
if( 
or( 
contains(Product_Type__c, "Outrank 1.0" ), 
contains(Product_Type__c ,"Legacy Outrank")), 
"Outrank 1.0", 
if( 
and( 
contains(Product_Type__c, "ESSENTIALS" ), 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" ))), 
"Essentials", 
if( 
or( 
contains(Product_Type__c, "ORGANIC" ), 
contains(Product_Type__c, "OUTRANK" )), 
"Yodle Organic", 
if( 
contains(Product_Type__c, "SEM"), 
"Yodle Ads", 
if( 
and( 
contains(Product_Type__c, "OUTRANK" ), 
contains(Product_Type__c , "WEBSITE"), 
ispickval( Client_Type__c , "National")), 
"JCI", 
if( 
contains(Product_Type__c, "CENTERMARK" ), 
"YBN", 
if( 
or( 
contains( Product_Type__c , "WEBSITE"), 
contains( Product_Type__c , "YODLE_WEB")), 
"Yodle Web", 
"Other")))))))))))))))))))</formula>
        <label>Account Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rogers_IMS_Rep_Text__c</fullName>
        <formula>IMS_Rep__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rogers IMS Rep Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Management__c</fullName>
        <label>Test Management</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>tz__Local_Time_Short__c</fullName>
        <description>Shows the current local time (without date) for the Account.</description>
        <formula>IF(ISBLANK(tz__UTF_Offset__c),
"Unknown",
TEXT(
IF(
OR(
VALUE( MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 12, 2 ) ) = 0,
VALUE( MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 12, 2 ) ) = 12
),
12,
VALUE( MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 12, 2 ) )
-
IF(
VALUE( MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 12, 2 ) ) &lt; 12,
0,
12
)
)
)
&amp;":"&amp;
MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 15, 2 )
&amp;" "&amp;
IF(
VALUE( MID( TEXT( NOW()+ tz__UTF_Offset__c /24 ), 12, 2 ) ) &lt; 12,
"AM",
"PM"
)
&amp; " " &amp;
IF( $Setup.tz__lt_app_settings__c.tz__Abbreviation__c, 	tz__Timezone__c,"")
)</formula>
        <inlineHelpText>Shows the local time (without date) for the Account.</inlineHelpText>
        <label>Local Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>wrenBilling__c</fullName>
        <defaultValue>false</defaultValue>
        <label>wrenBilling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Franchise_Influencer__c</fullName>
        <inlineHelpText>(VIP) accounts within a network</inlineHelpText>
        <label>Franchise Influencer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <description>- CS Managers allowed to access also</description>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A+</fullName>
                </value>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_ID__c</fullName>
        <formula>Account.Client_ID__c</formula>
        <label>Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tz__Local_Time_Short__c</fullName>
        <description>Shows the current local time (without date) of the Account associated with the Opportunity.</description>
        <formula>Account.tz__Local_Time_Short__c</formula>
        <inlineHelpText>Shows the local time (without date) of the Account associated with the Opportunity.</inlineHelpText>
        <label>Local Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <formula>Account.Client_First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <formula>Account.Client_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Location_Service_Level__c</fullName>
        <label>Individual Location Service Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Level A</fullName>
                </value>
                <value>
                    <fullName>Service Level B</fullName>
                </value>
                <value>
                    <fullName>Service Level C</fullName>
                </value>
                <value>
                    <fullName>Service Level D</fullName>
                </value>
                <value>
                    <fullName>Service Level E</fullName>
                </value>
                <value>
                    <fullName>Service Level F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

classes/OppHLPanelController.cls
public with sharing class OppHLPanelController{

    public Id opportunityId {get; set;}
    public Id accountId {get; set;}
    public String acctName {get; set;}
    public String clientFullName {get; set;}
    public String acctBillingCtry {get; set;}
    public String acctEmail {get; set;}
    public String acctPhone {get; set;}
    public String acctLocalTmShrt {get; set;}
    public String acctStatus {get; set;}
    public String acctManager {get; set;}
    public String acctProductType {get; set;}
    public String acctClientId {get; set;}
    public String acctWebSite {get; set;}
    public String acctTestMgmt {get; set;}
    public String acctImportantNotes {get; set;}
    public String acctIndLocationSrvcLvl {get; set;}
    public String primaryMLOId {get; set;} 
    public String franchiseInfluencer {get; set;}
    public Date nextBillingDt {get; set;}
    public Date lastComplWBNtpDt {get; set;}
    public Date nextNeededTPDt {get; set;}
    public Boolean hasWrenBilling {get; set;}
    public Boolean hasPrimaryMLOForTP {get; set;}
    
    public OppHLPanelController(){
    
        opportunityId = ApexPages.currentPage().getParameters().get('id');
        acctName = '';
        clientFullName = '';
        acctBillingCtry = '';
        acctEmail = '';
        acctPhone = '';
        acctLocalTmShrt = '';
        acctStatus = '';
        acctManager = '';
        acctProductType = '';
        acctClientId = '';
        acctWebSite = '';
        acctTestMgmt = '';
        acctImportantNotes = '';
        acctIndLocationSrvcLvl = '';
        primaryMLOId = '';
        hasWrenBilling = false;
        hasPrimaryMLOForTP = false;
        franchiseInfluencer = '';
    }
    
    public PageReference onPageLoad(){
    
        if(opportunityId != null){
        
            for(Opportunity o :
                [SELECT Id,
                        AccountId
                   FROM Opportunity
                  WHERE Id =: opportunityId
                  LIMIT 1]){
            
                // set AccountId value    
                if(o.Id != null){
                    accountId = o.AccountId;
                }
            }
            
            if(accountId != null){
                
                for(Account a : 
                    [SELECT Id,
                            Name,
                            Client_First_Name__c,
                            Client_Last_Name__c,
                            Email__c,
                            Phone,
                            tz__Local_Time_Short__c,
                            Status__c,
                            Rogers_IMS_Rep_text__c,
                            Product_Type_Transactional__c,
                            Next_Billing_Date__c,
                            Client_ID__c,
                            Website,
                            Test_Management__c,
                            Individual_Location_Service_Level__c,
                            Primary_Multi_Location_Owner_For_TP__c,
                            Multi_Location_Owner_Primary_CID__c,
                            Last_Completed_YBN_TP__c,
                            Next_TP_Needed_By__c,
                            wrenBilling__c,
                            BillingCountry,
                            Franchise_Influencer__c,
                            Important_Account_Notes__c
                       FROM Account
                      WHERE Id = :accountId
                      LIMIT 1]){
                      
                    if(a.Id != null){
                    
                        acctName = a.Name;
                        clientFullName = a.Client_First_Name__c + ' ' + a.Client_Last_Name__c;
                        acctBillingCtry = a.BillingCountry;
                        acctEmail = a.Email__c;
                        acctPhone = a.Phone;
                        acctLocalTmShrt = a.tz__Local_Time_Short__c;
                        acctStatus = a.Status__c;
                        acctManager = a.Rogers_IMS_Rep_text__c;
                        acctProductType = a.Product_Type_Transactional__c;
                        nextBillingDt = a.Next_Billing_Date__c;
                        acctClientId = a.Client_ID__c;
                        acctWebSite = a.Website;
                        acctTestMgmt = a.Test_Management__c;
                        acctImportantNotes = a.Important_Account_Notes__c;
                        acctIndLocationSrvcLvl = a.Individual_Location_Service_Level__c;
                        primaryMLOId = a.Multi_Location_Owner_Primary_CID__c;
                        lastComplWBNtpDt = a.Last_Completed_YBN_TP__c;
                        nextNeededTPDt = a.Next_TP_Needed_By__c;
                        hasWrenBilling = a.wrenBilling__c;
                        hasPrimaryMLOForTP = a.Primary_Multi_Location_Owner_For_TP__c;
                        franchiseInfluencer = a.Franchise_Influencer__c;
                    }
                }
            }
        }
        
        return null;
    }
}