objects/Account.object
<CustomObject>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Used for YBN Individual Location accounts..</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Segment_Optimization_Case_Assignment__c.object
<CustomObject>
    <description>Currently only used for Local</description>
    <label>Segment Optimization Case Assignment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segment Optimization Case Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SegmentOptCaseAssignTriggerHandlerTest.cls
@isTest
private class SegmentOptCaseAssignTriggerHandlerTest {
	
	@isTest static void test_beforeInsert() {
		Segment_Optimization_Case_Assignment__c segAssign = new Segment_Optimization_Case_Assignment__c();
		segAssign.Name = 'Dentist';
		segAssign.OwnerId = [select Id from User where IsActive = true and Profile.Name = 'System Administrator' and Id != :UserInfo.getUserId() limit 1].Id;
		insert segAssign;

		try{
			Segment_Optimization_Case_Assignment__c dupeAssign = new Segment_Optimization_Case_Assignment__c();
			dupeAssign.Name = 'Dentist';
			dupeAssign.OwnerId = [select Id from User where IsActive = true and Profile.Name = 'System Administrator' and Id != :UserInfo.getUserId() limit 1].Id;
			insert dupeAssign;
		}catch(Exception E){
			system.assert([select Id from Segment_Optimization_Case_Assignment__c where Name = 'Dentist'].size() == 1);
		}
	}
	
	@isTest static void test_afterInsert() {
		Segment_Optimization_Case_Assignment__c segAssign = new Segment_Optimization_Case_Assignment__c();
		segAssign.Name = 'Dentist';
		segAssign.OwnerId = [select Id from User where IsActive = true and Profile.Name = 'System Administrator' and Id != :UserInfo.getUserId() limit 1].Id;
		insert segAssign;

		Account acct = new Account();
		acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
		acct.Name = 'Test Account';
		acct.Client_Type__c = 'Local';
		acct.Secondary_Segments__c = 'Dentist';
		insert acct;

		Case cs = new Case();
		cs.AccountId = acct.Id;
		cs.Reason2__c = 'Client Requested';
		cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Optimization').getRecordTypeId();
		insert cs;

		system.assert([select OwnerId from Case where Id =: cs.Id].OwnerId == segAssign.OwnerId);
	}

	@isTest static void test_afterUpdate() {
		Segment_Optimization_Case_Assignment__c segAssign = new Segment_Optimization_Case_Assignment__c();
		segAssign.Name = 'Dentist';
		segAssign.OwnerId = [select Id from User where IsActive = true and Profile.Name = 'System Administrator' and Id != :UserInfo.getUserId() limit 1].Id;
		insert segAssign;

		Account acct = new Account();
		acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Standard').getRecordTypeId();
		acct.Name = 'Test Account';
		acct.Client_Type__c = 'Local';
		acct.Secondary_Segments__c = 'Dentist';
		insert acct;

		Case cs = new Case();
		cs.AccountId = acct.Id;
		cs.Reason2__c = 'Client Requested';
		cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Optimization').getRecordTypeId();
		insert cs;

		Test.startTest();
		segAssign.Name = 'Dentist';
		segAssign.OwnerId = UserInfo.getUserId();
		update segAssign;
		Test.stopTest();

		system.assert([select OwnerId from Case where Id =: cs.Id].OwnerId == UserInfo.getUserId());
	}
	
}