objects/Account.object
<CustomObject>
    <fields>
        <fullName>Budget_Ads__c</fullName>
        <label>Budget Ads</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Secondary_Segments__c</fullName>
        <label>Segment</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yodle Core</fullName>
                </value>
                <value>
                    <fullName>Yodle Submit</fullName>
                </value>
                <value>
                    <fullName>National Account</fullName>
                </value>
                <value>
                    <fullName>OEM Account</fullName>
                </value>
                <value>
                    <fullName>National Master Account</fullName>
                </value>
                <value>
                    <fullName>OEM National</fullName>
                </value>
                <value>
                    <fullName>Service Task</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>YBN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>LIVE</fullName>
                </value>
                <value>
                    <fullName>AD_READY</fullName>
                </value>
                <value>
                    <fullName>PROVISIONING</fullName>
                </value>
                <value>
                    <fullName>SALES</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketo_ID__c</fullName>
        <externalId>true</externalId>
        <label>Marketo ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Categories_Inputted_into_BLocal__c</fullName>
        <label>Business Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Client_Type__c</fullName>
        <formula>TEXT(Account_Name__r.Client_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Date__c</fullName>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_for_Submission__c</fullName>
        <label>Reason for Submission</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Citation Network Escalation</fullName>
                </value>
                <value>
                    <fullName>Client Request Tasks</fullName>
                </value>
                <value>
                    <fullName>Custom Domain Request</fullName>
                </value>
                <value>
                    <fullName>G&amp;B Login Issues</fullName>
                </value>
                <value>
                    <fullName>Google/Bing Maps Listing Issue</fullName>
                </value>
                <value>
                    <fullName>Indexing Circuit Breaker – Google</fullName>
                </value>
                <value>
                    <fullName>Listing Keyword Update (SDB Only)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Poor Performance - Ranking Issues</fullName>
                </value>
                <value>
                    <fullName>Product &amp; Strategy Questions/Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sync_to_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync to Marketo</label>
        <type>Checkbox</type>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Org_Case_to_Marketo_Field_Mappings__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Field_API_Name__c</fullName>
        <label>SFDC Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Field__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Sync Field</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>SFDC Org Case to Marketo Field Mappings</label>
</CustomObject>

classes/OrganicCaseTriggerTest.cls
@isTest
private class OrganicCaseTriggerTest {
    
    @isTest static void test_ReasonForSubmission() {
    	//new TestCustomSettingInitializer();
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        insert newAccount;

        Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.Reason_for_Submission__c = 'Test Submission Pick Value';
        insert newOrganicAnalysis;
    }

    @isTest static void test_syncOrganicCaseRecordLogic(){
    	//new TestCustomSettingInitializer();

    	String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Secondary_Segments__c = 'Locksmith';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Test.startTest();
		Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        insert newOrganicAnalysis;
        Test.stopTest();
    }

    @isTest static void test_syncOrganicCaseRecordLogicUpdate(){
    	//new TestCustomSettingInitializer();

    	String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Secondary_Segments__c = 'Locksmith';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        insert newOrganicAnalysis;

        Test.startTest();
        OrganicCaseObjectHelper.alreadyFiredOrganicCaseObjectHelper = false;
        newOrganicAnalysis.Sync_to_Marketo__c = false;
        update newOrganicAnalysis;
        Test.stopTest();
    }

    @isTest static void test_syncOrganicCaseRecordLogicFieldUpdate(){
    	//new TestCustomSettingInitializer();

    	String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		SFDC_Org_Case_to_Marketo_Field_Mappings__c fieldMapping = new SFDC_Org_Case_to_Marketo_Field_Mappings__c();
		fieldMapping.Name = 'TestField';
		fieldMapping.Sync_Field__c = true;
		fieldMapping.SFDC_Field_API_Name__c = 'Categories_Inputted_into_BLocal__c';
		insert fieldMapping;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Secondary_Segments__c = 'Locksmith';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        insert newOrganicAnalysis;

        Test.startTest();
        OrganicCaseObjectHelper.alreadyFiredOrganicCaseObjectHelper = false;
        newOrganicAnalysis.Categories_Inputted_into_BLocal__c = 'Test Change';
        update newOrganicAnalysis;
        Test.stopTest();
    }

    @isTest static void test_organicCaseUpdateLeadsNotFuture(){
    	//new TestCustomSettingInitializer();

    	String responseExample = '{"requestId":"e42b#14272d07d78","success":true,"result":[{"id":50,"status":"created"}]}';
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		SFDC_Org_Case_to_Marketo_Field_Mappings__c fieldMapping = new SFDC_Org_Case_to_Marketo_Field_Mappings__c();
		fieldMapping.Name = 'TestField';
		fieldMapping.Sync_Field__c = true;
		fieldMapping.SFDC_Field_API_Name__c = 'Categories_Inputted_into_BLocal__c';
		insert fieldMapping;

		Account newAccount = new Account();
		newAccount.Name = 'Test Account';
		newAccount.Marketo_ID__c = String.valueof(DateTime.now().millisecondGMT());
		newAccount.Status__c = 'LIVE';
		newAccount.Email__c = String.valueof(DateTime.now().millisecondGMT()) + '@test.com';
		newAccount.Client_Type__c = 'Local';
		newAccount.Budget_Ads__c = 700;
		newAccount.Live_Date__c = Date.today();
		newAccount.Secondary_Segments__c = 'Locksmith';
		newAccount.Sync_to_Marketo__c = true;
		insert newAccount;

		Organic_Analysis__c newOrganicAnalysis = new Organic_Analysis__c();
        newOrganicAnalysis.Account_Name__c = newAccount.Id;
        newOrganicAnalysis.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
        newOrganicAnalysis.Categories_Inputted_into_BLocal__c = 'Test Change';
        insert newOrganicAnalysis;

        Test.startTest();
        Database.executeBatch(new CriteriaBasedBatchDataPushToMarketo(new List<Id>{newOrganicAnalysis.Id}, 'Organic_Analysis__c'));
        Test.stopTest();
    }
    
}