objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Connected with Gatekeeper</fullName>
                </value>
                <value>
                    <fullName>Connected with Target</fullName>
                </value>
                <value>
                    <fullName>LifeCycle Milestone Completed</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
  <sharingModel>ControlledByParent</sharingModel>

</CustomObject>

objects/Partner_Marketing_Development_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Notes__c</fullName>
        <label>Claim Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claimed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claimed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Activity__c</fullName>
        <label>Date of Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Cost_of_Activity__c</fullName>
        <label>Estimated Cost of Activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MDF_Date_Submitted__c</fullName>
        <label>MDF Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Request Denied</fullName>
                </value>
                <value>
                    <fullName>Request Expired</fullName>
                </value>
                <value>
                    <fullName>Claim Submitted</fullName>
                </value>
                <value>
                    <fullName>Claim In Review</fullName>
                </value>
                <value>
                    <fullName>Claim Needs More Information</fullName>
                </value>
                <value>
                    <fullName>Claim Approved</fullName>
                </value>
                <value>
                    <fullName>Claim Denied</fullName>
                </value>
                <value>
                    <fullName>Claim Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Activity__c</fullName>
        <label>Other Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Marketing Development Funds</relationshipLabel>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost_of_Activity__c</fullName>
        <label>Total Cost of Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Activity__c</fullName>
        <label>Type of Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Testimonial Videos</fullName>
                </value>
                <value>
                    <fullName>White Papers</fullName>
                </value>
                <value>
                    <fullName>Research Docs</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Promotional Items</fullName>
                </value>
                <value>
                    <fullName>Online Marketing</fullName>
                </value>
                <value>
                    <fullName>Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Direct Mail/Email</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_goal_of_the_activity__c</fullName>
        <label>What is the goal of the activity?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>When_will_the_activity_happen__c</fullName>
        <label>When will the activity happen</label>
        <type>Date</type>
    </fields>
    <label>Partner Marketing Development Fund</label>
    <nameField>
        <displayFormat>PMDF-{0000000}</displayFormat>
        <label>Partner MDF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Marketing Development Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_MDF_Quarterly_Budget_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Minimum_Managed_Accounts__c</fullName>
        <label>Minimum Managed Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner MDF Quarterly Budget Setting</label>
    <pluralLabel>Partner MDF Quarterly Budget Settings</pluralLabel>
</CustomObject>

objects/Partner_Quarterly_Managed_Account_Count__c.object
<CustomObject>
    <fields>
        <fullName>Child_Accounts_End_of_Quarter_Count__c</fullName>
        <label>Child Accounts End of Quarter Count</label>
        <summaryForeignKey>Partner_Quarterly_Managed_Child_Account__c.Partner_Quarterly_Managed_Account_Count__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_of_Quarter_Date__c</fullName>
        <label>End of Quarter Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Account Count</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Account_Count</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Quarterly Managed Account Count</label>
    <nameField>
        <displayFormat>PQMAC-{0000000}</displayFormat>
        <label>Partner Quarterly Managed Account Count</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Account Count</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Quarterly_Managed_Child_Account__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Quarterly_Managed_Account_Count__c</fullName>
        <label>Partner Quarterly Managed Account Count</label>
        <referenceTo>Partner_Quarterly_Managed_Account_Count__c</referenceTo>
        <relationshipLabel>Partner Quarterly Managed Child Accounts</relationshipLabel>
        <relationshipName>Partner_Quarterly_Managed_Child_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Quarterly Managed Child Account</label>
    <nameField>
        <displayFormat>PQAMN-{0000000}</displayFormat>
        <label>Partner Quarterly Account Managed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Quarterly Managed Child Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MDFRequestStatusAndClaimFormController.cls
public without sharing class MDFRequestStatusAndClaimFormController {
	public List<Partner_Marketing_Development_Fund__c> pmdfStatusList {get; set;}
	public List<Partner_Marketing_Development_Fund__c> pmdfClaimList {get; set;}
	public Partner_Marketing_Development_Fund__c pmdfSelected {get; set;}
	public Partner_Quarterly_Managed_Account_Count__c pqmacLastQuarter {get; set;}
	public Partner_MDF_Quarterly_Budget_Setting__mdt pmdfQuarterlyBudgetSetting {get; set;}
	public Integer currentRequestTotal {get; set;}

	private static List<Partner_MDF_Quarterly_Budget_Setting__mdt> mdfQuarterlyBudgetSettingList = PartnerMDFQuarterlyBudgetSettingsHelper.retrieveMDFQuarterlyBudgetSettingsList();
	private static Period currentQuarterPeriod = [Select StartDate, EndDate From Period Where type = 'Quarter' and StartDate = THIS_FISCAL_QUARTER];
	private static Period lastQuarterDate = [Select StartDate, EndDate From Period Where type = 'Quarter' and StartDate = LAST_FISCAL_QUARTER];
	private static User currentUser = [select Id, UserRoleId, IsPortalEnabled, AccountId from User where Id =: UserInfo.getUserId()];

	private String clientAccountId;

	public MDFRequestStatusAndClaimFormController() {
		if(String.isNotBlank(currentUser.AccountId)){
			clientAccountId = currentUser.AccountId;
		}else if(String.isNotBlank(ApexPages.currentPage().getParameters().get('clientAccountId'))){
			clientAccountId = ApexPages.currentPage().getParameters().get('clientAccountId');
		}

		currentRequestTotal = 0;
		populateClaimList();
		populateStatusList();
		pmdfSelected = new Partner_Marketing_Development_Fund__c();
		pqmacLastQuarter = new Partner_Quarterly_Managed_Account_Count__c();
		pmdfQuarterlyBudgetSetting = new Partner_MDF_Quarterly_Budget_Setting__mdt();


		if(String.isNotBlank(ApexPages.currentPage().getParameters().get('initialSelectedId'))){
			pmdfSelected = [select Id, Name, MDF_Status__c, Claimed_By__c, Date_of_Activity__c, Total_Cost_of_Activity__c, Claim_Notes__c from Partner_Marketing_Development_Fund__c where Id =: ApexPages.currentPage().getParameters().get('initialSelectedId') and Partner_Account__c =: clientAccountId];
		}
		for(Partner_Quarterly_Managed_Account_Count__c pqmac : [select Id, End_of_Quarter_Date__c, Parent_Account__c, Child_Accounts_End_of_Quarter_Count__c, (select Id, Child_Account__c, Child_Account__r.Name, Child_Account__r.Phone, Child_Account__r.Order_Date__c, Child_Account__r.Live_Date__c, Child_Account__r.Status__c from Partner_Quarterly_Managed_Child_Accounts__r order by Child_Account__r.Name) from Partner_Quarterly_Managed_Account_Count__c where Parent_Account__c =: clientAccountId and End_of_Quarter_Date__c =: lastQuarterDate.EndDate]){
			pqmacLastQuarter = pqmac;
		}
		for(Partner_MDF_Quarterly_Budget_Setting__mdt pmdfqbs : mdfQuarterlyBudgetSettingList){
			if(pqmacLastQuarter.Child_Accounts_End_of_Quarter_Count__c >= pmdfqbs.Minimum_Managed_Accounts__c){
				pmdfQuarterlyBudgetSetting = pmdfqbs;
				break;
			}
		}

	}

	public void populateStatusList(){
		pmdfStatusList = new List<Partner_Marketing_Development_Fund__c>();

		for(Partner_Marketing_Development_Fund__c record : [select Id, Name, MDF_Status__c, Total_Cost_of_Activity__c, Requested_By__c, Type_of_Activity__c, What_is_the_goal_of_the_activity__c, When_will_the_activity_happen__c, MDF_Date_Submitted__c, Estimated_Cost_of_Activity__c, Other_Activity__c from Partner_Marketing_Development_Fund__c where MDF_Date_Submitted__c >=: currentQuarterPeriod.StartDate and Id not in :pmdfClaimList and Partner_Account__c =: clientAccountId order by MDF_Date_Submitted__c]){
			pmdfStatusList.add(record);
			if(record.MDF_Status__c != 'Request Denied' && record.MDF_Status__c != 'Request Expired'){
				currentRequestTotal += (record.Total_Cost_of_Activity__c != null) ? (Integer)record.Total_Cost_of_Activity__c : (Integer)record.Estimated_Cost_of_Activity__c;
			}
		}
	}

	public void populateClaimList(){
		pmdfClaimList = new List<Partner_Marketing_Development_Fund__c>();

		for(Partner_Marketing_Development_Fund__c record : [select Id, Name, MDF_Status__c, Total_Cost_of_Activity__c, Requested_By__c, Type_of_Activity__c, What_is_the_goal_of_the_activity__c, When_will_the_activity_happen__c, MDF_Date_Submitted__c, Estimated_Cost_of_Activity__c, Other_Activity__c from Partner_Marketing_Development_Fund__c where MDF_Status__c = 'Request Approved' and Partner_Account__c =: clientAccountId order by MDF_Date_Submitted__c]){
			pmdfClaimList.add(record);
			if(record.MDF_Status__c != 'Request Denied' && record.MDF_Status__c != 'Request Expired'){
				currentRequestTotal += (record.Total_Cost_of_Activity__c != null) ? (Integer)record.Total_Cost_of_Activity__c : (Integer)record.Estimated_Cost_of_Activity__c;
			}
		}
	}

	public void refreshData(){
		currentRequestTotal = 0;
		populateClaimList();
		populateStatusList();
		//pmdfSelected = new Partner_Marketing_Development_Fund__c();
	}

	public void selectedPMDF(){
		String pmdfSelectedId = ApexPages.currentPage().getParameters().get('pmdfSelectedId');

		if(String.isNotBlank(pmdfSelectedId)){
			pmdfSelected = [select Id, Name, MDF_Status__c, Claimed_By__c, Date_of_Activity__c, Total_Cost_of_Activity__c, Claim_Notes__c from Partner_Marketing_Development_Fund__c where Id =: pmdfSelectedId and Partner_Account__c =: clientAccountId];
		}else{
			pmdfSelected = new Partner_Marketing_Development_Fund__c();
		}
	
		if(String.isBlank(pmdfSelected.Claimed_By__c) && pmdfSelected.MDF_Status__c == 'Request Approved'){
			pmdfSelected.Claimed_By__c = UserInfo.getUserId();
		}
	}

	public void saveClaimForm(){
		try{
			pmdfSelected.MDF_Status__c = 'Claim Submitted';
			update pmdfSelected;
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Please make sure to attach all proof of activity to speed up the claim process!');
	        ApexPages.addMessage(myMsg);
        }catch(Exception E){

        }
	}

	public PageReference attachFile(){
		String retUrlValue = '/LighthouseDental/apex/PartnerMarketingDevelopmentFundsTab?selectedTab=name3&initialSelectedId=' + pmdfSelected.Id;
		PageReference pageRef = new PageReference('/LighthouseDental/p/attach/NoteAttach?pid=' + pmdfSelected.Id + '&parentname=' + pmdfSelected.Name);
		pageRef.getParameters().put('retURL', retUrlValue);
		pageRef.setRedirect(true);
		
		return pageRef;
	}
}