objects/Apex_Debug_Log__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Class__c</fullName>
        <label>Apex Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id / Data</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>A Custom Object to hold Logs of type Error and Information created from various other Apex Classes. Unlike the native Debug Logs, the data or log created here are mere records and hence they're persistent.

Please employ the Apex Class named "ApexDebugLog" to utilize this Custom Object to save or log Errors or Information. There are also methods to create logs even via JavaScript.</description>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL-{0}</displayFormat>
        <label>Apex Debug Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attempts_to_Contact__c</fullName>
        <label>Attempts to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Attempt</fullName>
                </value>
                <value>
                    <fullName>Second Attempt</fullName>
                </value>
                <value>
                    <fullName>Third Attempt</fullName>
                </value>
                <value>
                    <fullName>Unreachable</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIN_Action_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PIN Action Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organic_Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pin_Action_Taken__c</fullName>
        <description>Possible outcomes of a pin case being submitted</description>
        <label>Pin Action Taken</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Address Issue</fullName>
                </value>
                <value>
                    <fullName>Awaiting Ownership Transfer</fullName>
                </value>
                <value>
                    <fullName>Awaiting Resolution from Google</fullName>
                </value>
                <value>
                    <fullName>Client Cancelling</fullName>
                </value>
                <value>
                    <fullName>Client Proactively Sent Invite</fullName>
                </value>
                <value>
                    <fullName>Client Refuses Claim</fullName>
                </value>
                <value>
                    <fullName>Contacted client</fullName>
                </value>
                <value>
                    <fullName>Contacted Google</fullName>
                </value>
                <value>
                    <fullName>Maps Escalation</fullName>
                </value>
                <value>
                    <fullName>Multiple Listings</fullName>
                </value>
                <value>
                    <fullName>Not Actionable</fullName>
                </value>
                <value>
                    <fullName>Organic Opt Case Needed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pin Collected: Invalid</fullName>
                </value>
                <value>
                    <fullName>Pin Collected: Valid &amp; Invalid Combination</fullName>
                </value>
                <value>
                    <fullName>Pin Collection: Valid</fullName>
                </value>
                <value>
                    <fullName>Pin Resend Not Actionable</fullName>
                </value>
                <value>
                    <fullName>Pin Team Follow Up Needed</fullName>
                </value>
                <value>
                    <fullName>Question/Inquiry</fullName>
                </value>
                <value>
                    <fullName>Resent Pin</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AutoClosePANOrganicCases.cls
/****************************************************************************
  Company/ Author ....: R. Wang
  Date Created .......: 03-Oct-2018
  Last Modified By ...: R. Wang
  Last Modified Date .: 05-Oct-2018
  Description ........: Class contains invocable method to close PAN Organic Cases based on business criteria 
  and logic when met.
*****************************************************************************/

public class AutoClosePANOrganicCases
{
    @InvocableMethod
    public static void ClosePANOrganicCases(List<Id> micCaseIds)
    {
        try{
            
            system.debug('micCaseIds: ' + micCaseIds);
                
            Id panCaseRecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('PIN Action Needed').getRecordTypeId();
            Map<Id, Organic_Analysis__c> micCaseMap = new Map<Id, Organic_Analysis__c>();  
            List<Organic_Analysis__c> panCaseList = new List<Organic_Analysis__c>();
                               
            for(Organic_Analysis__c micCase : 
                    [SELECT Id,
                            Account_Name__c,
                            OwnerId
                      FROM Organic_Analysis__c
                      WHERE Id IN :micCaseIds 
                            ]){
                
                    // add data to Map
                    if(micCase.Id != NULL){                     
                        micCaseMap.put(micCase.Account_Name__c, micCase);
                    }                                     
             }
             
             System.Debug('*** MIC Case Map size ' + String.valueOf(micCaseMap.size()));
             
             if(micCaseMap.size() > 0){
                 for(Organic_Analysis__c panCase :
                    [SELECT Id,
                            Account_Name__c,
                            Attempts_to_Contact__c,
                            Pin_Action_Taken__c,
                            PIN_Action_Owner__c,
                            OwnerId,
                            IsClosed__c,
                            Status__c
                     FROM Organic_Analysis__c
                     WHERE Account_Name__c in :micCaseMap.keySet() AND
                           RecordTypeId = :panCaseRecordTypeId AND
                           IsClosed__c = false]){ 
                                                         
                            if(panCase.Id != NULL){
                                System.Debug('*** PAN Case Id: ' + panCase.Id);
                                panCase.Attempts_to_Contact__c = (String.IsBlank(panCase.Attempts_to_Contact__c) || Integer.valueOf(panCase.Attempts_to_Contact__c) < 1 ? '1' : panCase.Attempts_to_Contact__c);
                                panCase.Pin_Action_Taken__c = (String.IsBlank(panCase.Pin_Action_Taken__c) ? 'Not Actionable' : panCase.Pin_Action_Taken__c);
                                panCase.PIN_Action_Owner__c = (String.IsBlank(panCase.PIN_Action_Owner__c) ? micCaseMap.get(panCase.Account_Name__c).OwnerId : panCase.PIN_Action_Owner__c);
                                panCase.Status__c = 'Completed';
                                panCase.IsClosed__c = true;
                                panCase.OwnerId = micCaseMap.get(panCase.Account_Name__c).OwnerId;
                                panCaseList.add(panCase);
                            }                          
                     }
             }
             
             System.Debug('*** PAN Case List size ' + String.valueOf(panCaseList.size()));
             
             if(panCaseList.size() > 0){
                 update(panCaseList);
             }
            
        }
        catch(Exception e){
        
            System.Debug('An error occurred: ' + e.getMessage());
            Apex_Debug_Log__c dbLog = new Apex_Debug_Log__c();
            dbLog.Apex_Class__c = 'AutoClosePANOrganicCases';
            dbLog.Message__c = e.getMessage();
            dbLog.Method__c = 'ClosePANOrganicCases(Invocable)';
            dbLog.Record_Id__c = '';
            dbLog.Stack_Trace__c = e.getMessage();
            dbLog.Type__c = 'Error';
            
            insert dbLog;
        }
    }
}