objects/AutoUpdateFieldValueCustomSetting__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_SOQL_Criteria__c</fullName>
        <label>Additional SOQL Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field_Value_Update__c</fullName>
        <label>Field Value Update</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SOQL__c</fullName>
        <label>SOQL</label>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Currently only supports simple field value update.</description>
    <label>AutoUpdateFieldValueCustomSetting</label>
</CustomObject>

classes/AutoUpdateFieldValueBatchTest.cls
@isTest
private class AutoUpdateFieldValueBatchTest {
	
	@isTest static void AutoUpdateFieldValueScheduleAndBatchTest() {
		Account acct = new Account();
		acct.Name = 'Test Name';
		insert acct;

		AutoUpdateFieldValueCustomSetting__c newUpdateFieldValueCS = new AutoUpdateFieldValueCustomSetting__c();
		newUpdateFieldValueCS.Name = 'Account Name Change';
		newUpdateFieldValueCS.SOQL__c = 'select Id from';
		newUpdateFieldValueCS.Additional_SOQL_Criteria__c = 'Account';
		newUpdateFieldValueCS.Active__c = true;
		newUpdateFieldValueCS.Field_Value_Update__c = 'Name:TestName';
		insert newUpdateFieldValueCS;

		Test.startTest();
		AutoUpdateFieldValueSchedule sched = new AutoUpdateFieldValueSchedule();
		sched.execute(null);
		Test.stopTest();
		System.assertEquals([select Name from Account where Id = :acct.Id].Name, 'TestName');
	}
	
}