objects/Batch_Automation_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Additional_SOQL_Criteria__c</fullName>
        <label>Additional SOQL Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Criteria__c</fullName>
        <label>SOQL Criteria</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Batch Automation Settings</label>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDCToCTSAsynchRequest__c.object
<CustomObject>
    <description>Stores DE-normalized CTS Ticket data to be executed by BULK job on a schedule to create CTS Tickets</description>
    <label>SFDCToCTSAsynchRequest</label>
    <nameField>
        <displayFormat>AR-{000000000}</displayFormat>
        <label>Asynch Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDCToCTSAsynchRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExecuteSFDCToCTSAsynchRequestBatch.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 02-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 02-Jan-2019
  Description ........: Batchable class to create CTS Tickets using the SFDC Sync Service to CTS ESB Service (API). 
  
  Dependencies: 
  - Custom Setting | Batch Automation Settings
  
*****************************************************************************/
public class ExecuteSFDCToCTSAsynchRequestBatch implements Database.Batchable<sObject>, Database.AllowsCallouts 
{
    private static Batch_Automation_Settings__c batchSetting;
    String objName;

    public ExecuteSFDCToCTSAsynchRequestBatch(string objectName) {
      
        objName = objectName;
        
        switch on objectName {
        
            when 'Case' {
                batchSetting = Batch_Automation_Settings__c.getValues('Async Request Cases');
            }
            when 'Customer_Surveys__c' {
                batchSetting = Batch_Automation_Settings__c.getValues('Async Request Customer Surveys');
            }
            when 'Organic_Analysis__c' {
                batchSetting = Batch_Automation_Settings__c.getValues('Async Request Organic Cases');
            }
            when 'Quality_Case__c' {
                batchSetting = Batch_Automation_Settings__c.getValues('Async Request Quality Cases');
            }
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
    
        String query = batchSetting.SOQL_Criteria__c;
        
        if(String.isNotBlank(batchSetting.Additional_SOQL_Criteria__c)){
            query += ' ' + batchSetting.Additional_SOQL_Criteria__c;
        }
        
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
    
        for(SFDCToCTSAsynchRequest__c ar :  (List<SFDCToCTSAsynchRequest__c>) scope){
        
            CTSSyncService.ProcessSFDCToCTSAsynchRequest(objName, scope);
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
}