objects/Best_Practice_Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Error Free</fullName>
                </value>
                <value>
                    <fullName>Error Found</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to evaluate best practices for Analysts in regards to New Client Setups and Optimizations.</description>
    <label>Best Practice Evaluation</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Evaluation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Best Practice Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CTS_Salesforce_Object_Ref__mdt.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Summary/ description for the Salesforce object record</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Salesforce Object API Name</description>
        <inlineHelpText>Salesforce Object API Name</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Salesforce objects referenced and used within the CTS Integration</description>
    <label>CTS Salesforce Object Ref</label>
    <pluralLabel>CTS Salesforce Object Refs</pluralLabel>
</CustomObject>

objects/CTSObjectTriggerMap__mdt.object
<CustomObject>
    <fields>
        <fullName>CTSAssignedToLoginName__c</fullName>
        <description>Login Name used to reference a CTS User</description>
        <inlineHelpText>Login Name used to reference a CTS User</inlineHelpText>
        <label>CTS Assigned To Login Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTSEmailAddress__c</fullName>
        <description>CTS Email Address referenced for CTS Ticket creation (if Email Integration Type)</description>
        <inlineHelpText>CTS Email Address referenced for CTS Ticket creation (if Email Integration Type)</inlineHelpText>
        <label>CTS Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CTSNoteType__c</fullName>
        <description>CTS Note Type referenced for CTS Ticket creation (if API Integration Type)</description>
        <inlineHelpText>CTS Note Type referenced for CTS Ticket creation (if API Integration Type)</inlineHelpText>
        <label>CTS Note Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Note</fullName>
                    <default>true</default>
                    <label>Internal Note</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Any description, comments or notes about the mapping record</description>
        <inlineHelpText>Any description, comments or notes about the mapping record</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DetailsTemplateName__c</fullName>
        <description>Salesforce Email Template Name corresponding to the Details Template Id</description>
        <inlineHelpText>Salesforce Email Template Name corresponding to the Details Template Id</inlineHelpText>
        <label>Details Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationType__c</fullName>
        <description>Integration Type referenced for what process is used to create the CTS Ticket (Email or API)</description>
        <inlineHelpText>Integration Type referenced for what process is used to create the CTS Ticket (Email or API)</inlineHelpText>
        <label>Integration Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                    <default>true</default>
                    <label>API</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag/ indicator signifying if the mapping record is Active; integration code references only look for Active records as criteria</description>
        <inlineHelpText>Flag/ indicator signifying if the mapping record is Active</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCreateCTSNote__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag/ Indicator signifying if an associated CTS Ticket Note should be created when creating the CTS Ticket (API Integration Type only)</description>
        <inlineHelpText>Flag/ Indicator signifying if an associated CTS Ticket Note should be created when creating the CTS Ticket (API Integration Type only)</inlineHelpText>
        <label>Is Create CTS Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NoteDetailsTemplateName__c</fullName>
        <description>Salesforce Email Template Name corresponding to the Note Details Template Id</description>
        <inlineHelpText>Salesforce Email Template Name corresponding to the Note Details Template Id</inlineHelpText>
        <label>Note Details Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Filter__c</fullName>
        <description>Additional Filter placeholder</description>
        <inlineHelpText>Additional Filter placeholder</inlineHelpText>
        <label>Additional Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAutoClose__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag/ Indicator signifying if the Salesforce record should be auto-closed</description>
        <inlineHelpText>Flag/ Indicator signifying if the Salesforce record should be auto-closed</inlineHelpText>
        <label>Is Auto Close</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsExcludeWBN__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag/ indicator signifying that WBN records will be excluded from the specified mapping record processing</description>
        <inlineHelpText>Flag/ indicator signifying that WBN records will be excluded from the specified mapping record processing</inlineHelpText>
        <label>Is Exclude WBN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CTSAPIIdentifier__c</fullName>
        <description>CTS API Identifier referenced for CTS Ticket creation (if API Integration Type)</description>
        <inlineHelpText>CTS API Identifier referenced for CTS Ticket creation (if API Integration Type)</inlineHelpText>
        <label>CTS API Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object Reference Metadata Type Lookup Relationship</description>
        <inlineHelpText>Object Reference Metadata Type Lookup Relationship</inlineHelpText>
        <label>Object Reference</label>
        <referenceTo>CTS_Salesforce_Object_Ref__mdt</referenceTo>
        <relationshipLabel>CTSObjectTriggerMaps</relationshipLabel>
        <relationshipName>CTSObjectTriggerMaps_SFDCObjectRef</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>CaseOrigin__c</fullName>
        <description>Salesforce Case Origin referenced for CTS Ticket creation (if applicable)</description>
        <inlineHelpText>Salesforce Case Origin referenced for CTS Ticket creation (if applicable)</inlineHelpText>
        <label>Case Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Circuit Breaker</fullName>
                </value>
                <value>
                    <fullName>customercare@yodle.com</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                    <default>true</default>
                    <label>Internal</label>
                </value>
                <value>
                    <fullName>New Client</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>YodleGoldService@yodle.com</fullName>
                </value>
                <value>
                    <fullName>Touch Plan 1</fullName>
                </value>
                <value>
                    <fullName>Touch Plan 2</fullName>
                </value>
                <value>
                    <fullName>Touch Plan 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseReason__c</fullName>
        <description>Salesforce Case Reason referenced for CTS Ticket creation (if applicable)</description>
        <inlineHelpText>Salesforce Case Reason referenced for CTS Ticket creation (if applicable)</inlineHelpText>
        <label>Case Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Adoption Call</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Charge Failure</fullName>
                </value>
                <value>
                    <fullName>Client Communication</fullName>
                </value>
                <value>
                    <fullName>Client Escalation</fullName>
                </value>
                <value>
                    <fullName>CSC</fullName>
                </value>
                <value>
                    <fullName>CS Touch Plan</fullName>
                </value>
                <value>
                    <fullName>Maps Verification</fullName>
                </value>
                <value>
                    <fullName>MLS</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Proactive Touch</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>New Client Setup</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Technical Issues</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Cancel Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used as reference to determine how a CTS Ticket should be created, what data elements should be included and the source of the ticket data from Salesforce data</description>
    <label>CTSObjectTriggerMap</label>
    <pluralLabel>CTSObjectTriggerMaps</pluralLabel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSSyncService.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 16-Nov-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 16-Nov-2018
  Description ........: CTS Sync Service class provides the mapping and data elements to send data to CTS from Salesforce
  to create tickets and reference the ticket back to the SFDC object
*****************************************************************************/
public without sharing class CTSSyncService{

    // will return object triggered by scheduled job; not void
    public static void GetCTSTicket(string SFDCObjectName, string SFDCObjectInstance, string SFDCObjectId, string RoutingTableObjectInstance){
 
        Map<String, CTSObjectTriggerMap__mdt> routeObjMap = new Map<String, CTSObjectTriggerMap__mdt>();
        Map<Id, EmailTemplate> emailTemplatesMap = new Map<Id, EmailTemplate>();
        Id ctsEmailTemplateFolderId = [SELECT Id FROM Folder WHERE Name = 'CTS Templates'].Id;
        
        for(CTSObjectTriggerMap__mdt om :
            [SELECT Additional_Filter__c,
                    CaseOrigin__c,
                    CaseReason__c,
                    CTSAPIIdentifier__c,
                    CTSAssignedToLoginName__c,
                    CTSEmailAddress__c,
                    CTSNoteType__c,
                    Description__c,
                    DetailsTemplateName__c,
                    IntegrationType__c,
                    IsActive__c,
                    IsAutoClose__c,
                    IsCreateCTSNote__c,
                    IsExcludeWBN__c,
                    NoteDetailsTemplateName__c,
                    Object__c,
                    Object__r.Object_API_Name__c,
                    ProductType__c,
                    RecordTypeName__c,
                    MasterLabel
               FROM CTSObjectTriggerMap__mdt 
              WHERE MasterLabel = :RoutingTableObjectInstance LIMIT 1]){
        
            routeObjMap.put(om.MasterLabel, om);
        }
              
        if(routeObjMap.size() > 0){
        
            for(EmailTemplate et :
                [SELECT Id,
                        DeveloperName,
                        FolderId
                   FROM EmailTemplate
                  WHERE FolderId = :ctsEmailTemplateFolderId]){
            
                emailTemplatesMap.put(et.Id, et);
            }
        
            for(CTSObjectTriggerMap__mdt rom : routeObjMap.values()){
                for(EmailTemplate etm : emailTemplatesMap.values()){
                
                    if(routeObjMap.get(RoutingTableObjectInstance).IntegrationType__c == 'Email'){
                        
                        
                        
                    }
                    else{
                    
                        // API
                    }
                
                }
            }
        }
    }
    
    public static CTS_SFDC_Object_Base GetSFDCObject(string objectName, Id objectId, CTSObjectTriggerMap__mdt mappingInstance, string CTSIntegrationType)    
    {          
    
       CTS_SFDC_Object_Base baseObject;
       
       switch on objectName {
           when 'Case' {
               baseObject = new CTSSFDCCase(objectId, objectName, mappingInstance);               
           }
           when 'Organic_Analysis__c', 'Quality_Case__c', 'Best_Practice_Evaluation__c', 'Customer_Surveys__c', 'Lighthouse_Worksheets__c' {
               baseObject = new CTS_SFDC_Object_Base(objectId, objectName, mappingInstance);
           }                     
           when else {
               system.debug('Not a valid object name: ' + objectName);                
           }
       }
                     
       return baseObject;

    }     
    
    
    public static CTSObjectTriggerMap__mdt GetRoutingTableObject(string objName, string objRecordType, string caseReason, string caseOrigin, string productType)
    {
        CTSObjectTriggerMap__mdt routingObj;
        
        List<SObject> routeMappings = [SELECT Id, 
                        Additional_Filter__c,
                        CaseOrigin__c,
                        CaseReason__c,
                        CTSAPIIdentifier__c,
                        CTSAssignedToLoginName__c,
                        CTSEmailAddress__c,
                        CTSNoteType__c,
                        Description__c,
                        DetailsTemplateName__c,
                        IntegrationType__c,
                        IsActive__c,
                        IsAutoClose__c,
                        IsCreateCTSNote__c,
                        IsExcludeWBN__c,
                        NoteDetailsTemplateName__c,
                        Object__c,
                        Object__r.Object_API_Name__c,
                        ProductType__c,
                        RecordTypeName__c,
                        MasterLabel
                   FROM CTSObjectTriggerMap__mdt];
         
         /*0  Object Name
         1 Object Record Type
         2. Case Reason
         3. Case Origin
         4. Product Type*/
                
         Map<String, String> fieldMap = new Map<String, String>();
         fieldMap.put('Object__c', objName);
         fieldMap.put('RecordTypeName__c', objRecordType);
         fieldMap.put('CaseReason__c', caseReason);
         fieldMap.put('CaseOrigin__c', caseOrigin);
         fieldMap.put('ProductType__c', productType);
         
         //A. 0 & 1 & 2 & 3 & 4 
         routingObj = FindRoutingObject(routeMappings, fieldMap);
         if (routingObj != null)
             return routingObj;
          
         //B. 0 & 1 & 2 & 4    
         fieldMap.remove('CaseOrigin__c');         
         routingObj = FindRoutingObject(routeMappings, fieldMap);
         if (routingObj != null)
             return routingObj;
             
         //C. 0 & 1 & 3 & 4
         fieldMap.remove('CaseReason__c');
         fieldMap.put('CaseReason__c', caseReason); 
         routingObj = FindRoutingObject(routeMappings, fieldMap);
         if (routingObj != null)
             return routingObj;  
             
         //D. 0 & 1 & 4
         fieldMap.remove('CaseOrigin__c');
         fieldMap.remove('CaseReason__c');
         routingObj = FindRoutingObject(routeMappings, fieldMap);
         if (routingObj != null)
             return routingObj;
             
         //E. 0 & 1  
         fieldMap.remove('ProductType__c');
         routingObj = FindRoutingObject(routeMappings, fieldMap);
         if (routingObj != null)
             return routingObj;
             
         //F. If none of the criteria above are met we will route to a catch all queue , by searching for "Object Record Type = "CATCHALL"
         for(SObject obj : routeMappings) {
             if (obj.get('RecordTypeName__c') == 'CATCHALL')
             {
                 return (CTSObjectTriggerMap__mdt)obj; 
             }
                 
         }
         
         return routingObj;

                           
    }
   
    private static CTSObjectTriggerMap__mdt FindRoutingObject(List<sObject> routingTableObjs, Map<string, string> fieldMap)
    {                
        for(SObject obj : routingTableObjs) {
            Boolean matched = true;
            for(string key : fieldMap.keySet()) {
               string inputValue = fieldMap.get(key);
               string routingObjFieldValue = (String)obj.get(key);
               if (inputValue != routingObjFieldValue)
               {
                   matched = false;
                   break;
               }
            }
            if (matched)
                return (CTSObjectTriggerMap__mdt)obj;        
        } 
        
        return null;
    }   
}