objects/Call_Quality_Concern__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Call Quality Concerns</relationshipLabel>
        <relationshipName>Call_Quality_Concerns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>To submit call quality concerns from clients to Marketing Ops team to review for potential paused distribution outlets.</description>
    <label>Call Quality Concern</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Call Quality Concern ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Quality Concerns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case_Master_Record_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag/ indicator signifying the active status of the record</description>
        <inlineHelpText>Flag/ indicator signifying the active status of the record; Apex code only looks for active records</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>The Master Record Type Name on the Case object</description>
        <inlineHelpText>Case object Master Record Type Name</inlineHelpText>
        <label>Record Type Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Case Master record types as decided by the business</description>
    <label>Case Master Record Type</label>
    <pluralLabel>Case Master Record Types</pluralLabel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Case_URL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>if(
 ISPICKVAL( Status__c , "Closed") ,
true,
false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Quality_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                    <isActive>false</isActive>
                    <label>Delete Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseWorkCompleted.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 19-Dec-2017
  Last Modified By ...: F. Poirier
  Last Modified Date .: 12-Sept-2018
  Description ........: Class contains invocable method to update status and work completed date of Parent Case 
  when all associated child Cases are closed.
*****************************************************************************/
public class CaseWorkCompleted
{
    @InvocableMethod
    public static void UpdateParentCaseWorkCompleted(List<Id> parentIds)
    {
        try{
        
            if(parentIds.size() > 0){
            
                Set<Id> parentCaseIdsSet = new Set<Id>();
                Set<String> parentRecordTypes = new Set<String>();
                Set<String> statusExceptions = new Set<String>{'Awaiting Customer Response','Bug Reported'};
                Boolean isParentCaseType = false;
                List<Case> dmlCases = new List<Case>();
                List<Case> allChildCases = new List<Case>();
                List<Organic_Analysis__c> allChildOrganicCases = new List<Organic_Analysis__c>();
                List<Call_Quality_Concern__c> allChildCallQualityConcerns = new List<Call_Quality_Concern__c>();
                List<Quality_Case__c> allChildQualityCases = new List<Quality_Case__c>();
                Integer allChildOrganicCasesCnt = 0;
                Integer allChildCallQltyConcernCnt = 0;
                Integer allChildQualityCasesCnt = 0;
                Integer allChildDefaultCasesCnt = 0;
                Integer allChildTotal = 0;
                Integer closedChildOrganicCasesCnt = 0;
                Integer closedChildCallQltyConcernCnt = 0;
                Integer closedChildQualityCasesCnt = 0;
                Integer closedChildDefaultCasesCnt = 0;
                Integer allClosedChildTotal = 0;
                
                // get list of Case Master Record Type Names
                for(Case_Master_Record_Type__mdt rt :
                    [SELECT Record_Type_Name__c
                       FROM Case_Master_Record_Type__mdt
                      WHERE Is_Active__c = true]){
                
                    if(rt.Record_Type_Name__c != null){
                        parentRecordTypes.add(rt.Record_Type_Name__c);
                    }
                }
                
               parentCaseIdsSet.addAll(parentIds);

                if(parentCaseIdsSet.size() > 0){
                
                    if(parentCaseIdsSet.size() > 0){

                        //Francois Poirier Refactor September 11 2018
                        // Get List of all child cases needed
                        allChildCases =
                        [
                                SELECT  Id,
                                        ParentId,
                                        Status,
                                        IsClosed
                                FROM    Case
                                WHERE   ParentId IN :parentCaseIdsSet
                        ];

                        for(Case c : allChildCases){

                            if(c.Status != 'Delete Case'){
                                allChildDefaultCasesCnt ++;
                                if(c.IsClosed){
                                    closedChildDefaultCasesCnt++;
                                }
                            }

                        }

                        system.debug('allChidlDefaultCasesCbt ===> ' + allChildDefaultCasesCnt);
                        system.debug('closedChildDefaultCasesCnt ===> ' + closedChildDefaultCasesCnt);

                        allChildOrganicCases =
                        [
                                SELECT  Id,
                                        IsClosed__c
                                FROM    Organic_Analysis__c
                                WHERE   Case_URL__c IN :parentCaseIdsSet
                        ];

                        allChildOrganicCasesCnt = allChildOrganicCases.size();

                        for(Organic_Analysis__c o : allChildOrganicCases){
                            if(o.IsClosed__c){
                                closedChildOrganicCasesCnt++;
                            }
                        }

                        system.debug('allChildOrganicCasesCnt ===> ' + allChildOrganicCasesCnt);
                        system.debug('closedChildOrganicCasesCnt ===> ' + closedChildOrganicCasesCnt);
                        allChildCallQualityConcerns =
                        [
                                SELECT  Id,
                                        Status__c
                                FROM Call_Quality_Concern__c
                                WHERE Case__c IN :parentCaseIdsSet

                        ];

                        allChildCallQltyConcernCnt = allChildCallQualityConcerns.size();

                        for(Call_Quality_Concern__c call : allChildCallQualityConcerns){
                            if(call.Status__c == 'Closed'){
                                closedChildCallQltyConcernCnt++;
                            }
                        }

                        allChildQualityCases = [
                                SELECT  Id,
                                        IsClosed__c
                                FROM Quality_Case__c
                                WHERE Parent_Case__c IN :parentCaseIdsSet

                        ];

                        allChildQualityCasesCnt = allChildQualityCases.size();

                        for(Quality_Case__c q : allChildQualityCases){
                            if(q.IsClosed__c){
                                closedChildQualityCasesCnt++;
                            }
                        }
                        
                        // total of all child Cases
                        allChildTotal = allChildDefaultCasesCnt + allChildOrganicCasesCnt + allChildCallQltyConcernCnt + allChildQualityCasesCnt;
                    
                        // total of all child Cases Closed
                        allClosedChildTotal = closedChildDefaultCasesCnt + closedChildOrganicCasesCnt + closedChildCallQltyConcernCnt + closedChildQualityCasesCnt;
                        
                        System.Debug('Total Child Cases: ' + String.valueOf(allChildTotal));
                        System.Debug('Total Child Cases Closed: ' + String.valueOf(allClosedChildTotal));
                        
                        // Check totals for match
                        if(allChildTotal == allClosedChildTotal && allClosedChildTotal > 0){
                            
                            // Update Parent Cases
                            for(Case cu :
                                [SELECT Id,
                                        Status,
                                        Date_Work_Completed__c
                                   FROM Case
                                  WHERE Id IN :parentCaseIdsSet AND
                                        IsClosed = false AND
                                        RecordType.Name IN :parentRecordTypes]){
                            
                                if(cu.Id != null && !statusExceptions.contains(cu.Status)){
                                
                                    cu.Status = 'All Work Completed – Contact Client';
                                    cu.Date_Work_Completed__c = System.Now();
                                    
                                    // add Case to update List
                                    dmlCases.add(cu);
                                }
                            }
                            
                            if(dmlCases.size() > 0){
                                update dmlCases;
                            }
                        }
                    }
                }
            }
        }
        catch(Exception e){
            System.Debug('An error occurred: ' + e.getMessage());
        }
    }
}