objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cancellation Requests</relationshipLabel>
        <relationshipName>Cancellation_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RetentionSLAEvaluationBatchTest.cls
@isTest
private class RetentionSLAEvaluationBatchTest {
	
	@isTest static void test_RetentionSLAEvaluationBatch() {
		Account newAccount = new Account();
		newAccount.Name = 'Tset Account';
		insert newAccount;

		Cancellation_Request__c newCancellationRequest = new Cancellation_Request__c();
		newCancellationRequest.Account_Name__c = newAccount.Id;
		insert newCancellationRequest;

		Test.startTest();
		RetentionSLAEvaluationSchedule scheduleExecute = new RetentionSLAEvaluationSchedule();
		scheduleExecute.execute(null);
		Test.stopTest();
	}
	
}