objects/Cancellation_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_in_Save_Mode__c</fullName>
        <label>Product in Cancel Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Web Only</fullName>
                </value>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>Ads</fullName>
                </value>
                <value>
                    <fullName>Leads By Web</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>TORCHx</fullName>
                </value>
                <value>
                    <fullName>Ads &amp; Organic Only</fullName>
                </value>
                <value>
                    <fullName>Already Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <inlineHelpText>Please only use for final notes regarding cancellation outcome or notes regarding duplicate retention cases. All other notes should be put in comment section below</inlineHelpText>
        <label>Additional Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>After_Call_Work_Complete__c</fullName>
        <label>After Call Work Complete</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agent_Confirmation__c</fullName>
        <inlineHelpText>Initial to verify that you have completed after call work, verified changes/status in YL, sent confirmation to client</inlineHelpText>
        <label>Agent Confirmation</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attempts_to_Contact__c</fullName>
        <label>Attempts to Contact</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Code__c</fullName>
        <description>5/2</description>
        <label>First Cancel Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AA-CONFLICTING_PAID_SEARCH_CAMPAIGN</fullName>
                </value>
                <value>
                    <fullName>AA-NO_ECONTRACT</fullName>
                </value>
                <value>
                    <fullName>AA-NO_PHYSICAL_ADDRESS</fullName>
                </value>
                <value>
                    <fullName>AA-NO_PSG_SELECTED/IRRELEVANT</fullName>
                </value>
                <value>
                    <fullName>AA-OTHER</fullName>
                </value>
                <value>
                    <fullName>AA-PHYSICAL_ADDRESS_TOO_FAR_AWAY</fullName>
                </value>
                <value>
                    <fullName>AA-POPULATION_TOO_SMALL</fullName>
                </value>
                <value>
                    <fullName>CI-CUTTING_ADVERTISING_BUDGET</fullName>
                </value>
                <value>
                    <fullName>CI-LIVE_UNDER_DIFFERENT_ACCOUNT_ID</fullName>
                </value>
                <value>
                    <fullName>CI-LOST_TO_COMPETITOR</fullName>
                </value>
                <value>
                    <fullName>CI-OUT_OF_BUSINESS</fullName>
                </value>
                <value>
                    <fullName>CI-SEASONAL_BUSINESS</fullName>
                </value>
                <value>
                    <fullName>CI-UNAUTHORIZED_PURCHASE</fullName>
                </value>
                <value>
                    <fullName>CI-UNRESPONSIVE/NO_CONTRACT</fullName>
                </value>
                <value>
                    <fullName>F-CONTACTS FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>F-DISLIKES_WEBSITE</fullName>
                </value>
                <value>
                    <fullName>F-EMAIL FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>F-EMAIL FEATURE NOT WORKING</fullName>
                </value>
                <value>
                    <fullName>F-ESSENTIALS TOO MUCH WORK</fullName>
                </value>
                <value>
                    <fullName>F-OFFERS FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>F-PHOTOS FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>F-REVIEWS FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>F-SOCIAL FEATURE IS LIMITED</fullName>
                </value>
                <value>
                    <fullName>LT-CUSTOMER_SERVICE_ISSUE</fullName>
                </value>
                <value>
                    <fullName>LT-GENERAL_SETUP_ERRORS</fullName>
                </value>
                <value>
                    <fullName>LT-NEGATIVE_REVIEWS</fullName>
                </value>
                <value>
                    <fullName>LT-TECHNICAL_ISSUES</fullName>
                </value>
                <value>
                    <fullName>P-POOR_LEAD_QUALITY</fullName>
                </value>
                <value>
                    <fullName>P-POOR_LEAD_VOLUME</fullName>
                </value>
                <value>
                    <fullName>P-POOR_RANKING</fullName>
                </value>
                <value>
                    <fullName>Customer Service Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>.</description>
        <label>Cancel Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Save Mode</fullName>
                </value>
                <value>
                    <fullName>Churned</fullName>
                </value>
                <value>
                    <fullName>Saved with No Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Hard Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Soft Concessions</fullName>
                </value>
                <value>
                    <fullName>Saved with Upsell</fullName>
                </value>
                <value>
                    <fullName>Saved By Sales</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Retention Case</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Standard</fullName>
                </value>
                <value>
                    <fullName>Saved - Bailout Pricing - Custom</fullName>
                </value>
                <value>
                    <fullName>Saved with Discount</fullName>
                </value>
                <value>
                    <fullName>Saved with OBC Package</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH Only</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack</fullName>
                </value>
                <value>
                    <fullName>Downsold to LH+ProPack+Mobile Manager</fullName>
                </value>
                <value>
                    <fullName>Ad Station Credit</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Saved With Free Time</fullName>
                </value>
                <value>
                    <fullName>Saved with Winback</fullName>
                </value>
                <value>
                    <fullName>Dollar Sync Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refund2__c</fullName>
        <label>Refund</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Offered and Accepted</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Not Requested</fullName>
                </value>
                <value>
                    <fullName>Requested and Approved</fullName>
                </value>
                <value>
                    <fullName>Requested and Denied</fullName>
                </value>
                <value>
                    <fullName>Requested, Countered and Accepted</fullName>
                </value>
                <value>
                    <fullName>Requested, Countered and Denied</fullName>
                </value>
                <value>
                    <fullName>Offered and Rejected</fullName>
                </value>
                <value>
                    <fullName>Did Not Offer</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Send_Confirmation_to_Client__c</fullName>
        <label>Send Confirmation to Client</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Web_Only2__c</fullName>
        <label>Web Only</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Did Not Offer</fullName>
                </value>
                <value>
                    <fullName>Offered and Rejected</fullName>
                </value>
                <value>
                    <fullName>Offered and Accepted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cancellation Form</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cancellation Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static Cancellation_Request__c setOutcomeToSavedWithNoConcessions(Cancellation_Request__c cancelRequest){
        cancelRequest.Outcome__c = 'Saved with No Concessions';
        cancelRequest.Web_Only2__c = 'Did Not Offer';
        cancelRequest.Refund2__c = 'Did Not Offer';
        cancelRequest.Account_in_Save_Mode__c = 'Web Only';
        cancelRequest.Additional_Notes__c = 'TestNotes';
        cancelRequest.After_Call_Work_Complete__c = 'Yes';
        cancelRequest.Agent_Confirmation__c = 'sadf';
        cancelRequest.Send_Confirmation_to_Client__c = 'Yes';
        cancelRequest.Attempts_to_Contact__c = '1';
        cancelRequest.Cancel_Code__c = 'Customer Service Issue';
        cancelRequest.First_Cancel_Code_Details__c = 'St. Lucia concerns';
        cancelRequest.First_Cancel_Code_Notes__c = 'Tadsf dsfa';
        cancelRequest.Got_client_into_dashboard__c = 'Yes reviewed dashboard';
        cancelRequest.Escalation_Potential__c = 'Yes';
        cancelRequest.Current_Monthly_Revenue__c = 234232;
        cancelRequest.Initial_Product__c = 'Leads By Web';
        cancelRequest.Future_Product__c = 'Leads By Web';
        cancelRequest.Retention_Consultant__c = UserInfo.getUserId();
        cancelRequest.Verify_Product_Changes_Status_in_YL__c = 'Yes';
        cancelRequest.Hit_Lead_Range__c = 'Yes';
        cancelRequest.Last_TP_Completed__c = 'Churned in first month';

        return cancelRequest;
    }
    
    
        static testMethod void test_TextbrokerSchedulableCheckReadyOrders() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          TextbrokerSchedulableCheckReadyOrders obj = new TextbrokerSchedulableCheckReadyOrders();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    
    static testMethod void test_TextbrokerSchedulableConfirmAccepted() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          TextbrokerSchedulableConfirmAccepted obj = new TextbrokerSchedulableConfirmAccepted();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    static testMethod void test_TextbrokerSchedulableExportOrders () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          TextbrokerSchedulableExportOrders  obj = new TextbrokerSchedulableExportOrders ();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    static testMethod void test_TextbrokerSchedulableRequestRevisions () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          TextbrokerSchedulableRequestRevisions  obj = new TextbrokerSchedulableRequestRevisions ();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        } 
    static testMethod void test_AutoCreateCaseEntitlement () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          AutoCreateCaseEntitlement  obj = new AutoCreateCaseEntitlement ();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        } 
    
    
     static testMethod void test_CaseCtl_MultiRequest () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CaseCtl_MultiRequest  obj = new CaseCtl_MultiRequest ();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        } 
     static testMethod void test_CaseCtl_ResultPage () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CaseCtl_ResultPage  obj = new CaseCtl_ResultPage();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        } 
    
    
    static testMethod void test_CaseMilestoneUtils () 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CaseMilestoneUtils  obj = new CaseMilestoneUtils();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
    
     static testMethod void test_clsS2SShareHelper() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          clsS2SShareHelper  obj = new clsS2SShareHelper();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    static testMethod void test_CompleteResolutionCaseMilestone() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CompleteResolutionCaseMilestone  obj = new CompleteResolutionCaseMilestone();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
    
        static testMethod void test_LaunchSalesWizardController() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          LaunchSalesWizardController  obj = new LaunchSalesWizardController();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
        static testMethod void test_OrganicCaseATVUpdates() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          OrganicCaseATVUpdates  obj = new OrganicCaseATVUpdates();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    static testMethod void test_wbnNationalNCSCreateNotificationSchedule() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          wbnNationalNCSCreateNotificationSchedule  obj = new wbnNationalNCSCreateNotificationSchedule();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
        
        static testMethod void test_wbnNationalNCSStatusNotificationBatch() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          wbnNationalNCSStatusNotificationBatch  obj = new wbnNationalNCSStatusNotificationBatch();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
    static testMethod void test_wbnNationalNCSStatusNotificationSchedule() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          wbnNationalNCSStatusNotificationSchedule  obj = new wbnNationalNCSStatusNotificationSchedule();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }
    
    
      
    
        
        static testMethod void test_SandboxPostCopyCleanUpClass() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          SandboxPostCopyCleanUpClass  obj = new SandboxPostCopyCleanUpClass();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    
    static testMethod void test_SendCancellationDMCNotifcation() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          SendCancellationDMCNotifcation  obj = new SendCancellationDMCNotifcation();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
     
    
    
         static testMethod void test_SL_CaseTriggerHandler() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          SL_CaseTriggerHandler  obj = new SL_CaseTriggerHandler();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        } 
    
    
}