objects/CPP_Lead_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Child_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Child Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CPP_Leads_Registration1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gold_Nugget_Client_ID__c</fullName>
        <label>Gold Nugget Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Registration</label>
    <nameField>
        <label>Lead Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Registration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPPLeadRegistrationChildAccountLinkBatch.cls
public class CPPLeadRegistrationChildAccountLinkBatch implements Database.Batchable<sObject> {
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([select Id from CPP_Lead_Registration__c where Gold_Nugget_Client_ID__c != '' and Child_Account__c = '']);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		update scope;
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}