objects/CPP_Lead_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Master Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>CPP_Leads_Registration</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Lead Registration</relationshipLabel>
        <relationshipName>Lead_Registration</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Lead Registration</label>
    <nameField>
        <label>Lead Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Registration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateCPPLeadRegistrationController.cls
public with sharing class CreateCPPLeadRegistrationController {
	public CPP_Lead_Registration__c registerLead {get; set;}
	private ApexPages.StandardController sController;

	public CreateCPPLeadRegistrationController(ApexPages.StandardController stdController) {
		sController = stdController;
		registerLead = (CPP_Lead_Registration__c)stdController.getRecord();
		User currentUser = [select Id, AccountId from User where Id = :UserInfo.getUserId()];
		if(String.isNotBlank(currentUser.AccountId)){
			registerLead.Partner_Account__c = currentUser.AccountId;
			registerLead.Submitted_By__c = [select ContactId from User where Id =: UserInfo.getUserId()].ContactId;
		}
		registerLead.Date_Submitted__c = Date.today();
	}

	public PageReference saveAndNew(){
		try{
			sController.save();
			Schema.DescribeSObjectResult describeResult = sController.getRecord().getSObjectType().getDescribe();

			PageReference pr = new PageReference('/' + describeResult.getKeyPrefix() + '/e?');  
            // Don't redirect with the viewstate of the current record.  
            pr.setRedirect(true);  
            return pr;
		}catch(Exception E){
			ApexPages.addMessages(e);
			return null;
		}
	}
}