objects/CTS_Integration_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>BatchSize__c</fullName>
        <description>Used to determine the batch size dynamically through the CTS Sync Service</description>
        <inlineHelpText>Used to determine the batch size dynamically through the CTS Sync Service</inlineHelpText>
        <label>Batch Size</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Integration Settings for the Salesforce to CTS configurations</description>
    <label>CTS Integration Setting</label>
    <pluralLabel>CTS Integration Settings</pluralLabel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExecuteAsynchRequestSchedQltyCases.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 03-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 03-Jan-2019
  Description ........: Schedulable class to create CTS Tickets using the SFDC Sync Service to CTS ESB Service (API).
  Quality Case object records.
*****************************************************************************/
public class ExecuteAsynchRequestSchedQltyCases implements Schedulable {

     CTS_Integration_Setting__mdt integrationSetting = CTSSyncService.GetCTSIntegrationSettings();

    public void execute(SchedulableContext sc) {
    
        ExecuteSFDCToCTSAsynchRequestBatch qcb = new ExecuteSFDCToCTSAsynchRequestBatch('Quality_Case__c');
        database.executebatch(qcb, Integer.valueOf(integrationSetting.BatchSize__c));
    }
}