objects/CTS_Integration_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>BatchSize__c</fullName>
        <description>Used to determine the batch size dynamically through the CTS Sync Service</description>
        <inlineHelpText>Used to determine the batch size dynamically through the CTS Sync Service</inlineHelpText>
        <label>Batch Size</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Integration Settings for the Salesforce to CTS configurations</description>
    <label>CTS Integration Setting</label>
    <pluralLabel>CTS Integration Settings</pluralLabel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExecuteAsynchRequestSchedOrgCasesErr.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 03-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 03-Jan-2019
  Description ........: Schedulable class to create CTS Tickets using the SFDC Sync Service to CTS ESB Service (API).
  Organic Case object records Errored.
*****************************************************************************/
public class ExecuteAsynchRequestSchedOrgCasesErr implements Schedulable {

     CTS_Integration_Setting__mdt integrationSetting = CTSSyncService.GetCTSIntegrationSettings();

    public void execute(SchedulableContext sc) {
    
        ExecuteErrSFDCToCTSAsynchRequestBatch ocbe = new ExecuteErrSFDCToCTSAsynchRequestBatch('Organic_Analysis__c');
        database.executebatch(ocbe, Integer.valueOf(integrationSetting.BatchSize__c));
    }
}