objects/CTSObjectTriggerMap__mdt.object
<CustomObject>
    <fields>
        <fullName>DetailsTemplateName__c</fullName>
        <description>Salesforce Email Template Name corresponding to the Details Template Id</description>
        <inlineHelpText>Salesforce Email Template Name corresponding to the Details Template Id</inlineHelpText>
        <label>Details Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Used as reference to determine how a CTS Ticket should be created, what data elements should be included and the source of the ticket data from Salesforce data</description>
    <label>CTSObjectTriggerMap</label>
    <pluralLabel>CTSObjectTriggerMaps</pluralLabel>
</CustomObject>

classes/CTS_SFDC_Object_Base.cls
public virtual class CTS_SFDC_Object_Base
{
    public Id Id { get; set; }
    public String ObjectName { get; set; }
    public String Subject { get; set; }
    public String Detail { get; set; }
    
    public CTS_SFDC_Object_Base(Id objId, String objName, CTSObjectTriggerMap__mdt mappingInstance)
    {
        this.Id = objId;
        this.ObjectName = objName;
        Messaging.SingleEmailMessage mail = PopulateEmailSubjectBody(mappingInstance.DetailsTemplateName__c);
        this.Subject = mail.getSubject();
        this.Detail = mail.getPlainTextBody();       
    }
    
    private Messaging.SingleEmailMessage PopulateEmailSubjectBody(String emailTemplateName)
    {
        EmailTemplate et=[SELECT id FROM EmailTemplate where name = :emailTemplateName LIMIT 1];
        Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate((string)et.Id, null, Id, Messaging.AttachmentRetrievalOption.NONE);
        return mail;      
    }
}