objects/Custom_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Custom Automations</relationshipLabel>
        <relationshipName>Account_Custom_Automations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Automation_Status__c</fullName>
        <label>Automation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Outcome</fullName>
                    <default>true</default>
                    <label>Waiting on Outcome</label>
                </value>
                <value>
                    <fullName>Evaluating</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Automation_Trigger_Date__c</fullName>
        <label>Automation Trigger Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Automation_Type_API_Name_External_ID__c</fullName>
        <inlineHelpText>Use the Touchplan API Name for Custom Metadata Types or the assigned External ID for Marketo Email Campaign</inlineHelpText>
        <label>Automation Type API Name/External ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create_Day_40_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>Create_Monthly_LBW_Account_Performance</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_7</fullName>
                </value>
                <value>
                    <fullName>TORCHX_TRAINING_DAY_27</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_DAY_40</fullName>
                </value>
                <value>
                    <fullName>TORCHX_MONTHLY_REVIEW_EVERY_30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Automation</label>
    <nameField>
        <displayFormat>AAN-{0000000}</displayFormat>
        <label>Custom Automation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Daily_Scheduled_Record_Auto_Create__mdt.object
<CustomObject>
    <fields>
        <fullName>Additional_Default_Values__c</fullName>
        <label>Additional Default Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Additional_SOQL_Criteria__c</fullName>
        <label>Additional SOQL Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Default_Values__c</fullName>
        <inlineHelpText>Enter the values ex: "Field_API_Name__c":"Value" and separate with a ','</inlineHelpText>
        <label>Default Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lookup_Relationships__c</fullName>
        <inlineHelpText>Value example API_Name_Of_Lookup_In_New_Record:API_Name_of_Parent_Id_In_SOQL__c and separated by ','</inlineHelpText>
        <label>Lookup Relationships</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Push_New_Record_Data_To_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use caution when checking this check box! Talk to developer, if unsure if you should check this box or not.</inlineHelpText>
        <label>Push New Record Data To Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOQL__c</fullName>
        <label>SOQL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Supported_Objects_for_Record_Auto_Create__c</fullName>
        <label>Supported Objects for Record Auto Create</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Organic_Analysis__c</fullName>
                    <label>Organic Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Daily Scheduled Record Auto Create</label>
    <pluralLabel>Daily Scheduled Record Auto Create</pluralLabel><visibility>Public</visibility>
</CustomObject>

objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <description>Debug Data</description>
        <label>Debug Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Debug Info</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Debug Info Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DailyScheduledRecordAutoCreateBatch.cls
public class DailyScheduledRecordAutoCreateBatch implements Database.Batchable<sObject>, Database.Stateful {
	
	private Daily_Scheduled_Record_Auto_Create__mdt scheduledAutoCreate;
	private String query;

	private List<Id> recordIdList = new List<Id>();
	
	public DailyScheduledRecordAutoCreateBatch(Daily_Scheduled_Record_Auto_Create__mdt scheduledCreateRecord, String criteriaOverride) {
		scheduledAutoCreate = scheduledCreateRecord;
		query = scheduledAutoCreate.SOQL__c;
		if(scheduledAutoCreate.Additional_SOQL_Criteria__c != null){
			query += ' ' + scheduledAutoCreate.Additional_SOQL_Criteria__c;
		}

		if(String.isNotBlank(criteriaOverride)){
			query = criteriaOverride;
		}
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
   		List<sObject> newRecordList = new List<sObject>();
		for(sObject record : scope){
			if(scheduledAutoCreate.Supported_Objects_for_Record_Auto_Create__c.equalsIgnoreCase('Case')){
				Case newRecord = createCase(record);
				newRecordList.add(newRecord);
			}else{
				sObject newRecord = createSObject(record);
				newRecordList.add(newRecord);
			}
		}

		if(!newRecordList.isEmpty()){
			Database.SaveResult[] srList = Database.insert(newRecordList, false);
			List<DebugInfo__c> debugInfo = new List<DebugInfo__c>();

			Set<Id> relatedAccountIdSet = new Set<Id>();

			//if(scheduledAutoCreate.Push_New_Record_Data_To_Marketo__c){
				/*for(sObject record : newRecordList){
					recordIdList.add(record.Id);
				}*/
				//for(Database.SaveResult sr : srList){
				for(Integer i = 0; i < srList.size(); i++){
					Database.SaveResult sr = srList[i];

					if(sr.isSuccess()){
						if(scheduledAutoCreate.Supported_Objects_for_Record_Auto_Create__c.equalsIgnoreCase('Case')){
							recordIdList.add(sr.getId());
							relatedAccountIdSet.add((Id)newRecordList[i].get('AccountId'));
						}
					}else{
						DebugInfo__c newDebug = new DebugInfo__c();
						newDebug.DebugData__c = 'DailyScheduledRecordAutoCreateBatch Error | ' + JSON.serializePretty(newRecordList[i]) + ' | ' + JSON.serializePretty(sr.getErrors());
						debugInfo.add(newDebug);
					}
				}

				if(!debugInfo.isEmpty()){
					Database.insert(debugInfo, false);
				}
			//}

			if(query.containsIgnoreCase('Custom_Automation__c') && scheduledAutoCreate.DeveloperName.equalsIgnoreCase('Create_Monthly_LBW_Account_Performance')){
				List<Custom_Automation__c> updateCustomAutomationList = new List<Custom_Automation__c>();

                for(Custom_Automation__c ca : [select Id, Automation_Status__c from Custom_Automation__c where Account__c in :relatedAccountIdSet and Automation_Status__c = 'Scheduled' and Automation_Trigger_Date__c = TODAY and Automation_Type_API_Name_External_ID__c = 'Create_Monthly_LBW_Account_Performance']){
                    ca.Automation_Status__c = 'Completed';
                    updateCustomAutomationList.add(ca);
                }

                if(!updateCustomAutomationList.isEmpty()){
                    Database.update(updateCustomAutomationList, false);
                }
			}
		}
	}
	
	public void finish(Database.BatchableContext BC) {
		if(!recordIdList.isEmpty() && scheduledAutoCreate.Push_New_Record_Data_To_Marketo__c){
			if(scheduledAutoCreate.Supported_Objects_for_Record_Auto_Create__c.equalsIgnoreCase('Case') && !Test.isRunningTest()){
				Database.executeBatch(new CriteriaBasedBatchDataPushToMarketo(recordIdList, 'Case'), 100);
			}
		}
	}

	private Case createCase(sObject recordScope){
		Case newCase = new Case();

		if(scheduledAutoCreate.Lookup_Relationships__c != null){
			for(String lookUp : scheduledAutoCreate.Lookup_Relationships__c.split(',')){
				List<String> lookUpAPINameParentAPINameList = lookUp.split(':');
				newCase.put(lookUpAPINameParentAPINameList[0].trim(), recordScope.get(lookUpAPINameParentAPINameList[1].trim()));
			}
		}

		if(scheduledAutoCreate.Default_Values__c != null){
			for(String defaultValue : scheduledAutoCreate.Default_Values__c.split(',')){
				List<String> defaultValueAPINameAndValueList = defaultValue.split(':');
				newCase.put(defaultValueAPINameAndValueList[0].trim(), defaultValueAPINameAndValueList[1].trim());
			}
		}

		if(scheduledAutoCreate.Additional_Default_Values__c != null){
			for(String defaultValue : scheduledAutoCreate.Additional_Default_Values__c.split(',')){
				List<String> defaultValueAPINameAndValueList = defaultValue.split(':');
				newCase.put(defaultValueAPINameAndValueList[0].trim(), defaultValueAPINameAndValueList[1].trim());
			}
		}

		return newCase;
	}

	private sObject createSObject(sObject recordScope){
		sObject newRecord = Schema.getGlobalDescribe().get(scheduledAutoCreate.Supported_Objects_for_Record_Auto_Create__c).newSObject();

		if(scheduledAutoCreate.Lookup_Relationships__c != null){
			for(String lookUp : scheduledAutoCreate.Lookup_Relationships__c.split(',')){
				List<String> lookUpAPINameParentAPINameList = lookUp.split(':');
				newRecord.put(lookUpAPINameParentAPINameList[0].trim(), recordScope.get(lookUpAPINameParentAPINameList[1].trim()));
			}
		}

		if(scheduledAutoCreate.Default_Values__c != null){
			for(String defaultValue : scheduledAutoCreate.Default_Values__c.split(',')){
				List<String> defaultValueAPINameAndValueList = defaultValue.split(':');
				newRecord.put(defaultValueAPINameAndValueList[0].trim(), defaultValueAPINameAndValueList[1].trim());
			}
		}

		if(scheduledAutoCreate.Additional_Default_Values__c != null){
			for(String defaultValue : scheduledAutoCreate.Additional_Default_Values__c.split(',')){
				List<String> defaultValueAPINameAndValueList = defaultValue.split(':');
				newRecord.put(defaultValueAPINameAndValueList[0].trim(), defaultValueAPINameAndValueList[1].trim());
			}
		}

		return newRecord;
	}
	
}