objects/Daily_Scheduled_Record_Auto_Create__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Default_Values__c</fullName>
        <label>Additional Default Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Additional_SOQL_Criteria__c</fullName>
        <label>Additional SOQL Criteria</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Default_Values__c</fullName>
        <inlineHelpText>Enter the values ex: "Field_API_Name__c":"Value" and separate with a ','</inlineHelpText>
        <label>Default Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lookup_Relationships__c</fullName>
        <inlineHelpText>Value example API_Name_Of_Lookup_In_New_Record:API_Name_of_Parent_Id_In_SOQL__c and separated by ','</inlineHelpText>
        <label>Lookup Relationships</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Push_New_Record_Data_To_Marketo__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use caution when checking this check box! Talk to developer, if unsure if you should check this box or not.</inlineHelpText>
        <label>Push New Record Data To Marketo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOQL__c</fullName>
        <label>SOQL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Supported_Objects_for_Record_Auto_Create__c</fullName>
        <label>Supported Objects for Record Auto Create</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                    <default>true</default>
                    <label>Case</label>
                </value>
                <value>
                    <fullName>Organic_Analysis__c</fullName>
                    <label>Organic Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Daily Scheduled Record Auto Create</label>
    <pluralLabel>Daily Scheduled Record Auto Create</pluralLabel><visibility>Public</visibility>
</CustomObject>

objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Custom_Automation_API_Reference__c</fullName>
        <label>Custom Automation API Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomAutomationScheduleBatches.cls
public class CustomAutomationScheduleBatches implements Schedulable {

	public void execute(SchedulableContext sc) {
		// Subba Gadhamsetty, on 8/24/2017, Commented Daily_Scheduled_Record_Auto_Create__mdt as the corresponding Daily Schedule Job Inactivated Ref:https://webdc--dreamforce.cs54.my.salesforce.com/m0532000000Gmai , to avoid Test Execution Fail due to lack of Active Record from below SOQl
		//Daily_Scheduled_Record_Auto_Create__mdt lbwMonthlyPerformanceMetadataId = [select Id, DeveloperName, Additional_Default_Values__c, Additional_SOQL_Criteria__c, Default_Values__c, Lookup_Relationships__c, SOQL__c, Supported_Objects_for_Record_Auto_Create__c, Push_New_Record_Data_To_Marketo__c from Daily_Scheduled_Record_Auto_Create__mdt where Active__c = true and DeveloperName = 'Create_Monthly_LBW_Account_Performance' limit 1];
		Id marketoEmailCampaignTorchxTemplateId = [select Id from Marketo_Email_Campaign__c where RecordType.Name = 'Template' and Active__c = true and Custom_Automation_API_Reference__c != '' and Custom_Automation_API_Reference__c = 'TORCHX_MONTHLY_REVIEW_EVERY_30'][0].Id;  /// throwing an internal salesforce.com error so trying this way

		Database.executeBatch(new MarketoEmailCampaignBatch(Label.TORCHXMonthlyReviewAutomationBatchQuery, marketoEmailCampaignTorchxTemplateId), 100);
		//Database.executeBatch(new DailyScheduledRecordAutoCreateBatch(lbwMonthlyPerformanceMetadataId, Label.LBWMonthlyPerformanceAutomationBatchQuery));
	}

}