objects/Integration_Configuration__mdt.object
<CustomObject>
    <fields>
        <fullName>Configuration_Label__c</fullName>
        <description>Label/ Name portion of the label/ value pair</description>
        <label>Configuration Label</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Value__c</fullName>
        <description>Value of the label/ value pair</description>
        <label>Configuration Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_System_Name__c</fullName>
        <description>Name selection for the external system/ platform integrated with Salesforce (Yodle SFDC)</description>
        <label>External System Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CTS</fullName>
                    <default>true</default>
                    <label>CTS</label>
                </value>
                <value>
                    <fullName>Marketo</fullName>
                </value>
                <value>
                    <fullName>Yodle Live</fullName>
                </value>
                <value>
                    <fullName>Acquisio SFDC</fullName>
                </value>
                <value>
                    <fullName>Dreamforce API</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag/ indicator signifying if the configuration setting is active or inactive; inactive configurations should not be used</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <description>Configurations and settings for various integrations between Salesforce and external systems/ platforms.</description>
    <label>Integration Configuration</label>
    <pluralLabel>Integration Configurations</pluralLabel>
</CustomObject>

classes/ATVCustomerRefIdAPIInvokeSchedule.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 11-Nov-2018
  Last Modified By ...: E. Ross
  Last Modified Date .: 11-Nov-2018
  Description ........: Schedulable class to invoke external Endpoint URL on a schedule
*****************************************************************************/
global class ATVCustomerRefIdAPIInvokeSchedule Implements Schedulable {

    global void execute(SchedulableContext sc) {
    
        invokeATVCustRefIdUpdtService();
    }
    
    public PageReference invokeATVCustRefIdUpdtService()
    {
        String endpointUrl = 
            [SELECT Configuration_Value__c 
               FROM Integration_Configuration__mdt 
              WHERE Is_Active__c = true AND
                    External_System_Name__c = 'Dreamforce API' AND
                    Configuration_Label__c = 'AccountUUIDUpdateURL' LIMIT 1].Configuration_Value__c;
        
        PageReference apiSrvcPage = new PageReference(endpointUrl);
        apiSrvcPage.setRedirect(true);
        return apiSrvcPage;
    }
}