objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>Post Install Ready</fullName>
                </value>
                <value>
                    <fullName>Post Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Logo Complete</fullName>
                </value>
                <value>
                    <fullName>Logo Ready</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Escalated (Bolt On)</fullName>
                </value>
                <value>
                    <fullName>Backed Out Sale</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>BOT Feature Request</fullName>
                </value>
                <value>
                    <fullName>Escalated (Dev)</fullName>
                </value>
                <value>
                    <fullName>Escalated (Internal)</fullName>
                </value>
                <value>
                    <fullName>MA-1 Ready</fullName>
                </value>
                <value>
                    <fullName>MA-2 Pending Review</fullName>
                </value>
                <value>
                    <fullName>MA-3 Pending Config</fullName>
                </value>
                <value>
                    <fullName>MA-4 Pending Input</fullName>
                </value>
                <value>
                    <fullName>MA-5 Config Done Pending Approval</fullName>
                </value>
                <value>
                    <fullName>MA-6 Ready/Config Complete</fullName>
                </value>
                <value>
                    <fullName>MA-7 Suspended for Fix</fullName>
                </value>
                <value>
                    <fullName>MA-8 Multi Location Split</fullName>
                </value>
                <value>
                    <fullName>Messages Activated</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Retention</fullName>
                </value>
                <value>
                    <fullName>RFC</fullName>
                </value>
                <value>
                    <fullName>S. Consultant Assistance Needed</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Case_URL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SL_CaseHandler.cls
public with sharing class SL_CaseHandler {
	public SL_CaseHandler() {
		
	} 

	public static void closeOut(Set<Id> casesToProcess){
		for(Case c: [SELECT Id, ParentId 
    					FROM Case 
    					WHERE (NOT Status like 'Closed%') 
    					AND ParentId in :casesToProcess])
    	{
    		casesToProcess.remove(c.ParentId);
    	}

    	for(Lighthouse_Worksheets__c l: [SELECT Id, Case__c 
    					FROM Lighthouse_Worksheets__c 
    					WHERE Status__c != 'Complete'
    					AND	Status__c != 'Delete Case'
    					AND Case__c in :casesToProcess])
    	{
    		casesToProcess.remove(l.Case__c);
    	}


    	for(Organic_Analysis__c o: [SELECT Id, Case_URL__c 
			    					FROM Organic_Analysis__c 
			    					WHERE (NOT Status__c like 'Closed%')
			    					AND	Status__c != 'Delete Case'
			    					AND Case_URL__c in :casesToProcess])
    	{
    		casesToProcess.remove(o.Case_URL__c);
    	}

    	List<Case> caseObjToProcess = [SELECT Id, Status FROM Case WHERE Id in :CasesToProcess AND IsClosed = false];
    	for(Case c :caseObjToProcess){
    		c.Status = 'All Work Completed – Contact Client';
    	}
    	update caseObjToProcess;
	}
}