objects/Lighthouse_Worksheets__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Lighthouse Worksheets</relationshipLabel>
        <relationshipName>Lighthouse_Worksheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Stalled</fullName>
                </value>
                <value>
                    <fullName>Post Install Ready</fullName>
                </value>
                <value>
                    <fullName>Post Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Logo Complete</fullName>
                </value>
                <value>
                    <fullName>Logo Ready</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Escalated (Bolt On)</fullName>
                </value>
                <value>
                    <fullName>Backed Out Sale</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>BOT Feature Request</fullName>
                </value>
                <value>
                    <fullName>Escalated (Dev)</fullName>
                </value>
                <value>
                    <fullName>Escalated (Internal)</fullName>
                </value>
                <value>
                    <fullName>MA-1 Ready</fullName>
                </value>
                <value>
                    <fullName>MA-2 Pending Review</fullName>
                </value>
                <value>
                    <fullName>MA-3 Pending Config</fullName>
                </value>
                <value>
                    <fullName>MA-4 Pending Input</fullName>
                </value>
                <value>
                    <fullName>MA-5 Config Done Pending Approval</fullName>
                </value>
                <value>
                    <fullName>MA-6 Ready/Config Complete</fullName>
                </value>
                <value>
                    <fullName>MA-7 Suspended for Fix</fullName>
                </value>
                <value>
                    <fullName>MA-8 Multi Location Split</fullName>
                </value>
                <value>
                    <fullName>Messages Activated</fullName>
                </value>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Pending Retention</fullName>
                </value>
                <value>
                    <fullName>RFC</fullName>
                </value>
                <value>
                    <fullName>S. Consultant Assistance Needed</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to create worksheets for Lighthouse CS, such as the CSC worksheet and the Installation Worksheet.</description>
    <label>Lighthouse Worksheets</label>
    <nameField>
        <displayFormat>LH-{0000}</displayFormat>
        <label>Lighthouse Worksheets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lighthouse Worksheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SL_Lighthouse_WorksheetsTriggerHandler.cls
/**  
* \arg ClassName        : SL_Lighthouse_WorksheetsTriggerHandler
* \arg JIRATicket       : YODLET-1
* \arg CreatedOn        : 07/29/2015
* \arg LastModifiedOn   : 07/29/2015
* \arg CreatededBy      : Sathya
* \arg ModifiedBy       : 
* \arg Description      : Handler class for Lighthouse_Worksheets object.
*/
global class SL_Lighthouse_WorksheetsTriggerHandler extends SL_TriggerHandlerBase {

	public override void beforeInsert(List<SObject> newListGeneric){
		List<Lighthouse_Worksheets__c> newList = (List<Lighthouse_Worksheets__c>) newListGeneric;
		/*BEFORE INSERT METHODS START*/
		collectUpdatedLightHouseRecs(newList);
		/*BEFORE INSERT METHODS END*/
	}
	
	public override void beforeUpdate(Map<Id, SObject> oldMapGeneric, Map<Id, SObject> newMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> oldMap = (Map<Id, Lighthouse_Worksheets__c>) oldMapGeneric;
		Map<Id, Lighthouse_Worksheets__c> newMap = (Map<Id, Lighthouse_Worksheets__c>) newMapGeneric;
		/*BEFORE UPDATE METHODS START*/
		collectUpdatedLightHouseRecs(newMap.values());
		/*BEFORE UPDATE METHODS END*/
	}
	
	public override void beforeDelete(Map<Id, SObject> oldMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> oldMap = (Map<Id, Lighthouse_Worksheets__c>) oldMapGeneric;
		/*BEFORE DELETE METHODS START*/
		collectUpdatedLightHouseRecs(oldMap.values());
		/*BEFORE DELETE METHODS END*/
	}
	
	public override void afterInsert(Map<Id, SObject> newMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> newMap = (Map<Id, Lighthouse_Worksheets__c>) newMapGeneric;
		/*AFTER INSERT METHODS START*/
		
		/*AFTER INSERT METHODS END*/
	}
	
	public override void afterUpdate(Map<Id, SObject> oldMapGeneric, Map<Id, SObject> newMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> oldMap = (Map<Id, Lighthouse_Worksheets__c>) oldMapGeneric;
		Map<Id, Lighthouse_Worksheets__c> newMap = (Map<Id, Lighthouse_Worksheets__c>) newMapGeneric;
		/*AFTER UPDATE METHODS START*/
		
		/*AFTER UPDATE METHODS END*/
	}
	
	public override void afterDelete(Map<Id, SObject> oldMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> oldMap = (Map<Id, Lighthouse_Worksheets__c>) oldMapGeneric;
		/*AFTER DELETE METHODS START*/
		
		/*AFTER DELETE METHODS END*/
	}
	
	public override void afterUndelete(Map<Id, SObject> newMapGeneric){
		Map<Id, Lighthouse_Worksheets__c> newMap = (Map<Id, Lighthouse_Worksheets__c>) newMapGeneric;
		/*AFTER UNDELETE METHODS START*/
		
		/*AFTER UNDELETE METHODS END*/
	}
	
	private void collectUpdatedLightHouseRecs(List<Lighthouse_Worksheets__c> lstNewLightHouse)
	{
		Set<Id> casesToProcess = new Set<Id>();
        // Itrating over new 'Lighthouse Worksheets' records to collect whose status Equals to "Complete"
        for(Lighthouse_Worksheets__c l : lstNewLightHouse){
          if(l.Status__c == 'Complete' && l.Case__c != null)
            casesToProcess.add(l.Case__c);
        }

        // Calling this method to update the 'Lighthouse Worksheets' related Parent_case.Status
        SL_CaseHandler.closeOut(casesToProcess);
	}
}