objects/Marketo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>Marketo's Campaign ID field.</description>
        <externalId>true</externalId>
        <label>Campaign ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Marketo Campaign</label>
    <nameField>
        <label>Marketo Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketoCampaignSyncBatchTest.cls
@isTest
private class MarketoCampaignSyncBatchTest {
	
	@isTest static void test_MarketoCampaignSyncBatch() {
		TestCustomSettingInitializer testInit = new TestCustomSettingInitializer();

		Marketo_Campaign__c mCampaign = new Marketo_Campaign__c();
		mCampaign.Name = 'Test';
		mCampaign.Campaign_ID__c = '6052';
		insert mCampaign;

		String responseExample = [SELECT Id, Body FROM StaticResource WHERE Name = 'MarketoCampaignTestDataJSON' LIMIT 1].Body.toString();
		Test.setMock(HttpCalloutMock.class, new YodleLiveIntegrationCalloutMock(200, 'OK', responseExample, new Map<String, String>{'Content-Type' => 'application/json'}));

		Test.startTest();
		Database.executeBatch(new MarketoCampaignSyncBatch());
		Test.stopTest();

		system.assert([select id, Name from Marketo_Campaign__c where id =: mCampaign.id].Name == 'Max Touchplans');
	}
	
}