objects/Marketo_Email_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hourly_Reminder_DateTime_Field__c</fullName>
        <label>Hourly Reminder DateTime Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_Many_Random_Records__c</fullName>
        <inlineHelpText>How many random records to return</inlineHelpText>
        <label>How Many Random Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Randomize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Randomize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Hours_For_Reminder__c</fullName>
        <label># of Hours For Reminder</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Marketo Email Campaign</label>
    <nameField>
        <label>Marketo Email Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketo Email Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MarketoHourlyEmailCampaignSchedule.cls
public class MarketoHourlyEmailCampaignSchedule implements Schedulable {
	public void execute(SchedulableContext sc) {
		for(Marketo_Email_Campaign__c mec : [select Id, Criteria__c, Randomize__c, How_Many_Random_Records__c, Hourly_Reminder_DateTime_Field__c, of_Hours_For_Reminder__c from Marketo_Email_Campaign__c where Active__c = true and RecordType.Name = 'Hourly Template']){
			//DateTime reminderStartTime = DateTime.now().addHours((Integer)mec.of_Hours_For_Reminder__c);
			DateTime dtNowUnscrubbedValue = DateTime.now().addHours((Integer)mec.of_Hours_For_Reminder__c);
			system.debug(DateTime.Now());
			system.debug(dtNowUnscrubbedValue);
			DateTime reminderStartTime = DateTime.newInstance(dtNowUnscrubbedValue.year(), dtNowUnscrubbedValue.month(), dtNowUnscrubbedValue.day(), dtNowUnscrubbedValue.hour(), 0, 0);
			DateTime reminderEndTime = reminderStartTime.addMinutes(60);
			system.debug(reminderStartTime);
			String hourlyCriteria = ' and ' + mec.Hourly_Reminder_DateTime_Field__c + ' >=: reminderStartTime and ' + mec.Hourly_Reminder_DateTime_Field__c + ' <: reminderEndTime ';
			if(!mec.Randomize__c){
				Database.executeBatch(new MarketoHourlyEmailCampaignBatch(mec.Criteria__c + hourlyCriteria, mec.Id, reminderStartTime), 100);
			}else{
				List<String> splitCriteriaForCount = mec.Criteria__c.toUpperCase().split('FROM', 2);
				Integer totalSize = Database.countQuery('SELECT COUNT() FROM ' + splitCriteriaForCount[1]);
				Integer rand = Math.floor(Math.random() * totalSize).intValue();

				List<String> orderBys = new List<String>{'LastModifiedDate Desc','LastModifiedDate Asc','CreatedDate Asc','CreatedDate Desc','Id Asc','Id Desc'};
				String orderBy = orderBys.get(Math.floor(Math.random() * orderBys.size()).intValue());
				String queryString = mec.Criteria__c + hourlyCriteria + ' Order By ' + orderBy + ' Limit ' + mec.How_Many_Random_Records__c + ' OFFSET ' + rand;
				system.debug(queryString);
				List<Id> idList = new List<Id>();
				for(SObject sObj : Database.query(queryString)){
					idList.add(sObj.Id);
				}
				system.debug(mec.Criteria__c + ' and Id IN ' + idList);
				system.debug(totalSize);
				Database.executeBatch(new MarketoHourlyEmailCampaignBatch(mec.Criteria__c + ' and Id IN (\'' + String.join(idList, '\',\'') + '\')', mec.Id, reminderStartTime), 100);
			}
		}
	}
}