objects/Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Previous_Milestone__c</fullName>
        <label>Previous Milestone</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Modified_Milestone__c</fullName>
        <description>Hidden field associated with milestone trigger to remove description</description>
        <label>Milestone #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>M001 - Discovery call</fullName>
                </value>
                <value>
                    <fullName>M002 - Internal download call</fullName>
                </value>
                <value>
                    <fullName>M003 - Demo/Value Presentation</fullName>
                </value>
                <value>
                    <fullName>M004 - Detailed Audit Discovery</fullName>
                </value>
                <value>
                    <fullName>M005 - Audit download</fullName>
                </value>
                <value>
                    <fullName>M006 - Implementation &amp; ROI Investigation Call</fullName>
                </value>
                <value>
                    <fullName>M007 - Product Assessment &amp; Strategy</fullName>
                </value>
                <value>
                    <fullName>M008 - Solutions in Action Presentation</fullName>
                </value>
                <value>
                    <fullName>M009 - Proposal Creation &amp; Update SOW</fullName>
                </value>
                <value>
                    <fullName>M010 - Present Proposal &amp; SOW</fullName>
                </value>
                <value>
                    <fullName>M011 - Moving to Close</fullName>
                </value>
                <value>
                    <fullName>M012 - Proof of Value Agreement</fullName>
                </value>
                <value>
                    <fullName>M013 - Contract Creation</fullName>
                </value>
                <value>
                    <fullName>M014 - Deliver Contract to the Customer</fullName>
                </value>
                <value>
                    <fullName>M001 - Set local demo (IL)</fullName>
                </value>
                <value>
                    <fullName>M002 - Complete local demo (IL)</fullName>
                </value>
                <value>
                    <fullName>M003 - Contract (IL)</fullName>
                </value>
                <value>
                    <fullName>M100 - Deal closes</fullName>
                </value>
                <value>
                    <fullName>CLOSED LOST</fullName>
                </value>
                <value>
                    <fullName>M1 - Discovery</fullName>
                </value>
                <value>
                    <fullName>M2 - Demo &amp; Value Presentation</fullName>
                </value>
                <value>
                    <fullName>M3 - Executive Review</fullName>
                </value>
                <value>
                    <fullName>M4 - Solutions Review</fullName>
                </value>
                <value>
                    <fullName>M5 - Proposal</fullName>
                </value>
                <value>
                    <fullName>M6 - Contract</fullName>
                </value>
                <value>
                    <fullName>Client Discovery</fullName>
                </value>
                <value>
                    <fullName>Demo/Value Prop</fullName>
                </value>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

classes/ybnTestTriggerOpportunityMilestone.cls
@isTest
public with sharing class ybnTestTriggerOpportunityMilestone {
	static testMethod void testInsertUpdateOpp() {
        Account acc = new Account(Name = 'My Account');
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'My Opp');
        opp.AccountId = acc.Id;
        opp.StageName = 'Qualification';
        opp.CloseDate = date.today().addDays(1);
        opp.Milestone__c = 'MS01 - First';
        //insert opp;
        
        //opp = [SELECT Id, Modified_Milestone__c FROM Opportunity WHERE Id = :opp.Id];
        //System.assertEquals('MS01', opp.Modified_Milestone__c);
        
        opp.Milestone__c = 'MS02 - Second';
        //update opp;
        //opp = [SELECT Id, Modified_Milestone__c FROM Opportunity WHERE Id = :opp.Id];
        //System.assertEquals('MS02', opp.Modified_Milestone__c);
        
        opp.Milestone__c = 'MS01 - First';
        //update opp;
        //opp = [SELECT Id, Modified_Milestone__c FROM Opportunity WHERE Id = :opp.Id];
        //System.assertEquals('MS01', opp.Modified_Milestone__c);
        
        List<Milestone__c> milestones = 
        	[SELECT Id, Name, Previous_Milestone__c FROM Milestone__c WHERE Opportunity__c = :opp.Id];
        //System.assertEquals(2, milestones.size());
        
        for (Milestone__c ms: milestones) {
        	if (ms.Name == 'MS01') {
        		//System.assertEquals(null, ms.Previous_Milestone__c);
        	}
        	if (ms.Name == 'MS02') {
        		//System.assertEquals('MS01', ms.Previous_Milestone__c);
        	}
        }
        
    }
}