objects/NetworkAdoptionProduct__c.object
<CustomObject>
    <fields>
        <fullName>AdoptionLen__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Adoption Length (Mth)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AdoptionPct__c</fullName>
        <label>Adoption %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Enhanced SEO</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Facebook Setup</fullName>
                </value>
                <value>
                    <fullName>Foundations</fullName>
                </value>
                <value>
                    <fullName>Location Setup</fullName>
                </value>
                <value>
                    <fullName>Paid Per Click (PPC)</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
                <value>
                    <fullName>Yodle Web</fullName>
                </value>
                <value>
                    <fullName>Media Management</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Qty / Loc</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Network Adoption Products</relationshipLabel>
        <relationshipName>Network_Adoption_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Network Adoption Product</label>
    <nameField>
        <displayFormat>NAP-{0000000}</displayFormat>
        <label>NAP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Network Adoption Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NetAPCtl_NetworkAdoption.cls
public with sharing class NetAPCtl_NetworkAdoption{
    private final Opportunity opp;
    private Integer count;
    
    public String selectedRow {get;set;}
    //public List<NetworkAdoptionProduct__c> lstNAPs {get;set;}
    public List<netProd> lstNetProds {get;set;}
    
    public NetAPCtl_NetworkAdoption(ApexPages.StandardController con) {
        List<NetworkAdoptionProduct__c> lstNAPs = new List<NetworkAdoptionProduct__c>();
        this.opp = (Opportunity) con.getRecord();        
        system.debug('$$$ opp: ' + opp);
        if(opp.Id!=null){
            lstNAPs = [SELECT Id, Product__c, SalesPrice__c, Quantity__c, AdoptionPct__c, StartDate__c, 
                        AdoptionLen__c, Opportunity__c 
                       FROM NetworkAdoptionProduct__c WHERE Opportunity__c = :opp.Id];
            system.debug('$$$ lstNAPs: ' + lstNAPs);
            this.lstNetProds = new List<netProd>();
            
            if(lstNAPs.size()>0){
                for(Integer x=0; x<lstNAPs.size(); x++){                   
                    this.lstNetProds.add(new netProd(x, lstNAPs[x]));                    
                }
                this.count = lstNAPs.size()-1;   
            } else {
                
                this.count = -1;
                addRow();   
            }
        }        
    }   
    
    public void addRow(){
        Boolean hasError = false;
        
        if(lstNetProds.size()>0){
            Set<String> setProdNames = new Set<String>();
            
            for(netProd np: lstNetProds){
                if(setProdNames.contains(np.nap.Product__c)){
                    np.nap.Product__c.addError('Duplicate product. Please update or remove.');
                    hasError = true;
                } else if(np.nap.AdoptionPct__c > 100){
                    np.nap.AdoptionPct__c.addError('100% max');
                    hasError = true;
                } else {
                    setProdNames.add(np.nap.Product__c);
                }
            }
        }
        
        if(hasError==false){
            count += 1;
            lstNetProds.add(new netProd(count, null));
        }
    }
    
    public void remove(){
        lstNetProds.remove(Integer.valueOf(selectedRow));
        count -= 1;
        if(lstNetProds.size()>0){
            for(Integer x=0; x<lstNetProds.size();x++){
                lstNetProds[x].rowNum = x;
            }
        }
    }
    
    public PageReference createRecords(){
        Boolean hasError = false;
        Set<String> setProdNames = new Set<String>();
        List<NetworkAdoptionProduct__c> lstToInsert = new List<NetworkAdoptionProduct__c>();

        if(lstNetProds.size()>0){                      
            for(netProd np: lstNetProds){
                if(setProdNames.contains(np.nap.Product__c)){
                    np.nap.Product__c.addError('Duplicate product. Please update or remove.');
                    hasError = true;
                } else if(np.nap.AdoptionPct__c > 100){
                    np.nap.AdoptionPct__c.addError('100% max');
                    hasError = true;
                } else {
                    if(np.nap.Opportunity__c==null)  np.nap.Opportunity__c = opp.Id;
                    lstToInsert.add(np.nap);
                    setProdNames.add(np.nap.Product__c);
                }
            }
        }
        
        if(hasError==true)  return null;  
        
        if(lstToInsert.size()>0)  upsert lstToInsert;
        
        PageReference pageRef = new PageReference('/apex/OppResultPage');
        pageref.getParameters().put('id', opp.Id);
        pageref.getParameters().put('msg', 'Adoption Products Created Successfully');
        pageref.getParameters().put('sev', 'confirm');
        pageref.setRedirect(true);
        
        return pageRef;
    }
    
    public PageReference back(){
        PageReference pageRef = new PageReference('/' + opp.Id);
        pageRef.setRedirect(true);
        
        return pageRef;
    }
    
    // Wrapper
    public class netProd{
        public Integer rowNum {get;set;}
        public NetworkAdoptionProduct__c nap {get;set;}
        
        public netProd(Integer rn, NetworkAdoptionProduct__c netProd){
            this.rowNum = rn;
            
            if(netProd==null)  this.nap = new NetworkAdoptionProduct__c();
            else  this.nap = netProd;
        }
    }
    
    public PageReference resultMsg() {
        String strMsg_MissingId = 'Missing Id';
        String oid = ApexPages.currentPage().getParameters().get('id');
        String strMessage = ApexPages.currentPage().getParameters().get('msg');
        String strSeverity = ApexPages.currentPage().getParameters().get('sev');
        
        if(oid==null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, strMsg_MissingId));    
            return null;
        } else if(strMessage!=''){
            if(strSeverity=='confirm'){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, strMessage)); 
            } else if(strSeverity=='error'){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, strMessage)); 
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, strMessage)); 
            }               
            return null;
        } 
        
        return null;
    }
}