objects/Notification_Log__c.object
<CustomObject>
    <description>Object used to store metadata about automated notifications sent through custom logic. Can be leveraged for any sObject and/ or Record Type</description>
    <fields>
        <fullName>Notification_Sent_Date__c</fullName>
        <description>Date the notification associated to the record was sent</description>
        <label>Notification Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Unique Id of the record associated to the SObject Name</description>
        <label>Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>Associated Record Type of the SObject Record</description>
        <label>Record Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Name__c</fullName>
        <description>Name of the Salesforce Standard or custom object the log record logic is related to</description>
        <label>SObject Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Field_Name__c</fullName>
        <description>Name of the associated record's field that stores the trigger value for logic to execute</description>
        <label>Trigger Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Value__c</fullName>
        <description>Value stored in reference to the Trigger Field Name</description>
        <label>Trigger Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NL-{00000000}</displayFormat>
        <label>Notification Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NCSStatusNotificationScheduleTest.cls
@isTest(seeAllData=true)
private class NCSStatusNotificationScheduleTest
{
    private static testMethod void statusNotificationSchedTest()
    {
        Test.StartTest();
        
        Id wbnLogId = Schema.SObjectType.Notification_Log__c.getRecordTypeInfosByName().get('WBN Log').getRecordTypeId();
        List<Notification_Log__c> dmlLog = new List<Notification_Log__c>();
        Date todayDt = System.TODAY();
        
        Notification_Log__c newLog = new Notification_Log__c();
        newLog.RecordTypeId = wbnLogId;
        newLog.SObject_Name__c = 'Case';
        newLog.Record_Type_Name__c = 'National - New Client Setup';
        newLog.Trigger_Field_Name__c = 'Status';
        newLog.Notification_Sent_Date__c = todayDt;
        newLog.Trigger_Value__c = '1 - New';
        newLog.Record_Id__c = '5001b000004ej7uAAA';
        dmlLog.add(newLog);
        
        if(dmlLog.size() > 0){
            insert dmlLog;
        }
        
        wbnNationalNCSStatusNotificationSchedule sched1 = new wbnNationalNCSStatusNotificationSchedule(); 
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test WBN Status Notification', sch, sched1);
        
        Test.stopTest(); 
    }
}