objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is checked when Process Builder - WBN IL Contract Creation runs.</description>
        <label>Contract Auto Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Term_in_months__c</fullName>
        <description>Contract terms in months.</description>
        <label>Contract Term (in months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Term_in_months__c</fullName>
        <description>renewal contract months.</description>
        <inlineHelpText>The number of months for the renewal period after the commitment period ends.</inlineHelpText>
        <label>Renewal Term (in months)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <inlineHelpText>What products are being purchased in this opportunity?</inlineHelpText>
        <label>Products Sold</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Miner</fullName>
                </value>
                <value>
                    <fullName>Centermark</fullName>
                </value>
                <value>
                    <fullName>Centermark Lite</fullName>
                </value>
                <value>
                    <fullName>Client Side Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Display</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded Organic</fullName>
                </value>
                <value>
                    <fullName>Corporate Funded PPC</fullName>
                </value>
                <value>
                    <fullName>Corporate Website</fullName>
                </value>
                <value>
                    <fullName>Corp Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Custom Implementation</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Email (Integrated)</fullName>
                </value>
                <value>
                    <fullName>Email (Non-Integrated)</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Foundations</fullName>
                </value>
                <value>
                    <fullName>Get Found</fullName>
                </value>
                <value>
                    <fullName>Google 360</fullName>
                </value>
                <value>
                    <fullName>IL Paid Foundations</fullName>
                </value>
                <value>
                    <fullName>IL Paid PPC</fullName>
                </value>
                <value>
                    <fullName>IL Paid Reviews</fullName>
                </value>
                <value>
                    <fullName>Leads by Web / G1</fullName>
                </value>
                <value>
                    <fullName>Lighthouse</fullName>
                </value>
                <value>
                    <fullName>Local Business Listings</fullName>
                </value>
                <value>
                    <fullName>Local SEO</fullName>
                </value>
                <value>
                    <fullName>National SEO</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>PPC</fullName>
                </value>
                <value>
                    <fullName>PPC Location Adoption</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
<enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel>
</CustomObject>

classes/testCreateAssetonClosedWon.cls
@isTest 
private class testCreateAssetonClosedWon {
  
  /*static testMethod void testCreateAssetonClosedWon(){
    
    Account a = [select Id from Account limit 1];
    PricebookEntry pbID = [select Id from PricebookEntry limit 1];
    Opportunity o = new Opportunity();
    OpportunityLineItem ol = new OpportunityLineItem();
    
    o.AccountId = a.Id;
    o.RecordTypeId = '012600000009YRTAA2';
    o.Name = 'test';
    o.StageName =  'New Opportunity';
    o.CloseDate = date.today();
    o.Contract_Term_in_months__c = 12;
    o.Renewal_Term_in_months__c = 12;
    o.Products__c = 'PPC';
    insert o;
    
    ol.OpportunityId = o.Id;
    ol.Quantity = 1;
    ol.UnitPrice = 2.00;
    ol.PricebookEntryId = pbId.Id;
    
    insert ol;
    
    o.StageName= 'Closed Won';
    o.Contract_Auto_Created__c = True;
    update o;
    
    delete ol;
    delete o;
    
    
    
  }*/
  
  
}