objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>IsClosed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>IsClosed__c</fullName>
        <formula>if(
 ISPICKVAL( Status__c , "Closed") ,
true,
false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsClosed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                    <isActive>false</isActive>
                    <label>Delete Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProcessCTSEmailsTest.cls
/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 28-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 28-Jan-2019
  Description ........: Test Class for ProcessCTSEmails
*****************************************************************************/
@isTest(seeAllData=true)
private class ProcessCTSEmailsTest
{
    private static testMethod void closeCaseRecordTest()
    {
        List<String> toAddresses = new List<String>();
        Id caseId = [SELECT Id FROM Case WHERE IsClosed = false LIMIT 1].Id;
        
        // start test
        Test.startTest();
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        toAddresses.add('SFDCListenerService@web.com');
        
        // Set up the data for the email
        email.Subject = 'Notify SFDC to Close,Reference Record: ' + String.valueOf(caseId) + ' [Tkt:3245676]';
        email.HtmlBody = 'Close SFDC Record';
        email.PlainTextBody = 'Close SFDC Record';
        email.toAddresses = toAddresses;

        // Call the email service class and test it with the data in this method
        ProcessCTSEmails emailProcess = new ProcessCTSEmails();
        emailProcess.handleInboundEmail(email, env);
        
        Test.stopTest();
    }
    
    private static testMethod void closeOrgCaseRecordTest()
    {
        List<String> toAddresses = new List<String>();
        Id orgCaseId = [SELECT Id FROM Organic_Analysis__c WHERE IsClosed__c = false LIMIT 1].Id;
        
        // start test
        Test.startTest();
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        toAddresses.add('SFDCListenerService@web.com');
        
        // Set up the data for the email
        email.Subject = 'Notify SFDC to Close,Reference Record: ' + String.valueOf(orgCaseId) + ' [Tkt:3245677]';
        email.HtmlBody = 'Close SFDC Record';
        email.PlainTextBody = 'Close SFDC Record';
        email.toAddresses = toAddresses;

        // Call the email service class and test it with the data in this method
        ProcessCTSEmails emailProcess = new ProcessCTSEmails();
        emailProcess.handleInboundEmail(email, env);
        
        Test.stopTest();
    }
    
    private static testMethod void closeQualityCaseRecordTest()
    {
        List<String> toAddresses = new List<String>();
        Id qualityCaseId = [SELECT Id FROM Quality_Case__c WHERE IsClosed__c = false LIMIT 1].Id;
        
        // start test
        Test.startTest();
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        toAddresses.add('SFDCListenerService@web.com');
        
        // Set up the data for the email
        email.Subject = 'Notify SFDC to Close,Reference Record: ' + String.valueOf(qualityCaseId) + ' [Tkt:3245678]';
        email.HtmlBody = 'Close SFDC Record';
        email.PlainTextBody = 'Close SFDC Record';
        email.toAddresses = toAddresses;

        // Call the email service class and test it with the data in this method
        ProcessCTSEmails emailProcess = new ProcessCTSEmails();
        emailProcess.handleInboundEmail(email, env);
        
        Test.stopTest();
    }
    
    private static testMethod void closeCustSurveyRecordTest()
    {
        List<String> toAddresses = new List<String>();
        Id custSurveyId = [SELECT Id FROM Customer_Surveys__c WHERE Status__c != 'Closed Completed' LIMIT 1].Id;
        
        // start test
        Test.startTest();
        
        // Create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        toAddresses.add('SFDCListenerService@web.com');
        
        // Set up the data for the email
        email.Subject = 'Notify SFDC to Close,Reference Record: ' + String.valueOf(custSurveyId) + ' [Tkt:3245679]';
        email.HtmlBody = 'Close SFDC Record';
        email.PlainTextBody = 'Close SFDC Record';
        email.toAddresses = toAddresses;

        // Call the email service class and test it with the data in this method
        ProcessCTSEmails emailProcess = new ProcessCTSEmails();
        emailProcess.handleInboundEmail(email, env);
        
        Test.stopTest();
    }
}