objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Case_URL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SL_Organic_AnalysisTriggerHandler.cls
/**  
* \arg ClassName        : SL_Organic_AnalysisTriggerHandler
* \arg JIRATicket       : YODLET-1
* \arg CreatedOn        : 07/29/2015
* \arg LastModifiedOn   : 07/29/2015
* \arg CreatededBy      : Sathya
* \arg ModifiedBy       : 
* \arg Description      : Handler class for Organic_Analysis object.
*/
global class SL_Organic_AnalysisTriggerHandler extends SL_TriggerHandlerBase {

    public override void beforeInsert(List<SObject> newListGeneric){
        List<Organic_Analysis__c> newList = (List<Organic_Analysis__c>) newListGeneric;
        /*BEFORE INSERT METHODS START*/
        collectUpdatedOrganicRecs(newList);
        /*BEFORE INSERT METHODS END*/
    }
    
    public override void beforeUpdate(Map<Id, SObject> oldMapGeneric, Map<Id, SObject> newMapGeneric){
        Map<Id, Organic_Analysis__c> oldMap = (Map<Id, Organic_Analysis__c>) oldMapGeneric;
        Map<Id, Organic_Analysis__c> newMap = (Map<Id, Organic_Analysis__c>) newMapGeneric;
        /*BEFORE UPDATE METHODS START*/
        collectUpdatedOrganicRecs(newMap.values());
        /*BEFORE UPDATE METHODS END*/
    }
    
    public override void beforeDelete(Map<Id, SObject> oldMapGeneric){
        Map<Id, Organic_Analysis__c> oldMap = (Map<Id, Organic_Analysis__c>) oldMapGeneric;
        /*BEFORE DELETE METHODS START*/
        collectUpdatedOrganicRecs(oldMap.values());
        /*BEFORE DELETE METHODS END*/
    }
    
    public override void afterInsert(Map<Id, SObject> newMapGeneric){
        Map<Id, Organic_Analysis__c> newMap = (Map<Id, Organic_Analysis__c>) newMapGeneric;
        /*AFTER INSERT METHODS START*/
        
        /*AFTER INSERT METHODS END*/
    }
    
    public override void afterUpdate(Map<Id, SObject> oldMapGeneric, Map<Id, SObject> newMapGeneric){
        Map<Id, Organic_Analysis__c> oldMap = (Map<Id, Organic_Analysis__c>) oldMapGeneric;
        Map<Id, Organic_Analysis__c> newMap = (Map<Id, Organic_Analysis__c>) newMapGeneric;
        /*AFTER UPDATE METHODS START*/
        
        /*AFTER UPDATE METHODS END*/
    }
    
    public override void afterDelete(Map<Id, SObject> oldMapGeneric){
        Map<Id, Organic_Analysis__c> oldMap = (Map<Id, Organic_Analysis__c>) oldMapGeneric;
        /*AFTER DELETE METHODS START*/
        
        /*AFTER DELETE METHODS END*/
    }
    
    public override void afterUndelete(Map<Id, SObject> newMapGeneric){
        Map<Id, Organic_Analysis__c> newMap = (Map<Id, Organic_Analysis__c>) newMapGeneric;
        /*AFTER UNDELETE METHODS START*/
        
        /*AFTER UNDELETE METHODS END*/
    }
    
    private void collectUpdatedOrganicRecs(List<Organic_Analysis__c> newList) {
        Set<Id> casesToProcess = new Set<Id>();
        // Itrating over new 'Orgnaic Anlysis' records to collect whose status contains "Closed"
        for(Organic_Analysis__c o : newList) {
            if(o.Status__c.contains('Closed') && o.Case_URL__c != null)
                casesToProcess.add(o.Case_URL__c);  
        }
        
        // Calling this method to update the 'Orgnaic Anlysis' related Parent_case.Status
        SL_CaseHandler.closeOut(casesToProcess);
    }
     
}