objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Organic_Analyses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Google_Listing_Status__c</fullName>
        <label>Google Listing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Listing</fullName>
                </value>
                <value>
                    <fullName>Active Listing - Read Only</fullName>
                </value>
                <value>
                    <fullName>Awaiting PIN</fullName>
                </value>
                <value>
                    <fullName>Awaiting Verification</fullName>
                </value>
                <value>
                    <fullName>Client Refuses Claim</fullName>
                </value>
                <value>
                    <fullName>Error Message</fullName>
                </value>
                <value>
                    <fullName>Migrated To Bulk Account</fullName>
                </value>
                <value>
                    <fullName>Needs Re-Verification</fullName>
                </value>
                <value>
                    <fullName>No Listing</fullName>
                </value>
                <value>
                    <fullName>Owner-Verified/Managed</fullName>
                </value>
                <value>
                    <fullName>Owner-Verified/Pending Management</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected - PO Box Used</fullName>
                </value>
                <value>
                    <fullName>Rejected Unknown</fullName>
                </value>
                <value>
                    <fullName>Restarted</fullName>
                </value>
                <value>
                    <fullName>Un-Claimable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LocalHLPanelControllerTest.cls
@isTest
private class LocalHLPanelControllerTest {
	
	@isTest static void test_method_one() {
		Account newAccount = new Account();
		newAccount.Name = 'Testing Cancellation Test';
		insert newAccount;

		Case newCase = new Case();
		newCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('LH Cancel Request').getRecordTypeId();
		newCase.AccountId = newAccount.Id;
		insert newCase;

		Organic_Analysis__c newOrgCase = new Organic_Analysis__c();
		newOrgCase.RecordTypeId = Schema.SObjectType.Organic_Analysis__c.getRecordTypeInfosByName().get('Maps Initial Claiming').getRecordTypeId();
		newOrgCase.Account_Name__c = newAccount.Id;
		newOrgCase.Google_Listing_Status__c = 'Awaiting PIN';
		insert newOrgCase;

		Test.startTest();
		ApexPages.StandardController stdAcct = new ApexPages.StandardController(newAccount);
	    LocalHLPanelController contrExt  = new LocalHLPanelController(stdAcct);
	    Test.stopTest();
	}
	
}