objects/Organic_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>All Tasks Completed</fullName>
                </value>
                <value>
                    <fullName>Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Errors Found/Fixed</fullName>
                </value>
                <value>
                    <fullName>G &amp; B Pins Received - Claim IYPs</fullName>
                </value>
                <value>
                    <fullName>Google &amp; Bing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Account Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>Google Listing Rebuild Needed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Scheduled Call</fullName>
                </value>
                <value>
                    <fullName>Listing Teardown Requested</fullName>
                </value>
                <value>
                    <fullName>Missing Information</fullName>
                </value>
                <value>
                    <fullName>Awaiting Internal Response</fullName>
                </value>
                <value>
                    <fullName>Non Compliant Client</fullName>
                </value>
                <value>
                    <fullName>Pending Reattempt</fullName>
                </value>
                <value>
                    <fullName>Pending Pin Receipt</fullName>
                </value>
                <value>
                    <fullName>Profile Optimization</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>Cannot Complete</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - False Trigger</fullName>
                </value>
                <value>
                    <fullName>Closed - No Errors Found</fullName>
                </value>
                <value>
                    <fullName>Closed - Sent to SDB</fullName>
                </value>
                <value>
                    <fullName>Opt Not Completed - Invalid Case</fullName>
                </value>
                <value>
                    <fullName>New Google Build Needed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to track our maps verification and pin collection</description>
    <label>Organic Case</label>
    <nameField>
        <displayFormat>YO-{0000}</displayFormat>
        <label>YO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organic Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quality_Case__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delete Case</fullName>
                    <isActive>false</isActive>
                    <label>Delete Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quality Case</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quality Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Case</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDCToCTSAsynchRequest__c.object
<CustomObject>
    <description>Stores DE-normalized CTS Ticket data to be executed by BULK job on a schedule to create CTS Tickets</description>
    <fields>
        <fullName>NumberOfRetryAttempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of attempts made to send a request to the CTS API for creating a ticket</description>
        <inlineHelpText>Number of attempts made to send a request to the CTS API for creating a ticket</inlineHelpText>
        <label>Number Of Retry Attempts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The corresponding record Id based on the Object Name</description>
        <inlineHelpText>The corresponding record Id based on the Object Name</inlineHelpText>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Salesforce Objects integrated with CTS</description>
        <inlineHelpText>Salesforce Objects integrated with CTS</inlineHelpText>
        <label>Object Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Customer_Surveys__c</fullName>
                </value>
                <value>
                    <fullName>Organic_Analysis__c</fullName>
                </value>
                <value>
                    <fullName>Quality_Case__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>"NEW"</defaultValue>
        <description>Async Request Status indicating the current state of the record</description>
        <inlineHelpText>Async Request Status indicating the current state of the record</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>INPROCESS</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>UNQUALIFIED</fullName>
                </value>
                <value>
                    <fullName>REPROCESS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SFDCToCTSAsynchRequest</label>
    <nameField>
        <displayFormat>AR-{000000000}</displayFormat>
        <label>Asynch Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDCToCTSAsynchRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSSyncServiceReprocssScheduler.cls
/*
 * To run it every 30 minutes go to Developer Console: Debug->Open Execute Anonymous Window:
        System.schedule('CTS Sync Service Reprocess Scheduler 1', '0 0 * * * ?', new CTSSyncServiceReprocssScheduler());        
        System.schedule('CTS Sync Service Reprocess Scheduler 2', '0 30 * * * ?', new CTSSyncServiceReprocssScheduler());        
 */
global with sharing class CTSSyncServiceReprocssScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {    
        Reprocess('Case');
        Reprocess('Organic_Analysis__c');
        Reprocess('Quality_Case__c');
        Reprocess('Customer_Surveys__c');                                
    }
    
    private void Reprocess(String objType)
    {
        List<SFDCToCTSAsynchRequest__c> asyncRecords = [SELECT Id,                        
                        Name,
                        NumberOfRetryAttempts__c,
                        ObjectId__c,
                        Object_Name__c,                       
                        Status__c
                   FROM SFDCToCTSAsynchRequest__c
                   WHERE Object_Name__c = :objType AND Status__c = 'ERROR' AND NumberOfRetryAttempts__c < 3
                   LIMIT 10]; 
        
        if (asyncRecords.size() > 0)
        {
            FOR(SFDCToCTSAsynchRequest__c record : asyncRecords)
                record.Status__c = 'REPROCESS';
                
            Update asyncRecords;
        }                    
    }
}