objects/Outbound_Call_Case_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Notes_Contains__c</fullName>
        <label>Sales Notes Contains</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Script_URL__c</fullName>
        <label>Script URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Account_Revenue__c</fullName>
        <label>Total Account Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Order__c</fullName>
        <label>Validation Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website_Type__c</fullName>
        <label>Website Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winback_CSC_Script__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Winback CSC Script</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Outbound Call Case Automation</label>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <description>For segment status in YL</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EditOutboundCallCaseAutomationController.cls
public without sharing class EditOutboundCallCaseAutomationController {
	public List<OCCAWrapper> outboundCallCaseRecords {get; set;}
	public Boolean editMode {get; set;}

	public EditOutboundCallCaseAutomationController() {
		editMode = false;
		fillData();
	}

	public void fillData(){
		/*outboundCallCaseRecords = Outbound_Call_Case_Automation__c.getAll().values();
		for(Outbound_Call_Case_Automation__c occa : Outbound_Call_Case_Automation__c.getAll().values()){
			outboundCallCaseRecords.set(Integer.valueof(occa.Name) - 1, occa);
		}*/

		outboundCallCaseRecords = new List<OCCAWrapper>();

		for(Outbound_Call_Case_Automation__c oc:  [select Id, Name, Case_Reason__c, Channel_Type__c, Product_Type__c, Sales_Notes_Contains__c, Script_URL__c, Segment__c, Total_Account_Revenue__c, Validation_Order__c, Website_Type__c, Winback_CSC_Script__c from Outbound_Call_Case_Automation__c order by Validation_Order__c]){
			OCCAWrapper occaWrap = new OCCAWrapper();
			occaWrap.selected = false;
			occaWrap.occa = oc;
			outboundCallCaseRecords.add(occaWrap);
		}
	}

	public void editChanges(){
		editMode = true;
	}

	public void cancelChanges(){
		editMode = false;
		fillData();
	}

	public void addCustomSetting(){
		OCCAWrapper occaWrap = new OCCAWrapper();
		occaWrap.selected = false;
		Outbound_Call_Case_Automation__c newOCCA = new Outbound_Call_Case_Automation__c(Validation_Order__c = outboundCallCaseRecords.size() + 1, Name = String.valueof(outboundCallCaseRecords.size() + 1));
		occaWrap.occa = newOCCA;
		outboundCallCaseRecords.add(occaWrap);
	}

	public void deleteSelected(){
		try{
			List<Outbound_Call_Case_Automation__c> deleteList = new List<Outbound_Call_Case_Automation__c>();

			List<OCCAWrapper> unsavedList = new List<OCCAWrapper>();

			for(OCCAWrapper oc : outboundCallCaseRecords){
				if(oc.selected && String.isNotBlank(oc.occa.Id)){
					deleteList.add(oc.occa);
				}else if(!oc.selected && String.isBlank(oc.occa.Id)){
					unsavedList.add(oc);
				}
			}
			delete deleteList;
			fillData();
			outboundCallCaseRecords.addAll(unsavedList);
		}catch(Exception E){

		}
	}

	public void saveChanges(){
		try{
			List<Outbound_Call_Case_Automation__c> updateList = new List<Outbound_Call_Case_Automation__c>();
			for(OCCAWrapper oc : outboundCallCaseRecords){
				updateList.add(oc.occa);
			}
			upsert updateList;
			fillData();
			editMode = false;
		}catch(Exception E){

		}
	}

	public class OCCAWrapper{
		public Boolean selected {get; set;}
		public Outbound_Call_Case_Automation__c occa {get; set;}
	}
}