objects/Outbound_Call_Case_Automation__c.object
<CustomObject>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Notes_Contains__c</fullName>
        <label>Sales Notes Contains</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Script_URL__c</fullName>
        <label>Script URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Account_Revenue__c</fullName>
        <label>Total Account Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Order__c</fullName>
        <label>Validation Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website_Type__c</fullName>
        <label>Website Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Winback_CSC_Script__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Winback CSC Script</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Outbound Call Case Automation</label>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <description>For segment status in YL</description>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseScriptAssignmentUtil.cls
public without sharing class CaseScriptAssignmentUtil {
	private static List<Outbound_Call_Case_Automation__c> occaList = [select Id, Name, Case_Reason__c, Channel_Type__c, Product_Type__c, Sales_Notes_Contains__c, Script_URL__c, Segment__c, Total_Account_Revenue__c, Validation_Order__c, Website_Type__c, Winback_CSC_Script__c from Outbound_Call_Case_Automation__c order by Validation_Order__c];

	public static Case setCallScript(Case newCaseValue){
		if(occaList.isEmpty()){
			return newCaseValue;
		}
		for(Outbound_Call_Case_Automation__c occa : occaList){
			if(newCaseValue.Reason != occa.Case_Reason__c){
				continue;
			}
			if(String.isNotBlank(occa.Channel_Type__c) && !occa.Channel_Type__c.contains(newCaseValue.Channel_Type__c)){
				continue;
			}
			if(String.isNotBlank(occa.Product_Type__c) && occa.Product_Type__c != newCaseValue.Product_Type__c){
				continue;
			}
			if(String.isNotBlank(occa.Sales_Notes_Contains__c) && (String.isBlank(newCaseValue.Sales_Notes__c) || (!newCaseValue.Sales_Notes__c.contains('LH') && !newCaseValue.Sales_Notes__c.contains('Lighthouse')))){
				continue;
			}
			if((String.isBlank(newCaseValue.Segment__c) && String.isNotBlank(occa.Segment__c)) || (String.isNotBlank(occa.Segment__c) && String.isNotBlank(newCaseValue.Segment__c) && !occa.Segment__c.contains(newCaseValue.Segment__c))){
				continue;
			}
			if(occa.Total_Account_Revenue__c != null && newCaseValue.Total_Acct_Revenue__c > occa.Total_Account_Revenue__c){
				continue;
			}
			if(String.isNotBlank(occa.Website_Type__c) && occa.Website_Type__c != newCaseValue.Website_Type2__c){
				continue;
			}
			if(occa.Winback_CSC_Script__c && !newCaseValue.Winback_CSC_Script__c){
				continue;
			}
			newCaseValue.Link_to_Script__c = occa.Script_URL__c;
			break;
			
		}

		return newCaseValue;
	}
	
}