objects/Partner_Pop_up_Ad__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pop_up_Content__c</fullName>
        <inlineHelpText>HTML tags are okay. Please use inline styling for CSS.</inlineHelpText>
        <label>Pop-up Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Show_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Show Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Pop-up Ad</label>
    <nameField>
        <label>Partner Pop-up Ad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Pop-up Ads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WelcomePagePopUpControllerTest.cls
@isTest
private class WelcomePagePopUpControllerTest {
	
	@isTest static void test_WelcomePagePopUpController() {
		Partner_Pop_up_Ad__c newPPAd = new Partner_Pop_up_Ad__c();
		newPPAd.Name = 'Test Ad';
		newPPAd.Active__c = true;
		newPPAd.Pop_up_Content__c = 'Test Content';
		newPPAd.Show_Order__c = 0;
		insert newPPAd;

		Partner_Pop_up_Ad__c newPPAd2 = new Partner_Pop_up_Ad__c();
		newPPAd2.Name = 'Test Ad';
		newPPAd2.Active__c = true;
		newPPAd2.Pop_up_Content__c = 'Test Content';
		newPPAd2.Show_Order__c = 1;
		insert newPPAd2;

		WelcomePagePopUpController.dismissPopUpAd(WelcomePagePopUpController.getPopUpAd(''));
	}

	@isTest static void test_WelcomePagePopUpControllerError() {
		WelcomePagePopUpController.dismissPopUpAd(WelcomePagePopUpController.getPopUpAd(''));
	}
	
}