objects/Partner_Pop_up_Ad__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pop_up_Content__c</fullName>
        <inlineHelpText>HTML tags are okay. Please use inline styling for CSS.</inlineHelpText>
        <label>Pop-up Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Show_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Show Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Pop-up Ad</label>
    <nameField>
        <label>Partner Pop-up Ad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Pop-up Ads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Pop_up_Ad_User_Dismissed__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Pop_up_Ad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Pop-up Ad</label>
        <referenceTo>Partner_Pop_up_Ad__c</referenceTo>
        <relationshipLabel>Partner Pop-up Ads User Dismissed</relationshipLabel>
        <relationshipName>Partner_Pop_up_Ads_User_Dismissed</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Pop_up_Ads_User_Dismissed</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Pop-up Ad User Dismissed</label>
    <nameField>
        <displayFormat>Dismissal #-{0000000}</displayFormat>
        <label>Partner Pop-up Ad User Dismissed Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Pop-up Ads User Dismissed</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WelcomePagePopUpController.cls
public without sharing class WelcomePagePopUpController {
	@AuraEnabled
    public static Partner_Pop_up_Ad__c getPopUpAd(String popUpId) {
        // Perform isAccessible() check here 
        try{
            if(String.isNotBlank(popUpId)){
                Partner_Pop_up_Ad__c popupAd = [select Id, Name, Pop_up_Content__c from Partner_Pop_up_Ad__c where Id =: popUpId];
                return popupAd;
            }else{
                Partner_Pop_up_Ad__c popupAd = [select Id, Name, Pop_up_Content__c from Partner_Pop_up_Ad__c where Active__c = true and Id not in (select Partner_Pop_up_Ad__c from Partner_Pop_up_Ad_User_Dismissed__c where User__c =: UserInfo.getUserId()) order by Show_Order__c limit 1];
                return popupAd;
            }
		}catch(Exception E){
			return new Partner_Pop_up_Ad__c();
		}
    }

    @AuraEnabled
    public static Partner_Pop_up_Ad__c dismissPopUpAd(Partner_Pop_up_Ad__c dismissedAd) {
    	Partner_Pop_up_Ad_User_Dismissed__c dismissThis = new Partner_Pop_up_Ad_User_Dismissed__c();
    	dismissThis.Partner_Pop_up_Ad__c = dismissedAd.Id;
    	dismissThis.User__c = UserInfo.getUserId();
    	insert dismissThis;
        // Perform isAccessible() check here 
        try{
        	Partner_Pop_up_Ad__c popupAd = [select Id, Name, Pop_up_Content__c from Partner_Pop_up_Ad__c where Active__c = true and Id not in (select Partner_Pop_up_Ad__c from Partner_Pop_up_Ad_User_Dismissed__c where User__c =: UserInfo.getUserId()) order by Show_Order__c limit 1];
    		return popupAd;
    	}catch(Exception E){
    		return new Partner_Pop_up_Ad__c();
    	}
    }
}