objects/Partner_Marketing_Development_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Notes__c</fullName>
        <label>Claim Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claimed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claimed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Activity__c</fullName>
        <label>Date of Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Cost_of_Activity__c</fullName>
        <label>Estimated Cost of Activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MDF_Date_Submitted__c</fullName>
        <label>MDF Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Request Denied</fullName>
                </value>
                <value>
                    <fullName>Request Expired</fullName>
                </value>
                <value>
                    <fullName>Claim Submitted</fullName>
                </value>
                <value>
                    <fullName>Claim In Review</fullName>
                </value>
                <value>
                    <fullName>Claim Needs More Information</fullName>
                </value>
                <value>
                    <fullName>Claim Approved</fullName>
                </value>
                <value>
                    <fullName>Claim Denied</fullName>
                </value>
                <value>
                    <fullName>Claim Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Activity__c</fullName>
        <label>Other Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Marketing Development Funds</relationshipLabel>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Partner_Marketing_Development_Funds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Cost_of_Activity__c</fullName>
        <label>Total Cost of Activity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type_of_Activity__c</fullName>
        <label>Type of Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Testimonial Videos</fullName>
                </value>
                <value>
                    <fullName>White Papers</fullName>
                </value>
                <value>
                    <fullName>Research Docs</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Events</fullName>
                </value>
                <value>
                    <fullName>Promotional Items</fullName>
                </value>
                <value>
                    <fullName>Online Marketing</fullName>
                </value>
                <value>
                    <fullName>Sponsorships</fullName>
                </value>
                <value>
                    <fullName>Direct Mail/Email</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>What_is_the_goal_of_the_activity__c</fullName>
        <label>What is the goal of the activity?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>When_will_the_activity_happen__c</fullName>
        <label>When will the activity happen</label>
        <type>Date</type>
    </fields>
    <label>Partner Marketing Development Fund</label>
    <nameField>
        <displayFormat>PMDF-{0000000}</displayFormat>
        <label>Partner MDF Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Marketing Development Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MDFRequestHistoryController.cls
public with sharing class MDFRequestHistoryController {
	public List<Partner_Marketing_Development_Fund__c> pmdfHistoryList {get; set;}
	public Partner_Marketing_Development_Fund__c pmdfSelected {get; set;}
	public String selectedOrderBy {get; set;}

	private String clientAccountId;

	private static User currentUser = [select Id, UserRoleId, IsPortalEnabled, AccountId from User where Id =: UserInfo.getUserId()];

	public MDFRequestHistoryController() {
		pmdfSelected = new Partner_Marketing_Development_Fund__c();
		selectedOrderBy = 'MDF_Date_Submitted__c DESC';
		populateHistoryList();
		if(String.isNotBlank(ApexPages.currentPage().getParameters().get('initialSelectedId'))){
			pmdfSelected = [select Id, Name, MDF_Status__c, Claimed_By__c, Date_of_Activity__c, Total_Cost_of_Activity__c, Claim_Notes__c from Partner_Marketing_Development_Fund__c where Id =: ApexPages.currentPage().getParameters().get('initialSelectedId') and Partner_Account__c =: clientAccountId];
		}
	}

	public void populateHistoryList(){
		if(String.isNotBlank(currentUser.AccountId)){
			clientAccountId = currentUser.AccountId;
		}else if(String.isNotBlank(ApexPages.currentPage().getParameters().get('clientAccountId'))){
			clientAccountId = ApexPages.currentPage().getParameters().get('clientAccountId');
		}

		pmdfHistoryList = new List<Partner_Marketing_Development_Fund__c>();

		for(Partner_Marketing_Development_Fund__c record : Database.query('select Id, Name, Total_Cost_of_Activity__c, MDF_Status__c, Requested_By__c, Type_of_Activity__c, What_is_the_goal_of_the_activity__c, When_will_the_activity_happen__c, MDF_Date_Submitted__c, Estimated_Cost_of_Activity__c, Other_Activity__c from Partner_Marketing_Development_Fund__c where Partner_Account__c = :clientAccountId order by ' +  selectedOrderBy)){
			pmdfHistoryList.add(record);
		}
	}

	public void selectedPMDF(){
		String pmdfSelectedId = ApexPages.currentPage().getParameters().get('pmdfSelectedId');
		if(String.isNotBlank(pmdfSelectedId)){
			pmdfSelected = [select Id, Name, MDF_Status__c, Claimed_By__c, Date_of_Activity__c, Total_Cost_of_Activity__c, Claim_Notes__c from Partner_Marketing_Development_Fund__c where Id =: pmdfSelectedId and Partner_Account__c =: clientAccountId];
		}else{
			pmdfSelected = new Partner_Marketing_Development_Fund__c();
		}
	}

	public void refreshData(){
		populateHistoryList();
	}

	public List<SelectOption> getOrderByList() {
 	 	List<SelectOption> options = new List<SelectOption>();
 	 	options.add(new SelectOption('MDF_Date_Submitted__c ASC','MDF Date Submitted ASC'));
 	 	options.add(new SelectOption('MDF_Date_Submitted__c DESC','MDF Date Submitted DESC'));
 	 	options.add(new SelectOption('Name ASC','Partner Marketing Development Fund Number ASC'));
 	 	options.add(new SelectOption('Name DESC','Partner Marketing Development Fund Number DESC'));
 	 	options.add(new SelectOption('MDF_Status__c ASC','MDF Status ASC'));
 	 	options.add(new SelectOption('MDF_Status__c DESC','MDF Status DESC'));
 	 	options.add(new SelectOption('Estimated_Cost_of_Activity__c ASC','Estimated Cost of Activity ASC'));
 	 	options.add(new SelectOption('Estimated_Cost_of_Activity__c DESC','Estimated Cost of Activity DESC'));
 	 	options.add(new SelectOption('Total_Cost_of_Activity__c ASC','Total Cost of Activity ASC'));
 	 	options.add(new SelectOption('Total_Cost_of_Activity__c DESC','Total Cost of Activity DESC'));
 	 	options.add(new SelectOption('Type_of_Activity__c ASC','Type of Activity ASC'));
 	 	options.add(new SelectOption('Type_of_Activity__c DESC','Type of Activity DESC'));
 	 	return options;
  	}
}