objects/SFDCToCTSAsynchRequest__c.object
<CustomObject>
    <description>Stores DE-normalized CTS Ticket data to be executed by BULK job on a schedule to create CTS Tickets</description>
    <fields>
        <fullName>API_Identifier__c</fullName>
        <description>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</description>
        <inlineHelpText>Identifier when the Integration Type is API; used by CTS system to create and place the new ticket in the proper CTS queue; required when Integration Type is API</inlineHelpText>
        <label>API Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailTemplateId__c</fullName>
        <description>The Id of the Email Template being used to pass data elements to CTS</description>
        <inlineHelpText>The Id of the Email Template being used to pass data elements to CTS</inlineHelpText>
        <label>Email Template Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalTicketId__c</fullName>
        <description>The Ticket Id created in the CTS system</description>
        <inlineHelpText>The Ticket Id created in the CTS system</inlineHelpText>
        <label>External Ticket Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Type__c</fullName>
        <description>Integration Type (API or Email) which determines the internal process methods to be called for ticket creation in CTS</description>
        <inlineHelpText>Integration Type (API or Email) which determines the internal process methods to be called for ticket creation in CTS</inlineHelpText>
        <label>Integration Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfRetryAttempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of attempts made to send a request to the CTS API for creating a ticket</description>
        <inlineHelpText>Number of attempts made to send a request to the CTS API for creating a ticket</inlineHelpText>
        <label>Number Of Retry Attempts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The corresponding record Id based on the Object Name</description>
        <inlineHelpText>The corresponding record Id based on the Object Name</inlineHelpText>
        <label>Object Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Salesforce Objects integrated with CTS</description>
        <inlineHelpText>Salesforce Objects integrated with CTS</inlineHelpText>
        <label>Object Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Customer_Surveys__c</fullName>
                </value>
                <value>
                    <fullName>Organic_Analysis__c</fullName>
                </value>
                <value>
                    <fullName>Quality_Case__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ScheduledDateTime__c</fullName>
        <description>The scheduled date/ time of the Async Record to be triggered to create the CTS ticket</description>
        <inlineHelpText>The scheduled date/ time of the Async Record to be triggered to create the CTS ticket</inlineHelpText>
        <label>Scheduled Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>"NEW"</defaultValue>
        <description>Async Request Status indicating the current state of the record</description>
        <inlineHelpText>Async Request Status indicating the current state of the record</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>INPROCESS</fullName>
                </value>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>UNQUALIFIED</fullName>
                </value>
                <value>
                    <fullName>REPROCESS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SFDCToCTSAsynchRequest</label>
    <nameField>
        <displayFormat>AR-{000000000}</displayFormat>
        <label>Asynch Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDCToCTSAsynchRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CTSTicketIdSyncTest.cls
/*
//Reason : “BeaconHS1Migration” : Inactivated the completed class , as this is not needed for LH Product.
//By : Mahesh Bogila , 7/3/2019

/****************************************************************************
  Company/ Author ....: E. Ross
  Date Created .......: 28-Jan-2019
  Last Modified By ...: E. Ross
  Last Modified Date .: 28-Jan-2019
  Description ........: Test Class for CTSTicketIdSync
*****************************************************************************/
@isTest(seeAllData=true)
public class CTSTicketIdSyncTest
{
    static testMethod void test_CTSTicketIdSync() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CTSTicketIdSync obj = new CTSTicketIdSync();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    
    static testMethod void test_CTSTicketResponse() 
        {
          Test.StartTest();
          //The object name below has to match up with your trigger/class
          CTSTicketResponse obj = new CTSTicketResponse();
          //This one link is asserting that you successfully created it
          system.assertNotEquals(null,obj);   
          Test.StopTest();
        }  
    /*
    private static testMethod void createAndUpdateAsyncRecord()
    {
        List<Id> objectIds = new List<Id>();
        List<SFDCToCTSAsynchRequest__c> dmlAsyncRequests = new List<SFDCToCTSAsynchRequest__c>();
        List<SFDCToCTSAsynchRequest__c> asyncRequestsToUpdate = new List<SFDCToCTSAsynchRequest__c>();
        DateTime currDate = System.Now();
        Id emailTemplateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'CTS_Touchplan_Send'].Id;
        
        SFDCToCTSAsynchRequest__c newAsync = new SFDCToCTSAsynchRequest__c();
        newAsync.API_Identifier__c = 'SFDCY_CASE_000012';
        newAsync.EmailTemplateId__c = String.valueOf(emailTemplateId);
        newAsync.Integration_Type__c = 'API';
        newAsync.NumberOfRetryAttempts__c = 0;
        newAsync.ObjectId__c = '5001b000005MXXX';
        newAsync.Object_Name__c = 'Case';
        newAsync.Status__c = 'New';
        newAsync.ScheduledDateTime__c = currDate;
        dmlAsyncRequests.add(newAsync);
        
        if(dmlAsyncRequests.size() > 0){
        
            insert dmlAsyncRequests;
            
            for(SFDCToCTSAsynchRequest__c asr : dmlAsyncRequests){
            
                asr.ExternalTicketId__c = '1234567';
                asr.Status__c = 'SUCCESS';
                asyncRequestsToUpdate.add(asr);
                objectIds.add(asr.Id);
            }
            
            if(asyncRequestsToUpdate.size() > 0){
                update asyncRequestsToUpdate;
            }
        }
        
        // start test
        Test.startTest();
        
        // execute Invocable method
        CTSTicketIdSync.UpdateRelatedObjectData(objectIds);
        
        Test.stopTest();
    }*/
}